package org.bouncycastle.asn1.bc;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes4.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier R;
    public static final ASN1ObjectIdentifier S;
    public static final ASN1ObjectIdentifier T;
    public static final ASN1ObjectIdentifier U;
    public static final ASN1ObjectIdentifier V;
    public static final ASN1ObjectIdentifier W;
    public static final ASN1ObjectIdentifier X;
    public static final ASN1ObjectIdentifier Y;
    public static final ASN1ObjectIdentifier Z;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier aA;
    public static final ASN1ObjectIdentifier aB;
    public static final ASN1ObjectIdentifier aC;
    public static final ASN1ObjectIdentifier aD;
    public static final ASN1ObjectIdentifier aE;
    public static final ASN1ObjectIdentifier aF;
    public static final ASN1ObjectIdentifier aG;
    public static final ASN1ObjectIdentifier aH;
    public static final ASN1ObjectIdentifier aI;
    public static final ASN1ObjectIdentifier aJ;
    public static final ASN1ObjectIdentifier aK;
    public static final ASN1ObjectIdentifier aL;
    public static final ASN1ObjectIdentifier aM;
    public static final ASN1ObjectIdentifier aN;
    public static final ASN1ObjectIdentifier aO;
    public static final ASN1ObjectIdentifier aP;
    public static final ASN1ObjectIdentifier aQ;
    public static final ASN1ObjectIdentifier aR;
    public static final ASN1ObjectIdentifier aS;
    public static final ASN1ObjectIdentifier aT;
    public static final ASN1ObjectIdentifier aU;
    public static final ASN1ObjectIdentifier aV;
    public static final ASN1ObjectIdentifier aW;
    public static final ASN1ObjectIdentifier aX;
    public static final ASN1ObjectIdentifier aY;
    public static final ASN1ObjectIdentifier aZ;
    public static final ASN1ObjectIdentifier aa;
    public static final ASN1ObjectIdentifier ab;
    public static final ASN1ObjectIdentifier ac;
    public static final ASN1ObjectIdentifier ad;
    public static final ASN1ObjectIdentifier ae;
    public static final ASN1ObjectIdentifier af;
    public static final ASN1ObjectIdentifier ag;
    public static final ASN1ObjectIdentifier ah;
    public static final ASN1ObjectIdentifier ai;
    public static final ASN1ObjectIdentifier aj;
    public static final ASN1ObjectIdentifier ak;
    public static final ASN1ObjectIdentifier al;
    public static final ASN1ObjectIdentifier am;
    public static final ASN1ObjectIdentifier an;
    public static final ASN1ObjectIdentifier ao;
    public static final ASN1ObjectIdentifier ap;
    public static final ASN1ObjectIdentifier aq;
    public static final ASN1ObjectIdentifier ar;
    public static final ASN1ObjectIdentifier as;
    public static final ASN1ObjectIdentifier at;
    public static final ASN1ObjectIdentifier au;
    public static final ASN1ObjectIdentifier av;
    public static final ASN1ObjectIdentifier aw;
    public static final ASN1ObjectIdentifier ax;
    public static final ASN1ObjectIdentifier ay;
    public static final ASN1ObjectIdentifier az;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier bA;
    public static final ASN1ObjectIdentifier bB;
    public static final ASN1ObjectIdentifier bC;
    public static final ASN1ObjectIdentifier bD;
    public static final ASN1ObjectIdentifier bE;
    public static final ASN1ObjectIdentifier bF;
    public static final ASN1ObjectIdentifier bG;
    public static final ASN1ObjectIdentifier bH;
    public static final ASN1ObjectIdentifier bI;
    public static final ASN1ObjectIdentifier bJ;
    public static final ASN1ObjectIdentifier bK;
    public static final ASN1ObjectIdentifier bL;
    public static final ASN1ObjectIdentifier bM;
    public static final ASN1ObjectIdentifier bN;
    public static final ASN1ObjectIdentifier bO;
    public static final ASN1ObjectIdentifier bP;
    public static final ASN1ObjectIdentifier bQ;
    public static final ASN1ObjectIdentifier bR;
    public static final ASN1ObjectIdentifier bS;
    public static final ASN1ObjectIdentifier bT;
    public static final ASN1ObjectIdentifier bU;
    public static final ASN1ObjectIdentifier bV;
    public static final ASN1ObjectIdentifier bW;
    public static final ASN1ObjectIdentifier bX;
    public static final ASN1ObjectIdentifier bY;
    public static final ASN1ObjectIdentifier bZ;
    public static final ASN1ObjectIdentifier ba;
    public static final ASN1ObjectIdentifier bb;
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bd;
    public static final ASN1ObjectIdentifier be;
    public static final ASN1ObjectIdentifier bf;
    public static final ASN1ObjectIdentifier bg;
    public static final ASN1ObjectIdentifier bh;
    public static final ASN1ObjectIdentifier bi;
    public static final ASN1ObjectIdentifier bj;
    public static final ASN1ObjectIdentifier bk;
    public static final ASN1ObjectIdentifier bl;
    public static final ASN1ObjectIdentifier bm;
    public static final ASN1ObjectIdentifier bn;
    public static final ASN1ObjectIdentifier bo;
    public static final ASN1ObjectIdentifier bp;
    public static final ASN1ObjectIdentifier bq;
    public static final ASN1ObjectIdentifier br;
    public static final ASN1ObjectIdentifier bs;
    public static final ASN1ObjectIdentifier bt;
    public static final ASN1ObjectIdentifier bu;
    public static final ASN1ObjectIdentifier bv;
    public static final ASN1ObjectIdentifier bw;
    public static final ASN1ObjectIdentifier bx;
    public static final ASN1ObjectIdentifier by;
    public static final ASN1ObjectIdentifier bz;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier ca;
    public static final ASN1ObjectIdentifier cb;
    public static final ASN1ObjectIdentifier cc;
    public static final ASN1ObjectIdentifier cd;
    public static final ASN1ObjectIdentifier ce;
    public static final ASN1ObjectIdentifier cf;
    public static final ASN1ObjectIdentifier cg;
    public static final ASN1ObjectIdentifier ch;
    public static final ASN1ObjectIdentifier ci;
    public static final ASN1ObjectIdentifier cj;
    public static final ASN1ObjectIdentifier ck;
    public static final ASN1ObjectIdentifier cl;
    public static final ASN1ObjectIdentifier cm;
    public static final ASN1ObjectIdentifier cn;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "1");
        b = aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "1");
        c = aSN1ObjectIdentifier3;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, VCardConstants.VERSION_V21);
        d = aSN1ObjectIdentifier4;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "2.2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "2.3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "2.4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "2");
        e = aSN1ObjectIdentifier5;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "2");
        f = aSN1ObjectIdentifier6;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1.2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1.22");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1.42");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1.2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1.22");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "2");
        g = aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "1");
        h = aSN1ObjectIdentifier8;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "2");
        i = aSN1ObjectIdentifier9;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "8");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "9");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "10");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "3");
        j = aSN1ObjectIdentifier10;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "8");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "9");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "10");
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "4");
        k = aSN1ObjectIdentifier11;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "5");
        l = new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "11");
        m = new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "5");
        n = aSN1ObjectIdentifier12;
        o = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "1");
        p = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "2");
        q = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "3");
        r = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "4");
        s = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "5");
        t = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "6");
        u = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "7");
        v = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "8");
        w = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "9");
        x = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "10");
        y = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "11");
        z = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "12");
        A = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "13");
        B = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "14");
        C = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "15");
        D = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "16");
        E = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "17");
        F = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "18");
        G = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "19");
        H = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "20");
        I = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "21");
        J = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "22");
        K = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "23");
        L = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "24");
        M = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "25");
        N = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "26");
        O = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "27");
        P = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "28");
        Q = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "29");
        R = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "30");
        S = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "31");
        T = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "32");
        U = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "33");
        V = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "34");
        W = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "35");
        X = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "36");
        Y = new ASN1ObjectIdentifier("1.3.9999.6");
        Z = new ASN1ObjectIdentifier("1.3.9999.6.4.13");
        aa = new ASN1ObjectIdentifier("1.3.9999.6.4.16");
        ab = new ASN1ObjectIdentifier("1.3.9999.6.5.10");
        ac = new ASN1ObjectIdentifier("1.3.9999.6.5.12");
        ad = new ASN1ObjectIdentifier("1.3.9999.6.6.10");
        ae = new ASN1ObjectIdentifier("1.3.9999.6.6.12");
        af = new ASN1ObjectIdentifier("1.3.9999.6.7.13");
        ag = new ASN1ObjectIdentifier("1.3.9999.6.7.16");
        ah = new ASN1ObjectIdentifier("1.3.9999.6.8.10");
        ai = new ASN1ObjectIdentifier("1.3.9999.6.8.12");
        aj = new ASN1ObjectIdentifier("1.3.9999.6.9.10");
        ak = new ASN1ObjectIdentifier("1.3.9999.6.9.12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "6");
        al = aSN1ObjectIdentifier13;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "1");
        am = aSN1ObjectIdentifier14;
        an = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "1");
        ao = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "2");
        ap = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "3");
        aq = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "4");
        ar = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "5");
        as = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "6");
        at = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "7");
        au = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "8");
        av = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "9");
        aw = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "10");
        ax = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "11");
        ay = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "12");
        ASN1ObjectIdentifier aSN1ObjectIdentifier15 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "2");
        az = aSN1ObjectIdentifier15;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "7");
        aA = new ASN1ObjectIdentifier("1.3.9999.3.6");
        aB = new ASN1ObjectIdentifier("1.3.9999.3.9");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "8");
        aC = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.4.4");
        aD = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.6.5");
        aE = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.12.8.7");
        aF = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.4.4");
        aG = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.6.5");
        aH = new ASN1ObjectIdentifier("1.3.6.1.4.1.2.267.11.8.7");
        ASN1ObjectIdentifier aSN1ObjectIdentifier16 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "9");
        aI = aSN1ObjectIdentifier16;
        aJ = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "1");
        aK = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "2");
        aL = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "3");
        aM = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "4");
        aN = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "5");
        aO = new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier17 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "3");
        aP = aSN1ObjectIdentifier17;
        aQ = new ASN1ObjectIdentifier(aSN1ObjectIdentifier17, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier18 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "4");
        aR = aSN1ObjectIdentifier18;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier18, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier18, "2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier19 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "5");
        aS = aSN1ObjectIdentifier19;
        ASN1ObjectIdentifier aSN1ObjectIdentifier20 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "1");
        aT = aSN1ObjectIdentifier20;
        aU = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "1");
        aV = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "2");
        aW = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "3");
        aX = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "4");
        aY = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "5");
        aZ = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "6");
        ba = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "7");
        bb = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "8");
        bc = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "9");
        bd = new ASN1ObjectIdentifier(aSN1ObjectIdentifier20, "10");
        ASN1ObjectIdentifier aSN1ObjectIdentifier21 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "2");
        be = aSN1ObjectIdentifier21;
        bf = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "1");
        bg = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "2");
        bh = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "3");
        bi = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "4");
        bj = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "5");
        bk = new ASN1ObjectIdentifier(aSN1ObjectIdentifier21, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier22 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "3");
        bl = aSN1ObjectIdentifier22;
        bm = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "1");
        bn = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "2");
        bo = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "3");
        bp = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "4");
        bq = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "5");
        br = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "6");
        bs = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "7");
        bt = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "8");
        bu = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "9");
        bv = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "10");
        bw = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "11");
        bx = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "12");
        by = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "13");
        bz = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "14");
        bA = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "15");
        bB = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "16");
        bC = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "17");
        bD = new ASN1ObjectIdentifier(aSN1ObjectIdentifier22, "18");
        ASN1ObjectIdentifier aSN1ObjectIdentifier23 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "4");
        bE = aSN1ObjectIdentifier23;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier23, "8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier24 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "5");
        bF = aSN1ObjectIdentifier24;
        bG = new ASN1ObjectIdentifier(aSN1ObjectIdentifier24, "1");
        bH = new ASN1ObjectIdentifier(aSN1ObjectIdentifier24, "2");
        bI = new ASN1ObjectIdentifier(aSN1ObjectIdentifier24, "3");
        bJ = new ASN1ObjectIdentifier(aSN1ObjectIdentifier24, "4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier25 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "6");
        bK = aSN1ObjectIdentifier25;
        bL = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "1");
        bM = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "2");
        bN = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "3");
        bO = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "4");
        bP = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "5");
        bQ = new ASN1ObjectIdentifier(aSN1ObjectIdentifier25, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier26 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "7");
        bR = aSN1ObjectIdentifier26;
        ASN1ObjectIdentifier aSN1ObjectIdentifier27 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier26, "1");
        bS = aSN1ObjectIdentifier27;
        bT = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "1");
        bU = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "2");
        bV = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "3");
        bW = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "4");
        bX = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "5");
        bY = new ASN1ObjectIdentifier(aSN1ObjectIdentifier27, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier28 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier26, "2");
        bZ = aSN1ObjectIdentifier28;
        ca = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "1");
        cb = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "2");
        cc = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "3");
        cd = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "4");
        ce = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "5");
        cf = new ASN1ObjectIdentifier(aSN1ObjectIdentifier28, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier29 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "8");
        cg = aSN1ObjectIdentifier29;
        ch = new ASN1ObjectIdentifier(aSN1ObjectIdentifier29, "1");
        ci = new ASN1ObjectIdentifier(aSN1ObjectIdentifier29, "2");
        cj = new ASN1ObjectIdentifier(aSN1ObjectIdentifier29, "3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier30 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier19, "9");
        ck = aSN1ObjectIdentifier30;
        cl = new ASN1ObjectIdentifier(aSN1ObjectIdentifier30, "1");
        cm = new ASN1ObjectIdentifier(aSN1ObjectIdentifier30, "2");
        cn = new ASN1ObjectIdentifier(aSN1ObjectIdentifier30, "3");
    }
}
