package org.bouncycastle.asn1.x9;

import com.android.vcard.VCardConstants;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes4.dex */
public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier J;
    public static final ASN1ObjectIdentifier K;
    public static final ASN1ObjectIdentifier L;
    public static final ASN1ObjectIdentifier M;
    public static final ASN1ObjectIdentifier N;
    public static final ASN1ObjectIdentifier O;
    public static final ASN1ObjectIdentifier P;
    public static final ASN1ObjectIdentifier Q;
    public static final ASN1ObjectIdentifier a;
    public static final ASN1ObjectIdentifier b;
    public static final ASN1ObjectIdentifier c;
    public static final ASN1ObjectIdentifier d;
    public static final ASN1ObjectIdentifier e;
    public static final ASN1ObjectIdentifier f;
    public static final ASN1ObjectIdentifier g;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        a = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "1");
        b = aSN1ObjectIdentifier2;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "2");
        c = aSN1ObjectIdentifier3;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "3.1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "3.2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "3.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "4");
        d = aSN1ObjectIdentifier4;
        e = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "2");
        f = aSN1ObjectIdentifier5;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "3");
        g = aSN1ObjectIdentifier6;
        h = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1");
        i = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "2");
        j = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "3");
        k = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "3");
        l = aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "0");
        m = aSN1ObjectIdentifier8;
        n = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "1");
        o = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "2");
        p = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "3");
        q = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "4");
        r = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "5");
        s = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "6");
        t = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "8");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "9");
        u = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "10");
        v = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "11");
        w = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "12");
        x = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "13");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "14");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "15");
        y = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "16");
        z = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "17");
        A = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "18");
        B = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "19");
        C = new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "20");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "1");
        D = aSN1ObjectIdentifier9;
        E = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "1");
        F = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "2");
        G = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3");
        H = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "4");
        I = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "5");
        J = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "6");
        K = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "7");
        new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        L = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        M = aSN1ObjectIdentifier10;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.2.840.10046");
        N = aSN1ObjectIdentifier11;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, VCardConstants.VERSION_V21);
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "3");
        O = aSN1ObjectIdentifier12;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "8");
        ASN1ObjectIdentifier aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        P = aSN1ObjectIdentifier13;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "1");
        Q = aSN1ObjectIdentifier14;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "2");
    }
}
