package com.google.android.apps.messaging.shared.datamodel.databasegen.queries;

import android.content.ContentValues;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.MessageIdType;
import defpackage.aabr;
import defpackage.aday;
import defpackage.aglz;
import defpackage.agmi;
import defpackage.agmk;
import defpackage.agmq;
import defpackage.agnc;
import defpackage.akec;
import defpackage.alok;
import defpackage.aozs;
import defpackage.apag;
import defpackage.aqby;
import defpackage.d;
import defpackage.lbz;
import defpackage.rha;
import defpackage.ruy;
import defpackage.rvc;
import defpackage.sbg;
import defpackage.scg;
import defpackage.wsy;
import defpackage.yta;
import j$.util.Objects;
import java.util.Locale;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class LocationSearchQuery {
    public static final String[] a = {"messages_annotations._id", "messages_annotations.message_id", "messages_annotations.annotation_details", "messages._id", "messages.conversation_id", "messages.received_timestamp", "participants.sub_id", "participants.normalized_destination", "participants.full_name", "message_star._id", "parent_disallowed_conversations.conversation_id", "conversations.participant_normalized_destination", "conversations.has_ea2p_bot_recipient"};

    /* compiled from: PG */
    /* loaded from: classes3.dex */
    public static abstract class BindData extends aglz<lbz, Object, Object, BindData, Object> implements Parcelable {
        public static final Parcelable.Creator<BindData> CREATOR = new rha(18);
        private String a;
        private MessageIdType b;
        private aqby c;
        private MessageIdType d;
        private ConversationIdType e;
        private long f;
        private int g;
        private String h;
        private String i;
        private long j;
        private ConversationIdType k;
        private String l;
        private boolean m;

        /* JADX INFO: Access modifiers changed from: protected */
        public BindData() {
            MessageIdType messageIdType = rvc.a;
            this.b = messageIdType;
            this.d = messageIdType;
            ConversationIdType conversationIdType = ruy.a;
            this.e = conversationIdType;
            this.f = 0L;
            this.g = -2;
            this.k = conversationIdType;
            this.m = false;
        }

        @Override // defpackage.aglz
        public final String a() {
            return String.format(Locale.US, "LocationSearchQuery [messages_annotations.messages_annotations__id: %s,\n  messages_annotations.messages_annotations_message_id: %s,\n  messages_annotations.messages_annotations_annotation_details: %s,\n  messages.messages__id: %s,\n  messages.messages_conversation_id: %s,\n  messages.messages_received_timestamp: %s,\n  participants.participants_sub_id: %s,\n  participants.participants_normalized_destination: %s,\n  participants.participants_full_name: %s,\n  message_star.message_star__id: %s,\n  parent_disallowed_conversations.parent_disallowed_conversations_conversation_id: %s,\n  conversations.conversations_participant_normalized_destination: %s,\n  conversations.conversations_has_ea2p_bot_recipient: %s\n]\n", String.valueOf(this.a), String.valueOf(this.b), String.valueOf(this.c), String.valueOf(this.d), String.valueOf(this.e), String.valueOf(this.f), String.valueOf(this.g), String.valueOf(this.h), String.valueOf(this.i), String.valueOf(this.j), String.valueOf(this.k), String.valueOf(this.l), String.valueOf(this.m));
        }

        @Override // defpackage.aglz
        public final void b(ContentValues contentValues) {
            Integer valueOf;
            valueOf = Integer.valueOf(d.P().W().c());
            valueOf.intValue();
        }

        @Override // defpackage.aglz
        public final /* bridge */ /* synthetic */ void c(agmq agmqVar) {
            aqby aqbyVar;
            lbz lbzVar = (lbz) agmqVar;
            aq();
            this.cJ = lbzVar.dx();
            boolean z = false;
            if (lbzVar.db(0)) {
                this.a = lbzVar.getString(lbzVar.cI(0, LocationSearchQuery.a));
                fE(0);
            }
            if (lbzVar.db(1)) {
                this.b = new MessageIdType(lbzVar.getLong(lbzVar.cI(1, LocationSearchQuery.a)));
                fE(1);
            }
            if (lbzVar.db(2)) {
                byte[] blob = lbzVar.getBlob(lbzVar.cI(2, LocationSearchQuery.a));
                if (blob == null) {
                    aqbyVar = null;
                } else {
                    try {
                        aqbyVar = (aqby) apag.parseFrom(aqby.a, blob, aozs.a());
                    } catch (Throwable unused) {
                        aqbyVar = aqby.a;
                    }
                }
                this.c = aqbyVar;
                fE(2);
            }
            if (lbzVar.db(3)) {
                this.d = new MessageIdType(lbzVar.getLong(lbzVar.cI(3, LocationSearchQuery.a)));
                fE(3);
            }
            if (lbzVar.db(4)) {
                this.e = new ConversationIdType(lbzVar.getLong(lbzVar.cI(4, LocationSearchQuery.a)));
                fE(4);
            }
            if (lbzVar.db(5)) {
                this.f = lbzVar.getLong(lbzVar.cI(5, LocationSearchQuery.a));
                fE(5);
            }
            if (lbzVar.db(6)) {
                this.g = lbzVar.getInt(lbzVar.cI(6, LocationSearchQuery.a));
                fE(6);
            }
            if (lbzVar.db(7)) {
                this.h = aabr.bb(lbzVar.getString(lbzVar.cI(7, LocationSearchQuery.a)));
                fE(7);
            }
            if (lbzVar.db(8)) {
                this.i = yta.a(lbzVar.getString(lbzVar.cI(8, LocationSearchQuery.a)));
                fE(8);
            }
            if (lbzVar.db(9)) {
                this.j = lbzVar.getLong(lbzVar.cI(9, LocationSearchQuery.a));
                fE(9);
            }
            if (lbzVar.db(10)) {
                this.k = new ConversationIdType(lbzVar.getLong(lbzVar.cI(10, LocationSearchQuery.a)));
                fE(10);
            }
            if (lbzVar.db(11)) {
                this.l = lbzVar.getString(lbzVar.cI(11, LocationSearchQuery.a));
                fE(11);
            }
            if (lbzVar.db(12)) {
                if (lbzVar.getInt(lbzVar.cI(12, LocationSearchQuery.a)) == 1) {
                    z = true;
                }
                this.m = z;
                fE(12);
            }
        }

        public int describeContents() {
            return 0;
        }

        public final boolean equals(Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof BindData)) {
                return false;
            }
            BindData bindData = (BindData) obj;
            if (super.aC(bindData.cJ) && Objects.equals(this.a, bindData.a) && Objects.equals(this.b, bindData.b) && Objects.equals(this.c, bindData.c) && Objects.equals(this.d, bindData.d) && Objects.equals(this.e, bindData.e) && this.f == bindData.f && this.g == bindData.g && Objects.equals(this.h, bindData.h) && Objects.equals(this.i, bindData.i) && this.j == bindData.j && Objects.equals(this.k, bindData.k) && Objects.equals(this.l, bindData.l) && this.m == bindData.m) {
                return true;
            }
            return false;
        }

        @Override // defpackage.aglz
        protected final void fo(Parcel parcel) {
            aqby aqbyVar;
            this.a = parcel.readString();
            this.b = new MessageIdType(parcel.readLong());
            byte[] createByteArray = parcel.createByteArray();
            if (createByteArray == null) {
                aqbyVar = null;
            } else {
                try {
                    aqbyVar = (aqby) apag.parseFrom(aqby.a, createByteArray, aozs.a());
                } catch (Throwable unused) {
                    this.c = null;
                }
            }
            this.c = aqbyVar;
            this.d = new MessageIdType(parcel.readLong());
            this.e = new ConversationIdType(parcel.readLong());
            this.f = parcel.readLong();
            this.g = parcel.readInt();
            this.h = parcel.readString();
            this.i = parcel.readString();
            this.j = parcel.readLong();
            this.k = new ConversationIdType(parcel.readLong());
            this.l = parcel.readString();
            boolean z = true;
            if (parcel.readInt() != 1) {
                z = false;
            }
            this.m = z;
        }

        @Override // defpackage.aglz
        protected final void fp(Parcel parcel) {
            byte[] byteArray;
            parcel.writeString(this.a);
            parcel.writeLong(rvc.a(this.b));
            aqby aqbyVar = this.c;
            if (aqbyVar == null) {
                byteArray = null;
            } else {
                byteArray = aqbyVar.toByteArray();
            }
            parcel.writeByteArray(byteArray);
            parcel.writeLong(rvc.a(this.d));
            parcel.writeLong(ruy.a(this.e));
            parcel.writeLong(this.f);
            parcel.writeInt(this.g);
            parcel.writeString(this.h);
            parcel.writeString(this.i);
            parcel.writeLong(this.j);
            parcel.writeLong(ruy.a(this.k));
            parcel.writeString(this.l);
            parcel.writeInt(this.m ? 1 : 0);
        }

        public final int hashCode() {
            aday adayVar;
            aday adayVar2 = this.cJ;
            if (adayVar2 != null && !adayVar2.Y()) {
                adayVar = this.cJ;
            } else {
                adayVar = null;
            }
            return Objects.hash(adayVar, this.a, this.b, this.c, this.d, this.e, Long.valueOf(this.f), Integer.valueOf(this.g), this.h, this.i, Long.valueOf(this.j), this.k, this.l, Boolean.valueOf(this.m), null);
        }

        public final String toString() {
            if (((aglz.a) akec.w(agnc.b, aglz.a.class)).QY().a()) {
                return String.format(Locale.US, "%s", "LocationSearchQuery -- REDACTED");
            }
            return a();
        }

        /* JADX INFO: Access modifiers changed from: protected */
        public BindData(Parcel parcel) {
            MessageIdType messageIdType = rvc.a;
            this.b = messageIdType;
            this.d = messageIdType;
            ConversationIdType conversationIdType = ruy.a;
            this.e = conversationIdType;
            this.f = 0L;
            this.g = -2;
            this.k = conversationIdType;
            this.m = false;
            ap(parcel);
        }
    }

    static {
        alok alokVar = new alok();
        alokVar.h("messages_annotations.message_id", 20040);
        alokVar.h("conversations.has_ea2p_bot_recipient", 12001);
        alokVar.b();
        d.aF();
        agmi a2 = agmk.a();
        a2.k(2);
        a2.j(true);
        a2.f(true);
        a2.c(true);
        a2.b("messages_annotations._id");
        a2.h(new wsy());
        a2.a();
        agmi a3 = agmk.a();
        a3.k(2);
        a3.c(true);
        a3.d(true);
        a3.g(new sbg(17));
        a3.b("messages_annotations.message_id");
        a3.h(new wsy());
        a3.a();
        agmi a4 = agmk.a();
        a4.k(5);
        a4.b("messages_annotations.annotation_details");
        a4.h(new wsy());
        a4.a();
        agmi a5 = agmk.a();
        a5.k(4);
        a5.c(true);
        a5.b("messages_annotations.conversation_id");
        a5.h(new wsy());
        a5.a();
        agmi a6 = agmk.a();
        a6.k(1);
        a6.c(true);
        a6.b("messages_annotations.annotation_type");
        a6.h(new wsy());
        a6.a();
        agmi a7 = agmk.a();
        a7.k(2);
        a7.j(true);
        a7.f(true);
        a7.c(true);
        a7.b("messages._id");
        a7.h(new wsy());
        a7.a();
        agmi a8 = agmk.a();
        a8.k(1);
        a8.c(true);
        a8.d(true);
        a8.b("messages.conversation_id");
        a8.h(new wsy());
        a8.a();
        agmi a9 = agmk.a();
        a9.k(1);
        a9.c(true);
        a9.b("messages.received_timestamp");
        a9.h(new wsy());
        a9.a();
        agmi a10 = agmk.a();
        a10.k(1);
        a10.c(true);
        a10.d(true);
        a10.b("messages.sender_id");
        a10.h(new wsy());
        a10.a();
        agmi a11 = agmk.a();
        a11.k(4);
        a11.b("messages.sender_send_destination");
        a11.h(new wsy());
        a11.a();
        agmi a12 = agmk.a();
        a12.k(4);
        a12.b("messages.msisdn_receiving_rcs_message");
        a12.h(new wsy());
        a12.a();
        agmi a13 = agmk.a();
        a13.k(4);
        a13.b("messages.receiving_network_country");
        a13.h(new wsy());
        a13.a();
        agmi a14 = agmk.a();
        a14.k(1);
        a14.c(true);
        a14.b("messages.sent_timestamp");
        a14.h(new wsy());
        a14.a();
        agmi a15 = agmk.a();
        a15.k(1);
        a15.b("messages.queue_insert_timestamp");
        a15.h(new wsy());
        a15.a();
        agmi a16 = agmk.a();
        a16.k(1);
        a16.b("messages.message_protocol");
        a16.h(new wsy());
        a16.a();
        agmi a17 = agmk.a();
        a17.k(1);
        a17.c(true);
        a17.b("messages.message_status");
        a17.h(new wsy());
        a17.a();
        agmi a18 = agmk.a();
        a18.k(1);
        a18.b("messages.message_report_status");
        a18.h(new wsy());
        a18.a();
        agmi a19 = agmk.a();
        a19.k(1);
        a19.c(true);
        a19.b("messages.seen");
        a19.e(true);
        a19.h(new wsy());
        a19.a();
        agmi a20 = agmk.a();
        a20.k(1);
        a20.c(true);
        a20.b("messages.read");
        a20.h(new wsy());
        a20.a();
        agmi a21 = agmk.a();
        a21.k(4);
        a21.c(true);
        a21.b("messages.sms_message_uri");
        a21.h(new wsy());
        a21.a();
        agmi a22 = agmk.a();
        a22.k(1);
        a22.b("messages.sms_priority");
        a22.h(new wsy());
        a22.a();
        agmi a23 = agmk.a();
        a23.k(1);
        a23.b("messages.sms_message_size");
        a23.h(new wsy());
        a23.a();
        agmi a24 = agmk.a();
        a24.k(4);
        a24.b("messages.mms_subject");
        a24.h(new wsy());
        a24.a();
        agmi a25 = agmk.a();
        a25.k(4);
        a25.b("messages.mms_transaction_id");
        a25.h(new wsy());
        a25.a();
        agmi a26 = agmk.a();
        a26.k(4);
        a26.b("messages.mms_content_location");
        a26.h(new wsy());
        a26.a();
        agmi a27 = agmk.a();
        a27.k(1);
        a27.b("messages.mms_expiry");
        a27.h(new wsy());
        a27.a();
        agmi a28 = agmk.a();
        a28.k(1);
        a28.c(true);
        a28.b("messages.rcs_expiry");
        a28.h(new wsy());
        a28.a();
        agmi a29 = agmk.a();
        a29.k(4);
        a29.b("messages.mms_retrieve_text");
        a29.h(new wsy());
        a29.a();
        agmi a30 = agmk.a();
        a30.k(1);
        a30.b("messages.raw_status");
        a30.h(new wsy());
        a30.a();
        agmi a31 = agmk.a();
        a31.k(1);
        a31.c(true);
        a31.d(true);
        a31.b("messages.self_id");
        a31.h(new wsy());
        a31.a();
        agmi a32 = agmk.a();
        a32.k(4);
        a32.c(true);
        a32.b("messages.my_identity");
        a32.h(new wsy());
        a32.a();
        agmi a33 = agmk.a();
        a33.k(4);
        a33.c(true);
        a33.d(true);
        a33.g(new sbg(18));
        a33.b("messages.my_identity_foreign_key");
        a33.h(new wsy());
        a33.a();
        agmi a34 = agmk.a();
        a34.k(1);
        a34.b("messages.retry_start_timestamp");
        a34.h(new wsy());
        a34.a();
        agmi a35 = agmk.a();
        a35.k(4);
        a35.c(true);
        a35.b("messages.cloud_sync_id");
        a35.h(new wsy());
        a35.a();
        agmi a36 = agmk.a();
        a36.k(7);
        a36.c(true);
        a36.b("messages.rcs_message_id");
        a36.e(true);
        a36.h(new wsy());
        a36.a();
        agmi a37 = agmk.a();
        a37.k(4);
        a37.c(true);
        a37.b("messages.rcs_message_id_with_text_type");
        a37.e(true);
        a37.h(new wsy());
        a37.a();
        agmi a38 = agmk.a();
        a38.k(1);
        a38.b("messages.etouffee_status");
        a38.h(new wsy());
        a38.a();
        agmi a39 = agmk.a();
        a39.k(1);
        a39.b("messages.verification_status");
        a39.h(new wsy());
        a39.a();
        agmi a40 = agmk.a();
        a40.k(1);
        a40.b("messages.rcs_ui_status");
        a40.h(new wsy());
        a40.a();
        agmi a41 = agmk.a();
        a41.k(1);
        a41.c(true);
        a41.b("messages.is_hidden");
        a41.h(new wsy());
        a41.a();
        agmi a42 = agmk.a();
        a42.k(7);
        a42.b("messages.rcs_remote_instance");
        a42.h(new wsy());
        a42.a();
        agmi a43 = agmk.a();
        a43.k(1);
        a43.b("messages.rcs_file_transfer_session_id");
        a43.h(new wsy());
        a43.a();
        agmi a44 = agmk.a();
        a44.k(1);
        a44.b("messages.sms_error_code");
        a44.h(new wsy());
        a44.a();
        agmi a45 = agmk.a();
        a45.k(4);
        a45.b("messages.sms_error_desc_map_name");
        a45.h(new wsy());
        a45.a();
        agmi a46 = agmk.a();
        a46.k(4);
        a46.b("messages.correlation_id");
        a46.h(new wsy());
        a46.a();
        agmi a47 = agmk.a();
        a47.k(4);
        a47.j(true);
        a47.c(true);
        a47.b("messages.cms_id");
        a47.e(true);
        a47.h(new wsy());
        a47.a();
        agmi a48 = agmk.a();
        a48.k(2);
        a48.b("messages.cms_last_mod_seq");
        a48.h(new wsy());
        a48.a();
        agmi a49 = agmk.a();
        a49.k(4);
        a49.c(true);
        a49.b("messages.web_id");
        a49.h(new wsy());
        a49.a();
        agmi a50 = agmk.a();
        a50.k(1);
        a50.b("messages.usage_stats_logging_id");
        a50.h(new wsy());
        a50.a();
        agmi a51 = agmk.a();
        a51.k(1);
        a51.b("messages.send_counter");
        a51.h(new wsy());
        a51.a();
        agmi a52 = agmk.a();
        a52.k(4);
        a52.c(true);
        a52.b("messages.original_rcs_message_id");
        a52.h(new wsy());
        a52.a();
        agmi a53 = agmk.a();
        a53.k(4);
        a53.b("messages.custom_delivery_receipt_mime_type");
        a53.h(new wsy());
        a53.a();
        agmi a54 = agmk.a();
        a54.k(5);
        a54.b("messages.custom_delivery_receipt_content");
        a54.h(new wsy());
        a54.a();
        agmi a55 = agmk.a();
        a55.k(1);
        a55.b("messages.report_attempt_acounter");
        a55.h(new wsy());
        a55.a();
        agmi a56 = agmk.a();
        a56.k(5);
        a56.b("messages.custom_headers");
        a56.h(new wsy());
        a56.a();
        agmi a57 = agmk.a();
        a57.k(4);
        a57.j(true);
        a57.c(true);
        a57.b("messages.cms_correlation_id");
        a57.e(true);
        a57.h(new wsy());
        a57.a();
        agmi a58 = agmk.a();
        a58.k(1);
        a58.c(true);
        a58.d(true);
        a58.g(new sbg(19));
        a58.b("messages.group_private_participant");
        a58.h(new wsy());
        a58.a();
        agmi a59 = agmk.a();
        a59.k(1);
        a59.c(true);
        a59.d(true);
        a59.g(new sbg(20));
        a59.b("messages.original_message_id");
        a59.h(new wsy());
        a59.a();
        agmi a60 = agmk.a();
        a60.k(1);
        a60.b("messages.awaiting_reverse_sync");
        a60.h(new wsy());
        a60.a();
        agmi a61 = agmk.a();
        a61.k(4);
        a61.b("messages.old_sms_message_uri");
        a61.h(new wsy());
        a61.a();
        agmi a62 = agmk.a();
        a62.k(4);
        a62.j(true);
        a62.c(true);
        a62.b("messages.draft_id");
        a62.e(true);
        a62.h(new wsy());
        a62.a();
        agmi a63 = agmk.a();
        a63.k(1);
        a63.b("messages.result_code");
        a63.h(new wsy());
        a63.a();
        agmi a64 = agmk.a();
        a64.k(1);
        a64.b("messages.cms_life_cycle");
        a64.h(new wsy());
        a64.a();
        agmi a65 = agmk.a();
        a65.k(1);
        a65.b("messages.fallback_reason");
        a65.h(new wsy());
        a65.a();
        agmi a66 = agmk.a();
        a66.k(1);
        a66.b("messages.auto_retry_counter");
        a66.h(new wsy());
        a66.a();
        agmi a67 = agmk.a();
        a67.k(2);
        a67.b("messages.can_revoke_before_delivered_with_rcs");
        a67.h(new wsy());
        a67.a();
        agmi a68 = agmk.a();
        a68.k(5);
        a68.b("messages.trace_id");
        a68.h(new wsy());
        a68.a();
        agmi a69 = agmk.a();
        a69.k(1);
        a69.b("messages.outgoing_delivery_report_status");
        a69.h(new wsy());
        a69.a();
        agmi a70 = agmk.a();
        a70.k(1);
        a70.b("messages.outgoing_read_report_status");
        a70.h(new wsy());
        a70.a();
        agmi a71 = agmk.a();
        a71.k(1);
        a71.b("messages.xms_transport");
        a71.h(new wsy());
        a71.a();
        agmi a72 = agmk.a();
        a72.k(1);
        a72.b("messages.message_original_protocol");
        a72.h(new wsy());
        a72.a();
        agmi a73 = agmk.a();
        a73.k(4);
        a73.j(true);
        a73.c(true);
        a73.b("messages.satellite_datagram_id");
        a73.e(true);
        a73.h(new wsy());
        a73.a();
        agmi a74 = agmk.a();
        a74.k(1);
        a74.b("messages.encryption_protocol");
        a74.h(new wsy());
        a74.a();
        agmi a75 = agmk.a();
        a75.k(4);
        a75.j(true);
        a75.c(true);
        a75.b("messages.message_persistence_id");
        a75.e(true);
        a75.h(new wsy());
        a75.a();
        agmi a76 = agmk.a();
        a76.k(1);
        a76.c(true);
        a76.b("participants.sub_id");
        a76.e(true);
        a76.h(new wsy());
        a76.a();
        agmi a77 = agmk.a();
        a77.k(4);
        a77.c(true);
        a77.b("participants.normalized_destination");
        a77.e(true);
        a77.h(new wsy());
        a77.a();
        agmi a78 = agmk.a();
        a78.k(4);
        a78.b("participants.full_name");
        a78.h(new wsy());
        a78.a();
        agmi a79 = agmk.a();
        a79.k(2);
        a79.j(true);
        a79.f(true);
        a79.c(true);
        a79.b("participants._id");
        a79.h(new wsy());
        a79.a();
        agmi a80 = agmk.a();
        a80.k(4);
        a80.c(true);
        a80.b("participants.my_identity_token");
        a80.h(new wsy());
        a80.a();
        agmi a81 = agmk.a();
        a81.k(4);
        a81.c(true);
        a81.d(true);
        a81.g(new scg(1));
        a81.b("participants.my_identity_token_foreign_key");
        a81.h(new wsy());
        a81.a();
        agmi a82 = agmk.a();
        a82.k(1);
        a82.b("participants.sim_slot_id");
        a82.h(new wsy());
        a82.a();
        agmi a83 = agmk.a();
        a83.k(4);
        a83.b("participants.send_destination");
        a83.h(new wsy());
        a83.a();
        agmi a84 = agmk.a();
        a84.k(4);
        a84.b("participants.display_destination");
        a84.h(new wsy());
        a84.a();
        agmi a85 = agmk.a();
        a85.k(4);
        a85.j(true);
        a85.c(true);
        a85.b("participants.comparable_destination");
        a85.e(true);
        a85.h(new wsy());
        a85.a();
        agmi a86 = agmk.a();
        a86.k(4);
        a86.b("participants.country_code");
        a86.h(new wsy());
        a86.a();
        agmi a87 = agmk.a();
        a87.k(2);
        a87.j(true);
        a87.c(true);
        a87.b("participants.recipient_id");
        a87.e(true);
        a87.h(new wsy());
        a87.a();
        agmi a88 = agmk.a();
        a88.k(4);
        a88.b("participants.recipient_canonical_address");
        a88.h(new wsy());
        a88.a();
        agmi a89 = agmk.a();
        a89.k(4);
        a89.b("participants.first_name");
        a89.h(new wsy());
        a89.a();
        agmi a90 = agmk.a();
        a90.k(4);
        a90.b("participants.profile_photo_uri");
        a90.h(new wsy());
        a90.a();
        agmi a91 = agmk.a();
        a91.k(4);
        a91.b("participants.contact_photo_uri");
        a91.h(new wsy());
        a91.a();
        agmi a92 = agmk.a();
        a92.k(1);
        a92.b("participants.contact_id");
        a92.h(new wsy());
        a92.a();
        agmi a93 = agmk.a();
        a93.k(4);
        a93.b("participants.lookup_key");
        a93.h(new wsy());
        a93.a();
        agmi a94 = agmk.a();
        a94.k(1);
        a94.b("participants.color_palette_index");
        a94.h(new wsy());
        a94.a();
        agmi a95 = agmk.a();
        a95.k(1);
        a95.b("participants.color_type");
        a95.h(new wsy());
        a95.a();
        agmi a96 = agmk.a();
        a96.k(1);
        a96.b("participants.extended_color");
        a96.h(new wsy());
        a96.a();
        agmi a97 = agmk.a();
        a97.k(1);
        a97.b("participants.blocked");
        a97.h(new wsy());
        a97.a();
        agmi a98 = agmk.a();
        a98.k(4);
        a98.b("participants.subscription_name");
        a98.h(new wsy());
        a98.a();
        agmi a99 = agmk.a();
        a99.k(1);
        a99.b("participants.subscription_color");
        a99.h(new wsy());
        a99.a();
        agmi a100 = agmk.a();
        a100.k(4);
        a100.b("participants.contact_destination");
        a100.h(new wsy());
        a100.a();
        agmi a101 = agmk.a();
        a101.k(1);
        a101.b("participants.participant_type");
        a101.h(new wsy());
        a101.a();
        agmi a102 = agmk.a();
        a102.k(1);
        a102.b("participants.video_reachability");
        a102.h(new wsy());
        a102.a();
        agmi a103 = agmk.a();
        a103.k(4);
        a103.b("participants.alias");
        a103.h(new wsy());
        a103.a();
        agmi a104 = agmk.a();
        a104.k(1);
        a104.b("participants.is_spam");
        a104.h(new wsy());
        a104.a();
        agmi a105 = agmk.a();
        a105.k(1);
        a105.b("participants.is_rcs_available");
        a105.h(new wsy());
        a105.a();
        agmi a106 = agmk.a();
        a106.k(1);
        a106.b("participants.is_spam_source");
        a106.h(new wsy());
        a106.a();
        agmi a107 = agmk.a();
        a107.k(4);
        a107.j(true);
        a107.c(true);
        a107.b("participants.cms_id");
        a107.e(true);
        a107.h(new wsy());
        a107.a();
        agmi a108 = agmk.a();
        a108.k(1);
        a108.b("participants.latest_verification_status");
        a108.h(new wsy());
        a108.a();
        agmi a109 = agmk.a();
        a109.k(4);
        a109.b("participants.profile_photo_blob_id");
        a109.h(new wsy());
        a109.a();
        agmi a110 = agmk.a();
        a110.k(5);
        a110.b("participants.profile_photo_encryption_key");
        a110.h(new wsy());
        a110.a();
        agmi a111 = agmk.a();
        a111.k(1);
        a111.b("participants.directory_id");
        a111.h(new wsy());
        a111.a();
        agmi a112 = agmk.a();
        a112.k(1);
        a112.b("participants.is_check_constraint_enabled_via_phenotype");
        a112.h(new wsy());
        a112.a();
        agmi a113 = agmk.a();
        a113.k(1);
        a113.b("participants.is_valid_phone_number_data");
        a113.h(new wsy());
        a113.a();
        agmi a114 = agmk.a();
        a114.k(2);
        a114.c(true);
        a114.d(true);
        a114.g(new scg(0));
        a114.b("participants.duplicate_of");
        a114.h(new wsy());
        a114.a();
        agmi a115 = agmk.a();
        a115.k(1);
        a115.b("participants.cms_life_cycle");
        a115.h(new wsy());
        a115.a();
        agmi a116 = agmk.a();
        a116.k(1);
        a116.b("participants.norm_ui_status");
        a116.h(new wsy());
        a116.a();
        agmi a117 = agmk.a();
        a117.k(4);
        a117.b("participants.last_modified_by_key");
        a117.h(new wsy());
        a117.a();
        agmi a118 = agmk.a();
        a118.k(1);
        a118.b("participants.name_source");
        a118.h(new wsy());
        a118.a();
        agmi a119 = agmk.a();
        a119.k(1);
        a119.b("participants.photo_source");
        a119.h(new wsy());
        a119.a();
        agmi a120 = agmk.a();
        a120.k(1);
        a120.b("participants.profile_photo_user_preference");
        a120.h(new wsy());
        a120.a();
        agmi a121 = agmk.a();
        a121.k(5);
        a121.b("participants.contact_metadata");
        a121.h(new wsy());
        a121.a();
        agmi a122 = agmk.a();
        a122.k(2);
        a122.j(true);
        a122.f(true);
        a122.c(true);
        a122.b("message_star._id");
        a122.h(new wsy());
        a122.a();
        agmi a123 = agmk.a();
        a123.k(2);
        a123.j(true);
        a123.c(true);
        a123.d(true);
        a123.g(new scg(2));
        a123.b("message_star.message_id");
        a123.e(true);
        a123.h(new wsy());
        a123.a();
        agmi a124 = agmk.a();
        a124.k(2);
        a124.j(true);
        a124.f(true);
        a124.c(true);
        a124.d(true);
        a124.g(new scg(3));
        a124.b("parent_disallowed_conversations.conversation_id");
        a124.h(new wsy());
        a124.a();
        agmi a125 = agmk.a();
        a125.k(4);
        a125.c(true);
        a125.b("conversations.participant_normalized_destination");
        a125.h(new wsy());
        a125.a();
        agmi a126 = agmk.a();
        a126.k(1);
        a126.b("conversations.has_ea2p_bot_recipient");
        a126.h(new wsy());
        a126.a();
        agmi a127 = agmk.a();
        a127.k(2);
        a127.j(true);
        a127.f(true);
        a127.c(true);
        a127.b("conversations._id");
        a127.h(new wsy());
        a127.a();
        agmi a128 = agmk.a();
        a128.k(1);
        a128.c(true);
        a128.b("conversations.sms_thread_id");
        a128.h(new wsy());
        a128.a();
        agmi a129 = agmk.a();
        a129.k(4);
        a129.b("conversations.name");
        a129.h(new wsy());
        a129.a();
        agmi a130 = agmk.a();
        a130.k(2);
        a130.b("conversations.name_is_automatic");
        a130.h(new wsy());
        a130.a();
        agmi a131 = agmk.a();
        a131.k(4);
        a131.b("conversations.subtitle");
        a131.h(new wsy());
        a131.a();
        agmi a132 = agmk.a();
        a132.k(1);
        a132.b("conversations.latest_message_id");
        a132.h(new wsy());
        a132.a();
        agmi a133 = agmk.a();
        a133.k(4);
        a133.b("conversations.snippet_text");
        a133.h(new wsy());
        a133.a();
        agmi a134 = agmk.a();
        a134.k(4);
        a134.b("conversations.subject_text");
        a134.h(new wsy());
        a134.a();
        agmi a135 = agmk.a();
        a135.k(4);
        a135.b("conversations.preview_uri");
        a135.h(new wsy());
        a135.a();
        agmi a136 = agmk.a();
        a136.k(4);
        a136.b("conversations.preview_content_type");
        a136.h(new wsy());
        a136.a();
        agmi a137 = agmk.a();
        a137.k(1);
        a137.b("conversations.show_draft");
        a137.h(new wsy());
        a137.a();
        agmi a138 = agmk.a();
        a138.k(4);
        a138.b("conversations.draft_snippet_text");
        a138.h(new wsy());
        a138.a();
        agmi a139 = agmk.a();
        a139.k(4);
        a139.b("conversations.draft_subject_text");
        a139.h(new wsy());
        a139.a();
        agmi a140 = agmk.a();
        a140.k(4);
        a140.b("conversations.draft_preview_uri");
        a140.h(new wsy());
        a140.a();
        agmi a141 = agmk.a();
        a141.k(4);
        a141.b("conversations.draft_preview_content_type");
        a141.h(new wsy());
        a141.a();
        agmi a142 = agmk.a();
        a142.k(1);
        a142.b("conversations.etouffee_default");
        a142.h(new wsy());
        a142.a();
        agmi a143 = agmk.a();
        a143.k(1);
        a143.c(true);
        a143.b("conversations.archive_status");
        a143.h(new wsy());
        a143.a();
        agmi a144 = agmk.a();
        a144.k(1);
        a144.c(true);
        a144.b("conversations.sort_timestamp");
        a144.h(new wsy());
        a144.a();
        agmi a145 = agmk.a();
        a145.k(1);
        a145.b("conversations.last_read_timestamp");
        a145.h(new wsy());
        a145.a();
        agmi a146 = agmk.a();
        a146.k(4);
        a146.b("conversations.icon");
        a146.h(new wsy());
        a146.a();
        agmi a147 = agmk.a();
        a147.k(1);
        a147.b("conversations.participant_contact_id");
        a147.h(new wsy());
        a147.a();
        agmi a148 = agmk.a();
        a148.k(1);
        a148.b("conversations.normalized_participant_contact_id");
        a148.h(new wsy());
        a148.a();
        agmi a149 = agmk.a();
        a149.k(4);
        a149.b("conversations.participant_lookup_key");
        a149.h(new wsy());
        a149.a();
        agmi a150 = agmk.a();
        a150.k(4);
        a150.b("conversations.normalized_participant_lookup_key");
        a150.h(new wsy());
        a150.a();
        agmi a151 = agmk.a();
        a151.k(4);
        a151.j(true);
        a151.c(true);
        a151.b("conversations.participant_comparable_destination");
        a151.e(true);
        a151.h(new wsy());
        a151.a();
        agmi a152 = agmk.a();
        a152.k(4);
        a152.b("conversations.current_self_id");
        a152.h(new wsy());
        a152.a();
        agmi a153 = agmk.a();
        a153.k(4);
        a153.b("conversations.current_my_identity");
        a153.h(new wsy());
        a153.a();
        agmi a154 = agmk.a();
        a154.k(4);
        a154.c(true);
        a154.d(true);
        a154.g(new scg(4));
        a154.b("conversations.current_my_identity_foreign_key");
        a154.h(new wsy());
        a154.a();
        agmi a155 = agmk.a();
        a155.k(4);
        a155.c(true);
        a155.d(true);
        a155.g(new scg(5));
        a155.b("conversations.destination_token");
        a155.h(new wsy());
        a155.a();
        agmi a156 = agmk.a();
        a156.k(1);
        a156.b("conversations.participant_count");
        a156.h(new wsy());
        a156.a();
        agmi a157 = agmk.a();
        a157.k(1);
        a157.b("conversations.notification_enabled");
        a157.h(new wsy());
        a157.a();
        agmi a158 = agmk.a();
        a158.k(4);
        a158.b("conversations.notification_sound_uri");
        a158.h(new wsy());
        a158.a();
        agmi a159 = agmk.a();
        a159.k(1);
        a159.b("conversations.notification_vibration");
        a159.h(new wsy());
        a159.a();
        agmi a160 = agmk.a();
        a160.k(1);
        a160.b("conversations.include_email_addr");
        a160.h(new wsy());
        a160.a();
        agmi a161 = agmk.a();
        a161.k(4);
        a161.b("conversations.sms_service_center");
        a161.h(new wsy());
        a161.a();
        agmi a162 = agmk.a();
        a162.k(4);
        a162.b("conversations.participant_id_list");
        a162.h(new wsy());
        a162.a();
        agmi a163 = agmk.a();
        a163.k(4);
        a163.j(true);
        a163.c(true);
        a163.b("conversations.normalized_participant_id_list");
        a163.e(true);
        a163.h(new wsy());
        a163.a();
        agmi a164 = agmk.a();
        a164.k(1);
        a164.b("conversations.source_type");
        a164.h(new wsy());
        a164.a();
        agmi a165 = agmk.a();
        a165.k(1);
        a165.c(true);
        a165.b("conversations.rcs_session_id");
        a165.h(new wsy());
        a165.a();
        agmi a166 = agmk.a();
        a166.k(1);
        a166.b("conversations.join_state");
        a166.h(new wsy());
        a166.a();
        agmi a167 = agmk.a();
        a167.k(1);
        a167.b("conversations.conv_type");
        a167.h(new wsy());
        a167.a();
        agmi a168 = agmk.a();
        a168.k(1);
        a168.b("conversations.send_mode");
        a168.h(new wsy());
        a168.a();
        agmi a169 = agmk.a();
        a169.k(1);
        a169.b("conversations.IS_ENTERPRISE");
        a169.h(new wsy());
        a169.a();
        agmi a170 = agmk.a();
        a170.k(1);
        a170.b("conversations.last_interactive_event_timestamp");
        a170.h(new wsy());
        a170.a();
        agmi a171 = agmk.a();
        a171.k(4);
        a171.b("conversations.participant_display_destination");
        a171.h(new wsy());
        a171.a();
        agmi a172 = agmk.a();
        a172.k(4);
        a172.b("conversations.normalized_participant_display_destination");
        a172.h(new wsy());
        a172.a();
        agmi a173 = agmk.a();
        a173.k(1);
        a173.b("conversations.spam_warning_dismiss_status");
        a173.h(new wsy());
        a173.a();
        agmi a174 = agmk.a();
        a174.k(1);
        a174.b("conversations.open_count");
        a174.h(new wsy());
        a174.a();
        agmi a175 = agmk.a();
        a175.k(1);
        a175.b("conversations.last_logged_scooby_metadata_timestamp");
        a175.h(new wsy());
        a175.a();
        agmi a176 = agmk.a();
        a176.k(1);
        a176.c(true);
        a176.b("conversations.delete_timestamp");
        a176.h(new wsy());
        a176.a();
        agmi a177 = agmk.a();
        a177.k(4);
        a177.j(true);
        a177.c(true);
        a177.b("conversations.cms_id");
        a177.e(true);
        a177.h(new wsy());
        a177.a();
        agmi a178 = agmk.a();
        a178.k(4);
        a178.c(true);
        a178.b("conversations.rcs_group_id");
        a178.h(new wsy());
        a178.a();
        agmi a179 = agmk.a();
        a179.k(4);
        a179.b("conversations.rcs_conference_uri");
        a179.h(new wsy());
        a179.a();
        agmi a180 = agmk.a();
        a180.k(5);
        a180.b("conversations.tachygram_group_routing_info_token");
        a180.h(new wsy());
        a180.a();
        agmi a181 = agmk.a();
        a181.k(1);
        a181.b("conversations.cms_most_recent_read_message_timestamp_ms");
        a181.h(new wsy());
        a181.a();
        agmi a182 = agmk.a();
        a182.k(2);
        a182.b("conversations.rcs_subject_change_timestamp_ms");
        a182.h(new wsy());
        a182.a();
        agmi a183 = agmk.a();
        a183.k(1);
        a183.b("conversations.rcs_session_allows_revocation");
        a183.h(new wsy());
        a183.a();
        agmi a184 = agmk.a();
        a184.k(2);
        a184.b("conversations.rcs_group_capabilities");
        a184.h(new wsy());
        a184.a();
        agmi a185 = agmk.a();
        a185.k(1);
        a185.b("conversations.awaiting_reverse_sync");
        a185.h(new wsy());
        a185.a();
        agmi a186 = agmk.a();
        a186.k(2);
        a186.c(true);
        a186.d(true);
        a186.g(new sbg(15));
        a186.b("conversations.duplicate_of");
        a186.h(new wsy());
        a186.a();
        agmi a187 = agmk.a();
        a187.k(2);
        a187.c(true);
        a187.d(true);
        a187.g(new sbg(16));
        a187.b("conversations.new_duplicate_of");
        a187.h(new wsy());
        a187.a();
        agmi a188 = agmk.a();
        a188.k(1);
        a188.b("conversations.error_state");
        a188.h(new wsy());
        a188.a();
        agmi a189 = agmk.a();
        a189.k(1);
        a189.b("conversations.cms_life_cycle");
        a189.h(new wsy());
        a189.a();
        agmi a190 = agmk.a();
        a190.k(4);
        a190.b("conversations.rcs_group_self_msisdn");
        a190.h(new wsy());
        a190.a();
        agmi a191 = agmk.a();
        a191.k(2);
        a191.b("conversations.recipient_offline_timestamp_ms");
        a191.h(new wsy());
        a191.a();
        agmi a192 = agmk.a();
        a192.k(2);
        a192.b("conversations.rcs_group_last_sync_timestamp");
        a192.h(new wsy());
        a192.a();
        agmi a193 = agmk.a();
        a193.k(1);
        a193.b("conversations.has_been_e2ee");
        a193.h(new wsy());
        a193.a();
        agmi a194 = agmk.a();
        a194.k(1);
        a194.b("conversations.marked_as_unread");
        a194.h(new wsy());
        a194.a();
        agmi a195 = agmk.a();
        a195.k(5);
        a195.b("conversations.custom_theme");
        a195.h(new wsy());
        a195.a();
        agmi a196 = agmk.a();
        a196.k(2);
        a196.b("conversations.mms_group_upgrade_status");
        a196.h(new wsy());
        a196.a();
        agmi a197 = agmk.a();
        a197.k(2);
        a197.b("conversations.mms_group_upgrade_retries");
        a197.h(new wsy());
        a197.a();
        agmi a198 = agmk.a();
        a198.k(2);
        a198.b("conversations.encryption_protocol");
        a198.h(new wsy());
        a198.a();
        agmi a199 = agmk.a();
        a199.k(4);
        a199.b("conversations.encryption_id");
        a199.h(new wsy());
        a199.a();
        agmi a200 = agmk.a();
        a200.k(4);
        a200.j(true);
        a200.c(true);
        a200.b("conversations.cms_correlation_id");
        a200.e(true);
        a200.h(new wsy());
        a200.a();
    }
}
