package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class ae {
    public int b;
    public int c;
    int d;
    boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = brg.a;
    public float O = brg.a;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = brg.a;
    public float U = brg.a;
    public float V = brg.a;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = brg.a;
    public float Z = brg.a;
    public float aa = brg.a;
    public float ab = brg.a;
    public float ac = brg.a;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(ad adVar) {
        adVar.d = this.h;
        adVar.e = this.i;
        adVar.f = this.j;
        adVar.g = this.k;
        adVar.h = this.l;
        adVar.i = this.m;
        adVar.j = this.n;
        adVar.k = this.o;
        adVar.l = this.p;
        adVar.m = this.q;
        adVar.n = this.r;
        adVar.o = this.s;
        adVar.p = this.t;
        adVar.leftMargin = this.A;
        adVar.rightMargin = this.B;
        adVar.topMargin = this.C;
        adVar.bottomMargin = this.D;
        adVar.u = this.M;
        adVar.v = this.L;
        adVar.w = this.u;
        adVar.x = this.v;
        adVar.y = this.w;
        adVar.K = this.x;
        adVar.L = this.y;
        adVar.B = this.N;
        adVar.A = this.O;
        adVar.D = this.Q;
        adVar.C = this.P;
        adVar.E = this.ad;
        adVar.F = this.ae;
        adVar.I = this.af;
        adVar.J = this.ag;
        adVar.G = this.ah;
        adVar.H = this.ai;
        adVar.M = this.z;
        adVar.c = this.g;
        adVar.a = this.e;
        adVar.b = this.f;
        adVar.width = this.b;
        adVar.height = this.c;
        adVar.setMarginStart(this.F);
        adVar.setMarginEnd(this.E);
        adVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ae aeVar = new ae();
        aeVar.a = this.a;
        aeVar.b = this.b;
        aeVar.c = this.c;
        aeVar.e = this.e;
        aeVar.f = this.f;
        aeVar.g = this.g;
        aeVar.h = this.h;
        aeVar.i = this.i;
        aeVar.j = this.j;
        aeVar.k = this.k;
        aeVar.l = this.l;
        aeVar.m = this.m;
        aeVar.n = this.n;
        aeVar.o = this.o;
        aeVar.p = this.p;
        aeVar.q = this.q;
        aeVar.r = this.r;
        aeVar.s = this.s;
        aeVar.t = this.t;
        aeVar.u = this.u;
        aeVar.v = this.v;
        aeVar.w = this.w;
        aeVar.x = this.x;
        aeVar.y = this.y;
        aeVar.u = this.u;
        aeVar.u = this.u;
        aeVar.u = this.u;
        aeVar.u = this.u;
        aeVar.u = this.u;
        aeVar.z = this.z;
        aeVar.A = this.A;
        aeVar.B = this.B;
        aeVar.C = this.C;
        aeVar.D = this.D;
        aeVar.E = this.E;
        aeVar.F = this.F;
        aeVar.G = this.G;
        aeVar.H = this.H;
        aeVar.I = this.I;
        aeVar.J = this.J;
        aeVar.K = this.K;
        aeVar.L = this.L;
        aeVar.M = this.M;
        aeVar.N = this.N;
        aeVar.O = this.O;
        aeVar.P = this.P;
        aeVar.Q = this.Q;
        aeVar.R = this.R;
        aeVar.S = this.S;
        aeVar.T = this.T;
        aeVar.U = this.U;
        aeVar.V = this.V;
        aeVar.W = this.W;
        aeVar.X = this.X;
        aeVar.Y = this.Y;
        aeVar.Z = this.Z;
        aeVar.aa = this.aa;
        aeVar.ab = this.ab;
        aeVar.ac = this.ac;
        aeVar.ad = this.ad;
        aeVar.ae = this.ae;
        aeVar.af = this.af;
        aeVar.ag = this.ag;
        aeVar.ah = this.ah;
        aeVar.ai = this.ai;
        return aeVar;
    }
}
