package defpackage;

import com.android.vcard.VCardConstants;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: PG */
/* loaded from: classes4.dex */
public final class aerb {
    private static final /* synthetic */ aerb[] dS;
    public static final aerb a = new aerb("ACCESSIBILITY_NEW", 0);
    public static final aerb b = new aerb("ACCOUNT_CIRCLE", 1);
    public static final aerb c = new aerb("ACCOUNT_CIRCLE_OFF", 2);
    public static final aerb d = new aerb("ADD", 3);
    public static final aerb e = new aerb("ADD_CALL", 4);
    public static final aerb f = new aerb("ADD_CIRCLE", 5);
    public static final aerb g = new aerb("ADD_CIRCLE_FILLED", 6);
    public static final aerb h = new aerb("ADD_REACTION", 7);
    public static final aerb i = new aerb("ALARM", 8);
    public static final aerb j = new aerb("ALARM_ON", 9);
    public static final aerb k = new aerb("ALARM_ON_FILLED", 10);
    public static final aerb l = new aerb("ANDROID_CONTACTS", 11);
    public static final aerb m = new aerb("ANDROID_SATELLITE", 12);
    public static final aerb n = new aerb("ARROW_BACK", 13);
    public static final aerb o = new aerb("ARROW_DOWNWARD", 14);
    public static final aerb p = new aerb("ARROW_DROP_DOWN", 15);
    public static final aerb q = new aerb("ARROW_DROP_UP", 16);
    public static final aerb r = new aerb("ARROW_FORWARD", 17);
    public static final aerb s = new aerb("ARROW_RIGHT_ALT", 18);
    public static final aerb t = new aerb(VCardConstants.PARAM_PHONE_EXTRA_TYPE_ASSISTANT, 19);
    public static final aerb u = new aerb("ATTACH_FILE", 20);
    public static final aerb v = new aerb("AUTORENEW", 21);
    public static final aerb w = new aerb("AVATAR_ANONYMOUS", 22);
    public static final aerb x = new aerb("BACK_HAND", 23);
    public static final aerb y = new aerb("BLOCK", 24);
    public static final aerb z = new aerb("BLOCK_FILLED", 25);
    public static final aerb A = new aerb("BLUR_ON", 26);
    public static final aerb B = new aerb("BOOKMARK", 27);
    public static final aerb C = new aerb("BOTTOM_SHEETS", 28);
    public static final aerb D = new aerb("BRIGHTNESS_2", 29);
    public static final aerb E = new aerb("BRIGHTNESS_4", 30);
    public static final aerb F = new aerb("BRIGHTNESS_5", 31);
    public static final aerb G = new aerb("BRIGHTNESS_6", 32);
    public static final aerb H = new aerb("BUTTONS_ALT", 33);
    public static final aerb I = new aerb("CAKE", 34);
    public static final aerb J = new aerb("CALENDAR_ADD", 35);
    public static final aerb K = new aerb("CALENDAR_MONTH", 36);
    public static final aerb L = new aerb("CALENDAR_TODAY", 37);
    public static final aerb M = new aerb("CALL", 38);
    public static final aerb N = new aerb("CALL_END", 39);
    public static final aerb O = new aerb("CALL_FILLED", 40);
    public static final aerb P = new aerb("CALL_MERGE", 41);
    public static final aerb Q = new aerb("CALL_WITH_DIALER", 42);
    public static final aerb R = new aerb("CANCEL", 43);
    public static final aerb S = new aerb("CANCEL_FILLED", 44);
    public static final aerb T = new aerb("CANCEL_FILLED_NO_PADDING", 45);
    public static final aerb U = new aerb("CHAT", 46);
    public static final aerb V = new aerb("CHAT_BUBBLE", 47);
    public static final aerb W = new aerb("CHAT_MIRROR", 48);
    public static final aerb X = new aerb("CHECK", 49);
    public static final aerb Y = new aerb("CHECK_CIRCLE", 50);
    public static final aerb Z = new aerb("CHECK_CIRCLE_FILLED", 51);
    public static final aerb aa = new aerb("CHEVRON_LEFT", 52);
    public static final aerb ab = new aerb("CHEVRON_RIGHT", 53);
    public static final aerb ac = new aerb("CLOSE", 54);
    public static final aerb ad = new aerb("CLOSE_FULLSCREEN", 55);
    public static final aerb ae = new aerb("CLOUD_OFF", 56);
    public static final aerb af = new aerb("COMPOSE_ADD_LEGACY", 57);
    public static final aerb ag = new aerb("COMPOSE_ADD_LEGACY_SELECTED", 58);
    public static final aerb ah = new aerb("COMPOSE_EMOJI", 59);
    public static final aerb ai = new aerb("COMPOSE_EMOJI_SELECTED", 60);
    public static final aerb aj = new aerb("COMPOSE_GALLERY", 61);
    public static final aerb ak = new aerb("COMPOSE_GALLERY_LEGACY", 62);
    public static final aerb al = new aerb("COMPOSE_GALLERY_LEGACY_SELECTED", 63);
    public static final aerb am = new aerb("COMPOSE_GALLERY_SELECTED", 64);
    public static final aerb an = new aerb("COMPOSE_MAGIC_COMPOSE", 65);
    public static final aerb ao = new aerb("COMPOSE_MAGIC_COMPOSE_SELECTED", 66);
    public static final aerb ap = new aerb("COMPOSE_SIM", 67);
    public static final aerb aq = new aerb("COMPOSE_SIM_FILLED", 68);
    public static final aerb ar = new aerb("COMPOSE_VOICE_FILLED", 69);
    public static final aerb as = new aerb("CONTACTS", 70);
    public static final aerb at = new aerb("CONTACTS_PRODUCT", 71);
    public static final aerb au = new aerb("CONTENT_COPY", 72);
    public static final aerb av = new aerb("CROP", 73);
    public static final aerb aw = new aerb("DELETE", 74);
    public static final aerb ax = new aerb("DESCRIPTION", 75);
    public static final aerb ay = new aerb("DEVICES", 76);
    public static final aerb az = new aerb("DIALPAD", 77);
    public static final aerb aA = new aerb("DOGFOOD", 78);
    public static final aerb aB = new aerb("DOMAIN", 79);
    public static final aerb aC = new aerb("DOWNLOAD", 80);
    public static final aerb aD = new aerb("DOWNLOADING", 81);
    public static final aerb aE = new aerb("DRAFT", 82);
    public static final aerb aF = new aerb("DRIVE_PDF", 83);
    public static final aerb aG = new aerb("DRIVE_PRESENTATION", 84);
    public static final aerb aH = new aerb("DRIVE_SPREADSHEET", 85);
    public static final aerb aI = new aerb("DRIVE_ZIP", 86);
    public static final aerb aJ = new aerb("EDIT", 87);
    public static final aerb aK = new aerb("EMERGENCY", 88);
    public static final aerb aL = new aerb("ENCRYPTION_SHIELD", 89);
    public static final aerb aM = new aerb("ERROR", 90);
    public static final aerb aN = new aerb("ERROR_FILLED", 91);
    public static final aerb aO = new aerb("EVENT", 92);
    public static final aerb aP = new aerb("EXPAND_LESS", 93);
    public static final aerb aQ = new aerb("EXPAND_MORE", 94);
    public static final aerb aR = new aerb("EXPERIMENT", 95);
    public static final aerb aS = new aerb("EXTENSION", 96);
    public static final aerb aT = new aerb("FACT_CHECK", 97);
    public static final aerb aU = new aerb("FAVORITE", 98);
    public static final aerb aV = new aerb("FIND_IN_PAGE", 99);
    public static final aerb aW = new aerb("FOLDER_COPY", 100);
    public static final aerb aX = new aerb("FORMAT_SIZE", 101);
    public static final aerb aY = new aerb("FORWARD", 102);
    public static final aerb aZ = new aerb("FULLSCREEN", 103);
    public static final aerb ba = new aerb("GEMINI_SPARK", 104);
    public static final aerb bb = new aerb("GEMINI_SPARK_FILLED", 105);
    public static final aerb bc = new aerb("GOOGLE", 106);
    public static final aerb bd = new aerb("GPP_MAYBE", 107);
    public static final aerb be = new aerb("GPP_MAYBE_FILLED", 108);
    public static final aerb bf = new aerb("GROUP", 109);
    public static final aerb bg = new aerb("GROUPS", 110);
    public static final aerb bh = new aerb("GROUP_ADD", 111);
    public static final aerb bi = new aerb("GROUP_ADD_FILLED", 112);
    public static final aerb bj = new aerb("GROUP_OFF", 113);
    public static final aerb bk = new aerb("GSHIELD", 114);
    public static final aerb bl = new aerb("HANDYMAN", 115);
    public static final aerb bm = new aerb("HELP", 116);
    public static final aerb bn = new aerb("HIDE", 117);
    public static final aerb bo = new aerb("HIDE_IMAGE", 118);
    public static final aerb bp = new aerb("HISTORY", 119);
    public static final aerb bq = new aerb("IMAGE", 120);
    public static final aerb br = new aerb("INFO", 121);
    public static final aerb bs = new aerb("INFO_FILLED", 122);
    public static final aerb bt = new aerb("INFO_SPARK", 123);
    public static final aerb bu = new aerb("INVENTORY_2", 124);
    public static final aerb bv = new aerb("KEYBOARD_ARROW_DOWN", 125);
    public static final aerb bw = new aerb("KEYBOARD_ARROW_UP", 126);
    public static final aerb bx = new aerb(VCardConstants.PARAM_LANGUAGE, 127);
    public static final aerb by = new aerb("LINK", 128);
    public static final aerb bz = new aerb("LIST", 129);
    public static final aerb bA = new aerb("LIST_ALT", 130);
    public static final aerb bB = new aerb("LOCATION_CHIP", 131);
    public static final aerb bC = new aerb("LOCATION_ON", 132);
    public static final aerb bD = new aerb("LOCK", 133);
    public static final aerb bE = new aerb("LOCK_CROSS", 134);
    public static final aerb bF = new aerb("LOCK_OPEN", 135);
    public static final aerb bG = new aerb("LOGOUT", 136);
    public static final aerb bH = new aerb("MAGIC_BUTTON_FILLED", 137);
    public static final aerb bI = new aerb("MESSAGES", 138);
    public static final aerb bJ = new aerb("MESSAGES_SPARK", 139);
    public static final aerb bK = new aerb("MESSAGES_SPARK_FILLED", 140);
    public static final aerb bL = new aerb("MIC", 141);
    public static final aerb bM = new aerb("MIC_FILLED", 142);
    public static final aerb bN = new aerb("MIC_OFF", 143);
    public static final aerb bO = new aerb("MMS", 144);
    public static final aerb bP = new aerb("MODE_NIGHT", 145);
    public static final aerb bQ = new aerb("MOOD", 146);
    public static final aerb bR = new aerb("MOOD_FILLED", 147);
    public static final aerb bS = new aerb("MORE_HORIZONTAL", 148);
    public static final aerb bT = new aerb("MORE_TIME", 149);
    public static final aerb bU = new aerb("MORE_VERTICAL", 150);
    public static final aerb bV = new aerb("MOVIE", 151);
    public static final aerb bW = new aerb("MY_LOCATION_FILLED", 152);
    public static final aerb bX = new aerb("NOTIFICATIONS", 153);
    public static final aerb bY = new aerb("NO_ACCOUNTS", 154);
    public static final aerb bZ = new aerb("OPEN_IN_FULL", 155);
    public static final aerb ca = new aerb("PALETTE", 156);
    public static final aerb cb = new aerb("PARTLY_CLOUDY_DAY", 157);
    public static final aerb cc = new aerb("PAUSE", 158);
    public static final aerb cd = new aerb("PAUSE_CIRCLE", 159);
    public static final aerb ce = new aerb("PAUSE_CIRCLE_FILLED", 160);
    public static final aerb cf = new aerb("PENDING", 161);
    public static final aerb cg = new aerb("PEN_SPARK", 162);
    public static final aerb ch = new aerb("PEN_SPARK_FILLED", 163);
    public static final aerb ci = new aerb("PEOPLE", 164);
    public static final aerb cj = new aerb("PERSON", 165);
    public static final aerb ck = new aerb("PERSON_ADD", 166);
    public static final aerb cl = new aerb("PERSON_ADD_FILLED", 167);
    public static final aerb cm = new aerb("PERSON_FILLED", 168);
    public static final aerb cn = new aerb("PERSON_OFF", 169);
    public static final aerb co = new aerb("PHONE_SPARK", 170);
    public static final aerb cp = new aerb(VCardConstants.PROPERTY_PHOTO, 171);
    public static final aerb cq = new aerb("PHOTO_CAMERA", 172);
    public static final aerb cr = new aerb("PIN_DROP", 173);
    public static final aerb cs = new aerb("PLAY_ARROW", 174);
    public static final aerb ct = new aerb("PLAY_ARROW_FILLED", 175);
    public static final aerb cu = new aerb("PLAY_CIRCLE", 176);
    public static final aerb cv = new aerb("PLAY_CIRCLE_FILLED", 177);
    public static final aerb cw = new aerb("PUBLIC", 178);
    public static final aerb cx = new aerb("REFRESH", 179);
    public static final aerb cy = new aerb("REPLY", 180);
    public static final aerb cz = new aerb("REPORT", 181);
    public static final aerb cA = new aerb("REPORT_FILLED", 182);
    public static final aerb cB = new aerb("RESTAURANT", 183);
    public static final aerb cC = new aerb("RTT", 184);
    public static final aerb cD = new aerb("SATELLITE_ALT", 185);
    public static final aerb cE = new aerb("SAVE", 186);
    public static final aerb cF = new aerb("SCREEN_ROTATION", 187);
    public static final aerb cG = new aerb("SEARCH", 188);
    public static final aerb cH = new aerb("SELECT_ALL", 189);
    public static final aerb cI = new aerb("SELFIE_GIF", 190);
    public static final aerb cJ = new aerb("SEND", 191);
    public static final aerb cK = new aerb("SEND_ENCRYPTED", 192);
    public static final aerb cL = new aerb("SEND_SCHEDULED", 193);
    public static final aerb cM = new aerb("SEND_SPARK", 194);
    public static final aerb cN = new aerb("SENTIMENT_FRUSTRATED", 195);
    public static final aerb cO = new aerb("SENTIMENT_SAD", 196);
    public static final aerb cP = new aerb("SETTINGS", 197);
    public static final aerb cQ = new aerb("SETTINGS_PHOTO_CAMERA", 198);
    public static final aerb cR = new aerb("SETTINGS_PHOTO_CAMERA_V2", 199);
    public static final aerb cS = new aerb("SHARE", BasePaymentResult.ERROR_REQUEST_FAILED);
    public static final aerb cT = new aerb("SHIELD_LOCKED", BasePaymentResult.ERROR_REQUEST_TIMEOUT);
    public static final aerb cU = new aerb("SIM_CARD", BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED);
    public static final aerb cV = new aerb("SMS", BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED);
    public static final aerb cW = new aerb("SMS_FAILED", 204);
    public static final aerb cX = new aerb("SORT_BY_ALPHA", 205);
    public static final aerb cY = new aerb("SOS", 206);
    public static final aerb cZ = new aerb("SPARK", 207);
    public static final aerb da = new aerb("SPARKLE_GALLERY", 208);
    public static final aerb db = new aerb("SPEECH_TO_TEXT", 209);
    public static final aerb dc = new aerb("STAR", 210);
    public static final aerb dd = new aerb("STAR_FILLED", 211);
    public static final aerb de = new aerb("STATUS_DELIVERED", 212);
    public static final aerb df = new aerb("STATUS_DOTS", 213);
    public static final aerb dg = new aerb("STATUS_DOUBLE_CHECK", 214);
    public static final aerb dh = new aerb("STATUS_GEMINI", 215);
    public static final aerb di = new aerb("STATUS_READ", 216);
    public static final aerb dj = new aerb("STATUS_SENDING", 217);
    public static final aerb dk = new aerb("STATUS_SENT", 218);
    public static final aerb dl = new aerb("STATUS_SINGLE_CHECK", 219);
    public static final aerb dm = new aerb("SUBTITLES", 220);
    public static final aerb dn = new aerb("SUNNY", 221);

    /* renamed from: do, reason: not valid java name */
    public static final aerb f0do = new aerb("SUPPORT_AGENT", 222);
    public static final aerb dp = new aerb("SWAP_CALLS", 223);
    public static final aerb dq = new aerb("SWAP_HORIZONTAL", 224);
    public static final aerb dr = new aerb("SWIPE", 225);
    public static final aerb ds = new aerb("SWITCH_ACCOUNT", 226);
    public static final aerb dt = new aerb("THUMB_DOWN", 227);
    public static final aerb du = new aerb("THUMB_UP", 228);
    public static final aerb dv = new aerb(VCardConstants.PROPERTY_TITLE, 229);
    public static final aerb dw = new aerb("TOGGLE_ON", 230);
    public static final aerb dx = new aerb("TRENDING_UP", 231);
    public static final aerb dy = new aerb("VERIFIED_BADGE", 232);
    public static final aerb dz = new aerb("VERIFIED_USER", 233);
    public static final aerb dA = new aerb("VERIFIED_USER_FILLED", 234);
    public static final aerb dB = new aerb("VERTICAL_ALIGN_BOTTOM", 235);
    public static final aerb dC = new aerb("VERTICAL_ALIGN_CENTER", 236);
    public static final aerb dD = new aerb("VERTICAL_ALIGN_TOP", 237);
    public static final aerb dE = new aerb("VIDEOCAM", 238);
    public static final aerb dF = new aerb("VIDEOCAM_FILLED", 239);
    public static final aerb dG = new aerb("VIDEOCAM_OFF", 240);
    public static final aerb dH = new aerb("VIDEOCAM_ONE_WAY", 241);
    public static final aerb dI = new aerb("VIEW_CAROUSEL", 242);
    public static final aerb dJ = new aerb("VISIBILITY", 243);
    public static final aerb dK = new aerb("VISIBILITY_OFF", 244);
    public static final aerb dL = new aerb("VOICEMAIL", 245);
    public static final aerb dM = new aerb("VOLUME_OFF", 246);
    public static final aerb dN = new aerb("VOLUME_UP", 247);
    public static final aerb dO = new aerb("VOLUNTEER_ACTIVISM", 248);
    public static final aerb dP = new aerb("WARNING", 249);
    public static final aerb dQ = new aerb("WIFI_FILLED", 250);
    public static final aerb dR = new aerb("WIFI_OFF", 251);

    static {
        aerb[] a2 = a();
        dS = a2;
        arhi.f(a2);
    }

    private aerb(String str, int i2) {
    }

    private static final /* synthetic */ aerb[] a() {
        return new aerb[]{a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, aA, aB, aC, aD, aE, aF, aG, aH, aI, aJ, aK, aL, aM, aN, aO, aP, aQ, aR, aS, aT, aU, aV, aW, aX, aY, aZ, ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, bA, bB, bC, bD, bE, bF, bG, bH, bI, bJ, bK, bL, bM, bN, bO, bP, bQ, bR, bS, bT, bU, bV, bW, bX, bY, bZ, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs, ct, cu, cv, cw, cx, cy, cz, cA, cB, cC, cD, cE, cF, cG, cH, cI, cJ, cK, cL, cM, cN, cO, cP, cQ, cR, cS, cT, cU, cV, cW, cX, cY, cZ, da, db, dc, dd, de, df, dg, dh, di, dj, dk, dl, dm, dn, f0do, dp, dq, dr, ds, dt, du, dv, dw, dx, dy, dz, dA, dB, dC, dD, dE, dF, dG, dH, dI, dJ, dK, dL, dM, dN, dO, dP, dQ, dR};
    }

    public static aerb[] values() {
        return (aerb[]) dS.clone();
    }
}
