package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class aezm {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    private final long I;
    private final long J;
    private final long K;
    private final long L;
    private final long M;
    public final ahhm a;
    public final aezl b;
    public final aezs c;
    public final aezk d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final boolean l;
    public final boolean m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public aezm(ahhm ahhmVar, aezl aezlVar, aezs aezsVar, aezk aezkVar, long j, long j2, long j3, long j4, long j5, long j6, long j7, boolean z, boolean z2, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33) {
        ahhmVar.getClass();
        aezsVar.getClass();
        this.a = ahhmVar;
        this.b = aezlVar;
        this.c = aezsVar;
        this.d = aezkVar;
        this.e = j;
        this.f = j2;
        this.g = j3;
        this.h = j4;
        this.i = j5;
        this.j = j6;
        this.k = j7;
        this.l = z;
        this.m = z2;
        this.n = j8;
        this.o = j9;
        this.p = j10;
        this.q = j11;
        this.r = j12;
        this.s = j13;
        this.t = j14;
        this.u = j15;
        this.v = j16;
        this.w = j17;
        this.x = j18;
        this.y = j19;
        this.z = j20;
        this.I = j21;
        this.J = j22;
        this.A = j23;
        this.B = j24;
        this.C = j25;
        this.D = j26;
        this.E = j27;
        this.K = j28;
        this.F = j29;
        this.L = j30;
        this.G = j31;
        this.M = j32;
        this.H = j33;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof aezm)) {
            return false;
        }
        aezm aezmVar = (aezm) obj;
        if (d.F(this.a, aezmVar.a) && d.F(this.b, aezmVar.b) && d.F(this.c, aezmVar.c) && d.F(this.d, aezmVar.d) && a.bB(this.e, aezmVar.e) && a.bB(this.f, aezmVar.f) && a.bB(this.g, aezmVar.g) && a.bB(this.h, aezmVar.h) && a.bB(this.i, aezmVar.i) && a.bB(this.j, aezmVar.j) && a.bB(this.k, aezmVar.k) && this.l == aezmVar.l && this.m == aezmVar.m && a.bB(this.n, aezmVar.n) && a.bB(this.o, aezmVar.o) && a.bB(this.p, aezmVar.p) && a.bB(this.q, aezmVar.q) && a.bB(this.r, aezmVar.r) && a.bB(this.s, aezmVar.s) && a.bB(this.t, aezmVar.t) && a.bB(this.u, aezmVar.u) && a.bB(this.v, aezmVar.v) && a.bB(this.w, aezmVar.w) && a.bB(this.x, aezmVar.x) && a.bB(this.y, aezmVar.y) && a.bB(this.z, aezmVar.z) && a.bB(this.I, aezmVar.I) && a.bB(this.J, aezmVar.J) && a.bB(this.A, aezmVar.A) && a.bB(this.B, aezmVar.B) && a.bB(this.C, aezmVar.C) && a.bB(this.D, aezmVar.D) && a.bB(this.E, aezmVar.E) && a.bB(this.K, aezmVar.K) && a.bB(this.F, aezmVar.F) && a.bB(this.L, aezmVar.L) && a.bB(this.G, aezmVar.G) && a.bB(this.M, aezmVar.M) && a.bB(this.H, aezmVar.H)) {
            return true;
        }
        return false;
    }

    public final int hashCode() {
        int hashCode = (((((((this.a.hashCode() * 31) + this.b.hashCode()) * 31) + this.c.hashCode()) * 31) + this.d.hashCode()) * 31) + a.A(this.e);
        long j = this.f;
        long j2 = this.g;
        int A = ((hashCode * 31) + a.A(j)) * 31;
        long j3 = this.h;
        int A2 = (A + a.A(j2)) * 31;
        long j4 = this.i;
        int A3 = (A2 + a.A(j3)) * 31;
        long j5 = this.j;
        int A4 = (A3 + a.A(j4)) * 31;
        long j6 = this.k;
        int A5 = (A4 + a.A(j5)) * 31;
        boolean z = this.l;
        int A6 = (A5 + a.A(j6)) * 31;
        boolean z2 = this.m;
        int v = (A6 + a.v(z)) * 31;
        long j7 = this.n;
        int v2 = (v + a.v(z2)) * 31;
        long j8 = this.o;
        int A7 = (v2 + a.A(j7)) * 31;
        long j9 = this.p;
        int A8 = (A7 + a.A(j8)) * 31;
        long j10 = this.q;
        int A9 = (A8 + a.A(j9)) * 31;
        long j11 = this.r;
        int A10 = (A9 + a.A(j10)) * 31;
        long j12 = this.s;
        int A11 = (A10 + a.A(j11)) * 31;
        long j13 = this.t;
        int A12 = (A11 + a.A(j12)) * 31;
        long j14 = this.u;
        int A13 = (A12 + a.A(j13)) * 31;
        long j15 = this.v;
        int A14 = (A13 + a.A(j14)) * 31;
        long j16 = this.w;
        int A15 = (A14 + a.A(j15)) * 31;
        long j17 = this.x;
        int A16 = (A15 + a.A(j16)) * 31;
        long j18 = this.y;
        return ((((((((((((((((((((((((((((((A16 + a.A(j17)) * 31) + a.A(j18)) * 31) + a.A(this.z)) * 31) + a.A(this.I)) * 31) + a.A(this.J)) * 31) + a.A(this.A)) * 31) + a.A(this.B)) * 31) + a.A(this.C)) * 31) + a.A(this.D)) * 31) + a.A(this.E)) * 31) + a.A(this.K)) * 31) + a.A(this.F)) * 31) + a.A(this.L)) * 31) + a.A(this.G)) * 31) + a.A(this.M)) * 31) + a.A(this.H);
    }

    public final String toString() {
        long j = this.H;
        long j2 = this.M;
        long j3 = this.G;
        long j4 = this.L;
        long j5 = this.F;
        long j6 = this.K;
        long j7 = this.E;
        long j8 = this.D;
        long j9 = this.C;
        long j10 = this.B;
        long j11 = this.A;
        long j12 = this.J;
        long j13 = this.I;
        long j14 = this.z;
        long j15 = this.y;
        long j16 = this.x;
        long j17 = this.w;
        long j18 = this.v;
        long j19 = this.u;
        long j20 = this.t;
        long j21 = this.s;
        long j22 = this.r;
        long j23 = this.q;
        long j24 = this.p;
        long j25 = this.o;
        long j26 = this.n;
        long j27 = this.k;
        long j28 = this.j;
        long j29 = this.i;
        long j30 = this.h;
        long j31 = this.g;
        long j32 = this.f;
        String g = cku.g(this.e);
        String g2 = cku.g(j32);
        String g3 = cku.g(j31);
        String g4 = cku.g(j30);
        String g5 = cku.g(j29);
        String g6 = cku.g(j28);
        String g7 = cku.g(j27);
        String g8 = cku.g(j26);
        String g9 = cku.g(j25);
        String g10 = cku.g(j24);
        String g11 = cku.g(j23);
        String g12 = cku.g(j22);
        String g13 = cku.g(j21);
        String g14 = cku.g(j20);
        String g15 = cku.g(j19);
        String g16 = cku.g(j18);
        String g17 = cku.g(j17);
        String g18 = cku.g(j16);
        String g19 = cku.g(j15);
        String g20 = cku.g(j14);
        String g21 = cku.g(j13);
        String g22 = cku.g(j12);
        String g23 = cku.g(j11);
        String g24 = cku.g(j10);
        String g25 = cku.g(j9);
        String g26 = cku.g(j8);
        String g27 = cku.g(j7);
        String g28 = cku.g(j6);
        String g29 = cku.g(j5);
        String g30 = cku.g(j4);
        String g31 = cku.g(j3);
        String g32 = cku.g(j2);
        String g33 = cku.g(j);
        StringBuilder sb = new StringBuilder("AbcColorScheme(tonalPalette=");
        sb.append(this.a);
        sb.append(", bubbleColors=");
        sb.append(this.b);
        sb.append(", monogramColors=");
        sb.append(this.c);
        sb.append(", backgroundColors=");
        sb.append(this.d);
        sb.append(", searchHighlight=");
        sb.append(g);
        sb.append(", onSearchHighlight=");
        sb.append(g2);
        sb.append(", searchHighlightFocused=");
        sb.append(g3);
        sb.append(", onSearchHighlightFocused=");
        sb.append(g4);
        sb.append(", mediaControlsBackground=");
        sb.append(g5);
        boolean z = this.m;
        boolean z2 = this.l;
        sb.append(", mediaControlsTint=");
        sb.append(g6);
        sb.append(", scrim=");
        sb.append(g7);
        sb.append(", isDarkTheme=");
        sb.append(z2);
        sb.append(", isRichConversationTheme=");
        sb.append(z);
        sb.append(", emergencyRed=");
        sb.append(g8);
        sb.append(", onEmergencyRed=");
        sb.append(g9);
        sb.append(", recordingDot=");
        sb.append(g10);
        sb.append(", recordingDotIndicator=");
        sb.append(g11);
        sb.append(", swipeUpToLockPillBackground=");
        sb.append(g12);
        sb.append(", swipeUpToLockPillIcon=");
        sb.append(g13);
        sb.append(", suggestionTabRowDivider=");
        sb.append(g14);
        sb.append(", composeRowDividerColor=");
        sb.append(g15);
        sb.append(", bannerErrorBackground=");
        sb.append(g16);
        sb.append(", genAiBackgroundStart=");
        sb.append(g17);
        sb.append(", genAiBackgroundMiddle=");
        sb.append(g18);
        sb.append(", genAiBackgroundEnd=");
        sb.append(g19);
        sb.append(", solidAccentOnGenAiBackground=");
        sb.append(g20);
        sb.append(", accentOnGenAiBackgroundStart=");
        sb.append(g21);
        sb.append(", accentOnGenAiBackgroundEnd=");
        sb.append(g22);
        sb.append(", geminiGradientStart=");
        sb.append(g23);
        sb.append(", geminiGradientMiddle=");
        sb.append(g24);
        sb.append(", geminiGradientEnd=");
        sb.append(g25);
        sb.append(", onGenAiBackground=");
        sb.append(g26);
        sb.append(", voiceMoodHighlight=");
        sb.append(g27);
        sb.append(", customThemeCardOutline=");
        sb.append(g28);
        sb.append(", semanticGreen=");
        sb.append(g29);
        sb.append(", onSemanticGreen=");
        sb.append(g30);
        sb.append(", semanticRed=");
        sb.append(g31);
        sb.append(", onSemanticRed=");
        sb.append(g32);
        sb.append(", backgroundSamsung=");
        sb.append(g33);
        sb.append(")");
        return sb.toString();
    }
}
