package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class ahic {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final dlx D;
    public static final dli E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final dlx I;
    public static final dli J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final dlx N;
    public static final dli O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final dlx S;
    public static final dli T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final dlx X;
    public static final dli Y;
    public static final long Z;
    public static final dli a;
    public static final long aa;
    public static final long ab;
    public static final dlx ac;
    public static final dli ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final dlx ah;
    public static final dli ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final dlx am;
    public static final dli an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final dlx ar;
    public static final dli as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final dlx aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final dlx e;
    public static final dli f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final dlx j;
    public static final dli k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final dlx o;
    public static final dli p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final dlx t;
    public static final dli u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final dlx y;
    public static final dli z;

    static {
        dli dliVar = ahid.a;
        a = ahid.b;
        b = drn.a(24.0d);
        c = drn.c(16);
        d = drn.a(0.0d);
        e = ahid.d;
        f = ahid.b;
        g = drn.a(20.0d);
        h = drn.c(14);
        i = drn.a(0.0d);
        j = ahid.d;
        k = ahid.b;
        l = drn.a(16.0d);
        m = drn.c(12);
        n = drn.a(0.1d);
        o = ahid.d;
        p = ahid.a;
        q = drn.a(64.0d);
        r = drn.c(57);
        s = drn.a(0.0d);
        t = ahid.d;
        u = ahid.a;
        v = drn.a(52.0d);
        w = drn.c(45);
        x = drn.a(0.0d);
        y = ahid.d;
        z = ahid.a;
        A = drn.a(44.0d);
        B = drn.c(36);
        C = drn.a(0.0d);
        D = ahid.d;
        E = ahid.a;
        F = drn.a(40.0d);
        G = drn.c(32);
        H = drn.a(0.0d);
        I = ahid.d;
        J = ahid.a;
        K = drn.a(36.0d);
        L = drn.c(28);
        M = drn.a(0.0d);
        N = ahid.d;
        O = ahid.a;
        P = drn.a(32.0d);
        Q = drn.c(24);
        R = drn.a(0.0d);
        S = ahid.d;
        T = ahid.b;
        U = drn.a(20.0d);
        V = drn.c(14);
        W = drn.a(0.0d);
        X = ahid.c;
        Y = ahid.b;
        Z = drn.a(16.0d);
        aa = drn.c(12);
        ab = drn.a(0.1d);
        ac = ahid.c;
        ad = ahid.b;
        ae = drn.a(16.0d);
        af = drn.c(11);
        ag = drn.a(0.1d);
        ah = ahid.c;
        ai = ahid.a;
        aj = drn.a(28.0d);
        ak = drn.c(22);
        al = drn.a(0.0d);
        am = ahid.d;
        an = ahid.b;
        ao = drn.a(24.0d);
        ap = drn.c(16);
        aq = drn.a(0.0d);
        ar = ahid.c;
        as = ahid.b;
        at = drn.a(20.0d);
        au = drn.c(14);
        av = drn.a(0.0d);
        aw = ahid.c;
    }
}
