package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public enum aoyb {
    SIZE("s", aoya.INTEGER),
    WIDTH("w", aoya.INTEGER),
    CROP("c", aoya.BOOLEAN),
    DOWNLOAD("d", aoya.BOOLEAN),
    HEIGHT("h", aoya.INTEGER),
    STRETCH("s", aoya.BOOLEAN),
    HTML("h", aoya.BOOLEAN),
    SMART_CROP("p", aoya.BOOLEAN),
    SMART_CROP_NO_CLIP("pp", aoya.BOOLEAN),
    SMART_CROP_USE_FACE("pf", aoya.BOOLEAN),
    CENTER_CROP("n", aoya.BOOLEAN),
    ROTATE("r", aoya.INTEGER),
    SKIP_REFERER_CHECK("r", aoya.BOOLEAN),
    OVERLAY("o", aoya.BOOLEAN),
    OBJECT_ID("o", aoya.FIXED_LENGTH_BASE_64),
    FRAME_ID("j", aoya.FIXED_LENGTH_BASE_64),
    TILE_X("x", aoya.INTEGER),
    TILE_Y("y", aoya.INTEGER),
    TILE_ZOOM("z", aoya.INTEGER),
    TILE_GENERATION("g", aoya.BOOLEAN),
    EXPIRATION_TIME("e", aoya.INTEGER),
    IMAGE_FILTER("f", aoya.STRING),
    KILL_ANIMATION("k", aoya.BOOLEAN),
    UNFILTERED("u", aoya.BOOLEAN),
    UNFILTERED_WITH_TRANSFORMS("ut", aoya.BOOLEAN),
    INCLUDE_METADATA("i", aoya.BOOLEAN),
    ES_PORTRAIT_APPROVED_ONLY("a", aoya.BOOLEAN),
    BYPASS_TAKEDOWN("b", aoya.BOOLEAN),
    BORDER_SIZE("b", aoya.INTEGER),
    BORDER_COLOR("c", aoya.PREFIX_HEX),
    QUERY_STRING("q", aoya.STRING),
    HORIZONTAL_FLIP("fh", aoya.BOOLEAN),
    VERTICAL_FLIP("fv", aoya.BOOLEAN),
    FORCE_TILE_GENERATION("fg", aoya.BOOLEAN),
    IMAGE_CROP("ci", aoya.BOOLEAN),
    REQUEST_WEBP("rw", aoya.BOOLEAN),
    REQUEST_WEBP_UNLESS_MAYBE_TRANSPARENT("rwu", aoya.BOOLEAN),
    REQUEST_ANIMATED_WEBP("rwa", aoya.BOOLEAN),
    NO_WEBP("nw", aoya.BOOLEAN),
    REQUEST_H264("rh", aoya.BOOLEAN),
    NO_OVERLAY("no", aoya.BOOLEAN),
    NO_SILHOUETTE("ns", aoya.BOOLEAN),
    FOCUS_BLUR("k", aoya.INTEGER),
    FOCAL_PLANE("p", aoya.INTEGER),
    QUALITY_LEVEL("l", aoya.INTEGER),
    QUALITY_BUCKET("v", aoya.INTEGER),
    NO_UPSCALE("nu", aoya.BOOLEAN),
    FORCE_TRANSFORMATION("ft", aoya.BOOLEAN),
    CIRCLE_CROP("cc", aoya.BOOLEAN),
    NO_DEFAULT_IMAGE("nd", aoya.BOOLEAN),
    INCLUDE_PUBLIC_METADATA("ip", aoya.BOOLEAN),
    NO_CORRECT_EXIF_ORIENTATION("nc", aoya.BOOLEAN),
    SELECT_FRAME_NUMBER("a", aoya.INTEGER),
    REQUEST_JPEG("rj", aoya.BOOLEAN),
    REQUEST_PNG("rp", aoya.BOOLEAN),
    REQUEST_GIF("rg", aoya.BOOLEAN),
    PAD("pd", aoya.BOOLEAN),
    PRESERVE_ASPECT_RATIO("pa", aoya.BOOLEAN),
    VIDEO_FORMAT("m", aoya.INTEGER),
    VIDEO_BEGIN("vb", aoya.LONG),
    VIDEO_LENGTH("vl", aoya.LONG),
    LOOSE_FACE_CROP("lf", aoya.BOOLEAN),
    MATCH_VERSION("mv", aoya.BOOLEAN),
    IMAGE_DIGEST("id", aoya.BOOLEAN),
    AUTOLOOP("al", aoya.BOOLEAN),
    INTERNAL_CLIENT("ic", aoya.INTEGER),
    TILE_PYRAMID_AS_PROTO("pg", aoya.BOOLEAN),
    MONOGRAM("mo", aoya.BOOLEAN),
    VERSIONED_TOKEN("nt0", aoya.STRING),
    IMAGE_VERSION("iv", aoya.LONG),
    PITCH_DEGREES("pi", aoya.FLOAT),
    YAW_DEGREES("ya", aoya.FLOAT),
    ROLL_DEGREES("ro", aoya.FLOAT),
    FOV_DEGREES("fo", aoya.FLOAT),
    DETECT_FACES("df", aoya.BOOLEAN),
    VIDEO_MULTI_FORMAT("mm", aoya.STRING),
    STRIP_GOOGLE_DATA("sg", aoya.BOOLEAN),
    PRESERVE_GOOGLE_DATA("gd", aoya.BOOLEAN),
    FORCE_MONOGRAM("fm", aoya.BOOLEAN),
    BADGE("ba", aoya.INTEGER),
    BORDER_RADIUS("br", aoya.INTEGER),
    BACKGROUND_COLOR("bc", aoya.PREFIX_HEX),
    PAD_COLOR("pc", aoya.PREFIX_HEX),
    SUBSTITUTION_COLOR("sc", aoya.PREFIX_HEX),
    DOWNLOAD_VIDEO("dv", aoya.BOOLEAN),
    MONOGRAM_DOGFOOD("md", aoya.BOOLEAN),
    COLOR_PROFILE("cp", aoya.INTEGER),
    STRIP_METADATA("sm", aoya.BOOLEAN),
    FACE_CROP_VERSION("cv", aoya.INTEGER),
    STRIP_GEOINFO("ng", aoya.BOOLEAN),
    IGNORE_LOW_RES_PROFILE_PHOTO("il", aoya.BOOLEAN),
    LOSSY("lo", aoya.BOOLEAN),
    VIDEO_MANIFEST("vm", aoya.BOOLEAN),
    DEEP_CROP("dc", aoya.FIFE_SAFE_BASE_64),
    REQUEST_VIDEO_FAST("rf", aoya.BOOLEAN),
    VIDEO_FORMAT_FILTERS("vf", aoya.STRING),
    REQUEST_AVIF("ra", aoya.BOOLEAN),
    DUMMY_CACHE_KEY_MODIFIER("ckm", aoya.BOOLEAN),
    GAIN_MAP("gm", aoya.BOOLEAN),
    NO_GAIN_MAP("ngm", aoya.BOOLEAN),
    EXPIRATION_TIME_IN_MINUTES("em", aoya.INTEGER),
    FORCE_COOKIE_REDIRECT("cr", aoya.BOOLEAN),
    STORYBOARD_LEVEL("sl", aoya.INTEGER),
    STORYBOARD_MOSAIC("sb", aoya.INTEGER);

    public final String ba;
    public final aoya bb;

    aoyb(String str, aoya aoyaVar) {
        this.ba = str;
        this.bb = aoyaVar;
    }
}
