package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class aqjb implements aojy {
    public final alog H;
    public final alpt I;
    private final alor L;
    public static final ahka a = new ahka("google.internal.communications.instantmessaging.v1.Registration.");
    private static final ahka J = new ahka("google.internal.communications.instantmessaging.v1.Registration/");
    public static final aojx b = new aqiz(8, (char[][]) null);
    public static final aojx c = new aqiz(19, (byte[]) null, (byte[]) null);
    public static final aojx d = new aqja(0);
    public static final aojx e = new aqja(2, (char[]) null);
    public static final aojx f = new aqja(3, (short[]) null);
    public static final aojx g = new aqja(4, (int[]) null);
    public static final aojx h = new aqja(5, (boolean[]) null);
    public static final aojx i = new aqja(6, (float[]) null);
    public static final aojx j = new aqja(7, (byte[][]) null);
    public static final aojx k = new aqiw(19, (byte[]) null, (byte[]) null);
    public static final aojx l = new aqiw(20, (char[]) null, (byte[]) null);
    public static final aojx m = new aqiz(1, (byte[]) null);
    public static final aojx n = new aqiz(0);
    public static final aojx o = new aqiz(2, (char[]) null);
    public static final aojx p = new aqiz(3, (short[]) null);
    public static final aojx q = new aqiz(4, (int[]) null);
    public static final aojx r = new aqiz(5, (boolean[]) null);
    public static final aojx s = new aqiz(6, (float[]) null);
    public static final aojx t = new aqiz(7, (byte[][]) null);
    public static final aojx u = new aqiz(9, (short[][]) null);
    public static final aojx v = new aqiz(10, (int[][]) null);
    public static final aojx w = new aqiz(11, (boolean[][]) null);
    public static final aojx x = new aqiz(12, (float[][]) null);
    public static final aojx y = new aqiz(13, (byte[][][]) null);
    public static final aojx z = new aqiz(14, (char[][][]) null);
    public static final aojx A = new aqiz(15, (short[][][]) null);
    public static final aojx B = new aqiz(16, (int[][][]) null);
    public static final aojx C = new aqiz(17, (boolean[][][]) null);
    public static final aojx D = new aqiz(18, (float[][][]) null);
    public static final aojx E = new aqiz(20, (char[]) null, (byte[]) null);
    public static final aojx F = new aqja(1, (byte[]) null);
    public static final aqjb G = new aqjb();
    private static final ahka K = new ahka("instantmessaging-pa.googleapis.com");

    private aqjb() {
        alob alobVar = new alob();
        alobVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-pa.mtls.googleapis.com");
        alobVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("zero-instantmessaging-pa.googleapis.com");
        alobVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        alobVar.h("instantmessaging-pa.googleapis.com");
        this.H = alobVar.g();
        this.I = new alpr().g();
        aojx aojxVar = b;
        aojx aojxVar2 = c;
        aojx aojxVar3 = d;
        aojx aojxVar4 = e;
        aojx aojxVar5 = f;
        aojx aojxVar6 = g;
        aojx aojxVar7 = h;
        aojx aojxVar8 = i;
        aojx aojxVar9 = j;
        aojx aojxVar10 = k;
        aojx aojxVar11 = l;
        aojx aojxVar12 = m;
        aojx aojxVar13 = n;
        aojx aojxVar14 = o;
        aojx aojxVar15 = p;
        aojx aojxVar16 = q;
        aojx aojxVar17 = r;
        aojx aojxVar18 = s;
        aojx aojxVar19 = t;
        aojx aojxVar20 = u;
        aojx aojxVar21 = v;
        aojx aojxVar22 = w;
        aojx aojxVar23 = x;
        aojx aojxVar24 = y;
        aojx aojxVar25 = z;
        aojx aojxVar26 = A;
        aojx aojxVar27 = B;
        aojx aojxVar28 = C;
        aojx aojxVar29 = D;
        aojx aojxVar30 = E;
        aojx aojxVar31 = F;
        alpt.v(aojxVar, aojxVar2, aojxVar3, aojxVar4, aojxVar5, aojxVar6, aojxVar7, aojxVar8, aojxVar9, aojxVar10, aojxVar11, aojxVar12, aojxVar13, aojxVar14, aojxVar15, aojxVar16, aojxVar17, aojxVar18, aojxVar19, aojxVar20, aojxVar21, aojxVar22, aojxVar23, aojxVar24, aojxVar25, aojxVar26, aojxVar27, aojxVar28, aojxVar29, aojxVar30, aojxVar31);
        alok alokVar = new alok();
        alokVar.h("Register", aojxVar);
        alokVar.h("RegisterSilent", aojxVar2);
        alokVar.h("PeriodicRegisterSilent", aojxVar3);
        alokVar.h("RegisterAnonymous", aojxVar4);
        alokVar.h("RegisterByAgent", aojxVar5);
        alokVar.h("RegisterRefresh", aojxVar6);
        alokVar.h("Verify", aojxVar7);
        alokVar.h("Unregister", aojxVar8);
        alokVar.h("DeleteAccount", aojxVar9);
        alokVar.h("LookupRegistered", aojxVar10);
        alokVar.h("LookupRegisteredSheddable", aojxVar11);
        alokVar.h("SetCapabilities", aojxVar12);
        alokVar.h("GetPreKey", aojxVar13);
        alokVar.h("GetPreKeyBatch", aojxVar14);
        alokVar.h("SetPreKeys", aojxVar15);
        alokVar.h("UpgradeAccount", aojxVar16);
        alokVar.h("DowngradeAccount", aojxVar17);
        alokVar.h("SignInGaia", aojxVar18);
        alokVar.h("SignInGaiaSilent", aojxVar19);
        alokVar.h("VerifyGaia", aojxVar20);
        alokVar.h("GetAccountInfo", aojxVar21);
        alokVar.h("AddPhoneReachability", aojxVar22);
        alokVar.h("VerifyPhoneReachability", aojxVar23);
        alokVar.h("RegisterGaiaSilent", aojxVar24);
        alokVar.h("ReplacePhoneReachability", aojxVar25);
        alokVar.h("UnregisterGoogleRCS", aojxVar26);
        alokVar.h("GetGaiaDeviceInfo", aojxVar27);
        alokVar.h("LinkIdentity", aojxVar28);
        alokVar.h("ListIdentities", aojxVar29);
        alokVar.h("SignInSecondary", aojxVar30);
        alokVar.h("UnlinkIdentity", aojxVar31);
        this.L = alokVar.b();
        new alok().b();
    }

    @Override // defpackage.aojy
    public final ahka a() {
        return K;
    }

    @Override // defpackage.aojy
    public final aojx b(String str) {
        String str2 = J.a;
        if (str.startsWith(str2)) {
            String substring = str.substring(str2.length());
            if (this.L.containsKey(substring)) {
                return (aojx) this.L.get(substring);
            }
            return null;
        }
        return null;
    }
}
