package defpackage;

/* compiled from: PG */
/* loaded from: classes4.dex */
public final class aqje implements aojy {
    public final alpt A;
    private final alor D;
    public final alog z;
    public static final ahka a = new ahka("google.internal.communications.instantmessaging.v1.UserData.");
    private static final ahka B = new ahka("google.internal.communications.instantmessaging.v1.UserData/");
    public static final aojx b = new aqjd(8, (char[][]) null);
    public static final aojx c = new aqjd(13, (byte[][][]) null);
    public static final aojx d = new aqjd(14, (char[][][]) null);
    public static final aojx e = new aqjd(15, (short[][][]) null);
    public static final aojx f = new aqjd(16, (int[][][]) null);
    public static final aojx g = new aqjd(17, (boolean[][][]) null);
    public static final aojx h = new aqjd(18, (float[][][]) null);
    public static final aojx i = new aqjd(19, (byte[]) null, (byte[]) null);
    public static final aojx j = new aqjd(20, (char[]) null, (byte[]) null);
    public static final aojx k = new aqja(19, (byte[]) null, (byte[]) null);
    public static final aojx l = new aqja(20, (char[]) null, (byte[]) null);
    public static final aojx m = new aqjd(1, (byte[]) null);
    public static final aojx n = new aqjd(0);
    public static final aojx o = new aqjd(2, (char[]) null);
    public static final aojx p = new aqjd(3, (short[]) null);
    public static final aojx q = new aqjd(4, (int[]) null);
    public static final aojx r = new aqjd(5, (boolean[]) null);
    public static final aojx s = new aqjd(6, (float[]) null);
    public static final aojx t = new aqjd(7, (byte[][]) null);
    public static final aojx u = new aqjd(9, (short[][]) null);
    public static final aojx v = new aqjd(10, (int[][]) null);
    public static final aojx w = new aqjd(11, (boolean[][]) null);
    public static final aojx x = new aqjd(12, (float[][]) null);
    public static final aqje y = new aqje();
    private static final ahka C = new ahka("instantmessaging-pa.googleapis.com");

    private aqje() {
        alob alobVar = new alob();
        alobVar.h("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-pa.mtls.googleapis.com");
        alobVar.h("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        alobVar.h("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        alobVar.h("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        alobVar.h("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        alobVar.h("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        alobVar.h("zero-instantmessaging-pa.googleapis.com");
        alobVar.h("zero-instantmessaging-pa.mtls.googleapis.com");
        alobVar.h("instantmessaging-pa.googleapis.com");
        this.z = alobVar.g();
        this.A = new alpr().g();
        aojx aojxVar = b;
        aojx aojxVar2 = c;
        aojx aojxVar3 = d;
        aojx aojxVar4 = e;
        aojx aojxVar5 = f;
        aojx aojxVar6 = g;
        aojx aojxVar7 = h;
        aojx aojxVar8 = i;
        aojx aojxVar9 = j;
        aojx aojxVar10 = k;
        aojx aojxVar11 = l;
        aojx aojxVar12 = m;
        aojx aojxVar13 = n;
        aojx aojxVar14 = o;
        aojx aojxVar15 = p;
        aojx aojxVar16 = q;
        aojx aojxVar17 = r;
        aojx aojxVar18 = s;
        aojx aojxVar19 = t;
        aojx aojxVar20 = u;
        aojx aojxVar21 = v;
        aojx aojxVar22 = w;
        aojx aojxVar23 = x;
        alpt.v(aojxVar, aojxVar2, aojxVar3, aojxVar4, aojxVar5, aojxVar6, aojxVar7, aojxVar8, aojxVar9, aojxVar10, aojxVar11, aojxVar12, aojxVar13, aojxVar14, aojxVar15, aojxVar16, aojxVar17, aojxVar18, aojxVar19, aojxVar20, aojxVar21, aojxVar22, aojxVar23);
        alok alokVar = new alok();
        alokVar.h("SetContacts", aojxVar);
        alokVar.h("NetworkTransition", aojxVar2);
        alokVar.h("AddContacts", aojxVar3);
        alokVar.h("RemoveContacts", aojxVar4);
        alokVar.h("SetProfile", aojxVar5);
        alokVar.h("GetProfile", aojxVar6);
        alokVar.h("LookupContacts", aojxVar7);
        alokVar.h("LookupContactLite", aojxVar8);
        alokVar.h("GetSelfUserInviteLink", aojxVar9);
        alokVar.h("ResetSelfUserInviteLink", aojxVar10);
        alokVar.h("GetUserInviteLinkDetails", aojxVar11);
        alokVar.h("CreateShortLinks", aojxVar12);
        alokVar.h("GetUserInviterId", aojxVar13);
        alokVar.h("LookupUserInviterId", aojxVar14);
        alokVar.h("InformInviter", aojxVar15);
        alokVar.h("GetContacts", aojxVar16);
        alokVar.h("GetStates", aojxVar17);
        alokVar.h("ApplyStateMutations", aojxVar18);
        alokVar.h("SetDeviceMute", aojxVar19);
        alokVar.h("GetDeviceMute", aojxVar20);
        alokVar.h("SendNotification", aojxVar21);
        alokVar.h("GetOnlineStatus", aojxVar22);
        alokVar.h("UpdateAccountSetting", aojxVar23);
        this.D = alokVar.b();
        new alok().b();
    }

    @Override // defpackage.aojy
    public final ahka a() {
        return C;
    }

    @Override // defpackage.aojy
    public final aojx b(String str) {
        String str2 = B.a;
        if (str.startsWith(str2)) {
            String substring = str.substring(str2.length());
            if (this.D.containsKey(substring)) {
                return (aojx) this.D.get(substring);
            }
            return null;
        }
        return null;
    }
}
