package defpackage;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.bc.BCObjectIdentifiers;
import org.bouncycastle.asn1.isara.IsaraObjectIdentifiers;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x509.AlgorithmIdentifier;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class atab {
    private static final Map a;

    static {
        HashMap hashMap = new HashMap();
        a = hashMap;
        hashMap.put(asvp.i, new aszs());
        hashMap.put(asvp.j, new aszs());
        hashMap.put(asvp.d, new aszw());
        hashMap.put(asvp.e, new aszo());
        hashMap.put(asvp.f, new aszz());
        hashMap.put(asvp.g, new ataa());
        hashMap.put(IsaraObjectIdentifiers.a, new aszz());
        hashMap.put(IsaraObjectIdentifiers.b, new ataa());
        hashMap.put(PKCSObjectIdentifiers.D, new aszm());
        hashMap.put(asvp.c, new aszn());
        hashMap.put(BCObjectIdentifiers.n, new aszx());
        hashMap.put(BCObjectIdentifiers.o, new aszx());
        hashMap.put(BCObjectIdentifiers.p, new aszx());
        hashMap.put(BCObjectIdentifiers.q, new aszx());
        hashMap.put(BCObjectIdentifiers.r, new aszx());
        hashMap.put(BCObjectIdentifiers.s, new aszx());
        hashMap.put(BCObjectIdentifiers.t, new aszx());
        hashMap.put(BCObjectIdentifiers.u, new aszx());
        hashMap.put(BCObjectIdentifiers.v, new aszx());
        hashMap.put(BCObjectIdentifiers.w, new aszx());
        hashMap.put(BCObjectIdentifiers.x, new aszx());
        hashMap.put(BCObjectIdentifiers.y, new aszx());
        hashMap.put(BCObjectIdentifiers.z, new aszx());
        hashMap.put(BCObjectIdentifiers.A, new aszx());
        hashMap.put(BCObjectIdentifiers.B, new aszx());
        hashMap.put(BCObjectIdentifiers.C, new aszx());
        hashMap.put(BCObjectIdentifiers.D, new aszx());
        hashMap.put(BCObjectIdentifiers.E, new aszx());
        hashMap.put(BCObjectIdentifiers.F, new aszx());
        hashMap.put(BCObjectIdentifiers.G, new aszx());
        hashMap.put(BCObjectIdentifiers.H, new aszx());
        hashMap.put(BCObjectIdentifiers.I, new aszx());
        hashMap.put(BCObjectIdentifiers.J, new aszx());
        hashMap.put(BCObjectIdentifiers.K, new aszx());
        hashMap.put(BCObjectIdentifiers.L, new aszx());
        hashMap.put(BCObjectIdentifiers.M, new aszx());
        hashMap.put(BCObjectIdentifiers.N, new aszx());
        hashMap.put(BCObjectIdentifiers.O, new aszx());
        hashMap.put(BCObjectIdentifiers.P, new aszx());
        hashMap.put(BCObjectIdentifiers.Q, new aszx());
        hashMap.put(BCObjectIdentifiers.R, new aszx());
        hashMap.put(BCObjectIdentifiers.S, new aszx());
        hashMap.put(BCObjectIdentifiers.T, new aszx());
        hashMap.put(BCObjectIdentifiers.U, new aszx());
        hashMap.put(BCObjectIdentifiers.V, new aszx());
        hashMap.put(BCObjectIdentifiers.W, new aszx());
        hashMap.put(BCObjectIdentifiers.X, new aszx());
        hashMap.put(BCObjectIdentifiers.aa, new aszx());
        hashMap.put(BCObjectIdentifiers.Z, new aszx());
        hashMap.put(BCObjectIdentifiers.ag, new aszx());
        hashMap.put(BCObjectIdentifiers.af, new aszx());
        hashMap.put(BCObjectIdentifiers.ac, new aszx());
        hashMap.put(BCObjectIdentifiers.ab, new aszx());
        hashMap.put(BCObjectIdentifiers.ai, new aszx());
        hashMap.put(BCObjectIdentifiers.ah, new aszx());
        hashMap.put(BCObjectIdentifiers.ae, new aszx());
        hashMap.put(BCObjectIdentifiers.ad, new aszx());
        hashMap.put(BCObjectIdentifiers.ak, new aszx());
        hashMap.put(BCObjectIdentifiers.aj, new aszx());
        hashMap.put(new ASN1ObjectIdentifier("1.3.9999.6.4.10"), new aszx());
        hashMap.put(BCObjectIdentifiers.aU, new aszg());
        hashMap.put(BCObjectIdentifiers.aV, new aszg());
        hashMap.put(BCObjectIdentifiers.aW, new aszg());
        hashMap.put(BCObjectIdentifiers.aX, new aszg());
        hashMap.put(BCObjectIdentifiers.aY, new aszg());
        hashMap.put(BCObjectIdentifiers.aZ, new aszg());
        hashMap.put(BCObjectIdentifiers.ba, new aszg());
        hashMap.put(BCObjectIdentifiers.bb, new aszg());
        hashMap.put(BCObjectIdentifiers.bc, new aszg());
        hashMap.put(BCObjectIdentifiers.bd, new aszg());
        hashMap.put(BCObjectIdentifiers.bf, new aszj());
        hashMap.put(BCObjectIdentifiers.bg, new aszj());
        hashMap.put(BCObjectIdentifiers.bh, new aszj());
        hashMap.put(BCObjectIdentifiers.bi, new aszj());
        hashMap.put(BCObjectIdentifiers.bj, new aszj());
        hashMap.put(BCObjectIdentifiers.bk, new aszj());
        hashMap.put(BCObjectIdentifiers.bm, new aszu());
        hashMap.put(BCObjectIdentifiers.bn, new aszu());
        hashMap.put(BCObjectIdentifiers.bo, new aszu());
        hashMap.put(BCObjectIdentifiers.bp, new aszu());
        hashMap.put(BCObjectIdentifiers.bq, new aszu());
        hashMap.put(BCObjectIdentifiers.br, new aszu());
        hashMap.put(BCObjectIdentifiers.bs, new aszu());
        hashMap.put(BCObjectIdentifiers.bt, new aszu());
        hashMap.put(BCObjectIdentifiers.bu, new aszu());
        hashMap.put(BCObjectIdentifiers.bv, new aszu());
        hashMap.put(BCObjectIdentifiers.bw, new aszu());
        hashMap.put(BCObjectIdentifiers.bx, new aszu());
        hashMap.put(BCObjectIdentifiers.by, new aszu());
        hashMap.put(BCObjectIdentifiers.bz, new aszu());
        hashMap.put(BCObjectIdentifiers.bA, new aszu());
        hashMap.put(BCObjectIdentifiers.bB, new aszu());
        hashMap.put(BCObjectIdentifiers.bC, new aszu());
        hashMap.put(BCObjectIdentifiers.bD, new aszu());
        hashMap.put(BCObjectIdentifiers.an, new aszr());
        hashMap.put(BCObjectIdentifiers.ao, new aszr());
        hashMap.put(BCObjectIdentifiers.ap, new aszr());
        hashMap.put(BCObjectIdentifiers.aq, new aszr());
        hashMap.put(BCObjectIdentifiers.ar, new aszr());
        hashMap.put(BCObjectIdentifiers.as, new aszr());
        hashMap.put(BCObjectIdentifiers.at, new aszr());
        hashMap.put(BCObjectIdentifiers.au, new aszr());
        hashMap.put(BCObjectIdentifiers.av, new aszr());
        hashMap.put(BCObjectIdentifiers.aw, new aszr());
        hashMap.put(BCObjectIdentifiers.ax, new aszr());
        hashMap.put(BCObjectIdentifiers.ay, new aszr());
        hashMap.put(BCObjectIdentifiers.bG, new aszq());
        hashMap.put(BCObjectIdentifiers.bH, new aszq());
        hashMap.put(BCObjectIdentifiers.bI, new aszq());
        hashMap.put(BCObjectIdentifiers.bJ, new aszq());
        hashMap.put(BCObjectIdentifiers.aA, new aszi());
        hashMap.put(BCObjectIdentifiers.aB, new aszi());
        hashMap.put(BCObjectIdentifiers.bL, new aszl());
        hashMap.put(BCObjectIdentifiers.bM, new aszl());
        hashMap.put(BCObjectIdentifiers.bN, new aszl());
        hashMap.put(BCObjectIdentifiers.bO, new aszl());
        hashMap.put(BCObjectIdentifiers.bP, new aszl());
        hashMap.put(BCObjectIdentifiers.bQ, new aszl());
        hashMap.put(BCObjectIdentifiers.bT, new aszp());
        hashMap.put(BCObjectIdentifiers.bU, new aszp());
        hashMap.put(BCObjectIdentifiers.bV, new aszp());
        hashMap.put(BCObjectIdentifiers.bW, new aszp());
        hashMap.put(BCObjectIdentifiers.bX, new aszp());
        hashMap.put(BCObjectIdentifiers.bY, new aszp());
        hashMap.put(BCObjectIdentifiers.ca, new aszv());
        hashMap.put(BCObjectIdentifiers.cb, new aszv());
        hashMap.put(BCObjectIdentifiers.cc, new aszv());
        hashMap.put(BCObjectIdentifiers.cd, new aszv());
        hashMap.put(BCObjectIdentifiers.ce, new aszv());
        hashMap.put(BCObjectIdentifiers.cf, new aszv());
        hashMap.put(BCObjectIdentifiers.aC, new aszh());
        hashMap.put(BCObjectIdentifiers.aD, new aszh());
        hashMap.put(BCObjectIdentifiers.aE, new aszh());
        hashMap.put(BCObjectIdentifiers.aF, new aszh());
        hashMap.put(BCObjectIdentifiers.aG, new aszh());
        hashMap.put(BCObjectIdentifiers.aH, new aszh());
        hashMap.put(BCObjectIdentifiers.ch, new aszf());
        hashMap.put(BCObjectIdentifiers.ci, new aszf());
        hashMap.put(BCObjectIdentifiers.cj, new aszf());
        hashMap.put(BCObjectIdentifiers.cl, new aszk());
        hashMap.put(BCObjectIdentifiers.cm, new aszk());
        hashMap.put(BCObjectIdentifiers.cn, new aszk());
        hashMap.put(BCObjectIdentifiers.aJ, new aszt());
        hashMap.put(BCObjectIdentifiers.aK, new aszt());
        hashMap.put(BCObjectIdentifiers.aL, new aszt());
        hashMap.put(BCObjectIdentifiers.aM, new aszt());
        hashMap.put(BCObjectIdentifiers.aN, new aszt());
        hashMap.put(BCObjectIdentifiers.aO, new aszt());
    }

    public static astl a(SubjectPublicKeyInfo subjectPublicKeyInfo) {
        if (subjectPublicKeyInfo != null) {
            AlgorithmIdentifier algorithmIdentifier = subjectPublicKeyInfo.a;
            aszy aszyVar = (aszy) a.get(algorithmIdentifier.a);
            if (aszyVar != null) {
                return aszyVar.a(subjectPublicKeyInfo);
            }
            throw new IOException("algorithm identifier in public key not recognised: ".concat(String.valueOf(String.valueOf(algorithmIdentifier.a))));
        }
        throw new IllegalArgumentException("keyInfo argument null");
    }
}
