package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class bvs {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final dlx D;
    public static final dlz E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final dlx I;
    public static final dlz J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final dlx N;
    public static final dlz O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final dlx S;
    public static final dlz T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final dlx X;
    public static final dlz Y;
    public static final long Z;
    public static final dlz a;
    public static final long aA;
    public static final dlx aB;
    public static final dlz aC;
    public static final long aD;
    public static final long aE;
    public static final long aF;
    public static final dlx aG;
    public static final dlz aH;
    public static final long aI;
    public static final long aJ;
    public static final long aK;
    public static final dlx aL;
    public static final dlz aM;
    public static final long aN;
    public static final long aO;
    public static final long aP;
    public static final dlx aQ;
    public static final dlz aR;
    public static final long aS;
    public static final long aT;
    public static final long aU;
    public static final dlx aV;
    public static final dlz aW;
    public static final long aX;
    public static final long aY;
    public static final long aZ;
    public static final long aa;
    public static final long ab;
    public static final dlx ac;
    public static final dlz ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final dlx ah;
    public static final dlz ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final dlx am;
    public static final dlz an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final dlx ar;
    public static final dlz as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final dlx aw;
    public static final dlz ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final dlz bA;
    public static final long bB;
    public static final long bC;
    public static final long bD;
    public static final dlx bE;
    public static final dlz bF;
    public static final long bG;
    public static final long bH;
    public static final long bI;
    public static final dlx bJ;
    public static final dlz bK;
    public static final long bL;
    public static final long bM;
    public static final long bN;
    public static final dlx bO;
    public static final dlz bP;
    public static final long bQ;
    public static final long bR;
    public static final long bS;
    public static final dlx bT;
    public static final dlx ba;
    public static final dlz bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final dlx bf;
    public static final dlz bg;
    public static final long bh;
    public static final long bi;
    public static final long bj;
    public static final dlx bk;
    public static final dlz bl;
    public static final long bm;
    public static final long bn;
    public static final long bo;
    public static final dlx bp;
    public static final dlz bq;
    public static final long br;
    public static final long bs;
    public static final long bt;
    public static final dlx bu;
    public static final dlz bv;
    public static final long bw;
    public static final long bx;
    public static final long by;
    public static final dlx bz;
    public static final long c;
    public static final long d;
    public static final dlx e;
    public static final dlz f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final dlx j;
    public static final dlz k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final dlx o;
    public static final dlz p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final dlx t;
    public static final dlz u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final dlx y;
    public static final dlz z;

    static {
        dlz dlzVar = bvt.a;
        a = bvt.b;
        b = drn.a(24.0d);
        c = drn.c(16);
        d = drn.a(0.5d);
        e = bvt.e;
        f = bvt.b;
        g = drn.a(20.0d);
        h = drn.c(14);
        i = drn.a(0.2d);
        j = bvt.e;
        k = bvt.b;
        l = drn.a(16.0d);
        m = drn.c(12);
        n = drn.a(0.4d);
        o = bvt.e;
        p = bvt.a;
        q = drn.a(64.0d);
        r = drn.c(57);
        long a2 = drn.a(0.2d);
        drn.e(a2);
        s = drn.d(drm.b(a2), -drm.a(a2));
        t = bvt.e;
        u = bvt.a;
        v = drn.a(52.0d);
        w = drn.c(45);
        x = drn.a(0.0d);
        y = bvt.e;
        z = bvt.a;
        A = drn.a(44.0d);
        B = drn.c(36);
        C = drn.a(0.0d);
        D = bvt.e;
        E = bvt.a;
        F = drn.a(40.0d);
        G = drn.c(32);
        H = drn.a(0.0d);
        I = bvt.e;
        J = bvt.a;
        K = drn.a(36.0d);
        L = drn.c(28);
        M = drn.a(0.0d);
        N = bvt.e;
        O = bvt.a;
        P = drn.a(32.0d);
        Q = drn.c(24);
        R = drn.a(0.0d);
        S = bvt.e;
        T = bvt.b;
        U = drn.a(20.0d);
        V = drn.c(14);
        W = drn.a(0.1d);
        X = bvt.d;
        Y = bvt.b;
        Z = drn.a(16.0d);
        aa = drn.c(12);
        ab = drn.a(0.5d);
        ac = bvt.d;
        ad = bvt.b;
        ae = drn.a(16.0d);
        af = drn.c(11);
        ag = drn.a(0.5d);
        ah = bvt.d;
        ai = bvt.a;
        aj = drn.a(28.0d);
        ak = drn.c(22);
        al = drn.a(0.0d);
        am = bvt.e;
        an = bvt.b;
        ao = drn.a(24.0d);
        ap = drn.c(16);
        aq = drn.a(0.2d);
        ar = bvt.d;
        as = bvt.b;
        at = drn.a(20.0d);
        au = drn.c(14);
        av = drn.a(0.1d);
        aw = bvt.d;
        ax = bvt.b;
        ay = drn.a(24.0d);
        az = drn.c(16);
        aA = drn.a(0.15d);
        aB = bvt.d;
        aC = bvt.b;
        aD = drn.a(20.0d);
        aE = drn.c(14);
        aF = drn.a(0.25d);
        aG = bvt.d;
        aH = bvt.b;
        aI = drn.a(16.0d);
        aJ = drn.c(12);
        aK = drn.a(0.4d);
        aL = bvt.d;
        aM = bvt.a;
        aN = drn.a(64.0d);
        aO = drn.c(57);
        aP = drn.c(0);
        aQ = bvt.d;
        aR = bvt.a;
        aS = drn.a(52.0d);
        aT = drn.c(45);
        aU = drn.c(0);
        aV = bvt.d;
        aW = bvt.a;
        aX = drn.a(44.0d);
        aY = drn.c(36);
        aZ = drn.c(0);
        ba = bvt.d;
        bb = bvt.a;
        bc = drn.a(40.0d);
        bd = drn.c(32);
        be = drn.c(0);
        bf = bvt.d;
        bg = bvt.a;
        bh = drn.a(36.0d);
        bi = drn.c(28);
        bj = drn.c(0);
        bk = bvt.d;
        bl = bvt.a;
        bm = drn.a(32.0d);
        bn = drn.c(24);
        bo = drn.c(0);
        bp = bvt.d;
        bq = bvt.b;
        br = drn.a(20.0d);
        bs = drn.c(14);
        bt = drn.a(0.1d);
        bu = bvt.c;
        bv = bvt.b;
        bw = drn.a(16.0d);
        bx = drn.c(12);
        by = drn.a(0.5d);
        bz = bvt.c;
        bA = bvt.b;
        bB = drn.a(16.0d);
        bC = drn.c(11);
        bD = drn.a(0.5d);
        bE = bvt.c;
        bF = bvt.a;
        bG = drn.a(28.0d);
        bH = drn.c(22);
        bI = drn.c(0);
        bJ = bvt.d;
        bK = bvt.b;
        bL = drn.a(24.0d);
        bM = drn.c(16);
        bN = drn.a(0.15d);
        bO = bvt.c;
        bP = bvt.b;
        bQ = drn.a(20.0d);
        bR = drn.c(14);
        bS = drn.a(0.1d);
        bT = bvt.c;
    }
}
