package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class bvv {
    public static final dje A;
    public static final dje B;
    public static final dje C;
    public static final dje D;
    public static final dje a;
    public static final dje b;
    public static final dje c;
    public static final dje d;
    public static final dje e;
    public static final dje f;
    public static final dje g;
    public static final dje h;
    public static final dje i;
    public static final dje j;
    public static final dje k;
    public static final dje l;
    public static final dje m;
    public static final dje n;
    public static final dje o;
    public static final dje p;
    public static final dje q;
    public static final dje r;
    public static final dje s;
    public static final dje t;
    public static final dje u;
    public static final dje v;
    public static final dje w;
    public static final dje x;
    public static final dje y;
    public static final dje z;

    static {
        dje djeVar = bvw.a;
        dlz dlzVar = bvs.a;
        dlz dlzVar2 = bvs.a;
        dlx dlxVar = bvs.e;
        a = dje.y(djeVar, 0L, bvs.c, dlxVar, null, dlzVar2, null, bvs.d, 0, 0, bvs.b, null, null, 0, 16645977);
        dje djeVar2 = bvw.a;
        dlz dlzVar3 = bvs.f;
        dlx dlxVar2 = bvs.j;
        b = dje.y(djeVar2, 0L, bvs.h, dlxVar2, null, dlzVar3, null, bvs.i, 0, 0, bvs.g, null, null, 0, 16645977);
        dje djeVar3 = bvw.a;
        dlz dlzVar4 = bvs.k;
        dlx dlxVar3 = bvs.o;
        c = dje.y(djeVar3, 0L, bvs.m, dlxVar3, null, dlzVar4, null, bvs.n, 0, 0, bvs.l, null, null, 0, 16645977);
        dje djeVar4 = bvw.a;
        dlz dlzVar5 = bvs.p;
        dlx dlxVar4 = bvs.t;
        d = dje.y(djeVar4, 0L, bvs.r, dlxVar4, null, dlzVar5, null, bvs.s, 0, 0, bvs.q, null, null, 0, 16645977);
        dje djeVar5 = bvw.a;
        dlz dlzVar6 = bvs.u;
        dlx dlxVar5 = bvs.y;
        e = dje.y(djeVar5, 0L, bvs.w, dlxVar5, null, dlzVar6, null, bvs.x, 0, 0, bvs.v, null, null, 0, 16645977);
        dje djeVar6 = bvw.a;
        dlz dlzVar7 = bvs.z;
        dlx dlxVar6 = bvs.D;
        f = dje.y(djeVar6, 0L, bvs.B, dlxVar6, null, dlzVar7, null, bvs.C, 0, 0, bvs.A, null, null, 0, 16645977);
        dje djeVar7 = bvw.a;
        dlz dlzVar8 = bvs.E;
        dlx dlxVar7 = bvs.I;
        g = dje.y(djeVar7, 0L, bvs.G, dlxVar7, null, dlzVar8, null, bvs.H, 0, 0, bvs.F, null, null, 0, 16645977);
        dje djeVar8 = bvw.a;
        dlz dlzVar9 = bvs.J;
        dlx dlxVar8 = bvs.N;
        h = dje.y(djeVar8, 0L, bvs.L, dlxVar8, null, dlzVar9, null, bvs.M, 0, 0, bvs.K, null, null, 0, 16645977);
        dje djeVar9 = bvw.a;
        dlz dlzVar10 = bvs.O;
        dlx dlxVar9 = bvs.S;
        i = dje.y(djeVar9, 0L, bvs.Q, dlxVar9, null, dlzVar10, null, bvs.R, 0, 0, bvs.P, null, null, 0, 16645977);
        dje djeVar10 = bvw.a;
        dlz dlzVar11 = bvs.T;
        dlx dlxVar10 = bvs.X;
        j = dje.y(djeVar10, 0L, bvs.V, dlxVar10, null, dlzVar11, null, bvs.W, 0, 0, bvs.U, null, null, 0, 16645977);
        dje djeVar11 = bvw.a;
        dlz dlzVar12 = bvs.Y;
        dlx dlxVar11 = bvs.ac;
        k = dje.y(djeVar11, 0L, bvs.aa, dlxVar11, null, dlzVar12, null, bvs.ab, 0, 0, bvs.Z, null, null, 0, 16645977);
        dje djeVar12 = bvw.a;
        dlz dlzVar13 = bvs.ad;
        dlx dlxVar12 = bvs.ah;
        l = dje.y(djeVar12, 0L, bvs.af, dlxVar12, null, dlzVar13, null, bvs.ag, 0, 0, bvs.ae, null, null, 0, 16645977);
        dje djeVar13 = bvw.a;
        dlz dlzVar14 = bvs.ai;
        dlx dlxVar13 = bvs.am;
        m = dje.y(djeVar13, 0L, bvs.ak, dlxVar13, null, dlzVar14, null, bvs.al, 0, 0, bvs.aj, null, null, 0, 16645977);
        dje djeVar14 = bvw.a;
        dlz dlzVar15 = bvs.an;
        dlx dlxVar14 = bvs.ar;
        n = dje.y(djeVar14, 0L, bvs.ap, dlxVar14, null, dlzVar15, null, bvs.aq, 0, 0, bvs.ao, null, null, 0, 16645977);
        dje djeVar15 = bvw.a;
        dlz dlzVar16 = bvs.as;
        dlx dlxVar15 = bvs.aw;
        o = dje.y(djeVar15, 0L, bvs.au, dlxVar15, null, dlzVar16, null, bvs.av, 0, 0, bvs.at, null, null, 0, 16645977);
        dje djeVar16 = bvw.a;
        dlz dlzVar17 = bvs.ax;
        dlx dlxVar16 = bvs.aB;
        p = dje.y(djeVar16, 0L, bvs.az, dlxVar16, null, dlzVar17, null, bvs.aA, 0, 0, bvs.ay, null, null, 0, 16645977);
        dje djeVar17 = bvw.a;
        dlz dlzVar18 = bvs.aC;
        dlx dlxVar17 = bvs.aG;
        q = dje.y(djeVar17, 0L, bvs.aE, dlxVar17, null, dlzVar18, null, bvs.aF, 0, 0, bvs.aD, null, null, 0, 16645977);
        dje djeVar18 = bvw.a;
        dlz dlzVar19 = bvs.aH;
        dlx dlxVar18 = bvs.aL;
        r = dje.y(djeVar18, 0L, bvs.aJ, dlxVar18, null, dlzVar19, null, bvs.aK, 0, 0, bvs.aI, null, null, 0, 16645977);
        dje djeVar19 = bvw.a;
        dlz dlzVar20 = bvs.aM;
        dlx dlxVar19 = bvs.aQ;
        s = dje.y(djeVar19, 0L, bvs.aO, dlxVar19, null, dlzVar20, null, bvs.aP, 0, 0, bvs.aN, null, null, 0, 16645977);
        dje djeVar20 = bvw.a;
        dlz dlzVar21 = bvs.aR;
        dlx dlxVar20 = bvs.aV;
        t = dje.y(djeVar20, 0L, bvs.aT, dlxVar20, null, dlzVar21, null, bvs.aU, 0, 0, bvs.aS, null, null, 0, 16645977);
        dje djeVar21 = bvw.a;
        dlz dlzVar22 = bvs.aW;
        dlx dlxVar21 = bvs.ba;
        u = dje.y(djeVar21, 0L, bvs.aY, dlxVar21, null, dlzVar22, null, bvs.aZ, 0, 0, bvs.aX, null, null, 0, 16645977);
        dje djeVar22 = bvw.a;
        dlz dlzVar23 = bvs.bb;
        dlx dlxVar22 = bvs.bf;
        v = dje.y(djeVar22, 0L, bvs.bd, dlxVar22, null, dlzVar23, null, bvs.be, 0, 0, bvs.bc, null, null, 0, 16645977);
        dje djeVar23 = bvw.a;
        dlz dlzVar24 = bvs.bg;
        dlx dlxVar23 = bvs.bk;
        w = dje.y(djeVar23, 0L, bvs.bi, dlxVar23, null, dlzVar24, null, bvs.bj, 0, 0, bvs.bh, null, null, 0, 16645977);
        dje djeVar24 = bvw.a;
        dlz dlzVar25 = bvs.bl;
        dlx dlxVar24 = bvs.bp;
        x = dje.y(djeVar24, 0L, bvs.bn, dlxVar24, null, dlzVar25, null, bvs.bo, 0, 0, bvs.bm, null, null, 0, 16645977);
        dje djeVar25 = bvw.a;
        dlz dlzVar26 = bvs.bq;
        dlx dlxVar25 = bvs.bu;
        y = dje.y(djeVar25, 0L, bvs.bs, dlxVar25, null, dlzVar26, null, bvs.bt, 0, 0, bvs.br, null, null, 0, 16645977);
        dje djeVar26 = bvw.a;
        dlz dlzVar27 = bvs.bv;
        dlx dlxVar26 = bvs.bz;
        z = dje.y(djeVar26, 0L, bvs.bx, dlxVar26, null, dlzVar27, null, bvs.by, 0, 0, bvs.bw, null, null, 0, 16645977);
        dje djeVar27 = bvw.a;
        dlz dlzVar28 = bvs.bA;
        dlx dlxVar27 = bvs.bE;
        A = dje.y(djeVar27, 0L, bvs.bC, dlxVar27, null, dlzVar28, null, bvs.bD, 0, 0, bvs.bB, null, null, 0, 16645977);
        dje djeVar28 = bvw.a;
        dlz dlzVar29 = bvs.bF;
        dlx dlxVar28 = bvs.bJ;
        B = dje.y(djeVar28, 0L, bvs.bH, dlxVar28, null, dlzVar29, null, bvs.bI, 0, 0, bvs.bG, null, null, 0, 16645977);
        dje djeVar29 = bvw.a;
        dlz dlzVar30 = bvs.bK;
        dlx dlxVar29 = bvs.bO;
        C = dje.y(djeVar29, 0L, bvs.bM, dlxVar29, null, dlzVar30, null, bvs.bN, 0, 0, bvs.bL, null, null, 0, 16645977);
        dje djeVar30 = bvw.a;
        dlz dlzVar31 = bvs.bP;
        dlx dlxVar30 = bvs.bT;
        D = dje.y(djeVar30, 0L, bvs.bR, dlxVar30, null, dlzVar31, null, bvs.bS, 0, 0, bvs.bQ, null, null, 0, 16645977);
    }
}
