package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class dxg {
    int a;
    public final dxj b = new dxj();
    public final dxi c = new dxi();
    public final dxh d = new dxh();
    public final dxk e = new dxk();
    public HashMap f = new HashMap();
    dxf g;

    public final void a(dxc dxcVar) {
        dxh dxhVar = this.d;
        dxcVar.e = dxhVar.j;
        dxcVar.f = dxhVar.k;
        dxcVar.g = dxhVar.l;
        dxcVar.h = dxhVar.m;
        dxcVar.i = dxhVar.n;
        dxcVar.j = dxhVar.o;
        dxcVar.k = dxhVar.p;
        dxcVar.l = dxhVar.q;
        dxcVar.m = dxhVar.r;
        dxcVar.n = dxhVar.s;
        dxcVar.o = dxhVar.t;
        dxcVar.s = dxhVar.u;
        dxcVar.t = dxhVar.v;
        dxcVar.u = dxhVar.w;
        dxcVar.v = dxhVar.x;
        dxcVar.leftMargin = dxhVar.H;
        dxcVar.rightMargin = this.d.I;
        dxcVar.topMargin = this.d.J;
        dxcVar.bottomMargin = this.d.K;
        dxh dxhVar2 = this.d;
        dxcVar.A = dxhVar2.T;
        dxcVar.B = dxhVar2.S;
        dxcVar.x = dxhVar2.P;
        dxcVar.z = dxhVar2.R;
        dxcVar.G = dxhVar2.y;
        dxcVar.H = dxhVar2.z;
        dxcVar.p = dxhVar2.B;
        dxcVar.q = dxhVar2.C;
        dxcVar.r = dxhVar2.D;
        dxcVar.I = dxhVar2.A;
        dxcVar.X = dxhVar2.E;
        dxcVar.Y = dxhVar2.F;
        dxcVar.M = dxhVar2.V;
        dxcVar.L = dxhVar2.W;
        dxcVar.O = dxhVar2.Y;
        dxcVar.N = dxhVar2.X;
        dxcVar.aa = dxhVar2.an;
        dxcVar.ab = dxhVar2.ao;
        dxcVar.P = dxhVar2.Z;
        dxcVar.Q = dxhVar2.aa;
        dxcVar.T = dxhVar2.ab;
        dxcVar.U = dxhVar2.ac;
        dxcVar.R = dxhVar2.ad;
        dxcVar.S = dxhVar2.ae;
        dxcVar.V = dxhVar2.af;
        dxcVar.W = dxhVar2.ag;
        dxcVar.Z = dxhVar2.G;
        dxcVar.c = dxhVar2.h;
        dxcVar.a = dxhVar2.f;
        dxcVar.b = dxhVar2.g;
        dxcVar.width = dxhVar2.d;
        dxcVar.height = this.d.e;
        dxh dxhVar3 = this.d;
        String str = dxhVar3.am;
        if (str != null) {
            dxcVar.ac = str;
        }
        dxcVar.ad = dxhVar3.aq;
        dxcVar.setMarginStart(dxhVar3.M);
        dxcVar.setMarginEnd(this.d.L);
        dxcVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        dxg dxgVar = new dxg();
        dxh dxhVar = dxgVar.d;
        dxh dxhVar2 = this.d;
        dxhVar.b = dxhVar2.b;
        dxhVar.d = dxhVar2.d;
        dxhVar.c = dxhVar2.c;
        dxhVar.e = dxhVar2.e;
        dxhVar.f = dxhVar2.f;
        dxhVar.g = dxhVar2.g;
        dxhVar.h = dxhVar2.h;
        dxhVar.i = dxhVar2.i;
        dxhVar.j = dxhVar2.j;
        dxhVar.k = dxhVar2.k;
        dxhVar.l = dxhVar2.l;
        dxhVar.m = dxhVar2.m;
        dxhVar.n = dxhVar2.n;
        dxhVar.o = dxhVar2.o;
        dxhVar.p = dxhVar2.p;
        dxhVar.q = dxhVar2.q;
        dxhVar.r = dxhVar2.r;
        dxhVar.s = dxhVar2.s;
        dxhVar.t = dxhVar2.t;
        dxhVar.u = dxhVar2.u;
        dxhVar.v = dxhVar2.v;
        dxhVar.w = dxhVar2.w;
        dxhVar.x = dxhVar2.x;
        dxhVar.y = dxhVar2.y;
        dxhVar.z = dxhVar2.z;
        dxhVar.A = dxhVar2.A;
        dxhVar.B = dxhVar2.B;
        dxhVar.C = dxhVar2.C;
        dxhVar.D = dxhVar2.D;
        dxhVar.E = dxhVar2.E;
        dxhVar.F = dxhVar2.F;
        dxhVar.G = dxhVar2.G;
        dxhVar.H = dxhVar2.H;
        dxhVar.I = dxhVar2.I;
        dxhVar.J = dxhVar2.J;
        dxhVar.K = dxhVar2.K;
        dxhVar.L = dxhVar2.L;
        dxhVar.M = dxhVar2.M;
        dxhVar.N = dxhVar2.N;
        dxhVar.O = dxhVar2.O;
        dxhVar.P = dxhVar2.P;
        dxhVar.Q = dxhVar2.Q;
        dxhVar.R = dxhVar2.R;
        dxhVar.S = dxhVar2.S;
        dxhVar.T = dxhVar2.T;
        dxhVar.U = dxhVar2.U;
        dxhVar.V = dxhVar2.V;
        dxhVar.W = dxhVar2.W;
        dxhVar.X = dxhVar2.X;
        dxhVar.Y = dxhVar2.Y;
        dxhVar.Z = dxhVar2.Z;
        dxhVar.aa = dxhVar2.aa;
        dxhVar.ab = dxhVar2.ab;
        dxhVar.ac = dxhVar2.ac;
        dxhVar.ad = dxhVar2.ad;
        dxhVar.ae = dxhVar2.ae;
        dxhVar.af = dxhVar2.af;
        dxhVar.ag = dxhVar2.ag;
        dxhVar.ah = dxhVar2.ah;
        dxhVar.ai = dxhVar2.ai;
        dxhVar.aj = dxhVar2.aj;
        dxhVar.am = dxhVar2.am;
        int[] iArr = dxhVar2.ak;
        if (iArr != null && dxhVar2.al == null) {
            dxhVar.ak = Arrays.copyOf(iArr, iArr.length);
        } else {
            dxhVar.ak = null;
        }
        dxhVar.al = dxhVar2.al;
        dxhVar.an = dxhVar2.an;
        dxhVar.ao = dxhVar2.ao;
        dxhVar.ap = dxhVar2.ap;
        dxhVar.aq = dxhVar2.aq;
        dxi dxiVar = dxgVar.c;
        dxi dxiVar2 = this.c;
        dxiVar.b = dxiVar2.b;
        dxiVar.c = dxiVar2.c;
        dxiVar.e = dxiVar2.e;
        dxiVar.f = dxiVar2.f;
        dxiVar.g = dxiVar2.g;
        dxiVar.j = dxiVar2.j;
        dxiVar.h = dxiVar2.h;
        dxiVar.i = dxiVar2.i;
        dxj dxjVar = dxgVar.b;
        dxj dxjVar2 = this.b;
        dxjVar.a = dxjVar2.a;
        dxjVar.b = dxjVar2.b;
        dxjVar.d = dxjVar2.d;
        dxjVar.e = dxjVar2.e;
        dxjVar.c = dxjVar2.c;
        dxk dxkVar = dxgVar.e;
        dxk dxkVar2 = this.e;
        dxkVar.b = dxkVar2.b;
        dxkVar.c = dxkVar2.c;
        dxkVar.d = dxkVar2.d;
        dxkVar.e = dxkVar2.e;
        dxkVar.f = dxkVar2.f;
        dxkVar.g = dxkVar2.g;
        dxkVar.h = dxkVar2.h;
        dxkVar.i = dxkVar2.i;
        dxkVar.j = dxkVar2.j;
        dxkVar.k = dxkVar2.k;
        dxkVar.l = dxkVar2.l;
        dxkVar.m = dxkVar2.m;
        dxkVar.n = dxkVar2.n;
        dxkVar.o = dxkVar2.o;
        dxgVar.a = this.a;
        dxgVar.g = this.g;
        return dxgVar;
    }
}
