package defpackage;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.text.TextUtils;
import android.util.Log;
import com.google.android.apps.messaging.R;
import com.google.android.apps.messaging.shared.datamodel.databasegen.tabledefinitions.ParticipantsTable;
import com.google.android.apps.messaging.shared.datamodel.etouffee.impl.TachyonKeyWorker;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class iew {
    public final Object a;

    public iew(Object obj) {
        this.a = obj;
    }

    public final String a(String str, String str2) {
        Object e = ((utz) ier.g.get()).e();
        e.getClass();
        if (!((Boolean) e).booleanValue()) {
            if (str == null || str.length() == 0) {
                str = null;
                if (str2 != null && str2.length() != 0) {
                    str = str2;
                }
            }
            if (str != null && !qqs.d(str)) {
                String string = ((Context) this.a).getString(R.string.happy_birthday_name, str);
                string.getClass();
                return string;
            }
            String string2 = ((Context) this.a).getString(R.string.happy_birthday_no_name);
            string2.getClass();
            return string2;
        }
        String string3 = ((Context) this.a).getString(R.string.same_birthday_nudge_text);
        string3.getClass();
        return string3;
    }

    /* JADX WARN: Type inference failed for: r0v2, types: [armf, java.lang.Object] */
    public final void b(int i) {
        aozy createBuilder = amts.a.createBuilder();
        if (!createBuilder.b.isMutable()) {
            createBuilder.u();
        }
        amts amtsVar = (amts) createBuilder.b;
        amtsVar.c = i - 1;
        amtsVar.b |= 1;
        amts amtsVar2 = (amts) createBuilder.s();
        maq maqVar = (maq) this.a.b();
        amfq amfqVar = (amfq) amfr.a.createBuilder();
        amfp amfpVar = amfp.BUGLE_SYSTEM_BACKUP_EVENT;
        if (!amfqVar.b.isMutable()) {
            amfqVar.u();
        }
        amfr amfrVar = (amfr) amfqVar.b;
        amfrVar.i = amfpVar.dg;
        amfrVar.b |= 1;
        if (!amfqVar.b.isMutable()) {
            amfqVar.u();
        }
        amfr amfrVar2 = (amfr) amfqVar.b;
        amtsVar2.getClass();
        amfrVar2.bn = amtsVar2;
        amfrVar2.g |= 32768;
        maqVar.k(amfqVar, amrs.BUGLE_SYSTEM_BACKUP_EVENT);
    }

    public final ikr c(String str, agoz agozVar, arqv arqvVar) {
        return ((gpx) this.a).B(str, new ikx(agozVar), new ikv(arqvVar, agozVar, (arpe) null, 0));
    }

    public final String d(List list) {
        if (!list.isEmpty()) {
            String y = wfh.y((String) ((agoe) list.get(0)).e);
            int i = ((alsx) list).c;
            if (i > 1) {
                String string = ((Context) this.a).getResources().getString(R.string.contact_has_multiple_destinations_phone, y, String.valueOf(i - 1));
                string.getClass();
                return string;
            }
            y.getClass();
            return y;
        }
        throw new IllegalStateException("Check failed.");
    }

    public final /* bridge */ /* synthetic */ Object e() {
        Method method = aiur.a;
        Object obj = this.a;
        boolean z = false;
        try {
            Method method2 = aiur.b;
            if (method2 != null) {
                z = ((Boolean) method2.invoke(null, obj, false)).booleanValue();
            }
        } catch (Exception e) {
            Log.e("SystemProperties", "get error", e);
        }
        return Boolean.valueOf(z);
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [armf, java.lang.Object] */
    public final akul f(twm twmVar) {
        return ((uof) this.a.b()).b(upk.a("encrypted_message_delete", twmVar));
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [armf, java.lang.Object] */
    public final void g() {
        ((agnw) this.a.b()).j().endTransaction();
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [armf, java.lang.Object] */
    public final boolean h() {
        SQLiteDatabase j = ((agnw) this.a.b()).j();
        if (j != null && j.isOpen()) {
            return true;
        }
        return false;
    }

    public final void i(String str) {
        hgi hgiVar = new hgi((char[]) null);
        hgiVar.n("canonical_number", str);
        gsz gszVar = new gsz(TachyonKeyWorker.class);
        gszVar.c("bugle_tk_worker");
        gszVar.i(hgiVar.j());
        gsd gsdVar = new gsd();
        gsdVar.c(2);
        gszVar.f(gsdVar.a());
        gvf.ar((Context) this.a).l("PrekeysManager-".concat(String.valueOf(str)), gso.KEEP, gszVar.j());
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [java.lang.Object, trz] */
    public final int j() {
        if (this.a.h()) {
            return R.string.message_is_end_to_end_encrypted;
        }
        return R.string.message_is_encrypted;
    }

    public final boolean k() {
        if (adwi.k((Context) this.a) && !adwi.g((Context) this.a, "FileTransferServiceVersions", 2)) {
            return false;
        }
        return true;
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [armf, java.lang.Object] */
    public final void l(trv trvVar, uta utaVar) {
        ((uof) this.a.b()).a(upk.b("upload_attachments_to_blobstore", trvVar, utaVar));
    }

    /* JADX WARN: Type inference failed for: r0v0, types: [armf, java.lang.Object] */
    public final rzz m(agoz agozVar, String str) {
        return new rzz((wfh) this.a.b(), agozVar, null, str);
    }

    public final String n(ParticipantsTable.BindData bindData, boolean z) {
        String L = bindData.L();
        String K = bindData.K();
        if (z) {
            if (!TextUtils.isEmpty(L)) {
                return L;
            }
            if (!TextUtils.isEmpty(K)) {
                return K;
            }
        } else {
            if (!TextUtils.isEmpty(K)) {
                return K;
            }
            if (!TextUtils.isEmpty(L)) {
                return L;
            }
        }
        String J = bindData.J();
        if (!TextUtils.isEmpty(J)) {
            return J;
        }
        return ((Context) this.a).getResources().getString(R.string.unknown_sender);
    }

    public iew(Object obj, byte[] bArr) {
        this.a = obj;
    }

    public iew() {
        this(false);
    }

    public iew(Set set) {
        set.getClass();
        this.a = set;
    }

    /* JADX WARN: Type inference failed for: r3v1, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r4v1, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r4v10, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r4v4, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r4v7, types: [armf, java.lang.Object] */
    public iew(iew iewVar, iew iewVar2, iew iewVar3, iew iewVar4, iew iewVar5) {
        ArrayList arrayList = new ArrayList();
        this.a = arrayList;
        Context context = (Context) iewVar.a.b();
        context.getClass();
        arrayList.add(new knh(context));
        Context context2 = (Context) iewVar2.a.b();
        context2.getClass();
        arrayList.add(new knd(context2));
        Context context3 = (Context) iewVar3.a.b();
        context3.getClass();
        arrayList.add(new kng(context3));
        Context context4 = (Context) iewVar5.a.b();
        context4.getClass();
        arrayList.add(new kne(context4));
        Context context5 = (Context) iewVar4.a.b();
        context5.getClass();
        arrayList.add(new knf(context5));
    }

    public iew(boolean z) {
        this.a = ascy.a(Boolean.valueOf(z));
    }

    public iew(Context context) {
        context.getClass();
        this.a = context;
    }

    public iew(Context context, byte[] bArr) {
        context.getClass();
        this.a = context;
    }

    public iew(armf armfVar, char[] cArr, byte[] bArr, byte[] bArr2) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(armf armfVar, byte[] bArr, char[] cArr) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(armf armfVar, char[] cArr, byte[] bArr) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(armf armfVar, byte[] bArr, byte[] bArr2, byte[] bArr3) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(armf armfVar, byte[] bArr, byte[] bArr2) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(armf armfVar, char[] cArr) {
        armfVar.getClass();
        this.a = armfVar;
    }

    public iew(char[] cArr, byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "messages._id";
        a.c = new wsy();
        a.a();
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.d(true);
        a2.a = "messages.conversation_id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.sender_id";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "messages.sender_send_destination";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.msisdn_receiving_rcs_message";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.receiving_network_country";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.c(true);
        a7.a = "messages.sent_timestamp";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "messages.queue_insert_timestamp";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.c(true);
        a9.a = "messages.received_timestamp";
        a9.c = new wsy();
        this.a = new scy(a9.a());
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "messages.message_protocol";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.c(true);
        a11.a = "messages.message_status";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "messages.message_report_status";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.c(true);
        a13.a = "messages.seen";
        a13.e(true);
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.read";
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.c(true);
        a15.a = "messages.sms_message_uri";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "messages.sms_priority";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_message_size";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "messages.mms_subject";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_transaction_id";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_content_location";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.a = "messages.mms_expiry";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.c(true);
        a22.a = "messages.rcs_expiry";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "messages.mms_retrieve_text";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "messages.raw_status";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.c(true);
        a25.d(true);
        a25.a = "messages.self_id";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.c(true);
        a26.a = "messages.my_identity";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.d(true);
        a27.b = new scs(7);
        a27.a = "messages.my_identity_foreign_key";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 1;
        a28.a = "messages.retry_start_timestamp";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.a = "messages.cloud_sync_id";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 7;
        a30.c(true);
        a30.a = "messages.rcs_message_id";
        a30.e(true);
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 4;
        a31.c(true);
        a31.a = "messages.rcs_message_id_with_text_type";
        a31.e(true);
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "messages.etouffee_status";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "messages.verification_status";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "messages.rcs_ui_status";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.c(true);
        a35.a = "messages.is_hidden";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 7;
        a36.a = "messages.rcs_remote_instance";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "messages.rcs_file_transfer_session_id";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "messages.sms_error_code";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.a = "messages.sms_error_desc_map_name";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 4;
        a40.a = "messages.correlation_id";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.j(true);
        a41.c(true);
        a41.a = "messages.cms_id";
        a41.e(true);
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 2;
        a42.a = "messages.cms_last_mod_seq";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 4;
        a43.c(true);
        a43.a = "messages.web_id";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "messages.usage_stats_logging_id";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "messages.send_counter";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 4;
        a46.c(true);
        a46.a = "messages.original_rcs_message_id";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.a = "messages.custom_delivery_receipt_mime_type";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 5;
        a48.a = "messages.custom_delivery_receipt_content";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 1;
        a49.a = "messages.report_attempt_acounter";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 5;
        a50.a = "messages.custom_headers";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 4;
        a51.j(true);
        a51.c(true);
        a51.a = "messages.cms_correlation_id";
        a51.e(true);
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.c(true);
        a52.d(true);
        a52.b = new scs(8);
        a52.a = "messages.group_private_participant";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 1;
        a53.c(true);
        a53.d(true);
        a53.b = new scs(9);
        a53.a = "messages.original_message_id";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.a = "messages.awaiting_reverse_sync";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 4;
        a55.a = "messages.old_sms_message_uri";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 4;
        a56.j(true);
        a56.c(true);
        a56.a = "messages.draft_id";
        a56.e(true);
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 1;
        a57.a = "messages.result_code";
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.cms_life_cycle";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.fallback_reason";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 1;
        a60.a = "messages.auto_retry_counter";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 2;
        a61.a = "messages.can_revoke_before_delivered_with_rcs";
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 5;
        a62.a = "messages.trace_id";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.a = "messages.outgoing_delivery_report_status";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.outgoing_read_report_status";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 1;
        a65.a = "messages.xms_transport";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 1;
        a66.a = "messages.message_original_protocol";
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 4;
        a67.j(true);
        a67.c(true);
        a67.a = "messages.satellite_datagram_id";
        a67.e(true);
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 1;
        a68.a = "messages.encryption_protocol";
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 4;
        a69.j(true);
        a69.c(true);
        a69.a = "messages.message_persistence_id";
        a69.e(true);
        a69.c = new wsy();
        a69.a();
    }

    public iew(byte[] bArr, byte[] bArr2, byte[] bArr3) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "messages._id";
        a.c = new wsy();
        a.a();
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.d(true);
        a2.a = "messages.conversation_id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.sender_id";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "messages.sender_send_destination";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.msisdn_receiving_rcs_message";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.receiving_network_country";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.c(true);
        a7.a = "messages.sent_timestamp";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "messages.queue_insert_timestamp";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.c(true);
        a9.a = "messages.received_timestamp";
        a9.c = new wsy();
        this.a = new sde(a9.a());
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "messages.message_protocol";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.c(true);
        a11.a = "messages.message_status";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "messages.message_report_status";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.c(true);
        a13.a = "messages.seen";
        a13.e(true);
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.read";
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.c(true);
        a15.a = "messages.sms_message_uri";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "messages.sms_priority";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_message_size";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "messages.mms_subject";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_transaction_id";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_content_location";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.a = "messages.mms_expiry";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.c(true);
        a22.a = "messages.rcs_expiry";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "messages.mms_retrieve_text";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "messages.raw_status";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.c(true);
        a25.d(true);
        a25.a = "messages.self_id";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.c(true);
        a26.a = "messages.my_identity";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.d(true);
        a27.b = new scs(10);
        a27.a = "messages.my_identity_foreign_key";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 1;
        a28.a = "messages.retry_start_timestamp";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.a = "messages.cloud_sync_id";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 7;
        a30.c(true);
        a30.a = "messages.rcs_message_id";
        a30.e(true);
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 4;
        a31.c(true);
        a31.a = "messages.rcs_message_id_with_text_type";
        a31.e(true);
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "messages.etouffee_status";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "messages.verification_status";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "messages.rcs_ui_status";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.c(true);
        a35.a = "messages.is_hidden";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 7;
        a36.a = "messages.rcs_remote_instance";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "messages.rcs_file_transfer_session_id";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "messages.sms_error_code";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.a = "messages.sms_error_desc_map_name";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 4;
        a40.a = "messages.correlation_id";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.j(true);
        a41.c(true);
        a41.a = "messages.cms_id";
        a41.e(true);
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 2;
        a42.a = "messages.cms_last_mod_seq";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 4;
        a43.c(true);
        a43.a = "messages.web_id";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "messages.usage_stats_logging_id";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "messages.send_counter";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 4;
        a46.c(true);
        a46.a = "messages.original_rcs_message_id";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.a = "messages.custom_delivery_receipt_mime_type";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 5;
        a48.a = "messages.custom_delivery_receipt_content";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 1;
        a49.a = "messages.report_attempt_acounter";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 5;
        a50.a = "messages.custom_headers";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 4;
        a51.j(true);
        a51.c(true);
        a51.a = "messages.cms_correlation_id";
        a51.e(true);
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.c(true);
        a52.d(true);
        a52.b = new scs(11);
        a52.a = "messages.group_private_participant";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 1;
        a53.c(true);
        a53.d(true);
        a53.b = new scs(12);
        a53.a = "messages.original_message_id";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.a = "messages.awaiting_reverse_sync";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 4;
        a55.a = "messages.old_sms_message_uri";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 4;
        a56.j(true);
        a56.c(true);
        a56.a = "messages.draft_id";
        a56.e(true);
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 1;
        a57.a = "messages.result_code";
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.cms_life_cycle";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.fallback_reason";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 1;
        a60.a = "messages.auto_retry_counter";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 2;
        a61.a = "messages.can_revoke_before_delivered_with_rcs";
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 5;
        a62.a = "messages.trace_id";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.a = "messages.outgoing_delivery_report_status";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.outgoing_read_report_status";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 1;
        a65.a = "messages.xms_transport";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 1;
        a66.a = "messages.message_original_protocol";
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 4;
        a67.j(true);
        a67.c(true);
        a67.a = "messages.satellite_datagram_id";
        a67.e(true);
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 1;
        a68.a = "messages.encryption_protocol";
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 4;
        a69.j(true);
        a69.c(true);
        a69.a = "messages.message_persistence_id";
        a69.e(true);
        a69.c = new wsy();
        a69.a();
        agmi a70 = agmk.a();
        a70.d = 2;
        a70.j(true);
        a70.f(true);
        a70.c(true);
        a70.a = "b._id";
        a70.c = new wsy();
        a70.a();
        agmi a71 = agmk.a();
        a71.d = 2;
        a71.j(true);
        a71.c(true);
        a71.d(true);
        a71.b = new scs(13);
        a71.a = "b.message_id";
        a71.c = new wsy();
        a71.a();
        agmi a72 = agmk.a();
        a72.d = 5;
        a72.a = "b.reactions_data";
        a72.c = new wsy();
        a72.a();
        agmi a73 = agmk.a();
        a73.d = 2;
        a73.c(true);
        a73.d(true);
        a73.b = new scs(14);
        a73.a = "b.reacted_message_id";
        a73.c = new wsy();
        a73.a();
        agmi a74 = agmk.a();
        a74.d = 2;
        a74.a = "b.reaction";
        a74.c = new wsy();
        a74.a();
        agmi a75 = agmk.a();
        a75.d = 5;
        a75.a = "b.applied_reaction";
        a75.c = new wsy();
        a75.a();
        agmi a76 = agmk.a();
        a76.d = 5;
        a76.c(true);
        a76.a = "b.animation_effect";
        a76.c = new wsy();
        a76.a();
    }

    public iew(byte[] bArr, byte[] bArr2) {
        agmi a = agmk.a();
        a.k(2);
        a.j(true);
        a.i(true);
        a.c(true);
        a.d(true);
        a.g(new scs(17));
        a.b("message_replies_view.message_id_message_replies");
        a.e(true);
        a.h(new wsy());
        this.a = new sdm(a.a());
        agmi a2 = agmk.a();
        a2.k(2);
        a2.c(true);
        a2.d(true);
        a2.g(new scs(18));
        a2.b("message_replies_view.replied_to_message_id_message_replies");
        a2.h(new wsy());
        a2.a();
        agmi a3 = agmk.a();
        a3.k(1);
        a3.b("message_replies_view.replied_to_message_id_null_reason_message_replies");
        a3.h(new wsy());
        a3.a();
        agmi a4 = agmk.a();
        a4.k(4);
        a4.c(true);
        a4.b("message_replies_view.replied_to_rcs_message_id_message_replies");
        a4.h(new wsy());
        a4.a();
        agmi a5 = agmk.a();
        a5.k(2);
        a5.j(true);
        a5.f(true);
        a5.c(true);
        a5.b("message_replies_view._id_messages");
        a5.h(new wsy());
        a5.a();
        agmi a6 = agmk.a();
        a6.k(1);
        a6.c(true);
        a6.b("message_replies_view.received_timestamp_messages");
        a6.h(new wsy());
        a6.a();
        agmi a7 = agmk.a();
        a7.k(1);
        a7.c(true);
        a7.d(true);
        a7.b("message_replies_view.conversation_id_messages");
        a7.h(new wsy());
        a7.a();
        agmi a8 = agmk.a();
        a8.k(1);
        a8.c(true);
        a8.d(true);
        a8.b("message_replies_view.sender_participant_id_messages");
        a8.h(new wsy());
        a8.a();
        agmi a9 = agmk.a();
        a9.k(4);
        a9.b("message_replies_view.sender_send_destination_messages");
        a9.h(new wsy());
        a9.a();
        agmi a10 = agmk.a();
        a10.k(4);
        a10.b("message_replies_view.msisdn_receiving_rcs_message_messages");
        a10.h(new wsy());
        a10.a();
        agmi a11 = agmk.a();
        a11.k(4);
        a11.b("message_replies_view.receiving_network_country_messages");
        a11.h(new wsy());
        a11.a();
        agmi a12 = agmk.a();
        a12.k(1);
        a12.c(true);
        a12.b("message_replies_view.sent_timestamp_messages");
        a12.h(new wsy());
        a12.a();
        agmi a13 = agmk.a();
        a13.k(1);
        a13.b("message_replies_view.queue_insert_timestamp_messages");
        a13.h(new wsy());
        a13.a();
        agmi a14 = agmk.a();
        a14.k(1);
        a14.b("message_replies_view.protocol_messages");
        a14.h(new wsy());
        a14.a();
        agmi a15 = agmk.a();
        a15.k(1);
        a15.c(true);
        a15.b("message_replies_view.status_messages");
        a15.h(new wsy());
        a15.a();
        agmi a16 = agmk.a();
        a16.k(1);
        a16.b("message_replies_view.message_report_status_messages");
        a16.h(new wsy());
        a16.a();
        agmi a17 = agmk.a();
        a17.k(1);
        a17.c(true);
        a17.b("message_replies_view.notified_messages");
        a17.e(true);
        a17.h(new wsy());
        a17.a();
        agmi a18 = agmk.a();
        a18.k(1);
        a18.c(true);
        a18.b("message_replies_view.read_messages");
        a18.h(new wsy());
        a18.a();
        agmi a19 = agmk.a();
        a19.k(4);
        a19.c(true);
        a19.b("message_replies_view.sms_message_uri_messages");
        a19.h(new wsy());
        a19.a();
        agmi a20 = agmk.a();
        a20.k(1);
        a20.b("message_replies_view.sms_priority_messages");
        a20.h(new wsy());
        a20.a();
        agmi a21 = agmk.a();
        a21.k(1);
        a21.b("message_replies_view.sms_message_size_messages");
        a21.h(new wsy());
        a21.a();
        agmi a22 = agmk.a();
        a22.k(4);
        a22.b("message_replies_view.mms_subject_messages");
        a22.h(new wsy());
        a22.a();
        agmi a23 = agmk.a();
        a23.k(4);
        a23.b("message_replies_view.mms_transaction_id_messages");
        a23.h(new wsy());
        a23.a();
        agmi a24 = agmk.a();
        a24.k(4);
        a24.b("message_replies_view.mms_content_location_messages");
        a24.h(new wsy());
        a24.a();
        agmi a25 = agmk.a();
        a25.k(1);
        a25.b("message_replies_view.mms_expiry_messages");
        a25.h(new wsy());
        a25.a();
        agmi a26 = agmk.a();
        a26.k(1);
        a26.c(true);
        a26.b("message_replies_view.rcs_expiry_messages");
        a26.h(new wsy());
        a26.a();
        agmi a27 = agmk.a();
        a27.k(4);
        a27.b("message_replies_view.mms_retrieve_text_messages");
        a27.h(new wsy());
        a27.a();
        agmi a28 = agmk.a();
        a28.k(1);
        a28.b("message_replies_view.raw_telephony_status_messages");
        a28.h(new wsy());
        a28.a();
        agmi a29 = agmk.a();
        a29.k(1);
        a29.c(true);
        a29.d(true);
        a29.b("message_replies_view.self_id_messages");
        a29.h(new wsy());
        a29.a();
        agmi a30 = agmk.a();
        a30.k(4);
        a30.c(true);
        a30.b("message_replies_view.my_identity_messages");
        a30.h(new wsy());
        a30.a();
        agmi a31 = agmk.a();
        a31.k(4);
        a31.c(true);
        a31.d(true);
        a31.g(new scs(19));
        a31.b("message_replies_view.my_identity_messages");
        a31.h(new wsy());
        a31.a();
        agmi a32 = agmk.a();
        a32.k(1);
        a32.b("message_replies_view.retry_start_timestamp_messages");
        a32.h(new wsy());
        a32.a();
        agmi a33 = agmk.a();
        a33.k(4);
        a33.c(true);
        a33.b("message_replies_view.cloud_sync_id_messages");
        a33.h(new wsy());
        a33.a();
        agmi a34 = agmk.a();
        a34.k(7);
        a34.c(true);
        a34.b("message_replies_view.rcs_message_id_messages");
        a34.e(true);
        a34.h(new wsy());
        a34.a();
        agmi a35 = agmk.a();
        a35.k(4);
        a35.c(true);
        a35.b("message_replies_view.rcs_message_id_messages");
        a35.e(true);
        a35.h(new wsy());
        a35.a();
        agmi a36 = agmk.a();
        a36.k(1);
        a36.b("message_replies_view.rcs_encryption_status_messages");
        a36.h(new wsy());
        a36.a();
        agmi a37 = agmk.a();
        a37.k(1);
        a37.b("message_replies_view.verification_status_messages");
        a37.h(new wsy());
        a37.a();
        agmi a38 = agmk.a();
        a38.k(1);
        a38.b("message_replies_view.rcs_ui_status_messages");
        a38.h(new wsy());
        a38.a();
        agmi a39 = agmk.a();
        a39.k(1);
        a39.c(true);
        a39.b("message_replies_view.is_hidden_messages");
        a39.h(new wsy());
        a39.a();
        agmi a40 = agmk.a();
        a40.k(7);
        a40.b("message_replies_view.rcs_remote_instance_messages");
        a40.h(new wsy());
        a40.a();
        agmi a41 = agmk.a();
        a41.k(1);
        a41.b("message_replies_view.rcs_file_transfer_session_id_messages");
        a41.h(new wsy());
        a41.a();
        agmi a42 = agmk.a();
        a42.k(1);
        a42.b("message_replies_view.sms_error_code_messages");
        a42.h(new wsy());
        a42.a();
        agmi a43 = agmk.a();
        a43.k(4);
        a43.b("message_replies_view.sms_error_desc_map_name_messages");
        a43.h(new wsy());
        a43.a();
        agmi a44 = agmk.a();
        a44.k(4);
        a44.b("message_replies_view.correlation_id_messages");
        a44.h(new wsy());
        a44.a();
        agmi a45 = agmk.a();
        a45.k(4);
        a45.j(true);
        a45.c(true);
        a45.b("message_replies_view.cms_id_messages");
        a45.e(true);
        a45.h(new wsy());
        a45.a();
        agmi a46 = agmk.a();
        a46.k(2);
        a46.b("message_replies_view.cms_last_mod_seq_messages");
        a46.h(new wsy());
        a46.a();
        agmi a47 = agmk.a();
        a47.k(4);
        a47.c(true);
        a47.b("message_replies_view.web_id_messages");
        a47.h(new wsy());
        a47.a();
        agmi a48 = agmk.a();
        a48.k(1);
        a48.b("message_replies_view.usage_stats_logging_id_messages");
        a48.h(new wsy());
        a48.a();
        agmi a49 = agmk.a();
        a49.k(1);
        a49.b("message_replies_view.send_counter_messages");
        a49.h(new wsy());
        a49.a();
        agmi a50 = agmk.a();
        a50.k(4);
        a50.c(true);
        a50.b("message_replies_view.original_rcs_message_id_messages");
        a50.h(new wsy());
        a50.a();
        agmi a51 = agmk.a();
        a51.k(4);
        a51.b("message_replies_view.custom_delivery_receipt_mime_type_messages");
        a51.h(new wsy());
        a51.a();
        agmi a52 = agmk.a();
        a52.k(5);
        a52.b("message_replies_view.custom_delivery_receipt_content_messages");
        a52.h(new wsy());
        a52.a();
        agmi a53 = agmk.a();
        a53.k(1);
        a53.b("message_replies_view.report_attempt_counter_messages");
        a53.h(new wsy());
        a53.a();
        agmi a54 = agmk.a();
        a54.k(5);
        a54.b("message_replies_view.custom_headers_messages");
        a54.h(new wsy());
        a54.a();
        agmi a55 = agmk.a();
        a55.k(4);
        a55.j(true);
        a55.c(true);
        a55.b("message_replies_view.cms_correlation_id_messages");
        a55.e(true);
        a55.h(new wsy());
        a55.a();
        agmi a56 = agmk.a();
        a56.k(1);
        a56.c(true);
        a56.d(true);
        a56.g(new scs(20));
        a56.b("message_replies_view.group_private_participant_messages");
        a56.h(new wsy());
        a56.a();
        agmi a57 = agmk.a();
        a57.k(1);
        a57.c(true);
        a57.d(true);
        a57.g(new sdl(1));
        a57.b("message_replies_view.original_message_id_messages");
        a57.h(new wsy());
        a57.a();
        agmi a58 = agmk.a();
        a58.k(1);
        a58.b("message_replies_view.awaiting_reverse_sync_messages");
        a58.h(new wsy());
        a58.a();
        agmi a59 = agmk.a();
        a59.k(4);
        a59.b("message_replies_view.old_sms_message_uri_messages");
        a59.h(new wsy());
        a59.a();
        agmi a60 = agmk.a();
        a60.k(4);
        a60.j(true);
        a60.c(true);
        a60.b("message_replies_view.draft_id_messages");
        a60.e(true);
        a60.h(new wsy());
        a60.a();
        agmi a61 = agmk.a();
        a61.k(1);
        a61.b("message_replies_view.result_code_messages");
        a61.h(new wsy());
        a61.a();
        agmi a62 = agmk.a();
        a62.k(1);
        a62.b("message_replies_view.cms_life_cycle_messages");
        a62.h(new wsy());
        a62.a();
        agmi a63 = agmk.a();
        a63.k(1);
        a63.b("message_replies_view.fallback_reason_messages");
        a63.h(new wsy());
        a63.a();
        agmi a64 = agmk.a();
        a64.k(1);
        a64.b("message_replies_view.auto_retry_counter_messages");
        a64.h(new wsy());
        a64.a();
        agmi a65 = agmk.a();
        a65.k(2);
        a65.b("message_replies_view.can_revoke_before_delivered_with_rcs_messages");
        a65.h(new wsy());
        a65.a();
        agmi a66 = agmk.a();
        a66.k(5);
        a66.b("message_replies_view.trace_id_messages");
        a66.h(new wsy());
        a66.a();
        agmi a67 = agmk.a();
        a67.k(1);
        a67.b("message_replies_view.outgoing_delivery_report_status_messages");
        a67.h(new wsy());
        a67.a();
        agmi a68 = agmk.a();
        a68.k(1);
        a68.b("message_replies_view.outgoing_read_report_status_messages");
        a68.h(new wsy());
        a68.a();
        agmi a69 = agmk.a();
        a69.k(1);
        a69.b("message_replies_view.xms_transport_messages");
        a69.h(new wsy());
        a69.a();
        agmi a70 = agmk.a();
        a70.k(1);
        a70.b("message_replies_view.original_protocol_messages");
        a70.h(new wsy());
        a70.a();
        agmi a71 = agmk.a();
        a71.k(4);
        a71.j(true);
        a71.c(true);
        a71.b("message_replies_view.satellite_datagram_id_messages");
        a71.e(true);
        a71.h(new wsy());
        a71.a();
        agmi a72 = agmk.a();
        a72.k(1);
        a72.b("message_replies_view.encryption_protocol_messages");
        a72.h(new wsy());
        a72.a();
        agmi a73 = agmk.a();
        a73.k(4);
        a73.j(true);
        a73.c(true);
        a73.b("message_replies_view.message_persistence_id_messages");
        a73.e(true);
        a73.h(new wsy());
        a73.a();
        agmi a74 = agmk.a();
        a74.k(2);
        a74.j(true);
        a74.f(true);
        a74.c(true);
        a74.b("message_replies_view._id_participants");
        a74.h(new wsy());
        a74.a();
        agmi a75 = agmk.a();
        a75.k(1);
        a75.c(true);
        a75.b("message_replies_view.sub_id_participants");
        a75.e(true);
        a75.h(new wsy());
        a75.a();
        agmi a76 = agmk.a();
        a76.k(4);
        a76.c(true);
        a76.b("message_replies_view.normalized_destination_participants");
        a76.e(true);
        a76.h(new wsy());
        a76.a();
        agmi a77 = agmk.a();
        a77.k(4);
        a77.b("message_replies_view.display_destination_participants");
        a77.h(new wsy());
        a77.a();
        agmi a78 = agmk.a();
        a78.k(4);
        a78.b("message_replies_view.full_name_participants");
        a78.h(new wsy());
        a78.a();
        agmi a79 = agmk.a();
        a79.k(4);
        a79.b("message_replies_view.first_name_participants");
        a79.h(new wsy());
        a79.a();
        agmi a80 = agmk.a();
        a80.k(4);
        a80.c(true);
        a80.b("message_replies_view.my_identity_token_participants");
        a80.h(new wsy());
        a80.a();
        agmi a81 = agmk.a();
        a81.k(4);
        a81.c(true);
        a81.d(true);
        a81.g(new sdl(0));
        a81.b("message_replies_view.my_identity_token_foreign_key_participants");
        a81.h(new wsy());
        a81.a();
        agmi a82 = agmk.a();
        a82.k(1);
        a82.b("message_replies_view.sim_slot_id_participants");
        a82.h(new wsy());
        a82.a();
        agmi a83 = agmk.a();
        a83.k(4);
        a83.b("message_replies_view.send_destination_participants");
        a83.h(new wsy());
        a83.a();
        agmi a84 = agmk.a();
        a84.k(4);
        a84.j(true);
        a84.c(true);
        a84.b("message_replies_view.comparable_destination_participants");
        a84.e(true);
        a84.h(new wsy());
        a84.a();
        agmi a85 = agmk.a();
        a85.k(4);
        a85.b("message_replies_view.country_code_participants");
        a85.h(new wsy());
        a85.a();
        agmi a86 = agmk.a();
        a86.k(2);
        a86.j(true);
        a86.c(true);
        a86.b("message_replies_view.recipient_id_participants");
        a86.e(true);
        a86.h(new wsy());
        a86.a();
        agmi a87 = agmk.a();
        a87.k(4);
        a87.b("message_replies_view.recipient_canonical_address_participants");
        a87.h(new wsy());
        a87.a();
        agmi a88 = agmk.a();
        a88.k(4);
        a88.b("message_replies_view.profile_photo_uri_participants");
        a88.h(new wsy());
        a88.a();
        agmi a89 = agmk.a();
        a89.k(4);
        a89.b("message_replies_view.contact_photo_uri_participants");
        a89.h(new wsy());
        a89.a();
        agmi a90 = agmk.a();
        a90.k(1);
        a90.b("message_replies_view.contact_id_participants");
        a90.h(new wsy());
        a90.a();
        agmi a91 = agmk.a();
        a91.k(4);
        a91.b("message_replies_view.lookup_key_participants");
        a91.h(new wsy());
        a91.a();
        agmi a92 = agmk.a();
        a92.k(1);
        a92.b("message_replies_view.color_palette_index_participants");
        a92.h(new wsy());
        a92.a();
        agmi a93 = agmk.a();
        a93.k(1);
        a93.b("message_replies_view.color_type_participants");
        a93.h(new wsy());
        a93.a();
        agmi a94 = agmk.a();
        a94.k(1);
        a94.b("message_replies_view.extended_color_participants");
        a94.h(new wsy());
        a94.a();
        agmi a95 = agmk.a();
        a95.k(1);
        a95.b("message_replies_view.blocked_participants");
        a95.h(new wsy());
        a95.a();
        agmi a96 = agmk.a();
        a96.k(4);
        a96.b("message_replies_view.subscription_name_participants");
        a96.h(new wsy());
        a96.a();
        agmi a97 = agmk.a();
        a97.k(1);
        a97.b("message_replies_view.subscription_color_participants");
        a97.h(new wsy());
        a97.a();
        agmi a98 = agmk.a();
        a98.k(4);
        a98.b("message_replies_view.contact_destination_participants");
        a98.h(new wsy());
        a98.a();
        agmi a99 = agmk.a();
        a99.k(1);
        a99.b("message_replies_view.participant_type_participants");
        a99.h(new wsy());
        a99.a();
        agmi a100 = agmk.a();
        a100.k(1);
        a100.b("message_replies_view.video_reachability_participants");
        a100.h(new wsy());
        a100.a();
        agmi a101 = agmk.a();
        a101.k(4);
        a101.b("message_replies_view.alias_participants");
        a101.h(new wsy());
        a101.a();
        agmi a102 = agmk.a();
        a102.k(1);
        a102.b("message_replies_view.is_spam_participants");
        a102.h(new wsy());
        a102.a();
        agmi a103 = agmk.a();
        a103.k(1);
        a103.b("message_replies_view.is_rcs_available_participants");
        a103.h(new wsy());
        a103.a();
        agmi a104 = agmk.a();
        a104.k(1);
        a104.b("message_replies_view.is_spam_source_participants");
        a104.h(new wsy());
        a104.a();
        agmi a105 = agmk.a();
        a105.k(4);
        a105.j(true);
        a105.c(true);
        a105.b("message_replies_view.cms_id_participants");
        a105.e(true);
        a105.h(new wsy());
        a105.a();
        agmi a106 = agmk.a();
        a106.k(1);
        a106.b("message_replies_view.latest_verification_status_participants");
        a106.h(new wsy());
        a106.a();
        agmi a107 = agmk.a();
        a107.k(4);
        a107.b("message_replies_view.profile_photo_blob_id_participants");
        a107.h(new wsy());
        a107.a();
        agmi a108 = agmk.a();
        a108.k(5);
        a108.b("message_replies_view.profile_photo_encryption_key_participants");
        a108.h(new wsy());
        a108.a();
        agmi a109 = agmk.a();
        a109.k(1);
        a109.b("message_replies_view.directory_id_participants");
        a109.h(new wsy());
        a109.a();
        agmi a110 = agmk.a();
        a110.k(1);
        a110.b("message_replies_view.is_check_constraint_enabled_via_phenotype_participants");
        a110.h(new wsy());
        a110.a();
        agmi a111 = agmk.a();
        a111.k(1);
        a111.b("message_replies_view.is_valid_phone_number_data_participants");
        a111.h(new wsy());
        a111.a();
        agmi a112 = agmk.a();
        a112.k(2);
        a112.c(true);
        a112.d(true);
        a112.g(new sdl(2));
        a112.b("message_replies_view.duplicate_of_participants");
        a112.h(new wsy());
        a112.a();
        agmi a113 = agmk.a();
        a113.k(1);
        a113.b("message_replies_view.cms_life_cycle_participants");
        a113.h(new wsy());
        a113.a();
        agmi a114 = agmk.a();
        a114.k(1);
        a114.b("message_replies_view.norm_ui_status_participants");
        a114.h(new wsy());
        a114.a();
        agmi a115 = agmk.a();
        a115.k(4);
        a115.b("message_replies_view.last_modified_by_key_participants");
        a115.h(new wsy());
        a115.a();
        agmi a116 = agmk.a();
        a116.k(1);
        a116.b("message_replies_view.name_source_participants");
        a116.h(new wsy());
        a116.a();
        agmi a117 = agmk.a();
        a117.k(1);
        a117.b("message_replies_view.photo_source_participants");
        a117.h(new wsy());
        a117.a();
        agmi a118 = agmk.a();
        a118.k(1);
        a118.b("message_replies_view.profile_photo_user_preference_participants");
        a118.h(new wsy());
        a118.a();
        agmi a119 = agmk.a();
        a119.k(5);
        a119.b("message_replies_view.contact_metadata_participants");
        a119.h(new wsy());
        a119.a();
        agmi a120 = agmk.a();
        a120.k(2);
        a120.j(true);
        a120.f(true);
        a120.c(true);
        a120.b("message_replies_view._id_parts");
        a120.h(new wsy());
        a120.a();
        agmi a121 = agmk.a();
        a121.k(4);
        a121.b("message_replies_view.text_parts");
        a121.h(new wsy());
        a121.a();
        agmi a122 = agmk.a();
        a122.k(4);
        a122.b("message_replies_view.uri_parts");
        a122.h(new wsy());
        a122.a();
        agmi a123 = agmk.a();
        a123.k(4);
        a123.c(true);
        a123.b("message_replies_view.content_type_parts");
        a123.h(new wsy());
        a123.a();
        agmi a124 = agmk.a();
        a124.k(4);
        a124.b("message_replies_view.file_name_parts");
        a124.h(new wsy());
        a124.a();
        agmi a125 = agmk.a();
        a125.k(1);
        a125.b("message_replies_view.duration_parts");
        a125.h(new wsy());
        a125.a();
        agmi a126 = agmk.a();
        a126.k(8);
        a126.b("message_replies_view.parts__ROWID_parts");
        a126.h(new wsy());
        a126.a();
        agmi a127 = agmk.a();
        a127.k(1);
        a127.c(true);
        a127.d(true);
        a127.b("message_replies_view.message_id_parts");
        a127.h(new wsy());
        a127.a();
        agmi a128 = agmk.a();
        a128.k(4);
        a128.b("message_replies_view.original_uri_parts");
        a128.h(new wsy());
        a128.a();
        agmi a129 = agmk.a();
        a129.k(4);
        a129.b("message_replies_view.storage_uri_parts");
        a129.h(new wsy());
        a129.a();
        agmi a130 = agmk.a();
        a130.k(1);
        a130.b("message_replies_view.width_parts");
        a130.h(new wsy());
        a130.a();
        agmi a131 = agmk.a();
        a131.k(1);
        a131.b("message_replies_view.height_parts");
        a131.h(new wsy());
        a131.a();
        agmi a132 = agmk.a();
        a132.k(1);
        a132.b("message_replies_view.timestamp_parts");
        a132.h(new wsy());
        a132.a();
        agmi a133 = agmk.a();
        a133.k(4);
        a133.c(true);
        a133.b("message_replies_view.processing_output_uri_parts");
        a133.h(new wsy());
        a133.a();
        agmi a134 = agmk.a();
        a134.k(1);
        a134.b("message_replies_view.target_size_parts");
        a134.h(new wsy());
        a134.a();
        agmi a135 = agmk.a();
        a135.k(1);
        a135.b("message_replies_view.processing_status_parts");
        a135.h(new wsy());
        a135.a();
        agmi a136 = agmk.a();
        a136.k(1);
        a136.b("message_replies_view.cms_attachment_processing_status_parts");
        a136.h(new wsy());
        a136.a();
        agmi a137 = agmk.a();
        a137.k(1);
        a137.c(true);
        a137.d(true);
        a137.b("message_replies_view.conversation_id_parts");
        a137.h(new wsy());
        a137.a();
        agmi a138 = agmk.a();
        a138.k(1);
        a138.b("message_replies_view.sticker_set_id_parts");
        a138.h(new wsy());
        a138.a();
        agmi a139 = agmk.a();
        a139.k(1);
        a139.b("message_replies_view.sticker_id_parts");
        a139.h(new wsy());
        a139.a();
        agmi a140 = agmk.a();
        a140.k(1);
        a140.b("message_replies_view.media_modified_timestamp_parts");
        a140.h(new wsy());
        a140.a();
        agmi a141 = agmk.a();
        a141.k(3);
        a141.b("message_replies_view.longitude_parts");
        a141.h(new wsy());
        a141.a();
        agmi a142 = agmk.a();
        a142.k(3);
        a142.b("message_replies_view.latitude_parts");
        a142.h(new wsy());
        a142.a();
        agmi a143 = agmk.a();
        a143.k(4);
        a143.b("message_replies_view.preview_content_uri_parts");
        a143.h(new wsy());
        a143.a();
        agmi a144 = agmk.a();
        a144.k(4);
        a144.c(true);
        a144.b("message_replies_view.preview_content_type_parts");
        a144.h(new wsy());
        a144.a();
        agmi a145 = agmk.a();
        a145.k(4);
        a145.b("message_replies_view.fallback_uri_parts");
        a145.h(new wsy());
        a145.a();
        agmi a146 = agmk.a();
        a146.k(1);
        a146.b("message_replies_view.source_parts");
        a146.h(new wsy());
        a146.a();
        agmi a147 = agmk.a();
        a147.k(1);
        a147.b("message_replies_view.bundle_index_parts");
        a147.h(new wsy());
        a147.a();
        agmi a148 = agmk.a();
        a148.k(4);
        a148.b("message_replies_view.blob_id_parts");
        a148.h(new wsy());
        a148.a();
        agmi a149 = agmk.a();
        a149.k(4);
        a149.b("message_replies_view.blob_gaia_email_parts");
        a149.h(new wsy());
        a149.a();
        agmi a150 = agmk.a();
        a150.k(4);
        a150.b("message_replies_view.cms_full_size_blob_id_parts");
        a150.h(new wsy());
        a150.a();
        agmi a151 = agmk.a();
        a151.k(5);
        a151.b("message_replies_view.cms_media_encryption_key_parts");
        a151.h(new wsy());
        a151.a();
        agmi a152 = agmk.a();
        a152.k(5);
        a152.b("message_replies_view.cms_compressed_media_encryption_key_parts");
        a152.h(new wsy());
        a152.a();
        agmi a153 = agmk.a();
        a153.k(1);
        a153.b("message_replies_view.blob_upload_permanent_failure_parts");
        a153.h(new wsy());
        a153.a();
        agmi a154 = agmk.a();
        a154.k(1);
        a154.b("message_replies_view.blob_upload_timestamp_parts");
        a154.h(new wsy());
        a154.a();
        agmi a155 = agmk.a();
        a155.k(4);
        a155.b("message_replies_view.expressive_sticker_name_parts");
        a155.h(new wsy());
        a155.a();
        agmi a156 = agmk.a();
        a156.k(4);
        a156.b("message_replies_view.compressed_blob_id_parts");
        a156.h(new wsy());
        a156.a();
        agmi a157 = agmk.a();
        a157.k(4);
        a157.b("message_replies_view.cms_compressed_blob_id_parts");
        a157.h(new wsy());
        a157.a();
        agmi a158 = agmk.a();
        a158.k(1);
        a158.b("message_replies_view.compressed_blob_upload_permanent_failure_parts");
        a158.h(new wsy());
        a158.a();
        agmi a159 = agmk.a();
        a159.k(1);
        a159.b("message_replies_view.compressed_blob_upload_timestamp_parts");
        a159.h(new wsy());
        a159.a();
        agmi a160 = agmk.a();
        a160.k(5);
        a160.b("message_replies_view.media_encryption_key_parts");
        a160.h(new wsy());
        a160.a();
        agmi a161 = agmk.a();
        a161.k(5);
        a161.b("message_replies_view.compressed_media_encryption_key_parts");
        a161.h(new wsy());
        a161.a();
        agmi a162 = agmk.a();
        a162.k(5);
        a162.b("message_replies_view.attachment_upload_response_parts");
        a162.h(new wsy());
        a162.a();
        agmi a163 = agmk.a();
        a163.k(1);
        a163.b("message_replies_view.missing_entry_in_telephony_parts");
        a163.h(new wsy());
        a163.a();
        agmi a164 = agmk.a();
        a164.k(1);
        a164.b("message_replies_view.awaiting_reverse_sync_parts");
        a164.h(new wsy());
        a164.a();
        agmi a165 = agmk.a();
        a165.k(1);
        a165.b("message_replies_view.file_size_bytes_parts");
        a165.h(new wsy());
        a165.a();
        agmi a166 = agmk.a();
        a166.k(4);
        a166.c(true);
        a166.b("message_replies_view.local_cache_path_parts");
        a166.h(new wsy());
        a166.a();
        agmi a167 = agmk.a();
        a167.k(1);
        a167.b("message_replies_view.media_send_type_parts");
        a167.h(new wsy());
        a167.a();
        agmi a168 = agmk.a();
        a168.k(5);
        a168.b("message_replies_view.voice_metadata_parts");
        a168.h(new wsy());
        a168.a();
        agmi a169 = agmk.a();
        a169.k(1);
        a169.b("message_replies_view.validation_status_parts");
        a169.h(new wsy());
        a169.a();
        agmi a170 = agmk.a();
        a170.k(4);
        a170.b("message_replies_view.processing_id_parts");
        a170.h(new wsy());
        a170.a();
        agmi a171 = agmk.a();
        a171.k(1);
        a171.b("message_replies_view.rich_card_media_download_failure_reason_parts");
        a171.h(new wsy());
        a171.a();
        agmi a172 = agmk.a();
        a172.k(1);
        a172.b("message_replies_view.image_display_state_parts");
        a172.h(new wsy());
        a172.a();
        agmi a173 = agmk.a();
        a173.k(4);
        a173.b("message_replies_view.trigger_url_link_preview");
        a173.h(new wsy());
        a173.a();
        agmi a174 = agmk.a();
        a174.k(2);
        a174.b("message_replies_view.expiration_time_millis_link_preview");
        a174.h(new wsy());
        a174.a();
        agmi a175 = agmk.a();
        a175.k(4);
        a175.b("message_replies_view.link_title_link_preview");
        a175.h(new wsy());
        a175.a();
        agmi a176 = agmk.a();
        a176.k(4);
        a176.b("message_replies_view.link_image_url_link_preview");
        a176.h(new wsy());
        a176.a();
        agmi a177 = agmk.a();
        a177.k(2);
        a177.b("message_replies_view.link_preview_failed_link_preview");
        a177.h(new wsy());
        a177.a();
        agmi a178 = agmk.a();
        a178.k(2);
        a178.j(true);
        a178.f(true);
        a178.c(true);
        a178.b("message_replies_view._id_link_preview");
        a178.h(new wsy());
        a178.a();
        agmi a179 = agmk.a();
        a179.k(2);
        a179.j(true);
        a179.c(true);
        a179.d(true);
        a179.g(new sdl(3));
        a179.b("message_replies_view.message_id_link_preview");
        a179.h(new wsy());
        a179.a();
        agmi a180 = agmk.a();
        a180.k(4);
        a180.b("message_replies_view.link_description_link_preview");
        a180.h(new wsy());
        a180.a();
        agmi a181 = agmk.a();
        a181.k(4);
        a181.b("message_replies_view.link_domain_link_preview");
        a181.h(new wsy());
        a181.a();
        agmi a182 = agmk.a();
        a182.k(4);
        a182.b("message_replies_view.link_canonical_url_link_preview");
        a182.h(new wsy());
        a182.a();
        agmi a183 = agmk.a();
        a183.k(2);
        a183.b("message_replies_view.link_preview_prevented_link_preview");
        a183.h(new wsy());
        a183.a();
    }

    public iew(char[] cArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "conversation_suggestions._id";
        a.c = new wsy();
        this.a = new tnv(a.a());
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.c(true);
        a2.d(true);
        a2.a = "conversation_suggestions.message_id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "conversation_suggestions.conversation_suggestion_type";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "conversation_suggestions.properties";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "conversation_suggestions.post_back_data";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "conversation_suggestions.post_back_encoding";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "conversation_suggestions.rcs_message_id";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.c(true);
        a8.a = "conversation_suggestions.target_rcs_message_id";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "conversation_suggestions.read";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "conversation_suggestions.received_timestamp";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.c(true);
        a11.d(true);
        a11.a = "messages.conversation_id";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 2;
        a12.j(true);
        a12.f(true);
        a12.c(true);
        a12.a = "messages._id";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.c(true);
        a13.d(true);
        a13.a = "messages.sender_id";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.a = "messages.sender_send_destination";
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "messages.msisdn_receiving_rcs_message";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "messages.receiving_network_country";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.c(true);
        a17.a = "messages.sent_timestamp";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "messages.queue_insert_timestamp";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 1;
        a19.c(true);
        a19.a = "messages.received_timestamp";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 1;
        a20.a = "messages.message_protocol";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.c(true);
        a21.a = "messages.message_status";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "messages.message_report_status";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 1;
        a23.c(true);
        a23.a = "messages.seen";
        a23.e(true);
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.c(true);
        a24.a = "messages.read";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 4;
        a25.c(true);
        a25.a = "messages.sms_message_uri";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.a = "messages.sms_priority";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "messages.sms_message_size";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "messages.mms_subject";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.a = "messages.mms_transaction_id";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.a = "messages.mms_content_location";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "messages.mms_expiry";
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.c(true);
        a32.a = "messages.rcs_expiry";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 4;
        a33.a = "messages.mms_retrieve_text";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "messages.raw_status";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.c(true);
        a35.d(true);
        a35.a = "messages.self_id";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 4;
        a36.c(true);
        a36.a = "messages.my_identity";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 4;
        a37.c(true);
        a37.d(true);
        a37.b = new tls(13);
        a37.a = "messages.my_identity_foreign_key";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "messages.retry_start_timestamp";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.c(true);
        a39.a = "messages.cloud_sync_id";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 7;
        a40.c(true);
        a40.a = "messages.rcs_message_id";
        a40.e(true);
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.c(true);
        a41.a = "messages.rcs_message_id_with_text_type";
        a41.e(true);
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "messages.etouffee_status";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "messages.verification_status";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "messages.rcs_ui_status";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.c(true);
        a45.a = "messages.is_hidden";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 7;
        a46.a = "messages.rcs_remote_instance";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 1;
        a47.a = "messages.rcs_file_transfer_session_id";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "messages.sms_error_code";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 4;
        a49.a = "messages.sms_error_desc_map_name";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 4;
        a50.a = "messages.correlation_id";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 4;
        a51.j(true);
        a51.c(true);
        a51.a = "messages.cms_id";
        a51.e(true);
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 2;
        a52.a = "messages.cms_last_mod_seq";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 4;
        a53.c(true);
        a53.a = "messages.web_id";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.a = "messages.usage_stats_logging_id";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 1;
        a55.a = "messages.send_counter";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 4;
        a56.c(true);
        a56.a = "messages.original_rcs_message_id";
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 4;
        a57.a = "messages.custom_delivery_receipt_mime_type";
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 5;
        a58.a = "messages.custom_delivery_receipt_content";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.report_attempt_acounter";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 5;
        a60.a = "messages.custom_headers";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 4;
        a61.j(true);
        a61.c(true);
        a61.a = "messages.cms_correlation_id";
        a61.e(true);
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 1;
        a62.c(true);
        a62.d(true);
        a62.b = new tls(14);
        a62.a = "messages.group_private_participant";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.c(true);
        a63.d(true);
        a63.b = new tls(15);
        a63.a = "messages.original_message_id";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.awaiting_reverse_sync";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 4;
        a65.a = "messages.old_sms_message_uri";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 4;
        a66.j(true);
        a66.c(true);
        a66.a = "messages.draft_id";
        a66.e(true);
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 1;
        a67.a = "messages.result_code";
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 1;
        a68.a = "messages.cms_life_cycle";
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 1;
        a69.a = "messages.fallback_reason";
        a69.c = new wsy();
        a69.a();
        agmi a70 = agmk.a();
        a70.d = 1;
        a70.a = "messages.auto_retry_counter";
        a70.c = new wsy();
        a70.a();
        agmi a71 = agmk.a();
        a71.d = 2;
        a71.a = "messages.can_revoke_before_delivered_with_rcs";
        a71.c = new wsy();
        a71.a();
        agmi a72 = agmk.a();
        a72.d = 5;
        a72.a = "messages.trace_id";
        a72.c = new wsy();
        a72.a();
        agmi a73 = agmk.a();
        a73.d = 1;
        a73.a = "messages.outgoing_delivery_report_status";
        a73.c = new wsy();
        a73.a();
        agmi a74 = agmk.a();
        a74.d = 1;
        a74.a = "messages.outgoing_read_report_status";
        a74.c = new wsy();
        a74.a();
        agmi a75 = agmk.a();
        a75.d = 1;
        a75.a = "messages.xms_transport";
        a75.c = new wsy();
        a75.a();
        agmi a76 = agmk.a();
        a76.d = 1;
        a76.a = "messages.message_original_protocol";
        a76.c = new wsy();
        a76.a();
        agmi a77 = agmk.a();
        a77.d = 4;
        a77.j(true);
        a77.c(true);
        a77.a = "messages.satellite_datagram_id";
        a77.e(true);
        a77.c = new wsy();
        a77.a();
        agmi a78 = agmk.a();
        a78.d = 1;
        a78.a = "messages.encryption_protocol";
        a78.c = new wsy();
        a78.a();
        agmi a79 = agmk.a();
        a79.d = 4;
        a79.j(true);
        a79.c(true);
        a79.a = "messages.message_persistence_id";
        a79.e(true);
        a79.c = new wsy();
        a79.a();
    }

    public iew(ykw ykwVar) {
        ykwVar.getClass();
        this.a = ykwVar;
    }
}
