package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class iue {
    public static final String[] a = {"messages._id", "message_reactions._id"};

    static {
        new alok().b();
        new alok().b();
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.j(true);
        a2.f(true);
        a2.c(true);
        a2.a = "messages._id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.conversation_id";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.c(true);
        a4.d(true);
        a4.a = "messages.sender_id";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.sender_send_destination";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.msisdn_receiving_rcs_message";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "messages.receiving_network_country";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.c(true);
        a8.a = "messages.sent_timestamp";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "messages.queue_insert_timestamp";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.c(true);
        a10.a = "messages.received_timestamp";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "messages.message_protocol";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.c(true);
        a12.a = "messages.message_status";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "messages.message_report_status";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.seen";
        a14.e(true);
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.c(true);
        a15.a = "messages.read";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.c(true);
        a16.a = "messages.sms_message_uri";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_priority";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "messages.sms_message_size";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_subject";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_transaction_id";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "messages.mms_content_location";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "messages.mms_expiry";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 1;
        a23.c(true);
        a23.a = "messages.rcs_expiry";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 4;
        a24.a = "messages.mms_retrieve_text";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "messages.raw_status";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.c(true);
        a26.d(true);
        a26.a = "messages.self_id";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.a = "messages.my_identity";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.c(true);
        a28.d(true);
        a28.b = new ijk(4);
        a28.a = "messages.my_identity_foreign_key";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "messages.retry_start_timestamp";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.c(true);
        a30.a = "messages.cloud_sync_id";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 7;
        a31.c(true);
        a31.a = "messages.rcs_message_id";
        a31.e(true);
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 4;
        a32.c(true);
        a32.a = "messages.rcs_message_id_with_text_type";
        a32.e(true);
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "messages.etouffee_status";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "messages.verification_status";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "messages.rcs_ui_status";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.c(true);
        a36.a = "messages.is_hidden";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 7;
        a37.a = "messages.rcs_remote_instance";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "messages.rcs_file_transfer_session_id";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.a = "messages.sms_error_code";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 4;
        a40.a = "messages.sms_error_desc_map_name";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.a = "messages.correlation_id";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 4;
        a42.j(true);
        a42.c(true);
        a42.a = "messages.cms_id";
        a42.e(true);
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 2;
        a43.a = "messages.cms_last_mod_seq";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 4;
        a44.c(true);
        a44.a = "messages.web_id";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "messages.usage_stats_logging_id";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 1;
        a46.a = "messages.send_counter";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.c(true);
        a47.a = "messages.original_rcs_message_id";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 4;
        a48.a = "messages.custom_delivery_receipt_mime_type";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 5;
        a49.a = "messages.custom_delivery_receipt_content";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "messages.report_attempt_acounter";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 5;
        a51.a = "messages.custom_headers";
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 4;
        a52.j(true);
        a52.c(true);
        a52.a = "messages.cms_correlation_id";
        a52.e(true);
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 1;
        a53.c(true);
        a53.d(true);
        a53.b = new ijk(5);
        a53.a = "messages.group_private_participant";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.c(true);
        a54.d(true);
        a54.b = new ijk(6);
        a54.a = "messages.original_message_id";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 1;
        a55.a = "messages.awaiting_reverse_sync";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 4;
        a56.a = "messages.old_sms_message_uri";
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 4;
        a57.j(true);
        a57.c(true);
        a57.a = "messages.draft_id";
        a57.e(true);
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.result_code";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.cms_life_cycle";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 1;
        a60.a = "messages.fallback_reason";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 1;
        a61.a = "messages.auto_retry_counter";
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 2;
        a62.a = "messages.can_revoke_before_delivered_with_rcs";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 5;
        a63.a = "messages.trace_id";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.outgoing_delivery_report_status";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 1;
        a65.a = "messages.outgoing_read_report_status";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 1;
        a66.a = "messages.xms_transport";
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 1;
        a67.a = "messages.message_original_protocol";
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 4;
        a68.j(true);
        a68.c(true);
        a68.a = "messages.satellite_datagram_id";
        a68.e(true);
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 1;
        a69.a = "messages.encryption_protocol";
        a69.c = new wsy();
        a69.a();
        agmi a70 = agmk.a();
        a70.d = 4;
        a70.j(true);
        a70.c(true);
        a70.a = "messages.message_persistence_id";
        a70.e(true);
        a70.c = new wsy();
        a70.a();
        agmi a71 = agmk.a();
        a71.d = 2;
        a71.j(true);
        a71.f(true);
        a71.c(true);
        a71.a = "message_reactions._id";
        a71.c = new wsy();
        a71.a();
        agmi a72 = agmk.a();
        a72.d = 2;
        a72.j(true);
        a72.c(true);
        a72.d(true);
        a72.b = new ijk(7);
        a72.a = "message_reactions.message_id";
        a72.c = new wsy();
        a72.a();
        agmi a73 = agmk.a();
        a73.d = 5;
        a73.a = "message_reactions.reactions_data";
        a73.c = new wsy();
        a73.a();
        agmi a74 = agmk.a();
        a74.d = 2;
        a74.c(true);
        a74.d(true);
        a74.b = new ijk(8);
        a74.a = "message_reactions.reacted_message_id";
        a74.c = new wsy();
        a74.a();
        agmi a75 = agmk.a();
        a75.d = 2;
        a75.a = "message_reactions.reaction";
        a75.c = new wsy();
        a75.a();
        agmi a76 = agmk.a();
        a76.d = 5;
        a76.a = "message_reactions.applied_reaction";
        a76.c = new wsy();
        a76.a();
        agmi a77 = agmk.a();
        a77.d = 5;
        a77.c(true);
        a77.a = "message_reactions.animation_effect";
        a77.c = new wsy();
        a77.a();
    }
}
