package defpackage;

import com.android.vcard.VCardConstants;
import com.google.android.gms.common.internal.IGmsServiceBroker;
import com.google.android.ims.rcsservice.businessinfo.BasePaymentResult;

/* compiled from: PG */
/* loaded from: classes3.dex */
class map extends algf {
    @Override // defpackage.algf
    protected final /* bridge */ /* synthetic */ Object a(Object obj) {
        amrs amrsVar = (amrs) obj;
        switch (amrsVar.ordinal()) {
            case 15:
                return amfp.BUGLE_APP;
            case 16:
                return amfp.BUGLE_MESSAGE;
            case 17:
                return amfp.BUGLE_CONTACTS_EVENT;
            case 18:
                return amfp.BUGLE_SUPER_SORT_EVENT;
            case 19:
                return amfp.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 20:
                return amfp.REACTIONS_PROMO_EVENT;
            case 21:
                return amfp.BUGLE_SMART_COMPOSE;
            case 22:
                return amfp.EXTERNAL_API_SERVICE_CALL_START;
            case 23:
                return amfp.EXTERNAL_API_SERVICE_CALL_END;
            case 24:
                return amfp.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 25:
                return amfp.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 26:
                return amfp.BUGLE_CONVERSATION;
            case 27:
                return amfp.BUGLE_PERFORMANCE;
            case 28:
                return amfp.BUGLE_SEARCH;
            case ahby.ERROR_VENDOR_IMS_NOT_FOUND /* 29 */:
                return amfp.BUGLE_SETTING;
            case 30:
                return amfp.BUGLE_USER_AND_DEVICE_INFO;
            case 31:
                return amfp.BUGLE_TRANSCODING;
            case 32:
                return amfp.BUGLE_RCS_PROVISIONING;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_CLOUD_SAVE_SERVICE /* 33 */:
                return amfp.BUGLE_P2P_SUGGESTION;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_UDC_SERVICE /* 34 */:
                return amfp.BUGLE_APP_CONFIGURATION;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_SEARCH_CORPORA_SERVICE /* 35 */:
                return amfp.BUGLE_RBM_BUSINESS_INFO;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_DEVICE_MANAGER_SERVICE /* 36 */:
                return amfp.BUGLE_ANNOTATION;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_PSEUDONYMOUS_ID_SERVICE /* 37 */:
                return amfp.DITTO_GRPC_MESSAGE;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_REMINDERS_SERVICE /* 38 */:
                return amfp.BUGLE_TELEPHONY_EVENT;
            case 39:
                return amfp.BUGLE_GIF_CHOOSER;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_COMMON_SERVICE /* 40 */:
                return amfp.BUGLE_GROUP;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_CLEARCUT_LOGGER_SERVICE /* 41 */:
                return amfp.BUGLE_ADD_CONTACT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_WALLET_SERVICE_WITH_PACKAGE /* 42 */:
                return amfp.DITTO_IMAGE;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_USAGE_REPORTING_SERVICE /* 43 */:
                return amfp.BUGLE_CONTACT_BANNER;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_DEVICE_CONNECTION_SERVICE /* 44 */:
                return amfp.BUGLE_REPORT_SPAM;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_KIDS_SERVICE /* 45 */:
                return amfp.BUGLE_COMPOSE;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_SERVICE /* 46 */:
                return amfp.BUGLE_FILE_PREVIEW_CLICK;
            case IGmsServiceBroker.Stub.TRANSACTION_VALIDATE_ACCOUNT /* 47 */:
                return amfp.BUGLE_INDEXING;
            case 48:
                return amfp.BUGLE_PARTICIPANTS_TABLE;
            case 49:
                return amfp.BUGLE_SPAM_DETECTION;
            case 50:
                return amfp.BUGLE_EDIT_CONTACT;
            case 51:
                return amfp.BUGLE_BLOCK_FILE_ATTACH;
            case 52:
                return amfp.BUGLE_ASSISTANT;
            case 53:
                return amfp.BUGLE_CONSENT;
            case 54:
                return amfp.BUGLE_ICING_SEARCH;
            case 55:
                return amfp.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case 56:
                return amfp.BUGLE_FEDERATED_LEARNING;
            case 57:
                return amfp.BUGLE_MDD_LIB;
            case 58:
                return amfp.BUGLE_VERIFIED_SMS;
            case 59:
                return amfp.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case 60:
                return amfp.BUGLE_SHAKE_TO_REPORT;
            case 61:
                return amfp.BUGLE_SCYTALE_EVENT;
            case 62:
                return amfp.BUGLE_SELECTED_MESSAGES_ACTION;
            case 63:
                return amfp.BUGLE_REMINDER;
            case 64:
                return amfp.DITTO_SESSION_INFO;
            case 65:
                return amfp.DITTO_QR_CODE_PAIRING_EVENT;
            case 66:
                return amfp.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 67:
                return amfp.BUGLE_E2EE_STATE_TRANSITION;
            case 68:
                return amfp.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 69:
                return amfp.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 70:
                return amfp.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 71:
                return amfp.BUGLE_CONTACT_PICKER;
            case 72:
                return amfp.BUGLE_MEDIA_VIEWER;
            case 73:
                return amfp.BUGLE_VIDEO_CALL_EVENT;
            case 74:
                return amfp.BUGLE_NOTIFICATION;
            case 75:
                return amfp.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 76:
                return amfp.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 77:
                return amfp.BUGLE_WELCOME_EVENT;
            case 78:
                return amfp.DITTO_BINDING_STATUS;
            case 79:
                return amfp.ICING_INDEX_UPDATE_EVENT;
            case 80:
                return amfp.TELEPHONY_DATABASE_EVENT;
            case 81:
                return amfp.TELEPHONY_DATABASE_ACTION_EVENT;
            case 82:
                return amfp.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 83:
                return amfp.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 84:
                return amfp.BUGLE_REPORT_ISSUE_EVENT;
            case 85:
                return amfp.SPAM_FOLDER_EVENT;
            case 86:
                return amfp.AVAILABILITY_LOG;
            case 87:
                return amfp.SEARCH_QUERY;
            case 88:
                return amfp.HOME_SCREEN;
            case 89:
                return amfp.BUGLE_MULTI_DEVICE_EVENT;
            case 90:
                return amfp.ICING_INDEX_REBUILD;
            case 91:
                return amfp.RCS_EVENT;
            case 92:
                return amfp.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 93:
                return amfp.MMS_METADATA_EXPERIMENT;
            case 94:
                return amfp.HADES_SDK_EVENT;
            case 95:
                return amfp.CUSTODIAN_REPORT;
            case 96:
                return amfp.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 97:
                return amfp.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 98:
                return amfp.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 99:
                return amfp.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return amfp.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case 101:
                return amfp.DATA_DONATION_EVENT;
            case 102:
                return amfp.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 103:
                return amfp.SCHEDULED_SEND_EVENT;
            case 104:
                return amfp.JIBE_SERVICE_CONNECTION;
            case 105:
                return amfp.DATABASE_UPGRADE;
            case 106:
                return amfp.FORWARD_TELEPHONY_SYNC;
            case 107:
                return amfp.RBM_EVENT;
            case 108:
                return amfp.TOGGLE_CHAT_FEATURES_EVENT;
            case 109:
                return amfp.SYNC_TELEPHONY_THREADS;
            case 110:
                return amfp.FUZZY_MATCH_LENGTH;
            case 111:
                return amfp.BUGLE_TABLET_MODE_SWITCH;
            case 112:
                return amfp.RCS_PROVISIONING;
            case 113:
                return amfp.BUGLE_CONVERSATION_MATCHING;
            case 114:
                return amfp.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 115:
                return amfp.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 116:
                return amfp.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 117:
                return amfp.WEAR_FAILURE_EVENT;
            case 118:
                return amfp.BUGLE_STAR_EVENT;
            case 119:
                return amfp.BUBBLE_SETTING_EVENT;
            case 120:
                return amfp.XSL_REQUEST_EVENT;
            case 121:
                return amfp.PIN_TO_TOP_EVENT;
            case 122:
                return amfp.TACHYGRAM_EVENT;
            case 123:
                return amfp.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 124:
                return amfp.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 125:
                return amfp.BUGLE_MESSAGE_CLASSIFICATION;
            case 126:
                return amfp.BANNER_EVENT;
            case 127:
                return amfp.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 128:
                return amfp.RCS_CHAT_SESSION_SERVICE;
            case 129:
                return amfp.SPAM_ABUSE_EVENT;
            case 130:
                return amfp.BUGLE_CONVERSATION_CLASSIFICATION;
            case 131:
                return amfp.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 132:
                return amfp.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 133:
                return amfp.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 134:
                return amfp.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 135:
                return amfp.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 136:
                return amfp.RCS_CONTACTS_CALLER_EVENT;
            case 137:
                return amfp.NOTIFICATION_METRICS_EVENT;
            case 138:
                return amfp.BUGLE_GAIA_INTEGRATION_EVENT;
            case 139:
                return amfp.WEAR_USER_AND_DEVICE_INFO;
            case 140:
                return amfp.LIGHTER_EVENT;
            case 141:
                return amfp.BUGLE_YOUTUBE_EVENT;
            case 142:
                return amfp.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 143:
                return amfp.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 144:
                return amfp.WELCOME_FLOW_UI_EVENT;
            case 145:
                return amfp.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 146:
                return amfp.BUGLE_CAPABILITIES_EVENT;
            case 147:
                return amfp.WELCOME_FLOW_PAGE_EVENT;
            case 148:
                return amfp.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 149:
                return amfp.WELCOME_FLOW_LAUNCH_EVENT;
            case 150:
                return amfp.VMT_SESSION_EVENT;
            case 151:
                return amfp.BUGLE_SMS_CAPABILITY_EVENT;
            case 152:
                return amfp.BUGLE_APP_CONTROL_EVENT;
            case 153:
                return amfp.CONVERSATION_E2EE_STATUS_UPDATE;
            case 154:
                return amfp.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 155:
                return amfp.PROFILE_EVENT;
            case 156:
                return amfp.IN_APP_UPDATE_EVENT;
            case 157:
                return amfp.HOME_SCREEN_METRICS_EVENT;
            case 158:
                return amfp.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 159:
                return amfp.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 160:
                return amfp.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 161:
                return amfp.CONVERSATION_SCREEN_METRIC_EVENT;
            case 162:
                return amfp.DATABASE_OPERATION;
            case 163:
                return amfp.THREAD_UTILIZATION;
            case 164:
                return amfp.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 165:
                return amfp.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 166:
                return amfp.MODIFIED_BY_EVENT;
            case 167:
                return amfp.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 168:
                return amfp.MAGIC_COMPOSE_FEEDBACK;
            case 169:
                return amfp.MAGIC_COMPOSE_CONSENT;
            case 170:
                return amfp.SIM_STATE_TRACKER_EVENT;
            case 171:
                return amfp.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 172:
                return amfp.BUGLE_SYSTEM_BACKUP_EVENT;
            case 173:
                return amfp.MAGIC_COMPOSE_ERROR;
            case 174:
                return amfp.MAGIC_COMPOSE_EVENT;
            case 175:
                return amfp.MAGIC_COMPOSE_DISPLAY;
            case 176:
                return amfp.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 177:
                return amfp.HOME_SCREEN_FIRST_VISIT;
            case 178:
                return amfp.DANGLING_PARTS_EVENT;
            case 179:
                return amfp.MAGIC_COMPOSE_ICON_EVENT;
            case 180:
                return amfp.MAGIC_COMPOSE_SETTING;
            case 181:
                return amfp.SMS_SUBJECT_REPORT_EVENT;
            case 182:
                return amfp.MULTI_SHARE_EVENT;
            case 183:
                return amfp.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 184:
                return amfp.TOGGLE_RCS_CHATS_EVENT;
            case 185:
                return amfp.EMOTIFY_CREATE_EVENT;
            case 186:
                return amfp.EMOTIFY_IMPRESSION_EVENT;
            case 187:
                return amfp.EMOTIFY_MESSAGE_SEND_EVENT;
            case 188:
                return amfp.EMOTIFY_DELETE_EVENT;
            case 189:
                return amfp.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 190:
                return amfp.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 191:
                return amfp.MEET_CALLING_EVENT;
            case 192:
                return amfp.RCS_PROVISIONING_MANAGER_EVENT;
            case 193:
                return amfp.VOICE_MOOD_EVENT;
            case 194:
                return amfp.BARD_EVENT;
            case 195:
                return amfp.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 196:
                return amfp.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 197:
                return amfp.REVOKE_CONSENT_EVENT;
            case 198:
                return amfp.RCS_LOCAL_IDENTITY_EVENT;
            case 199:
                return amfp.D2D_BACKUP_AND_RESTORE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return amfp.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return amfp.GAIA_SIGN_IN_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return amfp.SELFIE_GIF_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return amfp.GAIA_SIGN_IN_STATE;
            case 204:
                return amfp.SATELLITE_EVENT;
            case 205:
                return amfp.MMS_GROUP_UPGRADE_EVENT;
            case 206:
                return amfp.RESTORE_WORKFLOW_EVENT;
            case 207:
                return amfp.BACKUP_WORKFLOW_EVENT;
            case 208:
                return amfp.VIDEO_CALLING_EVENT;
            case 209:
                return amfp.TELEPHONY_PERSISTENCE_EVENT;
            case 210:
                return amfp.MMS_GROUP_EVENT;
            case 211:
                return amfp.OPEN_PENPAL_CHAT_EVENT;
            case 212:
                return amfp.BUGLE_COMPOSE_DISABLED_EVENT;
            case 213:
                return amfp.GAIA_REPORT_EVENT;
            case 214:
                return amfp.MMS_MERGING_EVENT;
            case 215:
                return amfp.BUGLE_FILE_PROCESSING;
            case 216:
                return amfp.CONVERSATION_SCREEN_FIRST_VISIT;
            case 217:
                return amfp.TYCHO_GRPC_EVENT;
            default:
                throw new IllegalArgumentException("unknown enum value: ".concat(amrsVar.toString()));
        }
    }

    @Override // defpackage.algf
    protected final /* bridge */ /* synthetic */ Object b(Object obj) {
        switch (((amfp) obj).ordinal()) {
            case 1:
                return amrs.BUGLE_APP;
            case 2:
                return amrs.BUGLE_MESSAGE;
            case 3:
                return amrs.BUGLE_CONVERSATION;
            case 4:
                return amrs.BUGLE_PERFORMANCE;
            case 5:
                return amrs.BUGLE_SEARCH;
            case 6:
                return amrs.BUGLE_SETTING;
            case 7:
            case 10:
            case 14:
            case 27:
            case 30:
            case 31:
            case 72:
            case 86:
            case 87:
            case 98:
            default:
                return c();
            case 8:
                return amrs.BUGLE_USER_AND_DEVICE_INFO;
            case 9:
                return amrs.BUGLE_TRANSCODING;
            case 11:
                return amrs.BUGLE_RCS_PROVISIONING;
            case 12:
                return amrs.BUGLE_P2P_SUGGESTION;
            case 13:
                return amrs.BUGLE_APP_CONFIGURATION;
            case 15:
                return amrs.BUGLE_RBM_BUSINESS_INFO;
            case 16:
                return amrs.BUGLE_ANNOTATION;
            case 17:
                return amrs.DITTO_GRPC_MESSAGE;
            case 18:
                return amrs.BUGLE_TELEPHONY_EVENT;
            case 19:
                return amrs.BUGLE_GIF_CHOOSER;
            case 20:
                return amrs.BUGLE_GROUP;
            case 21:
                return amrs.BUGLE_ADD_CONTACT;
            case 22:
                return amrs.DITTO_IMAGE;
            case 23:
                return amrs.BUGLE_CONTACT_BANNER;
            case 24:
                return amrs.BUGLE_REPORT_SPAM;
            case 25:
                return amrs.BUGLE_COMPOSE;
            case 26:
                return amrs.BUGLE_FILE_PREVIEW_CLICK;
            case 28:
                return amrs.BUGLE_INDEXING;
            case ahby.ERROR_VENDOR_IMS_NOT_FOUND /* 29 */:
                return amrs.BUGLE_PARTICIPANTS_TABLE;
            case 32:
                return amrs.BUGLE_SPAM_DETECTION;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_CLOUD_SAVE_SERVICE /* 33 */:
                return amrs.BUGLE_EDIT_CONTACT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_UDC_SERVICE /* 34 */:
                return amrs.BUGLE_BLOCK_FILE_ATTACH;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_SEARCH_CORPORA_SERVICE /* 35 */:
                return amrs.BUGLE_ASSISTANT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_DEVICE_MANAGER_SERVICE /* 36 */:
                return amrs.BUGLE_CONSENT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_PSEUDONYMOUS_ID_SERVICE /* 37 */:
                return amrs.BUGLE_ICING_SEARCH;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_REMINDERS_SERVICE /* 38 */:
                return amrs.BUGLE_CONVERSATION_LATCH_STATUS_CHANGE;
            case 39:
                return amrs.BUGLE_FEDERATED_LEARNING;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_COMMON_SERVICE /* 40 */:
                return amrs.BUGLE_MDD_LIB;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_CLEARCUT_LOGGER_SERVICE /* 41 */:
                return amrs.BUGLE_VERIFIED_SMS;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_WALLET_SERVICE_WITH_PACKAGE /* 42 */:
                return amrs.BUGLE_HAPPINESS_TRACKING_SURVEY_DOWNLOAD;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_USAGE_REPORTING_SERVICE /* 43 */:
                return amrs.BUGLE_SHAKE_TO_REPORT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_DEVICE_CONNECTION_SERVICE /* 44 */:
                return amrs.BUGLE_SCYTALE_EVENT;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_KIDS_SERVICE /* 45 */:
                return amrs.BUGLE_SELECTED_MESSAGES_ACTION;
            case IGmsServiceBroker.Stub.TRANSACTION_GET_SERVICE /* 46 */:
                return amrs.BUGLE_REMINDER;
            case IGmsServiceBroker.Stub.TRANSACTION_VALIDATE_ACCOUNT /* 47 */:
                return amrs.DITTO_SESSION_INFO;
            case 48:
                return amrs.DITTO_QR_CODE_PAIRING_EVENT;
            case 49:
                return amrs.BUGLE_TACHYON_TRANSPORT_EVENT;
            case 50:
                return amrs.BUGLE_E2EE_STATE_TRANSITION;
            case 51:
                return amrs.BUGLE_E2EE_LOOKUP_REGISTERED;
            case 52:
                return amrs.BUGLE_E2EE_MESSAGE_RETRY_LIMIT_EXCEEDED;
            case 53:
                return amrs.BUGLE_E2EE_EMPTY_GENERATED_PREKEYS_BUT_PROVISIONED;
            case 54:
                return amrs.BUGLE_CONTACT_PICKER;
            case 55:
                return amrs.BUGLE_MEDIA_VIEWER;
            case 56:
                return amrs.BUGLE_VIDEO_CALL_EVENT;
            case 57:
                return amrs.BUGLE_NOTIFICATION;
            case 58:
                return amrs.BUGLE_E2EE_IDENTITY_VERIFICATION_MESSAGE_DROPPED;
            case 59:
                return amrs.BUGLE_E2EE_ATTACHMENT_FAILED_TO_DECRYPT_USING_OTMK;
            case 60:
                return amrs.BUGLE_WELCOME_EVENT;
            case 61:
                return amrs.DITTO_BINDING_STATUS;
            case 62:
                return amrs.ICING_INDEX_UPDATE_EVENT;
            case 63:
                return amrs.TELEPHONY_DATABASE_EVENT;
            case 64:
                return amrs.TELEPHONY_DATABASE_ACTION_EVENT;
            case 65:
                return amrs.BUGLE_BUSINESS_MESSAGING_EVENT;
            case 66:
                return amrs.BUGLE_ADVANCED_FEEDBACK_EVENT;
            case 67:
                return amrs.BUGLE_REPORT_ISSUE_EVENT;
            case 68:
                return amrs.SPAM_FOLDER_EVENT;
            case 69:
                return amrs.AVAILABILITY_LOG;
            case 70:
                return amrs.SEARCH_QUERY;
            case 71:
                return amrs.HOME_SCREEN;
            case 73:
                return amrs.BUGLE_MULTI_DEVICE_EVENT;
            case 74:
                return amrs.ICING_INDEX_REBUILD;
            case 75:
                return amrs.RCS_EVENT;
            case 76:
                return amrs.TELEPHONY_WIPEOUT_DETECTOR_EXECUTION_EVENT;
            case 77:
                return amrs.MMS_METADATA_EXPERIMENT;
            case 78:
                return amrs.HADES_SDK_EVENT;
            case 79:
                return amrs.CUSTODIAN_REPORT;
            case 80:
                return amrs.TELEPHONY_REVERSE_SYNC_STARTED_EVENT;
            case 81:
                return amrs.TELEPHONY_REVERSE_SYNC_RESUMED_EVENT;
            case 82:
                return amrs.TELEPHONY_REVERSE_SYNC_COMPLETED_EVENT;
            case 83:
                return amrs.TELEPHONY_REVERSE_SYNC_FAILED_EVENT;
            case 84:
                return amrs.TELEPHONY_REVERSE_SYNC_NOT_ATTEMPTED_EVENT;
            case 85:
                return amrs.DATA_DONATION_EVENT;
            case 88:
                return amrs.BUGLE_CONTACTS_EVENT;
            case 89:
                return amrs.BUGLE_SUPER_SORT_EVENT;
            case 90:
                return amrs.BUGLE_FOREGROUND_SERVICE_EVENT;
            case 91:
                return amrs.REACTIONS_PROMO_EVENT;
            case 92:
                return amrs.BUGLE_SMART_COMPOSE;
            case 93:
                return amrs.BUGLE_SMART_COMPOSE_MODEL_EVAL;
            case 94:
                return amrs.EXTERNAL_API_SERVICE_CALL_START;
            case 95:
                return amrs.EXTERNAL_API_SERVICE_CALL_END;
            case 96:
                return amrs.EXTERNAL_API_SERVICE_CALL_PENDING;
            case 97:
                return amrs.BUGLE_E2EE_FETCH_PREKEYS_EVENT;
            case 99:
                return amrs.SCHEDULED_SEND_EVENT;
            case VCardConstants.DEFAULT_PREF /* 100 */:
                return amrs.JIBE_SERVICE_CONNECTION;
            case 101:
                return amrs.DATABASE_UPGRADE;
            case 102:
                return amrs.FORWARD_TELEPHONY_SYNC;
            case 103:
                return amrs.RBM_EVENT;
            case 104:
                return amrs.TOGGLE_CHAT_FEATURES_EVENT;
            case 105:
                return amrs.SYNC_TELEPHONY_THREADS;
            case 106:
                return amrs.FUZZY_MATCH_LENGTH;
            case 107:
                return amrs.BUGLE_TABLET_MODE_SWITCH;
            case 108:
                return amrs.RCS_PROVISIONING;
            case 109:
                return amrs.BUGLE_CONVERSATION_MATCHING;
            case 110:
                return amrs.BUGLE_HATS_NEXT_CLIENT_EVENT;
            case 111:
                return amrs.BUGLE_WEAR_GMS_RPC_RELIABILITY;
            case 112:
                return amrs.BUGLE_EXTERNAL_SEARCH_MESSAGE_EVENT;
            case 113:
                return amrs.WEAR_FAILURE_EVENT;
            case 114:
                return amrs.BUGLE_STAR_EVENT;
            case 115:
                return amrs.BUBBLE_SETTING_EVENT;
            case 116:
                return amrs.XSL_REQUEST_EVENT;
            case 117:
                return amrs.PIN_TO_TOP_EVENT;
            case 118:
                return amrs.TACHYGRAM_EVENT;
            case 119:
                return amrs.BUGLE_E2EE_IDENTITY_VERIFICATION_EVENT;
            case 120:
                return amrs.COMPOSE_BOX_HINT_TEXT_FLICKER_EVENT;
            case 121:
                return amrs.BUGLE_MESSAGE_CLASSIFICATION;
            case 122:
                return amrs.BANNER_EVENT;
            case 123:
                return amrs.BUGLE_INTERNET_CONNECTIVITY_CHECK_EVENT;
            case 124:
                return amrs.RCS_CHAT_SESSION_SERVICE;
            case 125:
                return amrs.SPAM_ABUSE_EVENT;
            case 126:
                return amrs.BUGLE_CONVERSATION_CLASSIFICATION;
            case 127:
                return amrs.BUGLE_BIRTHDAY_CONVERSATION_INFO;
            case 128:
                return amrs.BUGLE_BIRTHDAY_SUGGESTION_INFO;
            case 129:
                return amrs.GOOGLE_PHOTOS_CREATE_SHARE_LINK_EVENT;
            case 130:
                return amrs.GOOGLE_PHOTOS_ONBOARDING_EVENT;
            case 131:
                return amrs.GOOGLE_PHOTOS_OPTION_TRAY_EVENT;
            case 132:
                return amrs.RCS_CONTACTS_CALLER_EVENT;
            case 133:
                return amrs.NOTIFICATION_METRICS_EVENT;
            case 134:
                return amrs.BUGLE_GAIA_INTEGRATION_EVENT;
            case 135:
                return amrs.WEAR_USER_AND_DEVICE_INFO;
            case 136:
                return amrs.LIGHTER_EVENT;
            case 137:
                return amrs.BUGLE_YOUTUBE_EVENT;
            case 138:
                return amrs.BUGLE_SMARTS_SILENT_EXCEPTIONS_EVENT;
            case 139:
                return amrs.DUPLICATE_RCS_MESSAGE_ID_EVENT;
            case 140:
                return amrs.WELCOME_FLOW_UI_EVENT;
            case 141:
                return amrs.BUGLE_CONTACTS_BIRTHDAY_COVERAGE_INFO;
            case 142:
                return amrs.BUGLE_CAPABILITIES_EVENT;
            case 143:
                return amrs.WELCOME_FLOW_PAGE_EVENT;
            case 144:
                return amrs.WELCOME_FLOW_RELATED_SUPPRESSION_EVENT;
            case 145:
                return amrs.WELCOME_FLOW_LAUNCH_EVENT;
            case 146:
                return amrs.VMT_SESSION_EVENT;
            case 147:
                return amrs.BUGLE_SMS_CAPABILITY_EVENT;
            case 148:
                return amrs.BUGLE_APP_CONTROL_EVENT;
            case 149:
                return amrs.CONVERSATION_E2EE_STATUS_UPDATE;
            case 150:
                return amrs.PHENOTYPE_FIRST_REREGISTRATION_EVENT;
            case 151:
                return amrs.PROFILE_EVENT;
            case 152:
                return amrs.IN_APP_UPDATE_EVENT;
            case 153:
                return amrs.HOME_SCREEN_METRICS_EVENT;
            case 154:
                return amrs.BUGLE_MOBILE_CONFIGURATION_CLIENT_EVENT;
            case 155:
                return amrs.MMS_GROUP_UPGRADE_ELIGIBILITY_INFO;
            case 156:
                return amrs.BUGLE_WEAR_CONVERSATION_SYNC_EVENT;
            case 157:
                return amrs.CONVERSATION_SCREEN_METRIC_EVENT;
            case 158:
                return amrs.DATABASE_OPERATION;
            case 159:
                return amrs.THREAD_UTILIZATION;
            case 160:
                return amrs.BUGLE_EXPRESS_SIGN_IN_EVENT;
            case 161:
                return amrs.BUGLE_CONVERSATION_READ_STATUS_EVENT;
            case 162:
                return amrs.MODIFIED_BY_EVENT;
            case 163:
                return amrs.BUGLE_CONVERSATION_MERGING_MATCHED_CONVERSATIONS_INFO;
            case 164:
                return amrs.MAGIC_COMPOSE_FEEDBACK;
            case 165:
                return amrs.MAGIC_COMPOSE_CONSENT;
            case 166:
                return amrs.SIM_STATE_TRACKER_EVENT;
            case 167:
                return amrs.BUGLE_CARRIER_CONFIG_MISMATCH_EVENT;
            case 168:
                return amrs.BUGLE_SYSTEM_BACKUP_EVENT;
            case 169:
                return amrs.MAGIC_COMPOSE_ERROR;
            case 170:
                return amrs.MAGIC_COMPOSE_EVENT;
            case 171:
                return amrs.MAGIC_COMPOSE_DISPLAY;
            case 172:
                return amrs.BUGLE_ALARM_DELAY_METRICS_EVENT;
            case 173:
                return amrs.HOME_SCREEN_FIRST_VISIT;
            case 174:
                return amrs.DANGLING_PARTS_EVENT;
            case 175:
                return amrs.MAGIC_COMPOSE_ICON_EVENT;
            case 176:
                return amrs.MAGIC_COMPOSE_SETTING;
            case 177:
                return amrs.SMS_SUBJECT_REPORT_EVENT;
            case 178:
                return amrs.MULTI_SHARE_EVENT;
            case 179:
                return amrs.BUGLE_CMS_DATA_PROVIDER_EVENT;
            case 180:
                return amrs.TOGGLE_RCS_CHATS_EVENT;
            case 181:
                return amrs.EMOTIFY_CREATE_EVENT;
            case 182:
                return amrs.EMOTIFY_IMPRESSION_EVENT;
            case 183:
                return amrs.EMOTIFY_MESSAGE_SEND_EVENT;
            case 184:
                return amrs.EMOTIFY_DELETE_EVENT;
            case 185:
                return amrs.BUGLE_CARRIER_CONFIG_LOAD_LATENCY_EVENT;
            case 186:
                return amrs.BUGLE_RCS_GROUP_SELF_PARTICIPANT_INCLUSION;
            case 187:
                return amrs.MEET_CALLING_EVENT;
            case 188:
                return amrs.RCS_PROVISIONING_MANAGER_EVENT;
            case 189:
                return amrs.VOICE_MOOD_EVENT;
            case 190:
                return amrs.BARD_EVENT;
            case 191:
                return amrs.MAGIC_COMPOSE_INPUT_TOKEN_METRIC;
            case 192:
                return amrs.DOUBLE_TAP_REACT_PROMOTION_EVENT;
            case 193:
                return amrs.REVOKE_CONSENT_EVENT;
            case 194:
                return amrs.RCS_LOCAL_IDENTITY_EVENT;
            case 195:
                return amrs.D2D_BACKUP_AND_RESTORE_EVENT;
            case 196:
                return amrs.PARTICIPANTS_TABLE_VALIDATION_EVENT;
            case 197:
                return amrs.GAIA_SIGN_IN_EVENT;
            case 198:
                return amrs.SELFIE_GIF_EVENT;
            case 199:
                return amrs.GAIA_SIGN_IN_STATE;
            case BasePaymentResult.ERROR_REQUEST_FAILED /* 200 */:
                return amrs.SATELLITE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_TIMEOUT /* 201 */:
                return amrs.MMS_GROUP_UPGRADE_EVENT;
            case BasePaymentResult.ERROR_REQUEST_CONNECTION_FAILED /* 202 */:
                return amrs.RESTORE_WORKFLOW_EVENT;
            case BasePaymentResult.ERROR_BOT_DOMAIN_NOT_WHITELISTED /* 203 */:
                return amrs.BACKUP_WORKFLOW_EVENT;
            case 204:
                return amrs.VIDEO_CALLING_EVENT;
            case 205:
                return amrs.TELEPHONY_PERSISTENCE_EVENT;
            case 206:
                return amrs.MMS_GROUP_EVENT;
            case 207:
                return amrs.OPEN_PENPAL_CHAT_EVENT;
            case 208:
                return amrs.BUGLE_COMPOSE_DISABLED_EVENT;
            case 209:
                return amrs.GAIA_REPORT_EVENT;
            case 210:
                return amrs.MMS_MERGING_EVENT;
            case 211:
                return amrs.BUGLE_FILE_PROCESSING;
            case 212:
                return amrs.CONVERSATION_SCREEN_FIRST_VISIT;
            case 213:
                return amrs.TYCHO_GRPC_EVENT;
        }
    }

    public amrs c() {
        throw null;
    }
}
