package defpackage;

import com.google.android.apps.messaging.shared.api.messaging.conversation.bugle.BugleConversationId;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class muj implements mto {
    private final armf A;
    private final armf B;
    private final armf C;
    private final armf D;
    private final armf E;
    private final armf F;
    private final armf G;
    private final armf H;
    private final armf I;
    private final armf J;
    private final armf K;
    private final armf L;
    private final armf a;
    private final armf b;
    private final armf c;
    private final armf d;
    private final armf e;
    private final armf f;
    private final armf g;
    private final armf h;
    private final armf i;
    private final armf j;
    private final armf k;
    private final armf l;
    private final armf m;
    private final armf n;
    private final armf o;
    private final armf p;
    private final armf q;
    private final armf r;
    private final armf s;
    private final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;
    private final armf y;
    private final armf z;

    public muj(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, armf armfVar28, armf armfVar29, armf armfVar30, armf armfVar31, armf armfVar32, armf armfVar33, armf armfVar34, armf armfVar35, armf armfVar36, armf armfVar37, armf armfVar38, armf armfVar39, armf armfVar40, armf armfVar41, armf armfVar42, armf armfVar43, armf armfVar44) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        armfVar10.getClass();
        this.i = armfVar10;
        armfVar11.getClass();
        this.j = armfVar11;
        armfVar12.getClass();
        this.k = armfVar12;
        armfVar13.getClass();
        this.l = armfVar13;
        armfVar14.getClass();
        this.m = armfVar14;
        armfVar15.getClass();
        this.n = armfVar15;
        armfVar16.getClass();
        this.o = armfVar16;
        armfVar17.getClass();
        this.p = armfVar17;
        armfVar18.getClass();
        this.q = armfVar18;
        armfVar19.getClass();
        this.r = armfVar19;
        armfVar20.getClass();
        this.s = armfVar20;
        armfVar21.getClass();
        this.t = armfVar21;
        armfVar22.getClass();
        this.u = armfVar22;
        armfVar23.getClass();
        this.v = armfVar23;
        armfVar24.getClass();
        armfVar25.getClass();
        this.w = armfVar25;
        armfVar26.getClass();
        this.x = armfVar26;
        armfVar27.getClass();
        this.y = armfVar27;
        armfVar28.getClass();
        this.z = armfVar28;
        armfVar29.getClass();
        this.A = armfVar29;
        armfVar30.getClass();
        this.B = armfVar30;
        armfVar31.getClass();
        this.C = armfVar31;
        armfVar32.getClass();
        this.D = armfVar32;
        armfVar33.getClass();
        armfVar34.getClass();
        armfVar35.getClass();
        this.E = armfVar35;
        armfVar36.getClass();
        this.F = armfVar36;
        armfVar37.getClass();
        this.G = armfVar37;
        armfVar38.getClass();
        this.H = armfVar38;
        armfVar39.getClass();
        this.I = armfVar39;
        armfVar40.getClass();
        this.J = armfVar40;
        armfVar41.getClass();
        this.K = armfVar41;
        armfVar42.getClass();
        this.L = armfVar42;
        armfVar43.getClass();
        armfVar44.getClass();
    }

    @Override // defpackage.mto
    /* renamed from: b, reason: merged with bridge method [inline-methods] */
    public final mui a(BugleConversationId bugleConversationId, ncq ncqVar, ncq ncqVar2, ncq ncqVar3, mtc mtcVar, boolean z, boolean z2) {
        wfh wfhVar = (wfh) this.a.b();
        wfhVar.getClass();
        anen anenVar = (anen) this.b.b();
        anenVar.getClass();
        anen anenVar2 = (anen) this.c.b();
        anenVar2.getClass();
        anen anenVar3 = (anen) this.d.b();
        anenVar3.getClass();
        rae raeVar = (rae) this.e.b();
        raeVar.getClass();
        kjp kjpVar = (kjp) this.f.b();
        kjpVar.getClass();
        muw muwVar = (muw) this.g.b();
        muwVar.getClass();
        kor korVar = (kor) this.h.b();
        korVar.getClass();
        rtb rtbVar = (rtb) this.j.b();
        rtbVar.getClass();
        lxe lxeVar = (lxe) this.k.b();
        lxeVar.getClass();
        lxe lxeVar2 = (lxe) this.l.b();
        lxeVar2.getClass();
        kor korVar2 = (kor) this.p.b();
        korVar2.getClass();
        kor korVar3 = (kor) this.q.b();
        korVar3.getClass();
        lru lruVar = (lru) this.z.b();
        lruVar.getClass();
        kjp kjpVar2 = (kjp) this.A.b();
        kjpVar2.getClass();
        lrf lrfVar = (lrf) this.C.b();
        lrfVar.getClass();
        Optional optional = (Optional) ((apxx) this.D).a;
        ncqVar.getClass();
        ncqVar2.getClass();
        ncqVar3.getClass();
        armf armfVar = this.r;
        armf armfVar2 = this.s;
        armf armfVar3 = this.t;
        armf armfVar4 = this.u;
        armf armfVar5 = this.v;
        armf armfVar6 = this.m;
        armf armfVar7 = this.w;
        armf armfVar8 = this.n;
        armf armfVar9 = this.x;
        armf armfVar10 = this.E;
        armf armfVar11 = this.F;
        armf armfVar12 = this.G;
        armf armfVar13 = this.H;
        armf armfVar14 = this.I;
        armf armfVar15 = this.J;
        armf armfVar16 = this.K;
        armf armfVar17 = this.L;
        return new mui(wfhVar, anenVar, anenVar2, anenVar3, raeVar, kjpVar, muwVar, korVar, this.i, rtbVar, lxeVar, lxeVar2, armfVar6, armfVar8, this.o, korVar2, korVar3, armfVar, armfVar2, armfVar3, armfVar4, armfVar5, armfVar7, armfVar9, this.y, lruVar, kjpVar2, this.B, lrfVar, optional, armfVar10, armfVar11, armfVar12, armfVar13, armfVar14, armfVar15, armfVar16, armfVar17, bugleConversationId, ncqVar, ncqVar2, ncqVar3, mtcVar, z, z2);
    }
}
