package defpackage;

import android.content.Context;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rec {
    private final armf A;
    private final armf B;
    private final armf C;
    private final armf D;
    private final armf E;
    private final armf F;
    private final armf G;
    private final armf H;
    private final armf I;
    private final armf J;
    private final armf K;
    private final armf L;
    private final armf M;
    private final armf N;
    private final armf O;
    private final armf P;
    private final armf Q;
    private final armf R;
    private final armf S;
    private final armf T;
    private final armf U;
    private final armf V;
    private final armf W;
    private final armf X;
    private final armf Y;
    private final armf Z;
    private final armf a;
    private final armf aa;
    private final armf ab;
    private final armf ac;
    private final armf ad;
    private final armf ae;
    private final armf af;
    private final armf ag;
    private final armf ah;
    private final armf b;
    private final armf c;
    private final armf d;
    private final armf e;
    private final armf f;
    private final armf g;
    private final armf h;
    private final armf i;
    private final armf j;
    private final armf k;
    private final armf l;
    private final armf m;
    private final armf n;
    private final armf o;
    private final armf p;
    private final armf q;
    private final armf r;
    private final armf s;
    private final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;
    private final armf y;
    private final armf z;

    public rec(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, armf armfVar28, armf armfVar29, armf armfVar30, armf armfVar31, armf armfVar32, armf armfVar33, armf armfVar34, armf armfVar35, armf armfVar36, armf armfVar37, armf armfVar38, armf armfVar39, armf armfVar40, armf armfVar41, armf armfVar42, armf armfVar43, armf armfVar44, armf armfVar45, armf armfVar46, armf armfVar47, armf armfVar48, armf armfVar49, armf armfVar50, armf armfVar51, armf armfVar52, armf armfVar53, armf armfVar54, armf armfVar55, armf armfVar56, armf armfVar57, armf armfVar58, armf armfVar59, armf armfVar60, armf armfVar61) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.j = armfVar10;
        armfVar11.getClass();
        this.k = armfVar11;
        armfVar12.getClass();
        this.l = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.n = armfVar14;
        armfVar15.getClass();
        this.o = armfVar15;
        armfVar16.getClass();
        armfVar17.getClass();
        this.p = armfVar17;
        armfVar18.getClass();
        this.q = armfVar18;
        armfVar19.getClass();
        this.r = armfVar19;
        armfVar20.getClass();
        this.s = armfVar20;
        armfVar21.getClass();
        this.t = armfVar21;
        armfVar22.getClass();
        this.u = armfVar22;
        armfVar23.getClass();
        this.v = armfVar23;
        armfVar24.getClass();
        this.w = armfVar24;
        armfVar25.getClass();
        this.x = armfVar25;
        armfVar26.getClass();
        this.y = armfVar26;
        armfVar27.getClass();
        this.z = armfVar27;
        armfVar28.getClass();
        this.A = armfVar28;
        armfVar29.getClass();
        this.B = armfVar29;
        armfVar30.getClass();
        this.C = armfVar30;
        armfVar31.getClass();
        this.D = armfVar31;
        armfVar32.getClass();
        this.E = armfVar32;
        armfVar33.getClass();
        this.F = armfVar33;
        armfVar34.getClass();
        this.G = armfVar34;
        armfVar35.getClass();
        this.H = armfVar35;
        armfVar36.getClass();
        this.I = armfVar36;
        armfVar37.getClass();
        this.J = armfVar37;
        armfVar38.getClass();
        this.K = armfVar38;
        armfVar39.getClass();
        this.L = armfVar39;
        armfVar40.getClass();
        this.M = armfVar40;
        armfVar41.getClass();
        this.N = armfVar41;
        armfVar42.getClass();
        this.O = armfVar42;
        armfVar43.getClass();
        this.P = armfVar43;
        armfVar44.getClass();
        this.Q = armfVar44;
        armfVar45.getClass();
        this.R = armfVar45;
        armfVar46.getClass();
        this.S = armfVar46;
        armfVar47.getClass();
        this.T = armfVar47;
        armfVar48.getClass();
        this.U = armfVar48;
        armfVar49.getClass();
        this.V = armfVar49;
        armfVar50.getClass();
        this.W = armfVar50;
        armfVar51.getClass();
        this.X = armfVar51;
        armfVar52.getClass();
        this.Y = armfVar52;
        armfVar53.getClass();
        this.Z = armfVar53;
        armfVar54.getClass();
        this.aa = armfVar54;
        armfVar55.getClass();
        this.ab = armfVar55;
        armfVar56.getClass();
        this.ac = armfVar56;
        armfVar57.getClass();
        this.ad = armfVar57;
        armfVar58.getClass();
        this.ae = armfVar58;
        armfVar59.getClass();
        this.af = armfVar59;
        armfVar60.getClass();
        this.ag = armfVar60;
        armfVar61.getClass();
        this.ah = armfVar61;
    }

    public final reb a(Action action) {
        Context context = (Context) this.a.b();
        context.getClass();
        ryg rygVar = (ryg) this.h.b();
        rygVar.getClass();
        xnv xnvVar = (xnv) this.i.b();
        xnvVar.getClass();
        wzs wzsVar = (wzs) this.j.b();
        wzsVar.getClass();
        yjy yjyVar = (yjy) this.k.b();
        yjyVar.getClass();
        xbi xbiVar = (xbi) this.l.b();
        xbiVar.getClass();
        ((xca) this.m.b()).getClass();
        wys wysVar = (wys) this.p.b();
        wysVar.getClass();
        xbf xbfVar = (xbf) this.q.b();
        xbfVar.getClass();
        zai zaiVar = (zai) this.s.b();
        zaiVar.getClass();
        wyp wypVar = (wyp) this.t.b();
        wypVar.getClass();
        qyn qynVar = (qyn) this.u.b();
        qynVar.getClass();
        rjj rjjVar = (rjj) this.v.b();
        rjjVar.getClass();
        ((rji) this.w.b()).getClass();
        vjs vjsVar = (vjs) this.x.b();
        vjsVar.getClass();
        ((vjs) this.y.b()).getClass();
        uhj uhjVar = (uhj) this.z.b();
        uhjVar.getClass();
        rys rysVar = (rys) this.A.b();
        rysVar.getClass();
        vak vakVar = (vak) this.B.b();
        vakVar.getClass();
        uhg uhgVar = (uhg) this.C.b();
        uhgVar.getClass();
        uie uieVar = (uie) this.D.b();
        uieVar.getClass();
        tzn tznVar = (tzn) this.E.b();
        tznVar.getClass();
        armf armfVar = this.G;
        armf armfVar2 = this.F;
        armf armfVar3 = this.b;
        armf armfVar4 = this.c;
        armf armfVar5 = this.d;
        armf armfVar6 = this.e;
        armf armfVar7 = this.f;
        armf armfVar8 = this.g;
        armf armfVar9 = this.n;
        armf armfVar10 = this.o;
        armf armfVar11 = this.r;
        armf armfVar12 = this.H;
        armf armfVar13 = this.I;
        armf armfVar14 = this.J;
        armf armfVar15 = this.K;
        armf armfVar16 = this.L;
        armf armfVar17 = this.M;
        armf armfVar18 = this.N;
        armf armfVar19 = this.O;
        armf armfVar20 = this.P;
        armf armfVar21 = this.Q;
        armf armfVar22 = this.R;
        Optional optional = (Optional) ((apxx) armfVar).a;
        arwe arweVar = (arwe) armfVar22.b();
        arweVar.getClass();
        arpi arpiVar = (arpi) this.S.b();
        arpiVar.getClass();
        arwe arweVar2 = (arwe) this.T.b();
        arweVar2.getClass();
        arpi arpiVar2 = (arpi) this.U.b();
        arpiVar2.getClass();
        arpi arpiVar3 = (arpi) this.V.b();
        arpiVar3.getClass();
        armf armfVar23 = this.W;
        armf armfVar24 = this.X;
        armf armfVar25 = this.Y;
        wyq wyqVar = (wyq) this.Z.b();
        wyqVar.getClass();
        yck yckVar = (yck) this.aa.b();
        yckVar.getClass();
        return new reb(action, context, armfVar3, armfVar4, armfVar5, armfVar6, armfVar7, armfVar8, rygVar, xnvVar, wzsVar, yjyVar, xbiVar, armfVar9, armfVar10, wysVar, xbfVar, armfVar11, zaiVar, wypVar, qynVar, rjjVar, vjsVar, uhjVar, rysVar, vakVar, uhgVar, uieVar, tznVar, armfVar2, optional, armfVar12, armfVar13, armfVar14, armfVar15, armfVar16, armfVar17, armfVar18, armfVar19, armfVar20, armfVar21, arweVar, arpiVar, arweVar2, arpiVar2, arpiVar3, armfVar23, armfVar24, armfVar25, wyqVar, yckVar, this.ab, this.ac, this.ad, this.ae, this.af, this.ag, this.ah);
    }
}
