package defpackage;

import android.content.Context;
import android.os.Parcel;
import com.google.android.apps.messaging.shared.datamodel.action.ReceiveWapPushSiMessageAction;
import com.google.android.apps.messaging.shared.datamodel.action.ReplaceSmsMessageAction;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rfl implements rhp {
    public final armf A;
    private final /* synthetic */ int B;
    public final armf a;
    public final armf b;
    public final armf c;
    public final armf d;
    public final armf e;
    public final armf f;
    public final armf g;
    public final armf h;
    public final armf i;
    public final armf j;
    public final armf k;
    public final armf l;
    public final armf m;
    public final armf n;
    public final armf o;
    public final armf p;
    public final armf q;
    public final armf r;
    public final armf s;
    public final armf t;
    public final armf u;
    public final armf v;
    public final armf w;
    public final armf x;
    public final armf y;
    public final armf z;

    public rfl(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, int i, byte[] bArr) {
        this.B = i;
        armfVar.getClass();
        this.f = armfVar;
        armfVar2.getClass();
        this.t = armfVar2;
        armfVar3.getClass();
        this.o = armfVar3;
        armfVar4.getClass();
        this.p = armfVar4;
        armfVar5.getClass();
        this.z = armfVar5;
        armfVar6.getClass();
        this.r = armfVar6;
        armfVar7.getClass();
        this.s = armfVar7;
        armfVar8.getClass();
        this.n = armfVar8;
        armfVar9.getClass();
        this.x = armfVar9;
        armfVar10.getClass();
        this.w = armfVar10;
        armfVar11.getClass();
        this.v = armfVar11;
        armfVar12.getClass();
        this.A = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.e = armfVar14;
        armfVar15.getClass();
        this.a = armfVar15;
        armfVar16.getClass();
        this.l = armfVar16;
        armfVar17.getClass();
        this.c = armfVar17;
        armfVar18.getClass();
        this.k = armfVar18;
        armfVar19.getClass();
        this.j = armfVar19;
        armfVar20.getClass();
        this.i = armfVar20;
        armfVar21.getClass();
        this.h = armfVar21;
        armfVar22.getClass();
        this.y = armfVar22;
        armfVar23.getClass();
        this.u = armfVar23;
        armfVar24.getClass();
        this.q = armfVar24;
        armfVar25.getClass();
        this.d = armfVar25;
        armfVar26.getClass();
        this.g = armfVar26;
        armfVar27.getClass();
        this.b = armfVar27;
    }

    @Override // defpackage.rhp
    public final /* synthetic */ Action c(Parcel parcel) {
        if (this.B != 0) {
            Context context = (Context) this.f.b();
            context.getClass();
            xnv xnvVar = (xnv) this.o.b();
            xnvVar.getClass();
            wyt wytVar = (wyt) this.p.b();
            wytVar.getClass();
            ((xca) this.z.b()).getClass();
            mho mhoVar = (mho) this.r.b();
            mhoVar.getClass();
            wzs wzsVar = (wzs) this.s.b();
            wzsVar.getClass();
            ryg rygVar = (ryg) this.A.b();
            rygVar.getClass();
            qyn qynVar = (qyn) this.m.b();
            qynVar.getClass();
            rim rimVar = (rim) this.e.b();
            rimVar.getClass();
            rys rysVar = (rys) this.a.b();
            rysVar.getClass();
            rji rjiVar = (rji) this.l.b();
            rjiVar.getClass();
            tqx tqxVar = (tqx) this.c.b();
            tqxVar.getClass();
            rtb rtbVar = (rtb) this.k.b();
            rtbVar.getClass();
            agnq agnqVar = (agnq) this.j.b();
            agnqVar.getClass();
            lpg lpgVar = (lpg) this.h.b();
            lpgVar.getClass();
            parcel.getClass();
            return new ReceiveWapPushSiMessageAction(context, this.t, xnvVar, wytVar, mhoVar, wzsVar, this.n, this.x, this.w, this.v, rygVar, qynVar, rimVar, rysVar, rjiVar, tqxVar, rtbVar, agnqVar, this.i, lpgVar, this.y, this.u, this.q, this.d, this.g, this.b, parcel);
        }
        Context context2 = (Context) this.a.b();
        context2.getClass();
        zai zaiVar = (zai) this.i.b();
        zaiVar.getClass();
        mce mceVar = (mce) this.j.b();
        mceVar.getClass();
        wyt wytVar2 = (wyt) this.k.b();
        wytVar2.getClass();
        ryg rygVar2 = (ryg) this.l.b();
        rygVar2.getClass();
        mho mhoVar2 = (mho) this.m.b();
        mhoVar2.getClass();
        ((rji) this.n.b()).getClass();
        rys rysVar2 = (rys) this.o.b();
        rysVar2.getClass();
        rei reiVar = (rei) this.p.b();
        reiVar.getClass();
        tqx tqxVar2 = (tqx) this.q.b();
        tqxVar2.getClass();
        agnq agnqVar2 = (agnq) this.r.b();
        agnqVar2.getClass();
        parcel.getClass();
        return new ReplaceSmsMessageAction(context2, this.b, this.c, this.d, this.e, this.f, this.g, this.h, zaiVar, mceVar, wytVar2, rygVar2, mhoVar2, rysVar2, reiVar, tqxVar2, agnqVar2, this.s, this.t, this.u, this.v, this.w, this.x, this.y, this.z, this.A, parcel);
    }

    public rfl(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, int i) {
        this.B = i;
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.j = armfVar10;
        armfVar11.getClass();
        this.k = armfVar11;
        armfVar12.getClass();
        this.l = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.n = armfVar14;
        armfVar15.getClass();
        this.o = armfVar15;
        armfVar16.getClass();
        this.p = armfVar16;
        armfVar17.getClass();
        this.q = armfVar17;
        armfVar18.getClass();
        this.r = armfVar18;
        armfVar19.getClass();
        this.s = armfVar19;
        armfVar20.getClass();
        this.t = armfVar20;
        armfVar21.getClass();
        this.u = armfVar21;
        armfVar22.getClass();
        this.v = armfVar22;
        armfVar23.getClass();
        this.w = armfVar23;
        armfVar24.getClass();
        this.x = armfVar24;
        armfVar25.getClass();
        this.y = armfVar25;
        armfVar26.getClass();
        this.z = armfVar26;
        armfVar27.getClass();
        this.A = armfVar27;
    }
}
