package defpackage;

import android.content.Context;
import android.os.Parcel;
import com.google.android.apps.messaging.shared.datamodel.action.SendMessageAction;
import com.google.android.apps.messaging.shared.datamodel.action.common.Action;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rfy implements rhp {
    private final armf A;
    private final armf B;
    private final armf C;
    private final armf D;
    private final armf E;
    private final armf F;
    private final armf G;
    private final armf H;
    private final armf I;
    private final armf J;
    private final armf K;
    private final armf L;
    private final armf M;
    private final armf N;
    private final armf O;
    private final armf P;
    private final armf Q;
    private final armf R;
    private final armf S;
    private final armf T;
    private final armf U;
    private final armf a;
    private final armf b;
    private final armf c;
    private final armf d;
    private final armf e;
    private final armf f;
    private final armf g;
    private final armf h;
    private final armf i;
    private final armf j;
    private final armf k;
    private final armf l;
    private final armf m;
    private final armf n;
    private final armf o;
    private final armf p;
    private final armf q;
    private final armf r;
    private final armf s;
    private final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;
    private final armf y;
    private final armf z;

    public rfy(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, armf armfVar28, armf armfVar29, armf armfVar30, armf armfVar31, armf armfVar32, armf armfVar33, armf armfVar34, armf armfVar35, armf armfVar36, armf armfVar37, armf armfVar38, armf armfVar39, armf armfVar40, armf armfVar41, armf armfVar42, armf armfVar43, armf armfVar44, armf armfVar45, armf armfVar46, armf armfVar47, armf armfVar48, armf armfVar49, armf armfVar50, armf armfVar51, armf armfVar52) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        armfVar10.getClass();
        this.i = armfVar10;
        armfVar11.getClass();
        this.j = armfVar11;
        armfVar12.getClass();
        this.k = armfVar12;
        armfVar13.getClass();
        armfVar14.getClass();
        this.l = armfVar14;
        armfVar15.getClass();
        armfVar16.getClass();
        this.m = armfVar16;
        armfVar17.getClass();
        this.n = armfVar17;
        armfVar18.getClass();
        this.o = armfVar18;
        armfVar19.getClass();
        this.p = armfVar19;
        armfVar20.getClass();
        this.q = armfVar20;
        armfVar21.getClass();
        this.r = armfVar21;
        armfVar22.getClass();
        this.s = armfVar22;
        armfVar23.getClass();
        this.t = armfVar23;
        armfVar24.getClass();
        this.u = armfVar24;
        armfVar25.getClass();
        this.v = armfVar25;
        armfVar26.getClass();
        this.w = armfVar26;
        armfVar27.getClass();
        this.x = armfVar27;
        armfVar28.getClass();
        this.y = armfVar28;
        armfVar29.getClass();
        this.z = armfVar29;
        armfVar30.getClass();
        this.A = armfVar30;
        armfVar31.getClass();
        armfVar32.getClass();
        this.B = armfVar32;
        armfVar33.getClass();
        this.C = armfVar33;
        armfVar34.getClass();
        this.D = armfVar34;
        armfVar35.getClass();
        this.E = armfVar35;
        armfVar36.getClass();
        this.F = armfVar36;
        armfVar37.getClass();
        this.G = armfVar37;
        armfVar38.getClass();
        this.H = armfVar38;
        armfVar39.getClass();
        this.I = armfVar39;
        armfVar40.getClass();
        this.J = armfVar40;
        armfVar41.getClass();
        this.K = armfVar41;
        armfVar42.getClass();
        this.L = armfVar42;
        armfVar43.getClass();
        this.M = armfVar43;
        armfVar44.getClass();
        this.N = armfVar44;
        armfVar45.getClass();
        this.O = armfVar45;
        armfVar46.getClass();
        this.P = armfVar46;
        armfVar47.getClass();
        this.Q = armfVar47;
        armfVar48.getClass();
        this.R = armfVar48;
        armfVar49.getClass();
        this.S = armfVar49;
        armfVar50.getClass();
        this.T = armfVar50;
        armfVar51.getClass();
        armfVar52.getClass();
        this.U = armfVar52;
    }

    public final /* bridge */ /* synthetic */ Action a() {
        Context context = (Context) this.a.b();
        context.getClass();
        xnv xnvVar = (xnv) this.i.b();
        xnvVar.getClass();
        anen anenVar = (anen) this.r.b();
        anenVar.getClass();
        ((psw) this.P.b()).getClass();
        armf armfVar = this.s;
        armf armfVar2 = this.t;
        armf armfVar3 = this.u;
        armf armfVar4 = this.v;
        armf armfVar5 = this.w;
        armf armfVar6 = this.x;
        armf armfVar7 = this.y;
        armf armfVar8 = this.z;
        armf armfVar9 = this.A;
        armf armfVar10 = this.B;
        armf armfVar11 = this.C;
        armf armfVar12 = this.D;
        armf armfVar13 = this.E;
        armf armfVar14 = this.F;
        armf armfVar15 = this.G;
        armf armfVar16 = this.H;
        armf armfVar17 = this.I;
        armf armfVar18 = this.J;
        armf armfVar19 = this.K;
        armf armfVar20 = this.L;
        armf armfVar21 = this.M;
        armf armfVar22 = this.N;
        armf armfVar23 = this.O;
        armf armfVar24 = this.Q;
        armf armfVar25 = this.R;
        armf armfVar26 = this.S;
        armf armfVar27 = this.T;
        armf armfVar28 = this.U;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, xnvVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, anenVar, armfVar, armfVar2, armfVar3, armfVar4, armfVar5, armfVar6, armfVar7, armfVar8, armfVar9, armfVar10, armfVar11, armfVar12, armfVar13, armfVar14, armfVar15, armfVar16, armfVar17, armfVar18, armfVar19, armfVar20, armfVar21, armfVar22, armfVar23, armfVar24, armfVar25, armfVar26, armfVar27, armfVar28);
    }

    @Override // defpackage.rhp
    public final /* bridge */ /* synthetic */ Action c(Parcel parcel) {
        Context context = (Context) this.a.b();
        context.getClass();
        xnv xnvVar = (xnv) this.i.b();
        xnvVar.getClass();
        anen anenVar = (anen) this.r.b();
        anenVar.getClass();
        ((psw) this.P.b()).getClass();
        parcel.getClass();
        armf armfVar = this.s;
        armf armfVar2 = this.t;
        armf armfVar3 = this.u;
        armf armfVar4 = this.v;
        armf armfVar5 = this.w;
        armf armfVar6 = this.x;
        armf armfVar7 = this.y;
        armf armfVar8 = this.z;
        armf armfVar9 = this.A;
        armf armfVar10 = this.B;
        armf armfVar11 = this.C;
        armf armfVar12 = this.D;
        armf armfVar13 = this.E;
        armf armfVar14 = this.F;
        armf armfVar15 = this.G;
        armf armfVar16 = this.H;
        armf armfVar17 = this.I;
        armf armfVar18 = this.J;
        armf armfVar19 = this.K;
        armf armfVar20 = this.L;
        armf armfVar21 = this.N;
        armf armfVar22 = this.O;
        armf armfVar23 = this.M;
        armf armfVar24 = this.Q;
        armf armfVar25 = this.R;
        armf armfVar26 = this.S;
        armf armfVar27 = this.T;
        armf armfVar28 = this.U;
        return new SendMessageAction(context, this.b, this.c, this.d, this.e, this.f, this.g, this.h, xnvVar, this.j, this.k, this.l, this.m, this.n, this.o, this.p, this.q, anenVar, armfVar, armfVar2, armfVar3, armfVar4, armfVar5, armfVar6, armfVar7, armfVar8, armfVar9, armfVar10, armfVar11, armfVar12, armfVar13, armfVar14, armfVar15, armfVar16, armfVar17, armfVar18, armfVar19, armfVar20, armfVar21, armfVar22, armfVar23, armfVar24, armfVar25, armfVar26, armfVar27, armfVar28, parcel);
    }
}
