package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rne {
    public final rnf A;
    public final rnf B;
    public final rnf C;
    public final rnf D;
    public final rnf[] E;
    public final rnf a;
    public final rnf b;
    public final rnf c;
    public final rnf d;
    public final rnf e;
    public final rnf f;
    public final rnf g;
    public final rnf h;
    public final rnf i;
    public final rnf j;
    public final rnf k;
    public final rnf l;
    public final rnf m;
    public final rnf n;
    public final rnf o;
    public final rnf p;
    public final rnf q;
    public final rnf r;
    public final rnf s;
    public final rnf t;
    public final rnf u;
    public final rnf v;
    public final rnf w;
    public final rnf x;
    public final rnf y;
    public final rnf z;

    public rne() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "messages_backup._id";
        a.c = new wsy();
        rnf rnfVar = new rnf(a.a());
        this.a = rnfVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.j(true);
        a2.c(true);
        a2.a = "messages_backup.message_persistence_id";
        a2.e(true);
        a2.c = new wsy();
        rnf rnfVar2 = new rnf(a2.a());
        this.b = rnfVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.c(true);
        a3.d(true);
        a3.b = new rlm(12);
        a3.a = "messages_backup.my_identity";
        a3.c = new wsy();
        rnf rnfVar3 = new rnf(a3.a());
        this.c = rnfVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "messages_backup.message_status";
        a4.c = new wsy();
        rnf rnfVar4 = new rnf(a4.a());
        this.d = rnfVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "messages_backup.seen";
        a5.c = new wsy();
        rnf rnfVar5 = new rnf(a5.a());
        this.e = rnfVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.a = "messages_backup.read";
        a6.c = new wsy();
        rnf rnfVar6 = new rnf(a6.a());
        this.f = rnfVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.c(true);
        a7.d(true);
        a7.b = new rlm(13);
        a7.a = "messages_backup.conversation_id";
        a7.c = new wsy();
        rnf rnfVar7 = new rnf(a7.a());
        this.g = rnfVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.c(true);
        a8.d(true);
        a8.b = new rlm(14);
        a8.a = "messages_backup.sender_participant_id";
        a8.c = new wsy();
        rnf rnfVar8 = new rnf(a8.a());
        this.h = rnfVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "messages_backup.sender_send_destination";
        a9.c = new wsy();
        rnf rnfVar9 = new rnf(a9.a());
        this.i = rnfVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "messages_backup.msisdn_receiving_rcs_message";
        a10.c = new wsy();
        rnf rnfVar10 = new rnf(a10.a());
        this.j = rnfVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.c(true);
        a11.d(true);
        a11.b = new rlm(15);
        a11.a = "messages_backup.self_participant_id";
        a11.c = new wsy();
        rnf rnfVar11 = new rnf(a11.a());
        this.k = rnfVar11;
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "messages_backup.mms_subject";
        a12.c = new wsy();
        rnf rnfVar12 = new rnf(a12.a());
        this.l = rnfVar12;
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.c(true);
        a13.a = "messages_backup.received_timestamp";
        a13.c = new wsy();
        rnf rnfVar13 = new rnf(a13.a());
        this.m = rnfVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "messages_backup.sent_timestamp";
        a14.c = new wsy();
        rnf rnfVar14 = new rnf(a14.a());
        this.n = rnfVar14;
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.a = "messages_backup.protocol";
        a15.c = new wsy();
        rnf rnfVar15 = new rnf(a15.a());
        this.o = rnfVar15;
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "messages_backup.message_priority";
        a16.c = new wsy();
        rnf rnfVar16 = new rnf(a16.a());
        this.p = rnfVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages_backup.rcs_encryption_status";
        a17.c = new wsy();
        rnf rnfVar17 = new rnf(a17.a());
        this.q = rnfVar17;
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "messages_backup.cloud_sync_id";
        a18.c = new wsy();
        rnf rnfVar18 = new rnf(a18.a());
        this.r = rnfVar18;
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages_backup.correlation_id";
        a19.c = new wsy();
        rnf rnfVar19 = new rnf(a19.a());
        this.s = rnfVar19;
        agmi a20 = agmk.a();
        a20.d = 1;
        a20.a = "messages_backup.sms_error_code";
        a20.c = new wsy();
        rnf rnfVar20 = new rnf(a20.a());
        this.t = rnfVar20;
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "messages_backup.sms_error_desc_map_name";
        a21.c = new wsy();
        rnf rnfVar21 = new rnf(a21.a());
        this.u = rnfVar21;
        agmi a22 = agmk.a();
        a22.d = 4;
        a22.a = "messages_backup.mms_transaction_id";
        a22.c = new wsy();
        rnf rnfVar22 = new rnf(a22.a());
        this.v = rnfVar22;
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "messages_backup.mms_content_location";
        a23.c = new wsy();
        rnf rnfVar23 = new rnf(a23.a());
        this.w = rnfVar23;
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "messages_backup.is_hidden";
        a24.c = new wsy();
        rnf rnfVar24 = new rnf(a24.a());
        this.x = rnfVar24;
        agmi a25 = agmk.a();
        a25.d = 4;
        a25.c(true);
        a25.a = "messages_backup.rcs_message_id";
        a25.c = new wsy();
        rnf rnfVar25 = new rnf(a25.a());
        this.y = rnfVar25;
        agmi a26 = agmk.a();
        a26.d = 5;
        a26.c(true);
        a26.a = "messages_backup.custom_headers";
        a26.c = new wsy();
        rnf rnfVar26 = new rnf(a26.a());
        this.z = rnfVar26;
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.a = "messages_backup.cms_id";
        a27.c = new wsy();
        rnf rnfVar27 = new rnf(a27.a());
        this.A = rnfVar27;
        agmi a28 = agmk.a();
        a28.d = 1;
        a28.a = "messages_backup.cms_life_cycle";
        a28.c = new wsy();
        rnf rnfVar28 = new rnf(a28.a());
        this.B = rnfVar28;
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.a = "messages_backup.cms_correlation_id";
        a29.c = new wsy();
        rnf rnfVar29 = new rnf(a29.a());
        this.C = rnfVar29;
        agmi a30 = agmk.a();
        a30.d = 2;
        a30.a = "messages_backup.cms_last_mod_seq";
        a30.c = new wsy();
        rnf rnfVar30 = new rnf(a30.a());
        this.D = rnfVar30;
        this.E = new rnf[]{rnfVar, rnfVar2, rnfVar3, rnfVar4, rnfVar5, rnfVar6, rnfVar7, rnfVar8, rnfVar9, rnfVar10, rnfVar11, rnfVar12, rnfVar13, rnfVar14, rnfVar15, rnfVar16, rnfVar17, rnfVar18, rnfVar19, rnfVar20, rnfVar21, rnfVar22, rnfVar23, rnfVar24, rnfVar25, rnfVar26, rnfVar27, rnfVar28, rnfVar29, rnfVar30};
    }
}
