package defpackage;

import android.content.Context;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rss {
    private final armf A;
    private final armf a;
    private final armf b;
    private final armf c;
    private final armf d;
    private final armf e;
    private final armf f;
    private final armf g;
    private final armf h;
    private final armf i;
    private final armf j;
    private final armf k;
    private final armf l;
    private final armf m;
    private final armf n;
    private final armf o;
    private final armf p;
    private final armf q;
    private final armf r;
    private final armf s;
    private final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;
    private final armf y;
    private final armf z;

    public rss(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.j = armfVar10;
        armfVar11.getClass();
        this.k = armfVar11;
        armfVar12.getClass();
        this.l = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.n = armfVar14;
        armfVar15.getClass();
        this.o = armfVar15;
        armfVar16.getClass();
        this.p = armfVar16;
        armfVar17.getClass();
        this.q = armfVar17;
        armfVar18.getClass();
        this.r = armfVar18;
        armfVar19.getClass();
        this.s = armfVar19;
        armfVar20.getClass();
        this.t = armfVar20;
        armfVar21.getClass();
        this.u = armfVar21;
        armfVar22.getClass();
        this.v = armfVar22;
        armfVar23.getClass();
        this.w = armfVar23;
        armfVar24.getClass();
        this.x = armfVar24;
        armfVar25.getClass();
        this.y = armfVar25;
        armfVar26.getClass();
        this.z = armfVar26;
        armfVar27.getClass();
        this.A = armfVar27;
    }

    public final rsr a(ConversationIdType conversationIdType, boolean z) {
        xnv xnvVar = (xnv) this.a.b();
        xnvVar.getClass();
        ahmv ahmvVar = (ahmv) this.b.b();
        ahmvVar.getClass();
        vqu vquVar = (vqu) this.c.b();
        vquVar.getClass();
        xbf xbfVar = (xbf) this.d.b();
        xbfVar.getClass();
        xbi xbiVar = (xbi) this.e.b();
        xbiVar.getClass();
        Context context = (Context) this.f.b();
        context.getClass();
        yep yepVar = (yep) this.g.b();
        yepVar.getClass();
        yjy yjyVar = (yjy) this.h.b();
        yjyVar.getClass();
        ydf ydfVar = (ydf) this.i.b();
        ydfVar.getClass();
        wyp wypVar = (wyp) this.j.b();
        wypVar.getClass();
        xav xavVar = (xav) this.k.b();
        xavVar.getClass();
        wfh wfhVar = (wfh) this.l.b();
        wfhVar.getClass();
        rsv rsvVar = (rsv) this.m.b();
        rsvVar.getClass();
        nct nctVar = (nct) this.n.b();
        nctVar.getClass();
        rys rysVar = (rys) this.o.b();
        rysVar.getClass();
        rtg rtgVar = (rtg) this.p.b();
        rtgVar.getClass();
        tqx tqxVar = (tqx) this.q.b();
        tqxVar.getClass();
        ifb ifbVar = (ifb) this.r.b();
        ifbVar.getClass();
        rvp rvpVar = (rvp) this.s.b();
        rvpVar.getClass();
        Object b = this.x.b();
        armf armfVar = this.v;
        armf armfVar2 = this.w;
        lgg lggVar = (lgg) b;
        lggVar.getClass();
        return new rsr(xnvVar, ahmvVar, vquVar, xbfVar, xbiVar, context, yepVar, yjyVar, ydfVar, wypVar, xavVar, wfhVar, rsvVar, nctVar, rysVar, rtgVar, tqxVar, ifbVar, rvpVar, this.t, this.u, conversationIdType, z, armfVar, armfVar2, lggVar, this.y, this.z, this.A);
    }
}
