package defpackage;

import android.content.Context;
import android.net.Uri;
import com.google.android.apps.messaging.shared.datamodel.data.MessagePartData;
import com.google.android.apps.messaging.shared.datamodel.data.PendingAttachmentData;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class rtg {
    public final armf a;
    public final armf b;
    public final armf c;
    public final armf d;
    public final armf e;
    public final armf f;
    public final armf g;
    public final armf h;
    public final armf i;
    public final armf j;
    public final armf k;
    public final armf l;
    public final armf m;
    public final armf n;
    public final armf o;
    public final armf p;
    public final armf q;
    public final armf r;
    public final armf s;
    public final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;

    public rtg(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        armfVar11.getClass();
        this.j = armfVar11;
        armfVar12.getClass();
        this.k = armfVar12;
        armfVar13.getClass();
        this.l = armfVar13;
        armfVar14.getClass();
        this.m = armfVar14;
        armfVar15.getClass();
        this.n = armfVar15;
        armfVar16.getClass();
        this.o = armfVar16;
        armfVar17.getClass();
        this.p = armfVar17;
        armfVar18.getClass();
        this.u = armfVar18;
        armfVar19.getClass();
        this.v = armfVar19;
        armfVar20.getClass();
        this.w = armfVar20;
        armfVar21.getClass();
        this.q = armfVar21;
        armfVar22.getClass();
        this.r = armfVar22;
        armfVar23.getClass();
        this.x = armfVar23;
        armfVar24.getClass();
        this.s = armfVar24;
        armfVar25.getClass();
        this.t = armfVar25;
    }

    public final PendingAttachmentData a(MessagePartData messagePartData) {
        wfh wfhVar = (wfh) this.a.b();
        wfhVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        ydf ydfVar = (ydf) this.c.b();
        ydfVar.getClass();
        xbf xbfVar = (xbf) this.d.b();
        xbfVar.getClass();
        ydk ydkVar = (ydk) this.e.b();
        ydkVar.getClass();
        rtb rtbVar = (rtb) this.f.b();
        rtbVar.getClass();
        uff uffVar = (uff) this.g.b();
        uffVar.getClass();
        xav xavVar = (xav) this.i.b();
        xavVar.getClass();
        rtg rtgVar = (rtg) this.x.b();
        rtgVar.getClass();
        yfo yfoVar = (yfo) this.j.b();
        yfoVar.getClass();
        xnv xnvVar = (xnv) this.k.b();
        xnvVar.getClass();
        zxy zxyVar = (zxy) this.l.b();
        zxyVar.getClass();
        ydy ydyVar = (ydy) this.m.b();
        ydyVar.getClass();
        Optional optional = (Optional) ((apxx) this.n).a;
        wfh wfhVar2 = (wfh) this.o.b();
        wfhVar2.getClass();
        anen anenVar = (anen) this.p.b();
        anenVar.getClass();
        return new PendingAttachmentData(wfhVar, context, ydfVar, xbfVar, ydkVar, rtbVar, uffVar, this.h, xavVar, rtgVar, yfoVar, xnvVar, zxyVar, ydyVar, optional, wfhVar2, anenVar, messagePartData);
    }

    public final PendingAttachmentData b(String str, Uri uri, ameb amebVar) {
        wfh wfhVar = (wfh) this.a.b();
        wfhVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        ydf ydfVar = (ydf) this.c.b();
        ydfVar.getClass();
        xbf xbfVar = (xbf) this.d.b();
        xbfVar.getClass();
        ydk ydkVar = (ydk) this.e.b();
        ydkVar.getClass();
        rtb rtbVar = (rtb) this.f.b();
        rtbVar.getClass();
        uff uffVar = (uff) this.g.b();
        uffVar.getClass();
        xav xavVar = (xav) this.i.b();
        xavVar.getClass();
        rtg rtgVar = (rtg) this.v.b();
        rtgVar.getClass();
        yfo yfoVar = (yfo) this.j.b();
        yfoVar.getClass();
        xnv xnvVar = (xnv) this.k.b();
        xnvVar.getClass();
        zxy zxyVar = (zxy) this.l.b();
        zxyVar.getClass();
        ydy ydyVar = (ydy) this.m.b();
        ydyVar.getClass();
        Optional optional = (Optional) ((apxx) this.n).a;
        wfh wfhVar2 = (wfh) this.o.b();
        wfhVar2.getClass();
        anen anenVar = (anen) this.p.b();
        anenVar.getClass();
        amebVar.getClass();
        return new PendingAttachmentData(wfhVar, context, ydfVar, xbfVar, ydkVar, rtbVar, uffVar, this.h, xavVar, rtgVar, yfoVar, xnvVar, zxyVar, ydyVar, optional, wfhVar2, anenVar, null, str, uri, null, -1, -1, null, null, -1L, amebVar, -1L, null, null, null);
    }

    public final PendingAttachmentData c(String str, Uri uri, ameb amebVar, String str2, long j) {
        wfh wfhVar = (wfh) this.a.b();
        wfhVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        ydf ydfVar = (ydf) this.c.b();
        ydfVar.getClass();
        xbf xbfVar = (xbf) this.d.b();
        xbfVar.getClass();
        ydk ydkVar = (ydk) this.e.b();
        ydkVar.getClass();
        uff uffVar = (uff) this.g.b();
        uffVar.getClass();
        xav xavVar = (xav) this.i.b();
        xavVar.getClass();
        rtb rtbVar = (rtb) this.f.b();
        rtbVar.getClass();
        rtg rtgVar = (rtg) this.u.b();
        rtgVar.getClass();
        yfo yfoVar = (yfo) this.j.b();
        yfoVar.getClass();
        xnv xnvVar = (xnv) this.k.b();
        xnvVar.getClass();
        zxy zxyVar = (zxy) this.l.b();
        zxyVar.getClass();
        ydy ydyVar = (ydy) this.m.b();
        ydyVar.getClass();
        Optional optional = (Optional) ((apxx) this.n).a;
        wfh wfhVar2 = (wfh) this.o.b();
        wfhVar2.getClass();
        anen anenVar = (anen) this.p.b();
        anenVar.getClass();
        amebVar.getClass();
        return new PendingAttachmentData(wfhVar, context, ydfVar, xbfVar, ydkVar, rtbVar, uffVar, this.h, xavVar, rtgVar, yfoVar, xnvVar, zxyVar, ydyVar, optional, wfhVar2, anenVar, null, str, uri, null, -1, -1, null, null, j, amebVar, -1L, null, null, str2);
    }

    public final PendingAttachmentData d(String str, Uri uri, Uri uri2, int i, int i2, long j, ameb amebVar, String str2, String str3, long j2, String str4, String str5) {
        wfh wfhVar = (wfh) this.a.b();
        wfhVar.getClass();
        Context context = (Context) this.b.b();
        context.getClass();
        ydf ydfVar = (ydf) this.c.b();
        ydfVar.getClass();
        xbf xbfVar = (xbf) this.d.b();
        xbfVar.getClass();
        ydk ydkVar = (ydk) this.e.b();
        ydkVar.getClass();
        rtb rtbVar = (rtb) this.f.b();
        rtbVar.getClass();
        uff uffVar = (uff) this.g.b();
        uffVar.getClass();
        xav xavVar = (xav) this.i.b();
        xavVar.getClass();
        rtg rtgVar = (rtg) this.w.b();
        rtgVar.getClass();
        yfo yfoVar = (yfo) this.j.b();
        yfoVar.getClass();
        xnv xnvVar = (xnv) this.k.b();
        xnvVar.getClass();
        zxy zxyVar = (zxy) this.l.b();
        zxyVar.getClass();
        ydy ydyVar = (ydy) this.m.b();
        ydyVar.getClass();
        Optional optional = (Optional) ((apxx) this.n).a;
        wfh wfhVar2 = (wfh) this.o.b();
        wfhVar2.getClass();
        anen anenVar = (anen) this.p.b();
        anenVar.getClass();
        amebVar.getClass();
        return new PendingAttachmentData(wfhVar, context, ydfVar, xbfVar, ydkVar, rtbVar, uffVar, this.h, xavVar, rtgVar, yfoVar, xnvVar, zxyVar, ydyVar, optional, wfhVar2, anenVar, str, uri, uri2, i, i2, j, amebVar, str2, str3, j2, str4, str5);
    }
}
