package defpackage;

import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.MessageIdType;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sao extends agmb {
    public final ConversationIdType a;
    public final xhv b;
    public final tqh c;
    public final tqc d;
    public final long e;
    public final boolean f;
    public final boolean g;
    public final long h;
    public final boolean i;
    public final qpd j;
    public final Optional k;
    public final MessageIdType l;
    public final int m;
    public final int n;
    public final long o;
    public final nht p;
    public final ConversationIdType q;

    public sao(byte[] bArr) {
        super(a.bp());
        this.a = ruy.a;
        this.b = new xhv();
        this.c = tqh.NAME_IS_AUTOMATIC;
        this.d = tqc.UNARCHIVED;
        this.e = -1L;
        this.f = true;
        this.g = true;
        this.h = -1L;
        this.i = true;
        this.j = qpd.b(0);
        this.k = uxi.g(-1L);
        this.l = rvc.a;
        this.m = -1;
        this.n = -2;
        this.o = -1L;
        this.p = nht.VMT_STATUS_UNKNOWN;
        this.q = ruy.a;
    }

    public final san a() {
        int i = sap.a;
        san sanVar = new san();
        sanVar.ar(az());
        sanVar.a = this.a;
        sanVar.b = this.b;
        sanVar.c = null;
        sanVar.d = this.c;
        sanVar.e = null;
        sanVar.f = null;
        sanVar.g = null;
        sanVar.h = null;
        sanVar.i = false;
        sanVar.j = null;
        sanVar.k = null;
        sanVar.l = null;
        sanVar.m = null;
        sanVar.n = 0;
        sanVar.o = this.d;
        sanVar.p = 0L;
        sanVar.q = null;
        sanVar.r = -1L;
        sanVar.s = null;
        sanVar.t = null;
        sanVar.u = null;
        sanVar.v = null;
        sanVar.w = 0;
        sanVar.x = true;
        sanVar.y = null;
        sanVar.z = true;
        sanVar.A = false;
        sanVar.B = 0;
        sanVar.C = -1L;
        sanVar.D = 0;
        sanVar.E = 0;
        sanVar.F = 0;
        sanVar.G = false;
        sanVar.H = false;
        sanVar.I = null;
        sanVar.J = 0L;
        sanVar.K = null;
        sanVar.L = null;
        sanVar.M = null;
        sanVar.N = true;
        sanVar.O = false;
        sanVar.P = this.j;
        sanVar.Q = this.k;
        sanVar.R = false;
        sanVar.S = false;
        sanVar.T = this.l;
        sanVar.U = 0L;
        sanVar.V = 0L;
        sanVar.W = 0;
        sanVar.X = 0;
        sanVar.Y = false;
        sanVar.Z = 0;
        sanVar.aa = 0;
        sanVar.ab = -1;
        sanVar.ac = null;
        sanVar.ad = -2;
        sanVar.ae = null;
        sanVar.af = null;
        sanVar.ag = null;
        sanVar.ah = -1L;
        sanVar.ai = 0L;
        sanVar.aj = null;
        sanVar.ak = null;
        sanVar.al = null;
        sanVar.am = null;
        sanVar.an = null;
        sanVar.ao = null;
        sanVar.ap = this.p;
        sanVar.aq = null;
        sanVar.ar = 0L;
        sanVar.as = 0;
        sanVar.at = null;
        sanVar.au = 0L;
        sanVar.av = this.q;
        sanVar.cF = aA();
        return sanVar;
    }

    public final sac b() {
        int i = sad.a;
        sac sacVar = new sac();
        sacVar.ar(az());
        sacVar.a = this.a;
        sacVar.b = this.b;
        sacVar.c = null;
        sacVar.d = this.c;
        sacVar.e = null;
        sacVar.f = null;
        sacVar.g = null;
        sacVar.h = null;
        sacVar.i = false;
        sacVar.j = null;
        sacVar.k = null;
        sacVar.l = null;
        sacVar.m = null;
        sacVar.n = 0;
        sacVar.o = this.d;
        sacVar.p = 0L;
        sacVar.q = null;
        sacVar.r = -1L;
        sacVar.s = null;
        sacVar.t = null;
        sacVar.u = null;
        sacVar.v = null;
        sacVar.w = 0;
        sacVar.x = true;
        sacVar.y = null;
        sacVar.z = true;
        sacVar.A = false;
        sacVar.B = 0;
        sacVar.C = -1L;
        sacVar.D = 0;
        sacVar.E = 0;
        sacVar.F = 0;
        sacVar.G = false;
        sacVar.H = false;
        sacVar.I = null;
        sacVar.J = 0L;
        sacVar.K = null;
        sacVar.L = null;
        sacVar.M = null;
        sacVar.N = true;
        sacVar.O = false;
        sacVar.P = this.j;
        sacVar.Q = this.k;
        sacVar.R = false;
        sacVar.S = false;
        sacVar.T = this.l;
        sacVar.U = 0L;
        sacVar.V = 0L;
        sacVar.W = 0;
        sacVar.X = 0;
        sacVar.Y = false;
        sacVar.Z = 0;
        sacVar.aa = 0;
        sacVar.ab = -1;
        sacVar.ac = null;
        sacVar.ad = -2;
        sacVar.ae = null;
        sacVar.af = null;
        sacVar.ag = null;
        sacVar.ah = -1L;
        sacVar.ai = 0L;
        sacVar.aj = null;
        sacVar.ak = null;
        sacVar.al = null;
        sacVar.am = null;
        sacVar.an = null;
        sacVar.ao = null;
        sacVar.ap = this.p;
        sacVar.aq = null;
        sacVar.ar = 0L;
        sacVar.as = 0;
        sacVar.at = null;
        sacVar.au = 0L;
        sacVar.av = this.q;
        sacVar.cF = aA();
        return sacVar;
    }

    public sao() {
        super(a.bp());
        this.a = ruy.a;
        this.b = new xhv();
        this.c = tqh.NAME_IS_AUTOMATIC;
        this.d = tqc.UNARCHIVED;
        this.e = -1L;
        this.f = true;
        this.g = true;
        this.h = -1L;
        this.i = true;
        this.j = qpd.b(0);
        this.k = uxi.g(-1L);
        this.l = rvc.a;
        this.m = -1;
        this.n = -2;
        this.o = -1L;
        this.p = nht.VMT_STATUS_UNKNOWN;
        this.q = ruy.a;
    }
}
