package defpackage;

import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.MessageIdType;
import j$.util.Optional;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sba extends agmb {
    public final vox A;
    public final MessageIdType B;
    public final MessageIdType C;
    public final MessageIdType D;
    public final boolean E;
    public final Optional F;
    public final MessageIdType G;
    public final MessageIdType H;
    public final MessageIdType I;
    public final MessageIdType a;
    public final ConversationIdType b;
    public final rve c;
    public final tqr d;
    public final long e;
    public final int f;
    public final String g;
    public final rve h;
    public final int i;
    public final xxw j;
    public final tqf k;
    public final tqu l;
    public final MessageIdType m;
    public final tql n;
    public final ConversationIdType o;
    public final tqa p;
    public final tqa q;
    public final long r;
    public final tqw s;
    public final tqq t;
    public final tqi u;
    public final long v;
    public final int w;
    public final tqr x;
    public final long y;
    public final vox z;

    public sba() {
        super(a.bp());
        this.a = rvc.a;
        this.b = ruy.a;
        this.c = rve.a;
        this.d = tqr.VERIFICATION_NA;
        this.e = -1L;
        this.f = -1;
        this.g = "";
        this.h = rve.a;
        this.i = -2;
        this.j = xxw.UNKNOWN;
        this.k = tqf.UNKNOWN;
        this.l = tqu.UNKNOWN;
        MessageIdType messageIdType = rvc.a;
        this.m = messageIdType;
        this.n = tql.SUCCEEDED;
        this.o = ruy.a;
        this.p = new tqa(-1);
        this.q = new tqa(-1);
        this.r = -1L;
        this.s = tqw.UNKNOWN;
        this.t = tqq.NONE;
        this.u = tqi.DEFAULT_NO_VERDICT;
        this.v = -1L;
        this.w = -1;
        this.x = tqr.VERIFICATION_NA;
        this.y = -1L;
        vox voxVar = vox.PROFILE_CONTACT_SOURCE;
        this.z = voxVar;
        this.A = voxVar;
        this.B = messageIdType;
        this.C = messageIdType;
        this.D = messageIdType;
        this.E = true;
        this.F = uxi.g(-1L);
        MessageIdType messageIdType2 = rvc.a;
        this.G = messageIdType2;
        this.H = messageIdType2;
        this.I = messageIdType2;
    }

    public final saz a() {
        int i = sbb.a;
        saz sazVar = new saz();
        sazVar.ar(az());
        sazVar.a = this.a;
        sazVar.b = this.b;
        sazVar.c = null;
        sazVar.d = 0L;
        sazVar.e = 0L;
        sazVar.f = 0;
        sazVar.g = 0;
        sazVar.h = 0;
        sazVar.i = false;
        sazVar.j = false;
        sazVar.k = null;
        sazVar.l = 0;
        sazVar.m = 0L;
        sazVar.n = null;
        sazVar.o = 0L;
        sazVar.p = 0L;
        sazVar.q = null;
        sazVar.r = 0;
        sazVar.s = null;
        sazVar.t = this.c;
        sazVar.u = 0;
        sazVar.v = this.d;
        sazVar.w = false;
        sazVar.x = -1L;
        sazVar.y = -1;
        sazVar.z = null;
        sazVar.A = null;
        sazVar.B = this.g;
        sazVar.C = 0L;
        sazVar.D = this.h;
        sazVar.E = -2;
        sazVar.F = this.j;
        sazVar.G = this.k;
        sazVar.H = null;
        sazVar.I = this.l;
        sazVar.J = null;
        sazVar.K = null;
        sazVar.L = this.m;
        sazVar.M = null;
        sazVar.N = null;
        sazVar.O = null;
        sazVar.P = null;
        sazVar.Q = null;
        sazVar.R = null;
        sazVar.S = null;
        sazVar.T = 0L;
        sazVar.U = null;
        sazVar.V = null;
        sazVar.W = this.n;
        sazVar.X = null;
        sazVar.Y = this.o;
        sazVar.Z = this.p;
        sazVar.aa = this.q;
        sazVar.ab = -1L;
        sazVar.ac = 0.0d;
        sazVar.ad = 0.0d;
        sazVar.ae = null;
        sazVar.af = null;
        sazVar.ag = null;
        sazVar.ah = null;
        sazVar.ai = null;
        sazVar.aj = null;
        sazVar.ak = null;
        sazVar.al = null;
        sazVar.am = null;
        sazVar.an = null;
        sazVar.ao = null;
        sazVar.ap = null;
        sazVar.aq = null;
        sazVar.ar = null;
        sazVar.as = null;
        sazVar.at = null;
        sazVar.au = null;
        sazVar.av = null;
        sazVar.aw = null;
        sazVar.ax = null;
        sazVar.ay = null;
        sazVar.az = null;
        sazVar.aA = false;
        sazVar.aB = 0L;
        sazVar.aC = null;
        sazVar.aD = null;
        sazVar.aE = null;
        sazVar.aF = this.s;
        sazVar.aG = null;
        sazVar.aH = this.t;
        sazVar.aI = this.u;
        sazVar.aJ = null;
        sazVar.aL = null;
        sazVar.aM = null;
        sazVar.aN = null;
        sazVar.aO = null;
        sazVar.aP = null;
        sazVar.aQ = null;
        sazVar.aR = -1L;
        sazVar.aS = null;
        sazVar.aT = -1;
        sazVar.aU = 0;
        sazVar.aV = 0;
        sazVar.aW = false;
        sazVar.aX = 0;
        sazVar.aY = false;
        sazVar.aZ = this.x;
        sazVar.ba = -1L;
        sazVar.bb = this.z;
        sazVar.bc = this.A;
        sazVar.be = null;
        sazVar.bf = this.B;
        sazVar.bg = null;
        sazVar.bh = null;
        sazVar.bi = null;
        sazVar.bj = null;
        sazVar.bk = null;
        sazVar.bm = this.C;
        sazVar.bn = null;
        sazVar.bo = null;
        sazVar.bp = null;
        sazVar.bq = null;
        sazVar.br = null;
        sazVar.bs = null;
        sazVar.bt = null;
        sazVar.bu = null;
        sazVar.bv = null;
        sazVar.bw = null;
        sazVar.bx = null;
        sazVar.by = null;
        sazVar.bA = this.D;
        sazVar.bB = null;
        sazVar.bC = 0L;
        sazVar.bD = null;
        sazVar.bE = null;
        sazVar.bF = null;
        sazVar.bG = null;
        sazVar.bH = null;
        sazVar.bI = false;
        sazVar.bJ = false;
        sazVar.bL = null;
        sazVar.bM = null;
        sazVar.bN = null;
        sazVar.bP = null;
        sazVar.bQ = 0;
        sazVar.bR = false;
        sazVar.bS = null;
        sazVar.bT = true;
        sazVar.bU = this.F;
        sazVar.bV = null;
        sazVar.bW = null;
        sazVar.bX = this.G;
        sazVar.bY = null;
        sazVar.bZ = null;
        sazVar.ca = null;
        sazVar.cb = null;
        sazVar.cc = null;
        sazVar.cd = null;
        sazVar.cf = this.H;
        sazVar.cg = this.I;
        sazVar.ch = 0L;
        sazVar.ci = null;
        sazVar.cj = 0;
        sazVar.ck = null;
        sazVar.cl = null;
        sazVar.cm = null;
        sazVar.cn = null;
        sazVar.co = null;
        sazVar.cp = null;
        sazVar.cq = null;
        sazVar.cr = null;
        sazVar.cs = null;
        sazVar.ct = null;
        sazVar.cu = null;
        sazVar.cv = null;
        sazVar.cw = 0L;
        sazVar.cx = null;
        sazVar.cy = null;
        sazVar.cz = false;
        sazVar.cB = null;
        sazVar.cC = null;
        sazVar.h();
        sazVar.cF = aA();
        return sazVar;
    }
}
