package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sbn {
    public static final String[] a = {"conversation_participants.conversation_id", "conversation_participants.participant_id", "conversation_participants.rcs_group_join_status", "participants._id", "participants.normalized_destination"};

    static {
        alok alokVar = new alok();
        alokVar.h("conversation_participants.rcs_group_join_status", 58570);
        alokVar.b();
        alok alokVar2 = new alok();
        alokVar2.h("conversation_id", "index_null_conversation_id");
        alokVar2.h("participant_id", "index_null_participant_id");
        alokVar2.b();
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.d(true);
        a2.a = "conversation_participants.conversation_id";
        a2.e(true);
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "conversation_participants.participant_id";
        a3.e(true);
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "conversation_participants.rcs_group_join_status";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.j(true);
        a5.f(true);
        a5.c(true);
        a5.a = "conversation_participants._id";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.c(true);
        a6.a = "conversation_participants.is_normalized";
        a6.e(true);
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "conversation_participants.last_modified_by_key";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.j(true);
        a8.f(true);
        a8.c(true);
        a8.a = "participants._id";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.c(true);
        a9.a = "participants.normalized_destination";
        a9.e(true);
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.c(true);
        a10.a = "participants.my_identity_token";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.c(true);
        a11.d(true);
        a11.b = new sbg(3);
        a11.a = "participants.my_identity_token_foreign_key";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.c(true);
        a12.a = "participants.sub_id";
        a12.e(true);
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "participants.sim_slot_id";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.a = "participants.send_destination";
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "participants.display_destination";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.j(true);
        a16.c(true);
        a16.a = "participants.comparable_destination";
        a16.e(true);
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.a = "participants.country_code";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 2;
        a18.j(true);
        a18.c(true);
        a18.a = "participants.recipient_id";
        a18.e(true);
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "participants.recipient_canonical_address";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "participants.full_name";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "participants.first_name";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 4;
        a22.a = "participants.profile_photo_uri";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "participants.contact_photo_uri";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "participants.contact_id";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 4;
        a25.a = "participants.lookup_key";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.a = "participants.color_palette_index";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "participants.color_type";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 1;
        a28.a = "participants.extended_color";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "participants.blocked";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.a = "participants.subscription_name";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "participants.subscription_color";
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 4;
        a32.a = "participants.contact_destination";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "participants.participant_type";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "participants.video_reachability";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 4;
        a35.a = "participants.alias";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.a = "participants.is_spam";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "participants.is_rcs_available";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "participants.is_spam_source";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.j(true);
        a39.c(true);
        a39.a = "participants.cms_id";
        a39.e(true);
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 1;
        a40.a = "participants.latest_verification_status";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.a = "participants.profile_photo_blob_id";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 5;
        a42.a = "participants.profile_photo_encryption_key";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "participants.directory_id";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "participants.is_check_constraint_enabled_via_phenotype";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "participants.is_valid_phone_number_data";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 2;
        a46.c(true);
        a46.d(true);
        a46.b = new sbg(2);
        a46.a = "participants.duplicate_of";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 1;
        a47.a = "participants.cms_life_cycle";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "participants.norm_ui_status";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 4;
        a49.a = "participants.last_modified_by_key";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "participants.name_source";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.a = "participants.photo_source";
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.a = "participants.profile_photo_user_preference";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 5;
        a53.a = "participants.contact_metadata";
        a53.c = new wsy();
        a53.a();
    }

    public static final sbl a() {
        Integer valueOf;
        String[] strArr;
        valueOf = Integer.valueOf(d.P().W().c());
        if (valueOf.intValue() == Integer.MAX_VALUE) {
            strArr = a;
        } else {
            alob alobVar = new alob();
            alobVar.h("conversation_participants.conversation_id");
            alobVar.h("conversation_participants.participant_id");
            if (valueOf.intValue() >= 58570) {
                alobVar.h("conversation_participants.rcs_group_join_status");
            }
            alobVar.h("participants._id");
            alobVar.h("participants.normalized_destination");
            strArr = (String[]) alobVar.g().toArray(new String[0]);
        }
        return new sbl(strArr);
    }
}
