package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sbs {
    public static final String[] a = {"conversation_to_participants.conversation_id", "conversation_to_participants.participant_id", "conversation_to_participants.rcs_group_join_status", "participants._id", "participants.normalized_destination"};

    static {
        new alok().b();
        alok alokVar = new alok();
        alokVar.h("conversation_id", "index_null_conversation_id");
        alokVar.h("participant_id", "index_null_participant_id");
        alokVar.b();
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.j(true);
        a2.i(true);
        a2.f(true);
        a2.c(true);
        a2.d(true);
        a2.a = "conversation_to_participants.conversation_id";
        a2.e(true);
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.j(true);
        a3.i(true);
        a3.f(true);
        a3.c(true);
        a3.d(true);
        a3.a = "conversation_to_participants.participant_id";
        a3.e(true);
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.i(true);
        a4.a = "conversation_to_participants.rcs_group_join_status";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "conversation_to_participants.last_modified_by_key";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.j(true);
        a6.f(true);
        a6.c(true);
        a6.a = "participants._id";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.c(true);
        a7.a = "participants.normalized_destination";
        a7.e(true);
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.c(true);
        a8.a = "participants.my_identity_token";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.c(true);
        a9.d(true);
        a9.b = new sbg(6);
        a9.a = "participants.my_identity_token_foreign_key";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.c(true);
        a10.a = "participants.sub_id";
        a10.e(true);
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "participants.sim_slot_id";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "participants.send_destination";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "participants.display_destination";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.j(true);
        a14.c(true);
        a14.a = "participants.comparable_destination";
        a14.e(true);
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "participants.country_code";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 2;
        a16.j(true);
        a16.c(true);
        a16.a = "participants.recipient_id";
        a16.e(true);
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.a = "participants.recipient_canonical_address";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "participants.full_name";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "participants.first_name";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "participants.profile_photo_uri";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "participants.contact_photo_uri";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "participants.contact_id";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "participants.lookup_key";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "participants.color_palette_index";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "participants.color_type";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.a = "participants.extended_color";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "participants.blocked";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "participants.subscription_name";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "participants.subscription_color";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.a = "participants.contact_destination";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "participants.participant_type";
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "participants.video_reachability";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 4;
        a33.a = "participants.alias";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "participants.is_spam";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "participants.is_rcs_available";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.a = "participants.is_spam_source";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 4;
        a37.j(true);
        a37.c(true);
        a37.a = "participants.cms_id";
        a37.e(true);
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "participants.latest_verification_status";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.a = "participants.profile_photo_blob_id";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 5;
        a40.a = "participants.profile_photo_encryption_key";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 1;
        a41.a = "participants.directory_id";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "participants.is_check_constraint_enabled_via_phenotype";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "participants.is_valid_phone_number_data";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 2;
        a44.c(true);
        a44.d(true);
        a44.b = new sbg(5);
        a44.a = "participants.duplicate_of";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "participants.cms_life_cycle";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 1;
        a46.a = "participants.norm_ui_status";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.a = "participants.last_modified_by_key";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "participants.name_source";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 1;
        a49.a = "participants.photo_source";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "participants.profile_photo_user_preference";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 5;
        a51.a = "participants.contact_metadata";
        a51.c = new wsy();
        a51.a();
    }
}
