package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sbx {
    public static final String[] a = {"messages._id", "messages.conversation_id", "messages.sender_id", "messages.sender_send_destination", "messages.msisdn_receiving_rcs_message", "messages.receiving_network_country", "messages.sent_timestamp", "messages.queue_insert_timestamp", "messages.received_timestamp", "messages.message_protocol", "messages.message_status", "messages.message_report_status", "messages.seen", "messages.read", "messages.sms_message_uri", "messages.sms_priority", "messages.sms_message_size", "messages.mms_subject", "messages.mms_transaction_id", "messages.mms_content_location", "messages.mms_expiry", "messages.rcs_expiry", "messages.mms_retrieve_text", "messages.raw_status", "messages.self_id", "messages.my_identity_foreign_key", "messages.retry_start_timestamp", "messages.cloud_sync_id", "messages.rcs_message_id_with_text_type", "messages.etouffee_status", "messages.verification_status", "messages.rcs_ui_status", "messages.is_hidden", "messages.rcs_remote_instance", "messages.rcs_file_transfer_session_id", "messages.sms_error_code", "messages.sms_error_desc_map_name", "messages.correlation_id", "messages.cms_id", "messages.cms_last_mod_seq", "messages.web_id", "messages.usage_stats_logging_id", "messages.send_counter", "messages.original_rcs_message_id", "messages.custom_delivery_receipt_mime_type", "messages.custom_delivery_receipt_content", "messages.report_attempt_acounter", "messages.custom_headers", "messages.cms_correlation_id", "messages.group_private_participant", "messages.original_message_id", "messages.awaiting_reverse_sync", "messages.old_sms_message_uri", "messages.draft_id", "messages.result_code", "messages.cms_life_cycle", "messages.fallback_reason", "messages.auto_retry_counter", "messages.can_revoke_before_delivered_with_rcs", "messages.trace_id", "messages.outgoing_delivery_report_status", "messages.outgoing_read_report_status", "messages.xms_transport", "messages.message_original_protocol", "messages.satellite_datagram_id", "messages.encryption_protocol", "messages.message_persistence_id", "message_replies_view.message_id_message_replies", "message_replies_view._id_messages", "message_replies_view.received_timestamp_messages", "message_replies_view._id_participants", "message_replies_view.sub_id_participants", "message_replies_view.normalized_destination_participants", "message_replies_view.display_destination_participants", "message_replies_view.full_name_participants", "message_replies_view.first_name_participants", "message_replies_view._id_parts", "message_replies_view.text_parts", "message_replies_view.uri_parts", "message_replies_view.content_type_parts", "message_replies_view.file_name_parts", "message_replies_view.duration_parts", "message_replies_view.parts__ROWID_parts", "message_replies_view.trigger_url_link_preview", "message_replies_view.expiration_time_millis_link_preview", "message_replies_view.link_title_link_preview", "message_replies_view.link_image_url_link_preview", "message_replies_view.link_preview_failed_link_preview"};

    static {
        alok alokVar = new alok();
        alokVar.h("messages.sender_send_destination", 54040);
        alokVar.h("messages.msisdn_receiving_rcs_message", 59340);
        alokVar.h("messages.receiving_network_country", 54040);
        alokVar.h("messages.queue_insert_timestamp", 17030);
        alokVar.h("messages.message_report_status", 13020);
        alokVar.h("messages.rcs_expiry", 59890);
        alokVar.h("messages.mms_retrieve_text", 9030);
        alokVar.h("messages.my_identity_foreign_key", 60160);
        alokVar.h("messages.cloud_sync_id", 8500);
        alokVar.h("messages.rcs_message_id_with_text_type", 41040);
        alokVar.h("messages.etouffee_status", 29060);
        alokVar.h("messages.verification_status", 29090);
        alokVar.h("messages.rcs_ui_status", 39000);
        alokVar.h("messages.is_hidden", 30010);
        alokVar.h("messages.rcs_remote_instance", 10002);
        alokVar.h("messages.rcs_file_transfer_session_id", 10004);
        alokVar.h("messages.sms_error_code", 9000);
        alokVar.h("messages.sms_error_desc_map_name", 9000);
        alokVar.h("messages.correlation_id", 9010);
        alokVar.h("messages.cms_id", 31010);
        alokVar.h("messages.cms_last_mod_seq", 37040);
        alokVar.h("messages.web_id", 19020);
        alokVar.h("messages.usage_stats_logging_id", 29100);
        alokVar.h("messages.send_counter", 35030);
        alokVar.h("messages.original_rcs_message_id", 35030);
        alokVar.h("messages.custom_delivery_receipt_mime_type", 37020);
        alokVar.h("messages.custom_delivery_receipt_content", 37020);
        alokVar.h("messages.report_attempt_acounter", 37030);
        alokVar.h("messages.custom_headers", 45020);
        alokVar.h("messages.cms_correlation_id", 46010);
        alokVar.h("messages.group_private_participant", 48030);
        alokVar.h("messages.original_message_id", 48030);
        alokVar.h("messages.awaiting_reverse_sync", 49060);
        alokVar.h("messages.old_sms_message_uri", 49060);
        alokVar.h("messages.draft_id", 56000);
        alokVar.h("messages.result_code", 58040);
        alokVar.h("messages.cms_life_cycle", 58210);
        alokVar.h("messages.fallback_reason", 58710);
        alokVar.h("messages.auto_retry_counter", 58230);
        alokVar.h("messages.can_revoke_before_delivered_with_rcs", 58280);
        alokVar.h("messages.trace_id", 58680);
        alokVar.h("messages.outgoing_delivery_report_status", 58720);
        alokVar.h("messages.outgoing_read_report_status", 58720);
        alokVar.h("messages.xms_transport", 59310);
        alokVar.h("messages.message_original_protocol", 59430);
        alokVar.h("messages.satellite_datagram_id", 59490);
        alokVar.h("messages.encryption_protocol", 60190);
        alokVar.h("messages.message_persistence_id", 60370);
        alokVar.h("message_replies_view.message_id_message_replies", 0);
        alokVar.h("message_replies_view._id_messages", 0);
        alokVar.h("message_replies_view.received_timestamp_messages", 0);
        alokVar.h("message_replies_view._id_participants", 0);
        alokVar.h("message_replies_view.sub_id_participants", 0);
        alokVar.h("message_replies_view.normalized_destination_participants", 0);
        alokVar.h("message_replies_view.display_destination_participants", 0);
        alokVar.h("message_replies_view.full_name_participants", 0);
        alokVar.h("message_replies_view.first_name_participants", 0);
        alokVar.h("message_replies_view._id_parts", 0);
        alokVar.h("message_replies_view.text_parts", 0);
        alokVar.h("message_replies_view.uri_parts", 0);
        alokVar.h("message_replies_view.content_type_parts", 0);
        alokVar.h("message_replies_view.file_name_parts", 0);
        alokVar.h("message_replies_view.duration_parts", 0);
        alokVar.h("message_replies_view.trigger_url_link_preview", 0);
        alokVar.h("message_replies_view.expiration_time_millis_link_preview", 0);
        alokVar.h("message_replies_view.link_title_link_preview", 0);
        alokVar.h("message_replies_view.link_image_url_link_preview", 0);
        alokVar.h("message_replies_view.link_preview_failed_link_preview", 0);
        alokVar.b();
        vom.s();
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.j(true);
        a2.f(true);
        a2.c(true);
        a2.a = "messages._id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.conversation_id";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.c(true);
        a4.d(true);
        a4.a = "messages.sender_id";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.sender_send_destination";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.msisdn_receiving_rcs_message";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "messages.receiving_network_country";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.c(true);
        a8.a = "messages.sent_timestamp";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "messages.queue_insert_timestamp";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.c(true);
        a10.a = "messages.received_timestamp";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "messages.message_protocol";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.c(true);
        a12.a = "messages.message_status";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "messages.message_report_status";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.seen";
        a14.e(true);
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.c(true);
        a15.a = "messages.read";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.c(true);
        a16.a = "messages.sms_message_uri";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_priority";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "messages.sms_message_size";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_subject";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_transaction_id";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "messages.mms_content_location";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "messages.mms_expiry";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 1;
        a23.c(true);
        a23.a = "messages.rcs_expiry";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 4;
        a24.a = "messages.mms_retrieve_text";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "messages.raw_status";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.c(true);
        a26.d(true);
        a26.a = "messages.self_id";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.d(true);
        a27.b = new sbg(8);
        a27.a = "messages.my_identity_foreign_key";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 1;
        a28.a = "messages.retry_start_timestamp";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.a = "messages.cloud_sync_id";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.c(true);
        a30.a = "messages.rcs_message_id_with_text_type";
        a30.e(true);
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "messages.etouffee_status";
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "messages.verification_status";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "messages.rcs_ui_status";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.c(true);
        a34.a = "messages.is_hidden";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 7;
        a35.a = "messages.rcs_remote_instance";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.a = "messages.rcs_file_transfer_session_id";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "messages.sms_error_code";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 4;
        a38.a = "messages.sms_error_desc_map_name";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.a = "messages.correlation_id";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 4;
        a40.j(true);
        a40.c(true);
        a40.a = "messages.cms_id";
        a40.e(true);
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 2;
        a41.a = "messages.cms_last_mod_seq";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 4;
        a42.c(true);
        a42.a = "messages.web_id";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "messages.usage_stats_logging_id";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "messages.send_counter";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 4;
        a45.c(true);
        a45.a = "messages.original_rcs_message_id";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 4;
        a46.a = "messages.custom_delivery_receipt_mime_type";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 5;
        a47.a = "messages.custom_delivery_receipt_content";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "messages.report_attempt_acounter";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 5;
        a49.a = "messages.custom_headers";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 4;
        a50.j(true);
        a50.c(true);
        a50.a = "messages.cms_correlation_id";
        a50.e(true);
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.c(true);
        a51.d(true);
        a51.b = new sbg(9);
        a51.a = "messages.group_private_participant";
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.c(true);
        a52.d(true);
        a52.b = new sbg(10);
        a52.a = "messages.original_message_id";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 1;
        a53.a = "messages.awaiting_reverse_sync";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 4;
        a54.a = "messages.old_sms_message_uri";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 4;
        a55.j(true);
        a55.c(true);
        a55.a = "messages.draft_id";
        a55.e(true);
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 1;
        a56.a = "messages.result_code";
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 1;
        a57.a = "messages.cms_life_cycle";
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.fallback_reason";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.auto_retry_counter";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 2;
        a60.a = "messages.can_revoke_before_delivered_with_rcs";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 5;
        a61.a = "messages.trace_id";
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 1;
        a62.a = "messages.outgoing_delivery_report_status";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.a = "messages.outgoing_read_report_status";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.xms_transport";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 1;
        a65.a = "messages.message_original_protocol";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 4;
        a66.j(true);
        a66.c(true);
        a66.a = "messages.satellite_datagram_id";
        a66.e(true);
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 1;
        a67.a = "messages.encryption_protocol";
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 4;
        a68.j(true);
        a68.c(true);
        a68.a = "messages.message_persistence_id";
        a68.e(true);
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 2;
        a69.j(true);
        a69.i(true);
        a69.c(true);
        a69.d(true);
        a69.b = new sbg(11);
        a69.a = "message_replies_view.message_id_message_replies";
        a69.e(true);
        a69.c = new wsy();
        a69.a();
        agmi a70 = agmk.a();
        a70.d = 2;
        a70.c(true);
        a70.a = "message_replies_view._id_messages";
        a70.c = new wsy();
        a70.a();
        agmi a71 = agmk.a();
        a71.d = 1;
        a71.c(true);
        a71.a = "message_replies_view.received_timestamp_messages";
        a71.c = new wsy();
        a71.a();
        agmi a72 = agmk.a();
        a72.d = 2;
        a72.c(true);
        a72.a = "message_replies_view._id_participants";
        a72.c = new wsy();
        a72.a();
        agmi a73 = agmk.a();
        a73.d = 1;
        a73.c(true);
        a73.a = "message_replies_view.sub_id_participants";
        a73.e(true);
        a73.c = new wsy();
        a73.a();
        agmi a74 = agmk.a();
        a74.d = 4;
        a74.c(true);
        a74.a = "message_replies_view.normalized_destination_participants";
        a74.e(true);
        a74.c = new wsy();
        a74.a();
        agmi a75 = agmk.a();
        a75.d = 4;
        a75.a = "message_replies_view.display_destination_participants";
        a75.c = new wsy();
        a75.a();
        agmi a76 = agmk.a();
        a76.d = 4;
        a76.a = "message_replies_view.full_name_participants";
        a76.c = new wsy();
        a76.a();
        agmi a77 = agmk.a();
        a77.d = 4;
        a77.a = "message_replies_view.first_name_participants";
        a77.c = new wsy();
        a77.a();
        agmi a78 = agmk.a();
        a78.d = 2;
        a78.c(true);
        a78.a = "message_replies_view._id_parts";
        a78.c = new wsy();
        a78.a();
        agmi a79 = agmk.a();
        a79.d = 4;
        a79.a = "message_replies_view.text_parts";
        a79.c = new wsy();
        a79.a();
        agmi a80 = agmk.a();
        a80.d = 4;
        a80.a = "message_replies_view.uri_parts";
        a80.c = new wsy();
        a80.a();
        agmi a81 = agmk.a();
        a81.d = 4;
        a81.c(true);
        a81.a = "message_replies_view.content_type_parts";
        a81.c = new wsy();
        a81.a();
        agmi a82 = agmk.a();
        a82.d = 4;
        a82.a = "message_replies_view.file_name_parts";
        a82.c = new wsy();
        a82.a();
        agmi a83 = agmk.a();
        a83.d = 1;
        a83.a = "message_replies_view.duration_parts";
        a83.c = new wsy();
        a83.a();
        agmi a84 = agmk.a();
        a84.d = 8;
        a84.a = "message_replies_view.parts__ROWID_parts";
        a84.c = new wsy();
        a84.a();
        agmi a85 = agmk.a();
        a85.d = 4;
        a85.i(true);
        a85.a = "message_replies_view.trigger_url_link_preview";
        a85.c = new wsy();
        a85.a();
        agmi a86 = agmk.a();
        a86.d = 2;
        a86.a = "message_replies_view.expiration_time_millis_link_preview";
        a86.c = new wsy();
        a86.a();
        agmi a87 = agmk.a();
        a87.d = 4;
        a87.a = "message_replies_view.link_title_link_preview";
        a87.c = new wsy();
        a87.a();
        agmi a88 = agmk.a();
        a88.d = 4;
        a88.a = "message_replies_view.link_image_url_link_preview";
        a88.c = new wsy();
        a88.a();
        agmi a89 = agmk.a();
        a89.d = 2;
        a89.a = "message_replies_view.link_preview_failed_link_preview";
        a89.c = new wsy();
        a89.a();
    }
}
