package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class scw {
    public static final String[] a = {"messages._id"};

    static {
        new alok().b();
        new alok().b();
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.j(true);
        a2.f(true);
        a2.c(true);
        a2.a = "messages._id";
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.conversation_id";
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.c(true);
        a4.d(true);
        a4.a = "messages.sender_id";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.sender_send_destination";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.msisdn_receiving_rcs_message";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "messages.receiving_network_country";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.c(true);
        a8.a = "messages.sent_timestamp";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "messages.queue_insert_timestamp";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.c(true);
        a10.a = "messages.received_timestamp";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "messages.message_protocol";
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.c(true);
        a12.a = "messages.message_status";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "messages.message_report_status";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.seen";
        a14.e(true);
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.c(true);
        a15.a = "messages.read";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.c(true);
        a16.a = "messages.sms_message_uri";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_priority";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "messages.sms_message_size";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_subject";
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_transaction_id";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "messages.mms_content_location";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "messages.mms_expiry";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 1;
        a23.c(true);
        a23.a = "messages.rcs_expiry";
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 4;
        a24.a = "messages.mms_retrieve_text";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "messages.raw_status";
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.c(true);
        a26.d(true);
        a26.a = "messages.self_id";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.c(true);
        a27.a = "messages.my_identity";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.c(true);
        a28.d(true);
        a28.b = new scs(4);
        a28.a = "messages.my_identity_foreign_key";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "messages.retry_start_timestamp";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.c(true);
        a30.a = "messages.cloud_sync_id";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 7;
        a31.c(true);
        a31.a = "messages.rcs_message_id";
        a31.e(true);
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 4;
        a32.c(true);
        a32.a = "messages.rcs_message_id_with_text_type";
        a32.e(true);
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "messages.etouffee_status";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "messages.verification_status";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "messages.rcs_ui_status";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.c(true);
        a36.a = "messages.is_hidden";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 7;
        a37.a = "messages.rcs_remote_instance";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "messages.rcs_file_transfer_session_id";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.a = "messages.sms_error_code";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 4;
        a40.a = "messages.sms_error_desc_map_name";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.a = "messages.correlation_id";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 4;
        a42.j(true);
        a42.c(true);
        a42.a = "messages.cms_id";
        a42.e(true);
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 2;
        a43.a = "messages.cms_last_mod_seq";
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 4;
        a44.c(true);
        a44.a = "messages.web_id";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "messages.usage_stats_logging_id";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 1;
        a46.a = "messages.send_counter";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.c(true);
        a47.a = "messages.original_rcs_message_id";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 4;
        a48.a = "messages.custom_delivery_receipt_mime_type";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 5;
        a49.a = "messages.custom_delivery_receipt_content";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "messages.report_attempt_acounter";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 5;
        a51.a = "messages.custom_headers";
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 4;
        a52.j(true);
        a52.c(true);
        a52.a = "messages.cms_correlation_id";
        a52.e(true);
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 1;
        a53.c(true);
        a53.d(true);
        a53.b = new scs(5);
        a53.a = "messages.group_private_participant";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.c(true);
        a54.d(true);
        a54.b = new scs(6);
        a54.a = "messages.original_message_id";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 1;
        a55.a = "messages.awaiting_reverse_sync";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 4;
        a56.a = "messages.old_sms_message_uri";
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 4;
        a57.j(true);
        a57.c(true);
        a57.a = "messages.draft_id";
        a57.e(true);
        a57.c = new wsy();
        a57.a();
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.result_code";
        a58.c = new wsy();
        a58.a();
        agmi a59 = agmk.a();
        a59.d = 1;
        a59.a = "messages.cms_life_cycle";
        a59.c = new wsy();
        a59.a();
        agmi a60 = agmk.a();
        a60.d = 1;
        a60.a = "messages.fallback_reason";
        a60.c = new wsy();
        a60.a();
        agmi a61 = agmk.a();
        a61.d = 1;
        a61.a = "messages.auto_retry_counter";
        a61.c = new wsy();
        a61.a();
        agmi a62 = agmk.a();
        a62.d = 2;
        a62.a = "messages.can_revoke_before_delivered_with_rcs";
        a62.c = new wsy();
        a62.a();
        agmi a63 = agmk.a();
        a63.d = 5;
        a63.a = "messages.trace_id";
        a63.c = new wsy();
        a63.a();
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.outgoing_delivery_report_status";
        a64.c = new wsy();
        a64.a();
        agmi a65 = agmk.a();
        a65.d = 1;
        a65.a = "messages.outgoing_read_report_status";
        a65.c = new wsy();
        a65.a();
        agmi a66 = agmk.a();
        a66.d = 1;
        a66.a = "messages.xms_transport";
        a66.c = new wsy();
        a66.a();
        agmi a67 = agmk.a();
        a67.d = 1;
        a67.a = "messages.message_original_protocol";
        a67.c = new wsy();
        a67.a();
        agmi a68 = agmk.a();
        a68.d = 4;
        a68.j(true);
        a68.c(true);
        a68.a = "messages.satellite_datagram_id";
        a68.e(true);
        a68.c = new wsy();
        a68.a();
        agmi a69 = agmk.a();
        a69.d = 1;
        a69.a = "messages.encryption_protocol";
        a69.c = new wsy();
        a69.a();
        agmi a70 = agmk.a();
        a70.d = 4;
        a70.j(true);
        a70.c(true);
        a70.a = "messages.message_persistence_id";
        a70.e(true);
        a70.c = new wsy();
        a70.a();
        agmi a71 = agmk.a();
        a71.d = 2;
        a71.j(true);
        a71.f(true);
        a71.c(true);
        a71.a = "b._id";
        a71.c = new wsy();
        a71.a();
        agmi a72 = agmk.a();
        a72.d = 1;
        a72.c(true);
        a72.d(true);
        a72.a = "b.conversation_id";
        a72.c = new wsy();
        a72.a();
        agmi a73 = agmk.a();
        a73.d = 1;
        a73.c(true);
        a73.d(true);
        a73.a = "b.sender_id";
        a73.c = new wsy();
        a73.a();
        agmi a74 = agmk.a();
        a74.d = 4;
        a74.a = "b.sender_send_destination";
        a74.c = new wsy();
        a74.a();
        agmi a75 = agmk.a();
        a75.d = 4;
        a75.a = "b.msisdn_receiving_rcs_message";
        a75.c = new wsy();
        a75.a();
        agmi a76 = agmk.a();
        a76.d = 4;
        a76.a = "b.receiving_network_country";
        a76.c = new wsy();
        a76.a();
        agmi a77 = agmk.a();
        a77.d = 1;
        a77.c(true);
        a77.a = "b.sent_timestamp";
        a77.c = new wsy();
        a77.a();
        agmi a78 = agmk.a();
        a78.d = 1;
        a78.a = "b.queue_insert_timestamp";
        a78.c = new wsy();
        a78.a();
        agmi a79 = agmk.a();
        a79.d = 1;
        a79.c(true);
        a79.a = "b.received_timestamp";
        a79.c = new wsy();
        a79.a();
        agmi a80 = agmk.a();
        a80.d = 1;
        a80.a = "b.message_protocol";
        a80.c = new wsy();
        a80.a();
        agmi a81 = agmk.a();
        a81.d = 1;
        a81.c(true);
        a81.a = "b.message_status";
        a81.c = new wsy();
        a81.a();
        agmi a82 = agmk.a();
        a82.d = 1;
        a82.a = "b.message_report_status";
        a82.c = new wsy();
        a82.a();
        agmi a83 = agmk.a();
        a83.d = 1;
        a83.c(true);
        a83.a = "b.seen";
        a83.e(true);
        a83.c = new wsy();
        a83.a();
        agmi a84 = agmk.a();
        a84.d = 1;
        a84.c(true);
        a84.a = "b.read";
        a84.c = new wsy();
        a84.a();
        agmi a85 = agmk.a();
        a85.d = 4;
        a85.c(true);
        a85.a = "b.sms_message_uri";
        a85.c = new wsy();
        a85.a();
        agmi a86 = agmk.a();
        a86.d = 1;
        a86.a = "b.sms_priority";
        a86.c = new wsy();
        a86.a();
        agmi a87 = agmk.a();
        a87.d = 1;
        a87.a = "b.sms_message_size";
        a87.c = new wsy();
        a87.a();
        agmi a88 = agmk.a();
        a88.d = 4;
        a88.a = "b.mms_subject";
        a88.c = new wsy();
        a88.a();
        agmi a89 = agmk.a();
        a89.d = 4;
        a89.a = "b.mms_transaction_id";
        a89.c = new wsy();
        a89.a();
        agmi a90 = agmk.a();
        a90.d = 4;
        a90.a = "b.mms_content_location";
        a90.c = new wsy();
        a90.a();
        agmi a91 = agmk.a();
        a91.d = 1;
        a91.a = "b.mms_expiry";
        a91.c = new wsy();
        a91.a();
        agmi a92 = agmk.a();
        a92.d = 1;
        a92.c(true);
        a92.a = "b.rcs_expiry";
        a92.c = new wsy();
        a92.a();
        agmi a93 = agmk.a();
        a93.d = 4;
        a93.a = "b.mms_retrieve_text";
        a93.c = new wsy();
        a93.a();
        agmi a94 = agmk.a();
        a94.d = 1;
        a94.a = "b.raw_status";
        a94.c = new wsy();
        a94.a();
        agmi a95 = agmk.a();
        a95.d = 1;
        a95.c(true);
        a95.d(true);
        a95.a = "b.self_id";
        a95.c = new wsy();
        a95.a();
        agmi a96 = agmk.a();
        a96.d = 4;
        a96.c(true);
        a96.a = "b.my_identity";
        a96.c = new wsy();
        a96.a();
        agmi a97 = agmk.a();
        a97.d = 4;
        a97.c(true);
        a97.d(true);
        a97.b = new scs(0);
        a97.a = "b.my_identity_foreign_key";
        a97.c = new wsy();
        a97.a();
        agmi a98 = agmk.a();
        a98.d = 1;
        a98.a = "b.retry_start_timestamp";
        a98.c = new wsy();
        a98.a();
        agmi a99 = agmk.a();
        a99.d = 4;
        a99.c(true);
        a99.a = "b.cloud_sync_id";
        a99.c = new wsy();
        a99.a();
        agmi a100 = agmk.a();
        a100.d = 7;
        a100.c(true);
        a100.a = "b.rcs_message_id";
        a100.e(true);
        a100.c = new wsy();
        a100.a();
        agmi a101 = agmk.a();
        a101.d = 4;
        a101.c(true);
        a101.a = "b.rcs_message_id_with_text_type";
        a101.e(true);
        a101.c = new wsy();
        a101.a();
        agmi a102 = agmk.a();
        a102.d = 1;
        a102.a = "b.etouffee_status";
        a102.c = new wsy();
        a102.a();
        agmi a103 = agmk.a();
        a103.d = 1;
        a103.a = "b.verification_status";
        a103.c = new wsy();
        a103.a();
        agmi a104 = agmk.a();
        a104.d = 1;
        a104.a = "b.rcs_ui_status";
        a104.c = new wsy();
        a104.a();
        agmi a105 = agmk.a();
        a105.d = 1;
        a105.c(true);
        a105.a = "b.is_hidden";
        a105.c = new wsy();
        a105.a();
        agmi a106 = agmk.a();
        a106.d = 7;
        a106.a = "b.rcs_remote_instance";
        a106.c = new wsy();
        a106.a();
        agmi a107 = agmk.a();
        a107.d = 1;
        a107.a = "b.rcs_file_transfer_session_id";
        a107.c = new wsy();
        a107.a();
        agmi a108 = agmk.a();
        a108.d = 1;
        a108.a = "b.sms_error_code";
        a108.c = new wsy();
        a108.a();
        agmi a109 = agmk.a();
        a109.d = 4;
        a109.a = "b.sms_error_desc_map_name";
        a109.c = new wsy();
        a109.a();
        agmi a110 = agmk.a();
        a110.d = 4;
        a110.a = "b.correlation_id";
        a110.c = new wsy();
        a110.a();
        agmi a111 = agmk.a();
        a111.d = 4;
        a111.j(true);
        a111.c(true);
        a111.a = "b.cms_id";
        a111.e(true);
        a111.c = new wsy();
        a111.a();
        agmi a112 = agmk.a();
        a112.d = 2;
        a112.a = "b.cms_last_mod_seq";
        a112.c = new wsy();
        a112.a();
        agmi a113 = agmk.a();
        a113.d = 4;
        a113.c(true);
        a113.a = "b.web_id";
        a113.c = new wsy();
        a113.a();
        agmi a114 = agmk.a();
        a114.d = 1;
        a114.a = "b.usage_stats_logging_id";
        a114.c = new wsy();
        a114.a();
        agmi a115 = agmk.a();
        a115.d = 1;
        a115.a = "b.send_counter";
        a115.c = new wsy();
        a115.a();
        agmi a116 = agmk.a();
        a116.d = 4;
        a116.c(true);
        a116.a = "b.original_rcs_message_id";
        a116.c = new wsy();
        a116.a();
        agmi a117 = agmk.a();
        a117.d = 4;
        a117.a = "b.custom_delivery_receipt_mime_type";
        a117.c = new wsy();
        a117.a();
        agmi a118 = agmk.a();
        a118.d = 5;
        a118.a = "b.custom_delivery_receipt_content";
        a118.c = new wsy();
        a118.a();
        agmi a119 = agmk.a();
        a119.d = 1;
        a119.a = "b.report_attempt_acounter";
        a119.c = new wsy();
        a119.a();
        agmi a120 = agmk.a();
        a120.d = 5;
        a120.a = "b.custom_headers";
        a120.c = new wsy();
        a120.a();
        agmi a121 = agmk.a();
        a121.d = 4;
        a121.j(true);
        a121.c(true);
        a121.a = "b.cms_correlation_id";
        a121.e(true);
        a121.c = new wsy();
        a121.a();
        agmi a122 = agmk.a();
        a122.d = 1;
        a122.c(true);
        a122.d(true);
        a122.b = new scs(2);
        a122.a = "b.group_private_participant";
        a122.c = new wsy();
        a122.a();
        agmi a123 = agmk.a();
        a123.d = 1;
        a123.c(true);
        a123.d(true);
        a123.b = new scs(3);
        a123.a = "b.original_message_id";
        a123.c = new wsy();
        a123.a();
        agmi a124 = agmk.a();
        a124.d = 1;
        a124.a = "b.awaiting_reverse_sync";
        a124.c = new wsy();
        a124.a();
        agmi a125 = agmk.a();
        a125.d = 4;
        a125.a = "b.old_sms_message_uri";
        a125.c = new wsy();
        a125.a();
        agmi a126 = agmk.a();
        a126.d = 4;
        a126.j(true);
        a126.c(true);
        a126.a = "b.draft_id";
        a126.e(true);
        a126.c = new wsy();
        a126.a();
        agmi a127 = agmk.a();
        a127.d = 1;
        a127.a = "b.result_code";
        a127.c = new wsy();
        a127.a();
        agmi a128 = agmk.a();
        a128.d = 1;
        a128.a = "b.cms_life_cycle";
        a128.c = new wsy();
        a128.a();
        agmi a129 = agmk.a();
        a129.d = 1;
        a129.a = "b.fallback_reason";
        a129.c = new wsy();
        a129.a();
        agmi a130 = agmk.a();
        a130.d = 1;
        a130.a = "b.auto_retry_counter";
        a130.c = new wsy();
        a130.a();
        agmi a131 = agmk.a();
        a131.d = 2;
        a131.a = "b.can_revoke_before_delivered_with_rcs";
        a131.c = new wsy();
        a131.a();
        agmi a132 = agmk.a();
        a132.d = 5;
        a132.a = "b.trace_id";
        a132.c = new wsy();
        a132.a();
        agmi a133 = agmk.a();
        a133.d = 1;
        a133.a = "b.outgoing_delivery_report_status";
        a133.c = new wsy();
        a133.a();
        agmi a134 = agmk.a();
        a134.d = 1;
        a134.a = "b.outgoing_read_report_status";
        a134.c = new wsy();
        a134.a();
        agmi a135 = agmk.a();
        a135.d = 1;
        a135.a = "b.xms_transport";
        a135.c = new wsy();
        a135.a();
        agmi a136 = agmk.a();
        a136.d = 1;
        a136.a = "b.message_original_protocol";
        a136.c = new wsy();
        a136.a();
        agmi a137 = agmk.a();
        a137.d = 4;
        a137.j(true);
        a137.c(true);
        a137.a = "b.satellite_datagram_id";
        a137.e(true);
        a137.c = new wsy();
        a137.a();
        agmi a138 = agmk.a();
        a138.d = 1;
        a138.a = "b.encryption_protocol";
        a138.c = new wsy();
        a138.a();
        agmi a139 = agmk.a();
        a139.d = 4;
        a139.j(true);
        a139.c(true);
        a139.a = "b.message_persistence_id";
        a139.e(true);
        a139.c = new wsy();
        a139.a();
    }
}
