package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sem {
    public static final String[] a = {"messages._id", "messages.conversation_id", "messages.sender_id", "messages.sender_send_destination", "messages.msisdn_receiving_rcs_message", "messages.receiving_network_country", "messages.sent_timestamp", "messages.queue_insert_timestamp", "messages.received_timestamp", "messages.message_protocol", "messages.message_status", "messages.message_report_status", "messages.seen", "messages.read", "messages.sms_message_uri", "messages.sms_priority", "messages.sms_message_size", "messages.mms_subject", "messages.mms_transaction_id", "messages.mms_content_location", "messages.mms_expiry", "messages.rcs_expiry", "messages.mms_retrieve_text", "messages.raw_status", "messages.self_id", "messages.my_identity_foreign_key", "messages.retry_start_timestamp", "messages.cloud_sync_id", "messages.rcs_message_id_with_text_type", "messages.etouffee_status", "messages.verification_status", "messages.rcs_ui_status", "messages.is_hidden", "messages.rcs_remote_instance", "messages.rcs_file_transfer_session_id", "messages.sms_error_code", "messages.sms_error_desc_map_name", "messages.correlation_id", "messages.cms_id", "messages.cms_last_mod_seq", "messages.web_id", "messages.usage_stats_logging_id", "messages.send_counter", "messages.original_rcs_message_id", "messages.custom_delivery_receipt_mime_type", "messages.custom_delivery_receipt_content", "messages.report_attempt_acounter", "messages.custom_headers", "messages.cms_correlation_id", "messages.group_private_participant", "messages.original_message_id", "messages.awaiting_reverse_sync", "messages.old_sms_message_uri", "messages.draft_id", "messages.result_code", "messages.cms_life_cycle", "messages.fallback_reason", "messages.auto_retry_counter", "messages.can_revoke_before_delivered_with_rcs", "messages.trace_id", "messages.outgoing_delivery_report_status", "messages.outgoing_read_report_status", "messages.xms_transport", "messages.message_original_protocol", "messages.satellite_datagram_id", "messages.encryption_protocol", "messages.message_persistence_id", "participants._id", "participants.my_identity_token", "participants.my_identity_token_foreign_key", "participants.sub_id", "participants.sim_slot_id", "participants.normalized_destination", "participants.send_destination", "participants.display_destination", "participants.comparable_destination", "participants.country_code", "participants.recipient_id", "participants.recipient_canonical_address", "participants.full_name", "participants.first_name", "participants.profile_photo_uri", "participants.contact_photo_uri", "participants.contact_id", "participants.lookup_key", "participants.color_palette_index", "participants.color_type", "participants.extended_color", "participants.blocked", "participants.subscription_name", "participants.subscription_color", "participants.contact_destination", "participants.participant_type", "participants.video_reachability", "participants.alias", "participants.is_spam", "participants.is_spam_source", "participants.cms_id", "participants.latest_verification_status", "participants.profile_photo_blob_id", "participants.profile_photo_encryption_key", "participants.directory_id", "participants.is_check_constraint_enabled_via_phenotype", "participants.is_valid_phone_number_data", "participants.duplicate_of", "participants.cms_life_cycle", "participants.norm_ui_status", "participants.last_modified_by_key", "participants.name_source", "participants.photo_source", "participants.profile_photo_user_preference", "participants.contact_metadata", "conversations._id", "conversations.sms_thread_id", "conversations.name", "conversations.name_is_automatic", "conversations.subtitle", "conversations.latest_message_id", "conversations.snippet_text", "conversations.subject_text", "conversations.preview_uri", "conversations.preview_content_type", "conversations.show_draft", "conversations.draft_snippet_text", "conversations.draft_subject_text", "conversations.draft_preview_uri", "conversations.draft_preview_content_type", "conversations.etouffee_default", "conversations.archive_status", "conversations.sort_timestamp", "conversations.last_read_timestamp", "conversations.icon", "conversations.participant_contact_id", "conversations.normalized_participant_contact_id", "conversations.participant_lookup_key", "conversations.normalized_participant_lookup_key", "conversations.participant_normalized_destination", "conversations.participant_comparable_destination", "conversations.current_self_id", "conversations.current_my_identity_foreign_key", "conversations.destination_token", "conversations.participant_count", "conversations.notification_enabled", "conversations.notification_sound_uri", "conversations.notification_vibration", "conversations.include_email_addr", "conversations.sms_service_center", "conversations.participant_id_list", "conversations.normalized_participant_id_list", "conversations.source_type", "conversations.rcs_session_id", "conversations.join_state", "conversations.conv_type", "conversations.send_mode", "conversations.IS_ENTERPRISE", "conversations.has_ea2p_bot_recipient", "conversations.last_interactive_event_timestamp", "conversations.participant_display_destination", "conversations.normalized_participant_display_destination", "conversations.spam_warning_dismiss_status", "conversations.open_count", "conversations.last_logged_scooby_metadata_timestamp", "conversations.delete_timestamp", "conversations.cms_id", "conversations.rcs_group_id", "conversations.rcs_conference_uri", "conversations.tachygram_group_routing_info_token", "conversations.cms_most_recent_read_message_timestamp_ms", "conversations.rcs_subject_change_timestamp_ms", "conversations.rcs_session_allows_revocation", "conversations.rcs_group_capabilities", "conversations.awaiting_reverse_sync", "conversations.duplicate_of", "conversations.new_duplicate_of", "conversations.error_state", "conversations.cms_life_cycle", "conversations.rcs_group_self_msisdn", "conversations.recipient_offline_timestamp_ms", "conversations.rcs_group_last_sync_timestamp", "conversations.has_been_e2ee", "conversations.marked_as_unread", "conversations.custom_theme", "conversations.mms_group_upgrade_status", "conversations.mms_group_upgrade_retries", "conversations.encryption_protocol", "conversations.encryption_id", "conversations.cms_correlation_id"};

    static {
        alok alokVar = new alok();
        alokVar.h("messages.sender_send_destination", 54040);
        alokVar.h("messages.msisdn_receiving_rcs_message", 59340);
        alokVar.h("messages.receiving_network_country", 54040);
        alokVar.h("messages.queue_insert_timestamp", 17030);
        alokVar.h("messages.message_report_status", 13020);
        alokVar.h("messages.rcs_expiry", 59890);
        alokVar.h("messages.mms_retrieve_text", 9030);
        alokVar.h("messages.my_identity_foreign_key", 60160);
        alokVar.h("messages.cloud_sync_id", 8500);
        alokVar.h("messages.rcs_message_id_with_text_type", 41040);
        alokVar.h("messages.etouffee_status", 29060);
        alokVar.h("messages.verification_status", 29090);
        alokVar.h("messages.rcs_ui_status", 39000);
        alokVar.h("messages.is_hidden", 30010);
        alokVar.h("messages.rcs_remote_instance", 10002);
        alokVar.h("messages.rcs_file_transfer_session_id", 10004);
        alokVar.h("messages.sms_error_code", 9000);
        alokVar.h("messages.sms_error_desc_map_name", 9000);
        alokVar.h("messages.correlation_id", 9010);
        alokVar.h("messages.cms_id", 31010);
        alokVar.h("messages.cms_last_mod_seq", 37040);
        alokVar.h("messages.web_id", 19020);
        alokVar.h("messages.usage_stats_logging_id", 29100);
        alokVar.h("messages.send_counter", 35030);
        alokVar.h("messages.original_rcs_message_id", 35030);
        alokVar.h("messages.custom_delivery_receipt_mime_type", 37020);
        alokVar.h("messages.custom_delivery_receipt_content", 37020);
        alokVar.h("messages.report_attempt_acounter", 37030);
        alokVar.h("messages.custom_headers", 45020);
        alokVar.h("messages.cms_correlation_id", 46010);
        alokVar.h("messages.group_private_participant", 48030);
        alokVar.h("messages.original_message_id", 48030);
        alokVar.h("messages.awaiting_reverse_sync", 49060);
        alokVar.h("messages.old_sms_message_uri", 49060);
        alokVar.h("messages.draft_id", 56000);
        alokVar.h("messages.result_code", 58040);
        alokVar.h("messages.cms_life_cycle", 58210);
        alokVar.h("messages.fallback_reason", 58710);
        alokVar.h("messages.auto_retry_counter", 58230);
        alokVar.h("messages.can_revoke_before_delivered_with_rcs", 58280);
        alokVar.h("messages.trace_id", 58680);
        alokVar.h("messages.outgoing_delivery_report_status", 58720);
        alokVar.h("messages.outgoing_read_report_status", 58720);
        alokVar.h("messages.xms_transport", 59310);
        alokVar.h("messages.message_original_protocol", 59430);
        alokVar.h("messages.satellite_datagram_id", 59490);
        alokVar.h("messages.encryption_protocol", 60190);
        alokVar.h("messages.message_persistence_id", 60370);
        alokVar.h("participants.my_identity_token", 59930);
        alokVar.h("participants.my_identity_token_foreign_key", 60160);
        alokVar.h("participants.sim_slot_id", 2000);
        alokVar.h("participants.comparable_destination", 54040);
        alokVar.h("participants.country_code", 54040);
        alokVar.h("participants.recipient_id", 58090);
        alokVar.h("participants.recipient_canonical_address", 58090);
        alokVar.h("participants.contact_photo_uri", 59850);
        alokVar.h("participants.color_type", 1000);
        alokVar.h("participants.extended_color", 10027);
        alokVar.h("participants.subscription_name", 2000);
        alokVar.h("participants.subscription_color", 2000);
        alokVar.h("participants.contact_destination", 4000);
        alokVar.h("participants.participant_type", 12001);
        alokVar.h("participants.video_reachability", 13050);
        alokVar.h("participants.alias", 20060);
        alokVar.h("participants.is_spam", 24060);
        alokVar.h("participants.is_spam_source", 30000);
        alokVar.h("participants.cms_id", 31020);
        alokVar.h("participants.latest_verification_status", 31030);
        alokVar.h("participants.profile_photo_blob_id", 33000);
        alokVar.h("participants.profile_photo_encryption_key", 33060);
        alokVar.h("participants.directory_id", 35010);
        alokVar.h("participants.is_check_constraint_enabled_via_phenotype", 55010);
        alokVar.h("participants.is_valid_phone_number_data", 55010);
        alokVar.h("participants.duplicate_of", 58090);
        alokVar.h("participants.cms_life_cycle", 58210);
        alokVar.h("participants.norm_ui_status", 58620);
        alokVar.h("participants.last_modified_by_key", 59440);
        alokVar.h("participants.name_source", 59550);
        alokVar.h("participants.photo_source", 59550);
        alokVar.h("participants.profile_photo_user_preference", 60060);
        alokVar.h("participants.contact_metadata", 60070);
        alokVar.h("conversations.name_is_automatic", 10012);
        alokVar.h("conversations.subtitle", 59760);
        alokVar.h("conversations.etouffee_default", 29060);
        alokVar.h("conversations.normalized_participant_contact_id", 58090);
        alokVar.h("conversations.normalized_participant_lookup_key", 58090);
        alokVar.h("conversations.participant_comparable_destination", 58090);
        alokVar.h("conversations.current_my_identity_foreign_key", 60160);
        alokVar.h("conversations.destination_token", 60360);
        alokVar.h("conversations.participant_id_list", 8500);
        alokVar.h("conversations.normalized_participant_id_list", 58090);
        alokVar.h("conversations.source_type", 8500);
        alokVar.h("conversations.rcs_session_id", 10000);
        alokVar.h("conversations.join_state", 10006);
        alokVar.h("conversations.conv_type", 10007);
        alokVar.h("conversations.send_mode", 10016);
        alokVar.h("conversations.IS_ENTERPRISE", 10018);
        alokVar.h("conversations.has_ea2p_bot_recipient", 12001);
        alokVar.h("conversations.last_interactive_event_timestamp", 15000);
        alokVar.h("conversations.participant_display_destination", 15010);
        alokVar.h("conversations.normalized_participant_display_destination", 58090);
        alokVar.h("conversations.spam_warning_dismiss_status", 23000);
        alokVar.h("conversations.open_count", 26020);
        alokVar.h("conversations.last_logged_scooby_metadata_timestamp", 28010);
        alokVar.h("conversations.delete_timestamp", 29020);
        alokVar.h("conversations.cms_id", 32000);
        alokVar.h("conversations.rcs_group_id", 40050);
        alokVar.h("conversations.rcs_conference_uri", 40050);
        alokVar.h("conversations.tachygram_group_routing_info_token", 58120);
        alokVar.h("conversations.cms_most_recent_read_message_timestamp_ms", 53030);
        alokVar.h("conversations.rcs_subject_change_timestamp_ms", 46050);
        alokVar.h("conversations.rcs_session_allows_revocation", 48040);
        alokVar.h("conversations.rcs_group_capabilities", 49020);
        alokVar.h("conversations.awaiting_reverse_sync", 49060);
        alokVar.h("conversations.duplicate_of", 58090);
        alokVar.h("conversations.new_duplicate_of", 59130);
        alokVar.h("conversations.error_state", 58140);
        alokVar.h("conversations.cms_life_cycle", 58210);
        alokVar.h("conversations.rcs_group_self_msisdn", 58540);
        alokVar.h("conversations.recipient_offline_timestamp_ms", 58750);
        alokVar.h("conversations.rcs_group_last_sync_timestamp", 58910);
        alokVar.h("conversations.has_been_e2ee", 59210);
        alokVar.h("conversations.marked_as_unread", 59220);
        alokVar.h("conversations.custom_theme", 59820);
        alokVar.h("conversations.mms_group_upgrade_status", 60050);
        alokVar.h("conversations.mms_group_upgrade_retries", 60050);
        alokVar.h("conversations.encryption_protocol", 60180);
        alokVar.h("conversations.encryption_id", 60210);
        alokVar.h("conversations.cms_correlation_id", 60250);
        alokVar.b();
        vom.s();
        agmi a2 = agmk.a();
        a2.k(2);
        a2.j(true);
        a2.f(true);
        a2.c(true);
        a2.b("messages._id");
        a2.h(new wsy());
        a2.a();
        agmi a3 = agmk.a();
        a3.k(1);
        a3.c(true);
        a3.d(true);
        a3.b("messages.conversation_id");
        a3.h(new wsy());
        a3.a();
        agmi a4 = agmk.a();
        a4.k(1);
        a4.c(true);
        a4.d(true);
        a4.b("messages.sender_id");
        a4.h(new wsy());
        a4.a();
        agmi a5 = agmk.a();
        a5.k(4);
        a5.b("messages.sender_send_destination");
        a5.h(new wsy());
        a5.a();
        agmi a6 = agmk.a();
        a6.k(4);
        a6.b("messages.msisdn_receiving_rcs_message");
        a6.h(new wsy());
        a6.a();
        agmi a7 = agmk.a();
        a7.k(4);
        a7.b("messages.receiving_network_country");
        a7.h(new wsy());
        a7.a();
        agmi a8 = agmk.a();
        a8.k(1);
        a8.c(true);
        a8.b("messages.sent_timestamp");
        a8.h(new wsy());
        a8.a();
        agmi a9 = agmk.a();
        a9.k(1);
        a9.b("messages.queue_insert_timestamp");
        a9.h(new wsy());
        a9.a();
        agmi a10 = agmk.a();
        a10.k(1);
        a10.c(true);
        a10.b("messages.received_timestamp");
        a10.h(new wsy());
        a10.a();
        agmi a11 = agmk.a();
        a11.k(1);
        a11.b("messages.message_protocol");
        a11.h(new wsy());
        a11.a();
        agmi a12 = agmk.a();
        a12.k(1);
        a12.c(true);
        a12.b("messages.message_status");
        a12.h(new wsy());
        a12.a();
        agmi a13 = agmk.a();
        a13.k(1);
        a13.b("messages.message_report_status");
        a13.h(new wsy());
        a13.a();
        agmi a14 = agmk.a();
        a14.k(1);
        a14.c(true);
        a14.b("messages.seen");
        a14.e(true);
        a14.h(new wsy());
        a14.a();
        agmi a15 = agmk.a();
        a15.k(1);
        a15.c(true);
        a15.b("messages.read");
        a15.h(new wsy());
        a15.a();
        agmi a16 = agmk.a();
        a16.k(4);
        a16.c(true);
        a16.b("messages.sms_message_uri");
        a16.h(new wsy());
        a16.a();
        agmi a17 = agmk.a();
        a17.k(1);
        a17.b("messages.sms_priority");
        a17.h(new wsy());
        a17.a();
        agmi a18 = agmk.a();
        a18.k(1);
        a18.b("messages.sms_message_size");
        a18.h(new wsy());
        a18.a();
        agmi a19 = agmk.a();
        a19.k(4);
        a19.b("messages.mms_subject");
        a19.h(new wsy());
        a19.a();
        agmi a20 = agmk.a();
        a20.k(4);
        a20.b("messages.mms_transaction_id");
        a20.h(new wsy());
        a20.a();
        agmi a21 = agmk.a();
        a21.k(4);
        a21.b("messages.mms_content_location");
        a21.h(new wsy());
        a21.a();
        agmi a22 = agmk.a();
        a22.k(1);
        a22.b("messages.mms_expiry");
        a22.h(new wsy());
        a22.a();
        agmi a23 = agmk.a();
        a23.k(1);
        a23.c(true);
        a23.b("messages.rcs_expiry");
        a23.h(new wsy());
        a23.a();
        agmi a24 = agmk.a();
        a24.k(4);
        a24.b("messages.mms_retrieve_text");
        a24.h(new wsy());
        a24.a();
        agmi a25 = agmk.a();
        a25.k(1);
        a25.b("messages.raw_status");
        a25.h(new wsy());
        a25.a();
        agmi a26 = agmk.a();
        a26.k(1);
        a26.c(true);
        a26.d(true);
        a26.b("messages.self_id");
        a26.h(new wsy());
        a26.a();
        agmi a27 = agmk.a();
        a27.k(4);
        a27.c(true);
        a27.d(true);
        a27.g(new sdl(6));
        a27.b("messages.my_identity_foreign_key");
        a27.h(new wsy());
        a27.a();
        agmi a28 = agmk.a();
        a28.k(1);
        a28.b("messages.retry_start_timestamp");
        a28.h(new wsy());
        a28.a();
        agmi a29 = agmk.a();
        a29.k(4);
        a29.c(true);
        a29.b("messages.cloud_sync_id");
        a29.h(new wsy());
        a29.a();
        agmi a30 = agmk.a();
        a30.k(4);
        a30.c(true);
        a30.b("messages.rcs_message_id_with_text_type");
        a30.e(true);
        a30.h(new wsy());
        a30.a();
        agmi a31 = agmk.a();
        a31.k(1);
        a31.b("messages.etouffee_status");
        a31.h(new wsy());
        a31.a();
        agmi a32 = agmk.a();
        a32.k(1);
        a32.b("messages.verification_status");
        a32.h(new wsy());
        a32.a();
        agmi a33 = agmk.a();
        a33.k(1);
        a33.b("messages.rcs_ui_status");
        a33.h(new wsy());
        a33.a();
        agmi a34 = agmk.a();
        a34.k(1);
        a34.c(true);
        a34.b("messages.is_hidden");
        a34.h(new wsy());
        a34.a();
        agmi a35 = agmk.a();
        a35.k(7);
        a35.b("messages.rcs_remote_instance");
        a35.h(new wsy());
        a35.a();
        agmi a36 = agmk.a();
        a36.k(1);
        a36.b("messages.rcs_file_transfer_session_id");
        a36.h(new wsy());
        a36.a();
        agmi a37 = agmk.a();
        a37.k(1);
        a37.b("messages.sms_error_code");
        a37.h(new wsy());
        a37.a();
        agmi a38 = agmk.a();
        a38.k(4);
        a38.b("messages.sms_error_desc_map_name");
        a38.h(new wsy());
        a38.a();
        agmi a39 = agmk.a();
        a39.k(4);
        a39.b("messages.correlation_id");
        a39.h(new wsy());
        a39.a();
        agmi a40 = agmk.a();
        a40.k(4);
        a40.j(true);
        a40.c(true);
        a40.b("messages.cms_id");
        a40.e(true);
        a40.h(new wsy());
        a40.a();
        agmi a41 = agmk.a();
        a41.k(2);
        a41.b("messages.cms_last_mod_seq");
        a41.h(new wsy());
        a41.a();
        agmi a42 = agmk.a();
        a42.k(4);
        a42.c(true);
        a42.b("messages.web_id");
        a42.h(new wsy());
        a42.a();
        agmi a43 = agmk.a();
        a43.k(1);
        a43.b("messages.usage_stats_logging_id");
        a43.h(new wsy());
        a43.a();
        agmi a44 = agmk.a();
        a44.k(1);
        a44.b("messages.send_counter");
        a44.h(new wsy());
        a44.a();
        agmi a45 = agmk.a();
        a45.k(4);
        a45.c(true);
        a45.b("messages.original_rcs_message_id");
        a45.h(new wsy());
        a45.a();
        agmi a46 = agmk.a();
        a46.k(4);
        a46.b("messages.custom_delivery_receipt_mime_type");
        a46.h(new wsy());
        a46.a();
        agmi a47 = agmk.a();
        a47.k(5);
        a47.b("messages.custom_delivery_receipt_content");
        a47.h(new wsy());
        a47.a();
        agmi a48 = agmk.a();
        a48.k(1);
        a48.b("messages.report_attempt_acounter");
        a48.h(new wsy());
        a48.a();
        agmi a49 = agmk.a();
        a49.k(5);
        a49.b("messages.custom_headers");
        a49.h(new wsy());
        a49.a();
        agmi a50 = agmk.a();
        a50.k(4);
        a50.j(true);
        a50.c(true);
        a50.b("messages.cms_correlation_id");
        a50.e(true);
        a50.h(new wsy());
        a50.a();
        agmi a51 = agmk.a();
        a51.k(1);
        a51.c(true);
        a51.d(true);
        a51.g(new sdl(7));
        a51.b("messages.group_private_participant");
        a51.h(new wsy());
        a51.a();
        agmi a52 = agmk.a();
        a52.k(1);
        a52.c(true);
        a52.d(true);
        a52.g(new sdl(8));
        a52.b("messages.original_message_id");
        a52.h(new wsy());
        a52.a();
        agmi a53 = agmk.a();
        a53.k(1);
        a53.b("messages.awaiting_reverse_sync");
        a53.h(new wsy());
        a53.a();
        agmi a54 = agmk.a();
        a54.k(4);
        a54.b("messages.old_sms_message_uri");
        a54.h(new wsy());
        a54.a();
        agmi a55 = agmk.a();
        a55.k(4);
        a55.j(true);
        a55.c(true);
        a55.b("messages.draft_id");
        a55.e(true);
        a55.h(new wsy());
        a55.a();
        agmi a56 = agmk.a();
        a56.k(1);
        a56.b("messages.result_code");
        a56.h(new wsy());
        a56.a();
        agmi a57 = agmk.a();
        a57.k(1);
        a57.b("messages.cms_life_cycle");
        a57.h(new wsy());
        a57.a();
        agmi a58 = agmk.a();
        a58.k(1);
        a58.b("messages.fallback_reason");
        a58.h(new wsy());
        a58.a();
        agmi a59 = agmk.a();
        a59.k(1);
        a59.b("messages.auto_retry_counter");
        a59.h(new wsy());
        a59.a();
        agmi a60 = agmk.a();
        a60.k(2);
        a60.b("messages.can_revoke_before_delivered_with_rcs");
        a60.h(new wsy());
        a60.a();
        agmi a61 = agmk.a();
        a61.k(5);
        a61.b("messages.trace_id");
        a61.h(new wsy());
        a61.a();
        agmi a62 = agmk.a();
        a62.k(1);
        a62.b("messages.outgoing_delivery_report_status");
        a62.h(new wsy());
        a62.a();
        agmi a63 = agmk.a();
        a63.k(1);
        a63.b("messages.outgoing_read_report_status");
        a63.h(new wsy());
        a63.a();
        agmi a64 = agmk.a();
        a64.k(1);
        a64.b("messages.xms_transport");
        a64.h(new wsy());
        a64.a();
        agmi a65 = agmk.a();
        a65.k(1);
        a65.b("messages.message_original_protocol");
        a65.h(new wsy());
        a65.a();
        agmi a66 = agmk.a();
        a66.k(4);
        a66.j(true);
        a66.c(true);
        a66.b("messages.satellite_datagram_id");
        a66.e(true);
        a66.h(new wsy());
        a66.a();
        agmi a67 = agmk.a();
        a67.k(1);
        a67.b("messages.encryption_protocol");
        a67.h(new wsy());
        a67.a();
        agmi a68 = agmk.a();
        a68.k(4);
        a68.j(true);
        a68.c(true);
        a68.b("messages.message_persistence_id");
        a68.e(true);
        a68.h(new wsy());
        a68.a();
        agmi a69 = agmk.a();
        a69.k(2);
        a69.j(true);
        a69.f(true);
        a69.c(true);
        a69.b("participants._id");
        a69.h(new wsy());
        a69.a();
        agmi a70 = agmk.a();
        a70.k(4);
        a70.c(true);
        a70.b("participants.my_identity_token");
        a70.h(new wsy());
        a70.a();
        agmi a71 = agmk.a();
        a71.k(4);
        a71.c(true);
        a71.d(true);
        a71.g(new sdl(9));
        a71.b("participants.my_identity_token_foreign_key");
        a71.h(new wsy());
        a71.a();
        agmi a72 = agmk.a();
        a72.k(1);
        a72.c(true);
        a72.b("participants.sub_id");
        a72.e(true);
        a72.h(new wsy());
        a72.a();
        agmi a73 = agmk.a();
        a73.k(1);
        a73.b("participants.sim_slot_id");
        a73.h(new wsy());
        a73.a();
        agmi a74 = agmk.a();
        a74.k(4);
        a74.c(true);
        a74.b("participants.normalized_destination");
        a74.e(true);
        a74.h(new wsy());
        a74.a();
        agmi a75 = agmk.a();
        a75.k(4);
        a75.b("participants.send_destination");
        a75.h(new wsy());
        a75.a();
        agmi a76 = agmk.a();
        a76.k(4);
        a76.b("participants.display_destination");
        a76.h(new wsy());
        a76.a();
        agmi a77 = agmk.a();
        a77.k(4);
        a77.j(true);
        a77.c(true);
        a77.b("participants.comparable_destination");
        a77.e(true);
        a77.h(new wsy());
        a77.a();
        agmi a78 = agmk.a();
        a78.k(4);
        a78.b("participants.country_code");
        a78.h(new wsy());
        a78.a();
        agmi a79 = agmk.a();
        a79.k(2);
        a79.j(true);
        a79.c(true);
        a79.b("participants.recipient_id");
        a79.e(true);
        a79.h(new wsy());
        a79.a();
        agmi a80 = agmk.a();
        a80.k(4);
        a80.b("participants.recipient_canonical_address");
        a80.h(new wsy());
        a80.a();
        agmi a81 = agmk.a();
        a81.k(4);
        a81.b("participants.full_name");
        a81.h(new wsy());
        a81.a();
        agmi a82 = agmk.a();
        a82.k(4);
        a82.b("participants.first_name");
        a82.h(new wsy());
        a82.a();
        agmi a83 = agmk.a();
        a83.k(4);
        a83.b("participants.profile_photo_uri");
        a83.h(new wsy());
        a83.a();
        agmi a84 = agmk.a();
        a84.k(4);
        a84.b("participants.contact_photo_uri");
        a84.h(new wsy());
        a84.a();
        agmi a85 = agmk.a();
        a85.k(1);
        a85.b("participants.contact_id");
        a85.h(new wsy());
        a85.a();
        agmi a86 = agmk.a();
        a86.k(4);
        a86.b("participants.lookup_key");
        a86.h(new wsy());
        a86.a();
        agmi a87 = agmk.a();
        a87.k(1);
        a87.b("participants.color_palette_index");
        a87.h(new wsy());
        a87.a();
        agmi a88 = agmk.a();
        a88.k(1);
        a88.b("participants.color_type");
        a88.h(new wsy());
        a88.a();
        agmi a89 = agmk.a();
        a89.k(1);
        a89.b("participants.extended_color");
        a89.h(new wsy());
        a89.a();
        agmi a90 = agmk.a();
        a90.k(1);
        a90.b("participants.blocked");
        a90.h(new wsy());
        a90.a();
        agmi a91 = agmk.a();
        a91.k(4);
        a91.b("participants.subscription_name");
        a91.h(new wsy());
        a91.a();
        agmi a92 = agmk.a();
        a92.k(1);
        a92.b("participants.subscription_color");
        a92.h(new wsy());
        a92.a();
        agmi a93 = agmk.a();
        a93.k(4);
        a93.b("participants.contact_destination");
        a93.h(new wsy());
        a93.a();
        agmi a94 = agmk.a();
        a94.k(1);
        a94.b("participants.participant_type");
        a94.h(new wsy());
        a94.a();
        agmi a95 = agmk.a();
        a95.k(1);
        a95.b("participants.video_reachability");
        a95.h(new wsy());
        a95.a();
        agmi a96 = agmk.a();
        a96.k(4);
        a96.b("participants.alias");
        a96.h(new wsy());
        a96.a();
        agmi a97 = agmk.a();
        a97.k(1);
        a97.b("participants.is_spam");
        a97.h(new wsy());
        a97.a();
        agmi a98 = agmk.a();
        a98.k(1);
        a98.b("participants.is_spam_source");
        a98.h(new wsy());
        a98.a();
        agmi a99 = agmk.a();
        a99.k(4);
        a99.j(true);
        a99.c(true);
        a99.b("participants.cms_id");
        a99.e(true);
        a99.h(new wsy());
        a99.a();
        agmi a100 = agmk.a();
        a100.k(1);
        a100.b("participants.latest_verification_status");
        a100.h(new wsy());
        a100.a();
        agmi a101 = agmk.a();
        a101.k(4);
        a101.b("participants.profile_photo_blob_id");
        a101.h(new wsy());
        a101.a();
        agmi a102 = agmk.a();
        a102.k(5);
        a102.b("participants.profile_photo_encryption_key");
        a102.h(new wsy());
        a102.a();
        agmi a103 = agmk.a();
        a103.k(1);
        a103.b("participants.directory_id");
        a103.h(new wsy());
        a103.a();
        agmi a104 = agmk.a();
        a104.k(1);
        a104.b("participants.is_check_constraint_enabled_via_phenotype");
        a104.h(new wsy());
        a104.a();
        agmi a105 = agmk.a();
        a105.k(1);
        a105.b("participants.is_valid_phone_number_data");
        a105.h(new wsy());
        a105.a();
        agmi a106 = agmk.a();
        a106.k(2);
        a106.c(true);
        a106.d(true);
        a106.g(new sdl(14));
        a106.b("participants.duplicate_of");
        a106.h(new wsy());
        a106.a();
        agmi a107 = agmk.a();
        a107.k(1);
        a107.b("participants.cms_life_cycle");
        a107.h(new wsy());
        a107.a();
        agmi a108 = agmk.a();
        a108.k(1);
        a108.b("participants.norm_ui_status");
        a108.h(new wsy());
        a108.a();
        agmi a109 = agmk.a();
        a109.k(4);
        a109.b("participants.last_modified_by_key");
        a109.h(new wsy());
        a109.a();
        agmi a110 = agmk.a();
        a110.k(1);
        a110.b("participants.name_source");
        a110.h(new wsy());
        a110.a();
        agmi a111 = agmk.a();
        a111.k(1);
        a111.b("participants.photo_source");
        a111.h(new wsy());
        a111.a();
        agmi a112 = agmk.a();
        a112.k(1);
        a112.b("participants.profile_photo_user_preference");
        a112.h(new wsy());
        a112.a();
        agmi a113 = agmk.a();
        a113.k(5);
        a113.b("participants.contact_metadata");
        a113.h(new wsy());
        a113.a();
        agmi a114 = agmk.a();
        a114.k(2);
        a114.j(true);
        a114.f(true);
        a114.c(true);
        a114.b("conversations._id");
        a114.h(new wsy());
        a114.a();
        agmi a115 = agmk.a();
        a115.k(1);
        a115.c(true);
        a115.b("conversations.sms_thread_id");
        a115.h(new wsy());
        a115.a();
        agmi a116 = agmk.a();
        a116.k(4);
        a116.b("conversations.name");
        a116.h(new wsy());
        a116.a();
        agmi a117 = agmk.a();
        a117.k(2);
        a117.b("conversations.name_is_automatic");
        a117.h(new wsy());
        a117.a();
        agmi a118 = agmk.a();
        a118.k(4);
        a118.b("conversations.subtitle");
        a118.h(new wsy());
        a118.a();
        agmi a119 = agmk.a();
        a119.k(1);
        a119.b("conversations.latest_message_id");
        a119.h(new wsy());
        a119.a();
        agmi a120 = agmk.a();
        a120.k(4);
        a120.b("conversations.snippet_text");
        a120.h(new wsy());
        a120.a();
        agmi a121 = agmk.a();
        a121.k(4);
        a121.b("conversations.subject_text");
        a121.h(new wsy());
        a121.a();
        agmi a122 = agmk.a();
        a122.k(4);
        a122.b("conversations.preview_uri");
        a122.h(new wsy());
        a122.a();
        agmi a123 = agmk.a();
        a123.k(4);
        a123.b("conversations.preview_content_type");
        a123.h(new wsy());
        a123.a();
        agmi a124 = agmk.a();
        a124.k(1);
        a124.b("conversations.show_draft");
        a124.h(new wsy());
        a124.a();
        agmi a125 = agmk.a();
        a125.k(4);
        a125.b("conversations.draft_snippet_text");
        a125.h(new wsy());
        a125.a();
        agmi a126 = agmk.a();
        a126.k(4);
        a126.b("conversations.draft_subject_text");
        a126.h(new wsy());
        a126.a();
        agmi a127 = agmk.a();
        a127.k(4);
        a127.b("conversations.draft_preview_uri");
        a127.h(new wsy());
        a127.a();
        agmi a128 = agmk.a();
        a128.k(4);
        a128.b("conversations.draft_preview_content_type");
        a128.h(new wsy());
        a128.a();
        agmi a129 = agmk.a();
        a129.k(1);
        a129.b("conversations.etouffee_default");
        a129.h(new wsy());
        a129.a();
        agmi a130 = agmk.a();
        a130.k(1);
        a130.c(true);
        a130.b("conversations.archive_status");
        a130.h(new wsy());
        a130.a();
        agmi a131 = agmk.a();
        a131.k(1);
        a131.c(true);
        a131.b("conversations.sort_timestamp");
        a131.h(new wsy());
        a131.a();
        agmi a132 = agmk.a();
        a132.k(1);
        a132.b("conversations.last_read_timestamp");
        a132.h(new wsy());
        a132.a();
        agmi a133 = agmk.a();
        a133.k(4);
        a133.b("conversations.icon");
        a133.h(new wsy());
        a133.a();
        agmi a134 = agmk.a();
        a134.k(1);
        a134.b("conversations.participant_contact_id");
        a134.h(new wsy());
        a134.a();
        agmi a135 = agmk.a();
        a135.k(1);
        a135.b("conversations.normalized_participant_contact_id");
        a135.h(new wsy());
        a135.a();
        agmi a136 = agmk.a();
        a136.k(4);
        a136.b("conversations.participant_lookup_key");
        a136.h(new wsy());
        a136.a();
        agmi a137 = agmk.a();
        a137.k(4);
        a137.b("conversations.normalized_participant_lookup_key");
        a137.h(new wsy());
        a137.a();
        agmi a138 = agmk.a();
        a138.k(4);
        a138.c(true);
        a138.b("conversations.participant_normalized_destination");
        a138.h(new wsy());
        a138.a();
        agmi a139 = agmk.a();
        a139.k(4);
        a139.j(true);
        a139.c(true);
        a139.b("conversations.participant_comparable_destination");
        a139.e(true);
        a139.h(new wsy());
        a139.a();
        agmi a140 = agmk.a();
        a140.k(4);
        a140.b("conversations.current_self_id");
        a140.h(new wsy());
        a140.a();
        agmi a141 = agmk.a();
        a141.k(4);
        a141.c(true);
        a141.d(true);
        a141.g(new sdl(10));
        a141.b("conversations.current_my_identity_foreign_key");
        a141.h(new wsy());
        a141.a();
        agmi a142 = agmk.a();
        a142.k(4);
        a142.c(true);
        a142.d(true);
        a142.g(new sdl(11));
        a142.b("conversations.destination_token");
        a142.h(new wsy());
        a142.a();
        agmi a143 = agmk.a();
        a143.k(1);
        a143.b("conversations.participant_count");
        a143.h(new wsy());
        a143.a();
        agmi a144 = agmk.a();
        a144.k(1);
        a144.b("conversations.notification_enabled");
        a144.h(new wsy());
        a144.a();
        agmi a145 = agmk.a();
        a145.k(4);
        a145.b("conversations.notification_sound_uri");
        a145.h(new wsy());
        a145.a();
        agmi a146 = agmk.a();
        a146.k(1);
        a146.b("conversations.notification_vibration");
        a146.h(new wsy());
        a146.a();
        agmi a147 = agmk.a();
        a147.k(1);
        a147.b("conversations.include_email_addr");
        a147.h(new wsy());
        a147.a();
        agmi a148 = agmk.a();
        a148.k(4);
        a148.b("conversations.sms_service_center");
        a148.h(new wsy());
        a148.a();
        agmi a149 = agmk.a();
        a149.k(4);
        a149.b("conversations.participant_id_list");
        a149.h(new wsy());
        a149.a();
        agmi a150 = agmk.a();
        a150.k(4);
        a150.j(true);
        a150.c(true);
        a150.b("conversations.normalized_participant_id_list");
        a150.e(true);
        a150.h(new wsy());
        a150.a();
        agmi a151 = agmk.a();
        a151.k(1);
        a151.b("conversations.source_type");
        a151.h(new wsy());
        a151.a();
        agmi a152 = agmk.a();
        a152.k(1);
        a152.c(true);
        a152.b("conversations.rcs_session_id");
        a152.h(new wsy());
        a152.a();
        agmi a153 = agmk.a();
        a153.k(1);
        a153.b("conversations.join_state");
        a153.h(new wsy());
        a153.a();
        agmi a154 = agmk.a();
        a154.k(1);
        a154.b("conversations.conv_type");
        a154.h(new wsy());
        a154.a();
        agmi a155 = agmk.a();
        a155.k(1);
        a155.b("conversations.send_mode");
        a155.h(new wsy());
        a155.a();
        agmi a156 = agmk.a();
        a156.k(1);
        a156.b("conversations.IS_ENTERPRISE");
        a156.h(new wsy());
        a156.a();
        agmi a157 = agmk.a();
        a157.k(1);
        a157.b("conversations.has_ea2p_bot_recipient");
        a157.h(new wsy());
        a157.a();
        agmi a158 = agmk.a();
        a158.k(1);
        a158.b("conversations.last_interactive_event_timestamp");
        a158.h(new wsy());
        a158.a();
        agmi a159 = agmk.a();
        a159.k(4);
        a159.b("conversations.participant_display_destination");
        a159.h(new wsy());
        a159.a();
        agmi a160 = agmk.a();
        a160.k(4);
        a160.b("conversations.normalized_participant_display_destination");
        a160.h(new wsy());
        a160.a();
        agmi a161 = agmk.a();
        a161.k(1);
        a161.b("conversations.spam_warning_dismiss_status");
        a161.h(new wsy());
        a161.a();
        agmi a162 = agmk.a();
        a162.k(1);
        a162.b("conversations.open_count");
        a162.h(new wsy());
        a162.a();
        agmi a163 = agmk.a();
        a163.k(1);
        a163.b("conversations.last_logged_scooby_metadata_timestamp");
        a163.h(new wsy());
        a163.a();
        agmi a164 = agmk.a();
        a164.k(1);
        a164.c(true);
        a164.b("conversations.delete_timestamp");
        a164.h(new wsy());
        a164.a();
        agmi a165 = agmk.a();
        a165.k(4);
        a165.j(true);
        a165.c(true);
        a165.b("conversations.cms_id");
        a165.e(true);
        a165.h(new wsy());
        a165.a();
        agmi a166 = agmk.a();
        a166.k(4);
        a166.c(true);
        a166.b("conversations.rcs_group_id");
        a166.h(new wsy());
        a166.a();
        agmi a167 = agmk.a();
        a167.k(4);
        a167.b("conversations.rcs_conference_uri");
        a167.h(new wsy());
        a167.a();
        agmi a168 = agmk.a();
        a168.k(5);
        a168.b("conversations.tachygram_group_routing_info_token");
        a168.h(new wsy());
        a168.a();
        agmi a169 = agmk.a();
        a169.k(1);
        a169.b("conversations.cms_most_recent_read_message_timestamp_ms");
        a169.h(new wsy());
        a169.a();
        agmi a170 = agmk.a();
        a170.k(2);
        a170.b("conversations.rcs_subject_change_timestamp_ms");
        a170.h(new wsy());
        a170.a();
        agmi a171 = agmk.a();
        a171.k(1);
        a171.b("conversations.rcs_session_allows_revocation");
        a171.h(new wsy());
        a171.a();
        agmi a172 = agmk.a();
        a172.k(2);
        a172.b("conversations.rcs_group_capabilities");
        a172.h(new wsy());
        a172.a();
        agmi a173 = agmk.a();
        a173.k(1);
        a173.b("conversations.awaiting_reverse_sync");
        a173.h(new wsy());
        a173.a();
        agmi a174 = agmk.a();
        a174.k(2);
        a174.c(true);
        a174.d(true);
        a174.g(new sdl(12));
        a174.b("conversations.duplicate_of");
        a174.h(new wsy());
        a174.a();
        agmi a175 = agmk.a();
        a175.k(2);
        a175.c(true);
        a175.d(true);
        a175.g(new sdl(13));
        a175.b("conversations.new_duplicate_of");
        a175.h(new wsy());
        a175.a();
        agmi a176 = agmk.a();
        a176.k(1);
        a176.b("conversations.error_state");
        a176.h(new wsy());
        a176.a();
        agmi a177 = agmk.a();
        a177.k(1);
        a177.b("conversations.cms_life_cycle");
        a177.h(new wsy());
        a177.a();
        agmi a178 = agmk.a();
        a178.k(4);
        a178.b("conversations.rcs_group_self_msisdn");
        a178.h(new wsy());
        a178.a();
        agmi a179 = agmk.a();
        a179.k(2);
        a179.b("conversations.recipient_offline_timestamp_ms");
        a179.h(new wsy());
        a179.a();
        agmi a180 = agmk.a();
        a180.k(2);
        a180.b("conversations.rcs_group_last_sync_timestamp");
        a180.h(new wsy());
        a180.a();
        agmi a181 = agmk.a();
        a181.k(1);
        a181.b("conversations.has_been_e2ee");
        a181.h(new wsy());
        a181.a();
        agmi a182 = agmk.a();
        a182.k(1);
        a182.b("conversations.marked_as_unread");
        a182.h(new wsy());
        a182.a();
        agmi a183 = agmk.a();
        a183.k(5);
        a183.b("conversations.custom_theme");
        a183.h(new wsy());
        a183.a();
        agmi a184 = agmk.a();
        a184.k(2);
        a184.b("conversations.mms_group_upgrade_status");
        a184.h(new wsy());
        a184.a();
        agmi a185 = agmk.a();
        a185.k(2);
        a185.b("conversations.mms_group_upgrade_retries");
        a185.h(new wsy());
        a185.a();
        agmi a186 = agmk.a();
        a186.k(2);
        a186.b("conversations.encryption_protocol");
        a186.h(new wsy());
        a186.a();
        agmi a187 = agmk.a();
        a187.k(4);
        a187.b("conversations.encryption_id");
        a187.h(new wsy());
        a187.a();
        agmi a188 = agmk.a();
        a188.k(4);
        a188.j(true);
        a188.c(true);
        a188.b("conversations.cms_correlation_id");
        a188.e(true);
        a188.h(new wsy());
        a188.a();
    }
}
