package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class smu {
    public final smv A;
    public final smv B;
    public final smv C;
    public final smv D;
    public final smv E;
    public final smv F;
    public final smv G;
    public final smv H;
    public final smv I;
    public final smv J;
    public final smv K;
    public final smv L;
    public final smv M;
    public final smv N;
    public final smv O;
    public final smv P;
    public final smv Q;
    public final smv R;
    public final smv S;
    public final smv T;
    public final smv U;
    public final smv V;
    public final smv W;
    public final smv X;
    public final smv Y;
    public final smv Z;
    public final smv a;
    public final smv aa;
    public final smv ab;
    public final smv ac;
    public final smv ad;
    public final smv ae;
    public final smv af;
    public final smv ag;
    public final smv ah;
    public final smv ai;
    public final smv aj;
    public final smv ak;
    public final smv al;
    public final smv am;
    public final smv an;
    public final smv ao;
    public final smv ap;
    public final smv aq;
    public final smv ar;
    public final smv as;
    public final smv at;
    public final smv au;
    public final smv av;
    public final smv aw;
    public final smv[] ax;
    public final smv b;
    public final smv c;
    public final smv d;
    public final smv e;
    public final smv f;
    public final smv g;
    public final smv h;
    public final smv i;
    public final smv j;
    public final smv k;
    public final smv l;
    public final smv m;
    public final smv n;
    public final smv o;
    public final smv p;
    public final smv q;
    public final smv r;
    public final smv s;
    public final smv t;
    public final smv u;
    public final smv v;
    public final smv w;
    public final smv x;
    public final smv y;
    public final smv z;

    public smu() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "conversations._id";
        a.c = new wsy();
        smv smvVar = new smv(a.a());
        this.a = smvVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.a = "conversations.sms_thread_id";
        a2.c = new wsy();
        smv smvVar2 = new smv(a2.a());
        this.b = smvVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "conversations.name";
        a3.c = new wsy();
        smv smvVar3 = new smv(a3.a());
        this.c = smvVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "conversations.name_is_automatic";
        a4.c = new wsy();
        smv smvVar4 = new smv(a4.a());
        this.d = smvVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "conversations.subtitle";
        a5.c = new wsy();
        smv smvVar5 = new smv(a5.a());
        this.e = smvVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.a = "conversations.latest_message_id";
        a6.c = new wsy();
        smv smvVar6 = new smv(a6.a());
        this.f = smvVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "conversations.snippet_text";
        a7.c = new wsy();
        smv smvVar7 = new smv(a7.a());
        this.g = smvVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "conversations.subject_text";
        a8.c = new wsy();
        smv smvVar8 = new smv(a8.a());
        this.h = smvVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "conversations.preview_uri";
        a9.c = new wsy();
        smv smvVar9 = new smv(a9.a());
        this.i = smvVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "conversations.preview_content_type";
        a10.c = new wsy();
        smv smvVar10 = new smv(a10.a());
        this.j = smvVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "conversations.show_draft";
        a11.c = new wsy();
        smv smvVar11 = new smv(a11.a());
        this.k = smvVar11;
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "conversations.draft_snippet_text";
        a12.c = new wsy();
        smv smvVar12 = new smv(a12.a());
        this.l = smvVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "conversations.draft_subject_text";
        a13.c = new wsy();
        smv smvVar13 = new smv(a13.a());
        this.m = smvVar13;
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.a = "conversations.draft_preview_uri";
        a14.c = new wsy();
        smv smvVar14 = new smv(a14.a());
        this.n = smvVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "conversations.draft_preview_content_type";
        a15.c = new wsy();
        smv smvVar15 = new smv(a15.a());
        this.o = smvVar15;
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "conversations.etouffee_default";
        a16.c = new wsy();
        smv smvVar16 = new smv(a16.a());
        this.p = smvVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.c(true);
        a17.a = "conversations.archive_status";
        a17.c = new wsy();
        smv smvVar17 = new smv(a17.a());
        this.q = smvVar17;
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.c(true);
        a18.a = "conversations.sort_timestamp";
        a18.c = new wsy();
        smv smvVar18 = new smv(a18.a());
        this.r = smvVar18;
        agmi a19 = agmk.a();
        a19.d = 1;
        a19.a = "conversations.last_read_timestamp";
        a19.c = new wsy();
        smv smvVar19 = new smv(a19.a());
        this.s = smvVar19;
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "conversations.icon";
        a20.c = new wsy();
        smv smvVar20 = new smv(a20.a());
        this.t = smvVar20;
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.a = "conversations.participant_contact_id";
        a21.c = new wsy();
        smv smvVar21 = new smv(a21.a());
        this.u = smvVar21;
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "conversations.normalized_participant_contact_id";
        a22.c = new wsy();
        smv smvVar22 = new smv(a22.a());
        this.v = smvVar22;
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "conversations.participant_lookup_key";
        a23.c = new wsy();
        smv smvVar23 = new smv(a23.a());
        this.w = smvVar23;
        agmi a24 = agmk.a();
        a24.d = 4;
        a24.a = "conversations.normalized_participant_lookup_key";
        a24.c = new wsy();
        smv smvVar24 = new smv(a24.a());
        this.x = smvVar24;
        agmi a25 = agmk.a();
        a25.d = 4;
        a25.c(true);
        a25.a = "conversations.participant_normalized_destination";
        a25.c = new wsy();
        smv smvVar25 = new smv(a25.a());
        this.y = smvVar25;
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.j(true);
        a26.c(true);
        a26.a = "conversations.participant_comparable_destination";
        a26.e(true);
        a26.c = new wsy();
        smv smvVar26 = new smv(a26.a());
        this.z = smvVar26;
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.a = "conversations.current_self_id";
        a27.c = new wsy();
        smv smvVar27 = new smv(a27.a());
        this.A = smvVar27;
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.c(true);
        a28.d(true);
        a28.b = new sms(3);
        a28.a = "conversations.current_my_identity_foreign_key";
        a28.c = new wsy();
        smv smvVar28 = new smv(a28.a());
        this.B = smvVar28;
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.d(true);
        a29.b = new sms(4);
        a29.a = "conversations.destination_token";
        a29.c = new wsy();
        smv smvVar29 = new smv(a29.a());
        this.C = smvVar29;
        agmi a30 = agmk.a();
        a30.d = 1;
        a30.a = "conversations.participant_count";
        a30.c = new wsy();
        smv smvVar30 = new smv(a30.a());
        this.D = smvVar30;
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "conversations.notification_enabled";
        a31.c = new wsy();
        smv smvVar31 = new smv(a31.a());
        this.E = smvVar31;
        agmi a32 = agmk.a();
        a32.d = 4;
        a32.a = "conversations.notification_sound_uri";
        a32.c = new wsy();
        smv smvVar32 = new smv(a32.a());
        this.F = smvVar32;
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "conversations.notification_vibration";
        a33.c = new wsy();
        smv smvVar33 = new smv(a33.a());
        this.G = smvVar33;
        agmi a34 = agmk.a();
        a34.d = 1;
        a34.a = "conversations.include_email_addr";
        a34.c = new wsy();
        smv smvVar34 = new smv(a34.a());
        this.H = smvVar34;
        agmi a35 = agmk.a();
        a35.d = 4;
        a35.a = "conversations.sms_service_center";
        a35.c = new wsy();
        smv smvVar35 = new smv(a35.a());
        this.I = smvVar35;
        agmi a36 = agmk.a();
        a36.d = 4;
        a36.a = "conversations.participant_id_list";
        a36.c = new wsy();
        smv smvVar36 = new smv(a36.a());
        this.J = smvVar36;
        agmi a37 = agmk.a();
        a37.d = 4;
        a37.j(true);
        a37.c(true);
        a37.a = "conversations.normalized_participant_id_list";
        a37.e(true);
        a37.c = new wsy();
        smv smvVar37 = new smv(a37.a());
        this.K = smvVar37;
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "conversations.source_type";
        a38.c = new wsy();
        smv smvVar38 = new smv(a38.a());
        this.L = smvVar38;
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.c(true);
        a39.a = "conversations.rcs_session_id";
        a39.c = new wsy();
        smv smvVar39 = new smv(a39.a());
        this.M = smvVar39;
        agmi a40 = agmk.a();
        a40.d = 1;
        a40.a = "conversations.join_state";
        a40.c = new wsy();
        smv smvVar40 = new smv(a40.a());
        this.N = smvVar40;
        agmi a41 = agmk.a();
        a41.d = 1;
        a41.a = "conversations.conv_type";
        a41.c = new wsy();
        smv smvVar41 = new smv(a41.a());
        this.O = smvVar41;
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "conversations.send_mode";
        a42.c = new wsy();
        smv smvVar42 = new smv(a42.a());
        this.P = smvVar42;
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "conversations.IS_ENTERPRISE";
        a43.c = new wsy();
        smv smvVar43 = new smv(a43.a());
        this.Q = smvVar43;
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "conversations.has_ea2p_bot_recipient";
        a44.c = new wsy();
        smv smvVar44 = new smv(a44.a());
        this.R = smvVar44;
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "conversations.last_interactive_event_timestamp";
        a45.c = new wsy();
        smv smvVar45 = new smv(a45.a());
        this.S = smvVar45;
        agmi a46 = agmk.a();
        a46.d = 4;
        a46.a = "conversations.participant_display_destination";
        a46.c = new wsy();
        smv smvVar46 = new smv(a46.a());
        this.T = smvVar46;
        agmi a47 = agmk.a();
        a47.d = 4;
        a47.a = "conversations.normalized_participant_display_destination";
        a47.c = new wsy();
        smv smvVar47 = new smv(a47.a());
        this.U = smvVar47;
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "conversations.spam_warning_dismiss_status";
        a48.c = new wsy();
        smv smvVar48 = new smv(a48.a());
        this.V = smvVar48;
        agmi a49 = agmk.a();
        a49.d = 1;
        a49.a = "conversations.open_count";
        a49.c = new wsy();
        smv smvVar49 = new smv(a49.a());
        this.W = smvVar49;
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "conversations.last_logged_scooby_metadata_timestamp";
        a50.c = new wsy();
        smv smvVar50 = new smv(a50.a());
        this.X = smvVar50;
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.c(true);
        a51.a = "conversations.delete_timestamp";
        a51.c = new wsy();
        smv smvVar51 = new smv(a51.a());
        this.Y = smvVar51;
        agmi a52 = agmk.a();
        a52.d = 4;
        a52.j(true);
        a52.c(true);
        a52.a = "conversations.cms_id";
        a52.e(true);
        a52.c = new wsy();
        smv smvVar52 = new smv(a52.a());
        this.Z = smvVar52;
        agmi a53 = agmk.a();
        a53.d = 4;
        a53.c(true);
        a53.a = "conversations.rcs_group_id";
        a53.c = new wsy();
        smv smvVar53 = new smv(a53.a());
        this.aa = smvVar53;
        agmi a54 = agmk.a();
        a54.d = 4;
        a54.a = "conversations.rcs_conference_uri";
        a54.c = new wsy();
        smv smvVar54 = new smv(a54.a());
        this.ab = smvVar54;
        agmi a55 = agmk.a();
        a55.d = 5;
        a55.a = "conversations.tachygram_group_routing_info_token";
        a55.c = new wsy();
        smv smvVar55 = new smv(a55.a());
        this.ac = smvVar55;
        agmi a56 = agmk.a();
        a56.d = 1;
        a56.a = "conversations.cms_most_recent_read_message_timestamp_ms";
        a56.c = new wsy();
        smv smvVar56 = new smv(a56.a());
        this.ad = smvVar56;
        agmi a57 = agmk.a();
        a57.d = 2;
        a57.a = "conversations.rcs_subject_change_timestamp_ms";
        a57.c = new wsy();
        smv smvVar57 = new smv(a57.a());
        this.ae = smvVar57;
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "conversations.rcs_session_allows_revocation";
        a58.c = new wsy();
        smv smvVar58 = new smv(a58.a());
        this.af = smvVar58;
        agmi a59 = agmk.a();
        a59.d = 2;
        a59.a = "conversations.rcs_group_capabilities";
        a59.c = new wsy();
        smv smvVar59 = new smv(a59.a());
        this.ag = smvVar59;
        agmi a60 = agmk.a();
        a60.d = 1;
        a60.a = "conversations.awaiting_reverse_sync";
        a60.c = new wsy();
        smv smvVar60 = new smv(a60.a());
        this.ah = smvVar60;
        agmi a61 = agmk.a();
        a61.d = 2;
        a61.c(true);
        a61.d(true);
        a61.b = new sms(5);
        a61.a = "conversations.duplicate_of";
        a61.c = new wsy();
        smv smvVar61 = new smv(a61.a());
        this.ai = smvVar61;
        agmi a62 = agmk.a();
        a62.d = 2;
        a62.c(true);
        a62.d(true);
        a62.b = new sms(6);
        a62.a = "conversations.new_duplicate_of";
        a62.c = new wsy();
        smv smvVar62 = new smv(a62.a());
        this.aj = smvVar62;
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.a = "conversations.error_state";
        a63.c = new wsy();
        smv smvVar63 = new smv(a63.a());
        this.ak = smvVar63;
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "conversations.cms_life_cycle";
        a64.c = new wsy();
        smv smvVar64 = new smv(a64.a());
        this.al = smvVar64;
        agmi a65 = agmk.a();
        a65.d = 4;
        a65.a = "conversations.rcs_group_self_msisdn";
        a65.c = new wsy();
        smv smvVar65 = new smv(a65.a());
        this.am = smvVar65;
        agmi a66 = agmk.a();
        a66.d = 2;
        a66.a = "conversations.recipient_offline_timestamp_ms";
        a66.c = new wsy();
        smv smvVar66 = new smv(a66.a());
        this.an = smvVar66;
        agmi a67 = agmk.a();
        a67.d = 2;
        a67.a = "conversations.rcs_group_last_sync_timestamp";
        a67.c = new wsy();
        smv smvVar67 = new smv(a67.a());
        this.ao = smvVar67;
        agmi a68 = agmk.a();
        a68.d = 1;
        a68.a = "conversations.has_been_e2ee";
        a68.c = new wsy();
        smv smvVar68 = new smv(a68.a());
        this.ap = smvVar68;
        agmi a69 = agmk.a();
        a69.d = 1;
        a69.a = "conversations.marked_as_unread";
        a69.c = new wsy();
        smv smvVar69 = new smv(a69.a());
        this.aq = smvVar69;
        agmi a70 = agmk.a();
        a70.d = 5;
        a70.a = "conversations.custom_theme";
        a70.c = new wsy();
        smv smvVar70 = new smv(a70.a());
        this.ar = smvVar70;
        agmi a71 = agmk.a();
        a71.d = 2;
        a71.a = "conversations.mms_group_upgrade_status";
        a71.c = new wsy();
        smv smvVar71 = new smv(a71.a());
        this.as = smvVar71;
        agmi a72 = agmk.a();
        a72.d = 2;
        a72.a = "conversations.mms_group_upgrade_retries";
        a72.c = new wsy();
        smv smvVar72 = new smv(a72.a());
        this.at = smvVar72;
        agmi a73 = agmk.a();
        a73.d = 2;
        a73.a = "conversations.encryption_protocol";
        a73.c = new wsy();
        smv smvVar73 = new smv(a73.a());
        this.au = smvVar73;
        agmi a74 = agmk.a();
        a74.d = 4;
        a74.a = "conversations.encryption_id";
        a74.c = new wsy();
        smv smvVar74 = new smv(a74.a());
        this.av = smvVar74;
        agmi a75 = agmk.a();
        a75.d = 4;
        a75.j(true);
        a75.c(true);
        a75.a = "conversations.cms_correlation_id";
        a75.e(true);
        a75.c = new wsy();
        smv smvVar75 = new smv(a75.a());
        this.aw = smvVar75;
        this.ax = new smv[]{smvVar, smvVar2, smvVar3, smvVar4, smvVar5, smvVar6, smvVar7, smvVar8, smvVar9, smvVar10, smvVar11, smvVar12, smvVar13, smvVar14, smvVar15, smvVar16, smvVar17, smvVar18, smvVar19, smvVar20, smvVar21, smvVar22, smvVar23, smvVar24, smvVar25, smvVar26, smvVar27, smvVar28, smvVar29, smvVar30, smvVar31, smvVar32, smvVar33, smvVar34, smvVar35, smvVar36, smvVar37, smvVar38, smvVar39, smvVar40, smvVar41, smvVar42, smvVar43, smvVar44, smvVar45, smvVar46, smvVar47, smvVar48, smvVar49, smvVar50, smvVar51, smvVar52, smvVar53, smvVar54, smvVar55, smvVar56, smvVar57, smvVar58, smvVar59, smvVar60, smvVar61, smvVar62, smvVar63, smvVar64, smvVar65, smvVar66, smvVar67, smvVar68, smvVar69, smvVar70, smvVar71, smvVar72, smvVar73, smvVar74, smvVar75};
    }
}
