package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class soi {
    public final soj a;
    public final soj b;
    public final soj c;
    public final soj d;
    public final soj e;
    public final soj f;
    public final soj g;
    public final soj h;
    public final soj i;
    public final soj j;
    public final soj k;
    public final soj l;
    public final soj m;
    public final soj n;
    public final soj o;
    public final soj p;
    public final soj q;
    public final soj r;
    public final soj s;
    public final soj t;
    public final soj u;
    public final soj v;
    final soj[] w;

    public soi() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "desktop._id";
        a.c = new wsy();
        soj sojVar = new soj(a.a());
        this.a = sojVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.i(true);
        a2.a = "desktop.desktop_id";
        a2.c = new wsy();
        soj sojVar2 = new soj(a2.a());
        this.b = sojVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "desktop.last_connection_time";
        a3.c = new wsy();
        soj sojVar3 = new soj(a3.a());
        this.c = sojVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "desktop.last_wakeup_time";
        a4.c = new wsy();
        soj sojVar4 = new soj(a4.a());
        this.d = sojVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "desktop.wakeup_attempts_count";
        a5.c = new wsy();
        soj sojVar5 = new soj(a5.a());
        this.e = sojVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.i(true);
        a6.a = "desktop.fingerprint";
        a6.c = new wsy();
        soj sojVar6 = new soj(a6.a());
        this.f = sojVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "desktop.force_refresh";
        a7.c = new wsy();
        soj sojVar7 = new soj(a7.a());
        this.g = sojVar7;
        agmi a8 = agmk.a();
        a8.d = 5;
        a8.a = "desktop.client_info";
        a8.c = new wsy();
        soj sojVar8 = new soj(a8.a());
        this.h = sojVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.i(true);
        a9.a = "desktop.operating_system";
        a9.c = new wsy();
        soj sojVar9 = new soj(a9.a());
        this.i = sojVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.i(true);
        a10.a = "desktop.operating_system_version";
        a10.c = new wsy();
        soj sojVar10 = new soj(a10.a());
        this.j = sojVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "desktop.browser_type";
        a11.c = new wsy();
        soj sojVar11 = new soj(a11.a());
        this.k = sojVar11;
        agmi a12 = agmk.a();
        a12.d = 5;
        a12.a = "desktop.encryption_key";
        a12.c = new wsy();
        soj sojVar12 = new soj(a12.a());
        this.l = sojVar12;
        agmi a13 = agmk.a();
        a13.d = 5;
        a13.a = "desktop.hmac_key";
        a13.c = new wsy();
        soj sojVar13 = new soj(a13.a());
        this.m = sojVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "desktop.backend_type";
        a14.c = new wsy();
        soj sojVar14 = new soj(a14.a());
        this.n = sojVar14;
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.a = "desktop.is_active";
        a15.c = new wsy();
        soj sojVar15 = new soj(a15.a());
        this.o = sojVar15;
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "desktop.request_id";
        a16.c = new wsy();
        soj sojVar16 = new soj(a16.a());
        this.p = sojVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "desktop.is_persistent";
        a17.c = new wsy();
        soj sojVar17 = new soj(a17.a());
        this.q = sojVar17;
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "desktop.desktop_type";
        a18.c = new wsy();
        soj sojVar18 = new soj(a18.a());
        this.r = sojVar18;
        agmi a19 = agmk.a();
        a19.d = 1;
        a19.a = "desktop.pairing_type";
        a19.c = new wsy();
        soj sojVar19 = new soj(a19.a());
        this.s = sojVar19;
        agmi a20 = agmk.a();
        a20.d = 5;
        a20.a = "desktop.destination_registration_id";
        a20.c = new wsy();
        soj sojVar20 = new soj(a20.a());
        this.t = sojVar20;
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "desktop.gaia_email";
        a21.c = new wsy();
        soj sojVar21 = new soj(a21.a());
        this.u = sojVar21;
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "desktop.creation_time";
        a22.c = new wsy();
        soj sojVar22 = new soj(a22.a());
        this.v = sojVar22;
        this.w = new soj[]{sojVar, sojVar2, sojVar3, sojVar4, sojVar5, sojVar6, sojVar7, sojVar8, sojVar9, sojVar10, sojVar11, sojVar12, sojVar13, sojVar14, sojVar15, sojVar16, sojVar17, sojVar18, sojVar19, sojVar20, sojVar21, sojVar22};
    }
}
