package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class spo {
    public final spp a;
    public final spp b;
    public final spp c;
    public final spp d;
    public final spp e;
    public final spp f;
    public final spp g;
    public final spp h;
    public final spp i;
    public final spp j;
    public final spp k;
    public final spp l;
    public final spp m;
    public final spp n;
    public final spp o;
    public final spp p;
    public final spp q;
    final spp[] r;

    public spo() {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "etouffee_rcs_metadata.rcs_message_id";
        a.c = new wsy();
        spp sppVar = new spp(a.a());
        this.a = sppVar;
        agmi a2 = agmk.a();
        a2.d = 5;
        a2.a = "etouffee_rcs_metadata.preview_etouffee";
        a2.c = new wsy();
        spp sppVar2 = new spp(a2.a());
        this.b = sppVar2;
        agmi a3 = agmk.a();
        a3.d = 5;
        a3.a = "etouffee_rcs_metadata.preview_summary";
        a3.c = new wsy();
        spp sppVar3 = new spp(a3.a());
        this.c = sppVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "etouffee_rcs_metadata.preview_version";
        a4.c = new wsy();
        spp sppVar4 = new spp(a4.a());
        this.d = sppVar4;
        agmi a5 = agmk.a();
        a5.d = 5;
        a5.a = "etouffee_rcs_metadata.attachment_etouffee";
        a5.c = new wsy();
        spp sppVar5 = new spp(a5.a());
        this.e = sppVar5;
        agmi a6 = agmk.a();
        a6.d = 5;
        a6.a = "etouffee_rcs_metadata.attachment_summary";
        a6.c = new wsy();
        spp sppVar6 = new spp(a6.a());
        this.f = sppVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "etouffee_rcs_metadata.attachment_version";
        a7.c = new wsy();
        spp sppVar7 = new spp(a7.a());
        this.g = sppVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "etouffee_rcs_metadata.creation_timestamp";
        a8.c = new wsy();
        spp sppVar8 = new spp(a8.a());
        this.h = sppVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "etouffee_rcs_metadata.attachment_uri";
        a9.c = new wsy();
        spp sppVar9 = new spp(a9.a());
        this.i = sppVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "etouffee_rcs_metadata.custom_delivery_receipt_mime_type";
        a10.c = new wsy();
        spp sppVar10 = new spp(a10.a());
        this.j = sppVar10;
        agmi a11 = agmk.a();
        a11.d = 5;
        a11.a = "etouffee_rcs_metadata.custom_delivery_receipt_content";
        a11.c = new wsy();
        spp sppVar11 = new spp(a11.a());
        this.k = sppVar11;
        agmi a12 = agmk.a();
        a12.d = 5;
        a12.a = "etouffee_rcs_metadata.file_uploaded_xml_from_content_server";
        a12.c = new wsy();
        spp sppVar12 = new spp(a12.a());
        this.l = sppVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "etouffee_rcs_metadata.file_uploaded_fallback_uri";
        a13.c = new wsy();
        spp sppVar13 = new spp(a13.a());
        this.m = sppVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "etouffee_rcs_metadata.file_uploaded_expiry";
        a14.c = new wsy();
        spp sppVar14 = new spp(a14.a());
        this.n = sppVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "etouffee_rcs_metadata.plaintext_attachment_name";
        a15.c = new wsy();
        spp sppVar15 = new spp(a15.a());
        this.o = sppVar15;
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "etouffee_rcs_metadata.plaintext_attachment_content_type";
        a16.c = new wsy();
        spp sppVar16 = new spp(a16.a());
        this.p = sppVar16;
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.a = "etouffee_rcs_metadata.plaintext_thumbnail_content_type";
        a17.c = new wsy();
        spp sppVar17 = new spp(a17.a());
        this.q = sppVar17;
        this.r = new spp[]{sppVar, sppVar2, sppVar3, sppVar4, sppVar5, sppVar6, sppVar7, sppVar8, sppVar9, sppVar10, sppVar11, sppVar12, sppVar13, sppVar14, sppVar15, sppVar16, sppVar17};
    }
}
