package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class sxo {
    public final sxp A;
    public final sxp B;
    public final sxp C;
    public final sxp D;
    public final sxp E;
    public final sxp F;
    public final sxp G;
    public final sxp H;
    public final sxp I;
    public final sxp J;
    public final sxp K;
    public final sxp L;
    public final sxp M;
    public final sxp N;
    public final sxp O;
    public final sxp P;
    public final sxp Q;
    public final sxp R;
    public final sxp S;
    public final sxp T;
    public final sxp U;
    public final sxp V;
    public final sxp W;
    public final sxp X;
    public final sxp Y;
    public final sxp Z;
    public final sxp a;
    public final sxp aa;
    public final sxp ab;
    public final sxp ac;
    public final sxp ad;
    public final sxp ae;
    public final sxp af;
    public final sxp ag;
    public final sxp ah;
    public final sxp ai;
    public final sxp aj;
    public final sxp ak;
    public final sxp al;
    public final sxp am;
    public final sxp an;
    public final sxp ao;
    public final sxp[] ap;
    public final sxp b;
    public final sxp c;
    public final sxp d;
    public final sxp e;
    public final sxp f;
    public final sxp g;
    public final sxp h;
    public final sxp i;
    public final sxp j;
    public final sxp k;
    public final sxp l;
    public final sxp m;
    public final sxp n;
    public final sxp o;
    public final sxp p;
    public final sxp q;
    public final sxp r;
    public final sxp s;
    public final sxp t;
    public final sxp u;
    public final sxp v;
    public final sxp w;
    public final sxp x;
    public final sxp y;
    public final sxp z;

    public sxo() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "messages._id";
        a.c = new wsy();
        sxp sxpVar = new sxp(a.a());
        this.a = sxpVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.d(true);
        a2.a = "messages.conversation_id";
        a2.c = new wsy();
        sxp sxpVar2 = new sxp(a2.a());
        this.b = sxpVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.c(true);
        a3.d(true);
        a3.a = "messages.sender_id";
        a3.c = new wsy();
        sxp sxpVar3 = new sxp(a3.a());
        this.c = sxpVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "messages.sender_send_destination";
        a4.c = new wsy();
        sxp sxpVar4 = new sxp(a4.a());
        this.d = sxpVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "messages.msisdn_receiving_rcs_message";
        a5.c = new wsy();
        sxp sxpVar5 = new sxp(a5.a());
        this.e = sxpVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "messages.receiving_network_country";
        a6.c = new wsy();
        sxp sxpVar6 = new sxp(a6.a());
        this.f = sxpVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.c(true);
        a7.a = "messages.sent_timestamp";
        a7.c = new wsy();
        sxp sxpVar7 = new sxp(a7.a());
        this.g = sxpVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "messages.queue_insert_timestamp";
        a8.c = new wsy();
        sxp sxpVar8 = new sxp(a8.a());
        this.h = sxpVar8;
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.c(true);
        a9.a = "messages.received_timestamp";
        a9.c = new wsy();
        sxp sxpVar9 = new sxp(a9.a());
        this.i = sxpVar9;
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "messages.message_protocol";
        a10.c = new wsy();
        sxp sxpVar10 = new sxp(a10.a());
        this.j = sxpVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.c(true);
        a11.a = "messages.message_status";
        a11.c = new wsy();
        sxp sxpVar11 = new sxp(a11.a());
        this.k = sxpVar11;
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "messages.message_report_status";
        a12.c = new wsy();
        sxp sxpVar12 = new sxp(a12.a());
        this.l = sxpVar12;
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.c(true);
        a13.a = "messages.seen";
        a13.e(true);
        a13.c = new wsy();
        sxp sxpVar13 = new sxp(a13.a());
        this.m = sxpVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.c(true);
        a14.a = "messages.read";
        a14.c = new wsy();
        sxp sxpVar14 = new sxp(a14.a());
        this.n = sxpVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.c(true);
        a15.a = "messages.sms_message_uri";
        a15.c = new wsy();
        sxp sxpVar15 = new sxp(a15.a());
        this.o = sxpVar15;
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "messages.sms_priority";
        a16.c = new wsy();
        sxp sxpVar16 = new sxp(a16.a());
        this.p = sxpVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "messages.sms_message_size";
        a17.c = new wsy();
        sxp sxpVar17 = new sxp(a17.a());
        this.q = sxpVar17;
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "messages.mms_subject";
        a18.c = new wsy();
        sxp sxpVar18 = new sxp(a18.a());
        this.r = sxpVar18;
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "messages.mms_transaction_id";
        a19.c = new wsy();
        sxp sxpVar19 = new sxp(a19.a());
        this.s = sxpVar19;
        agmi a20 = agmk.a();
        a20.d = 4;
        a20.a = "messages.mms_content_location";
        a20.c = new wsy();
        sxp sxpVar20 = new sxp(a20.a());
        this.t = sxpVar20;
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.a = "messages.mms_expiry";
        a21.c = new wsy();
        sxp sxpVar21 = new sxp(a21.a());
        this.u = sxpVar21;
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.c(true);
        a22.a = "messages.rcs_expiry";
        a22.c = new wsy();
        sxp sxpVar22 = new sxp(a22.a());
        this.v = sxpVar22;
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "messages.mms_retrieve_text";
        a23.c = new wsy();
        sxp sxpVar23 = new sxp(a23.a());
        this.w = sxpVar23;
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "messages.raw_status";
        a24.c = new wsy();
        sxp sxpVar24 = new sxp(a24.a());
        this.x = sxpVar24;
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.c(true);
        a25.d(true);
        a25.a = "messages.self_id";
        a25.c = new wsy();
        sxp sxpVar25 = new sxp(a25.a());
        this.y = sxpVar25;
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.c(true);
        a26.d(true);
        a26.b = new swm(16);
        a26.a = "messages.my_identity_foreign_key";
        a26.c = new wsy();
        sxp sxpVar26 = new sxp(a26.a());
        this.z = sxpVar26;
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "messages.retry_start_timestamp";
        a27.c = new wsy();
        sxp sxpVar27 = new sxp(a27.a());
        this.A = sxpVar27;
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.c(true);
        a28.a = "messages.cloud_sync_id";
        a28.c = new wsy();
        sxp sxpVar28 = new sxp(a28.a());
        this.B = sxpVar28;
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.c(true);
        a29.a = "messages.rcs_message_id_with_text_type";
        a29.e(true);
        a29.c = new wsy();
        sxp sxpVar29 = new sxp(a29.a());
        this.C = sxpVar29;
        agmi a30 = agmk.a();
        a30.d = 1;
        a30.a = "messages.etouffee_status";
        a30.c = new wsy();
        sxp sxpVar30 = new sxp(a30.a());
        this.D = sxpVar30;
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "messages.verification_status";
        a31.c = new wsy();
        sxp sxpVar31 = new sxp(a31.a());
        this.E = sxpVar31;
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "messages.rcs_ui_status";
        a32.c = new wsy();
        sxp sxpVar32 = new sxp(a32.a());
        this.F = sxpVar32;
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.c(true);
        a33.a = "messages.is_hidden";
        a33.c = new wsy();
        sxp sxpVar33 = new sxp(a33.a());
        this.G = sxpVar33;
        agmi a34 = agmk.a();
        a34.d = 7;
        a34.a = "messages.rcs_remote_instance";
        a34.c = new wsy();
        sxp sxpVar34 = new sxp(a34.a());
        this.H = sxpVar34;
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "messages.rcs_file_transfer_session_id";
        a35.c = new wsy();
        sxp sxpVar35 = new sxp(a35.a());
        this.I = sxpVar35;
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.a = "messages.sms_error_code";
        a36.c = new wsy();
        sxp sxpVar36 = new sxp(a36.a());
        this.J = sxpVar36;
        agmi a37 = agmk.a();
        a37.d = 4;
        a37.a = "messages.sms_error_desc_map_name";
        a37.c = new wsy();
        sxp sxpVar37 = new sxp(a37.a());
        this.K = sxpVar37;
        agmi a38 = agmk.a();
        a38.d = 4;
        a38.a = "messages.correlation_id";
        a38.c = new wsy();
        sxp sxpVar38 = new sxp(a38.a());
        this.L = sxpVar38;
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.j(true);
        a39.c(true);
        a39.a = "messages.cms_id";
        a39.e(true);
        a39.c = new wsy();
        sxp sxpVar39 = new sxp(a39.a());
        this.M = sxpVar39;
        agmi a40 = agmk.a();
        a40.d = 2;
        a40.a = "messages.cms_last_mod_seq";
        a40.c = new wsy();
        sxp sxpVar40 = new sxp(a40.a());
        this.N = sxpVar40;
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.c(true);
        a41.a = "messages.web_id";
        a41.c = new wsy();
        sxp sxpVar41 = new sxp(a41.a());
        this.O = sxpVar41;
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "messages.usage_stats_logging_id";
        a42.c = new wsy();
        sxp sxpVar42 = new sxp(a42.a());
        this.P = sxpVar42;
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "messages.send_counter";
        a43.c = new wsy();
        sxp sxpVar43 = new sxp(a43.a());
        this.Q = sxpVar43;
        agmi a44 = agmk.a();
        a44.d = 4;
        a44.c(true);
        a44.a = "messages.original_rcs_message_id";
        a44.c = new wsy();
        sxp sxpVar44 = new sxp(a44.a());
        this.R = sxpVar44;
        agmi a45 = agmk.a();
        a45.d = 4;
        a45.a = "messages.custom_delivery_receipt_mime_type";
        a45.c = new wsy();
        sxp sxpVar45 = new sxp(a45.a());
        this.S = sxpVar45;
        agmi a46 = agmk.a();
        a46.d = 5;
        a46.a = "messages.custom_delivery_receipt_content";
        a46.c = new wsy();
        sxp sxpVar46 = new sxp(a46.a());
        this.T = sxpVar46;
        agmi a47 = agmk.a();
        a47.d = 1;
        a47.a = "messages.report_attempt_acounter";
        a47.c = new wsy();
        sxp sxpVar47 = new sxp(a47.a());
        this.U = sxpVar47;
        agmi a48 = agmk.a();
        a48.d = 5;
        a48.a = "messages.custom_headers";
        a48.c = new wsy();
        sxp sxpVar48 = new sxp(a48.a());
        this.V = sxpVar48;
        agmi a49 = agmk.a();
        a49.d = 4;
        a49.j(true);
        a49.c(true);
        a49.a = "messages.cms_correlation_id";
        a49.e(true);
        a49.c = new wsy();
        sxp sxpVar49 = new sxp(a49.a());
        this.W = sxpVar49;
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.c(true);
        a50.d(true);
        a50.b = new swm(17);
        a50.a = "messages.group_private_participant";
        a50.c = new wsy();
        sxp sxpVar50 = new sxp(a50.a());
        this.X = sxpVar50;
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.c(true);
        a51.d(true);
        a51.b = new swm(18);
        a51.a = "messages.original_message_id";
        a51.c = new wsy();
        sxp sxpVar51 = new sxp(a51.a());
        this.Y = sxpVar51;
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.a = "messages.awaiting_reverse_sync";
        a52.c = new wsy();
        sxp sxpVar52 = new sxp(a52.a());
        this.Z = sxpVar52;
        agmi a53 = agmk.a();
        a53.d = 4;
        a53.a = "messages.old_sms_message_uri";
        a53.c = new wsy();
        sxp sxpVar53 = new sxp(a53.a());
        this.aa = sxpVar53;
        agmi a54 = agmk.a();
        a54.d = 4;
        a54.j(true);
        a54.c(true);
        a54.a = "messages.draft_id";
        a54.e(true);
        a54.c = new wsy();
        sxp sxpVar54 = new sxp(a54.a());
        this.ab = sxpVar54;
        agmi a55 = agmk.a();
        a55.d = 1;
        a55.a = "messages.result_code";
        a55.c = new wsy();
        sxp sxpVar55 = new sxp(a55.a());
        this.ac = sxpVar55;
        agmi a56 = agmk.a();
        a56.d = 1;
        a56.a = "messages.cms_life_cycle";
        a56.c = new wsy();
        sxp sxpVar56 = new sxp(a56.a());
        this.ad = sxpVar56;
        agmi a57 = agmk.a();
        a57.d = 1;
        a57.a = "messages.fallback_reason";
        a57.c = new wsy();
        sxp sxpVar57 = new sxp(a57.a());
        this.ae = sxpVar57;
        agmi a58 = agmk.a();
        a58.d = 1;
        a58.a = "messages.auto_retry_counter";
        a58.c = new wsy();
        sxp sxpVar58 = new sxp(a58.a());
        this.af = sxpVar58;
        agmi a59 = agmk.a();
        a59.d = 2;
        a59.a = "messages.can_revoke_before_delivered_with_rcs";
        a59.c = new wsy();
        sxp sxpVar59 = new sxp(a59.a());
        this.ag = sxpVar59;
        agmi a60 = agmk.a();
        a60.d = 5;
        a60.a = "messages.trace_id";
        a60.c = new wsy();
        sxp sxpVar60 = new sxp(a60.a());
        this.ah = sxpVar60;
        agmi a61 = agmk.a();
        a61.d = 1;
        a61.a = "messages.outgoing_delivery_report_status";
        a61.c = new wsy();
        sxp sxpVar61 = new sxp(a61.a());
        this.ai = sxpVar61;
        agmi a62 = agmk.a();
        a62.d = 1;
        a62.a = "messages.outgoing_read_report_status";
        a62.c = new wsy();
        sxp sxpVar62 = new sxp(a62.a());
        this.aj = sxpVar62;
        agmi a63 = agmk.a();
        a63.d = 1;
        a63.a = "messages.xms_transport";
        a63.c = new wsy();
        sxp sxpVar63 = new sxp(a63.a());
        this.ak = sxpVar63;
        agmi a64 = agmk.a();
        a64.d = 1;
        a64.a = "messages.message_original_protocol";
        a64.c = new wsy();
        sxp sxpVar64 = new sxp(a64.a());
        this.al = sxpVar64;
        agmi a65 = agmk.a();
        a65.d = 4;
        a65.j(true);
        a65.c(true);
        a65.a = "messages.satellite_datagram_id";
        a65.e(true);
        a65.c = new wsy();
        sxp sxpVar65 = new sxp(a65.a());
        this.am = sxpVar65;
        agmi a66 = agmk.a();
        a66.d = 1;
        a66.a = "messages.encryption_protocol";
        a66.c = new wsy();
        sxp sxpVar66 = new sxp(a66.a());
        this.an = sxpVar66;
        agmi a67 = agmk.a();
        a67.d = 4;
        a67.j(true);
        a67.c(true);
        a67.a = "messages.message_persistence_id";
        a67.e(true);
        a67.c = new wsy();
        sxp sxpVar67 = new sxp(a67.a());
        this.ao = sxpVar67;
        this.ap = new sxp[]{sxpVar, sxpVar2, sxpVar3, sxpVar4, sxpVar5, sxpVar6, sxpVar7, sxpVar8, sxpVar9, sxpVar10, sxpVar11, sxpVar12, sxpVar13, sxpVar14, sxpVar15, sxpVar16, sxpVar17, sxpVar18, sxpVar19, sxpVar20, sxpVar21, sxpVar22, sxpVar23, sxpVar24, sxpVar25, sxpVar26, sxpVar27, sxpVar28, sxpVar29, sxpVar30, sxpVar31, sxpVar32, sxpVar33, sxpVar34, sxpVar35, sxpVar36, sxpVar37, sxpVar38, sxpVar39, sxpVar40, sxpVar41, sxpVar42, sxpVar43, sxpVar44, sxpVar45, sxpVar46, sxpVar47, sxpVar48, sxpVar49, sxpVar50, sxpVar51, sxpVar52, sxpVar53, sxpVar54, sxpVar55, sxpVar56, sxpVar57, sxpVar58, sxpVar59, sxpVar60, sxpVar61, sxpVar62, sxpVar63, sxpVar64, sxpVar65, sxpVar66, sxpVar67};
    }
}
