package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class taf {
    public final tag A;
    public final tag B;
    public final tag C;
    public final tag D;
    public final tag E;
    public final tag F;
    public final tag G;
    public final tag H;
    public final tag I;
    public final tag J;
    public final tag K;
    public final tag L;
    public final tag M;
    public final tag N;
    public final tag O;
    public final tag P;
    public final tag Q;
    public final tag R;
    public final tag S;
    public final tag T;
    public final tag U;
    public final tag V;
    final tag[] W;
    public final tag a;
    public final tag b;
    public final tag c;
    public final tag d;
    public final tag e;
    public final tag f;
    public final tag g;
    public final tag h;
    public final tag i;
    public final tag j;
    public final tag k;
    public final tag l;
    public final tag m;
    public final tag n;
    public final tag o;
    public final tag p;
    public final tag q;
    public final tag r;
    public final tag s;
    public final tag t;
    public final tag u;
    public final tag v;
    public final tag w;
    public final tag x;
    public final tag y;
    public final tag z;

    public taf() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "participants_audit_log._id";
        a.c = new wsy();
        tag tagVar = new tag(a.a());
        this.a = tagVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.i(true);
        a2.a = "participants_audit_log.operation_datetime";
        a2.c = new wsy();
        tag tagVar2 = new tag(a2.a());
        this.b = tagVar2;
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.i(true);
        a3.a = "participants_audit_log.operation_type";
        a3.c = new wsy();
        tag tagVar3 = new tag(a3.a());
        this.c = tagVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.i(true);
        a4.a = "participants_audit_log.participant_id";
        a4.c = new wsy();
        tag tagVar4 = new tag(a4.a());
        this.d = tagVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "participants_audit_log.my_identity_token";
        a5.c = new wsy();
        tag tagVar5 = new tag(a5.a());
        this.e = tagVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.c(true);
        a6.d(true);
        a6.b = new sym(15);
        a6.a = "participants_audit_log.my_identity_token_foreign_key";
        a6.c = new wsy();
        tag tagVar6 = new tag(a6.a());
        this.f = tagVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "participants_audit_log.sub_id";
        a7.c = new wsy();
        tag tagVar7 = new tag(a7.a());
        this.g = tagVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "participants_audit_log.sim_slot_id";
        a8.c = new wsy();
        tag tagVar8 = new tag(a8.a());
        this.h = tagVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "participants_audit_log.normalized_destination";
        a9.c = new wsy();
        tag tagVar9 = new tag(a9.a());
        this.i = tagVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "participants_audit_log.send_destination";
        a10.c = new wsy();
        tag tagVar10 = new tag(a10.a());
        this.j = tagVar10;
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.a = "participants_audit_log.display_destination";
        a11.c = new wsy();
        tag tagVar11 = new tag(a11.a());
        this.k = tagVar11;
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "participants_audit_log.comparable_destination";
        a12.c = new wsy();
        tag tagVar12 = new tag(a12.a());
        this.l = tagVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "participants_audit_log.country_code";
        a13.c = new wsy();
        tag tagVar13 = new tag(a13.a());
        this.m = tagVar13;
        agmi a14 = agmk.a();
        a14.d = 2;
        a14.a = "participants_audit_log.recipient_id";
        a14.c = new wsy();
        tag tagVar14 = new tag(a14.a());
        this.n = tagVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "participants_audit_log.recipient_canonical_address";
        a15.c = new wsy();
        tag tagVar15 = new tag(a15.a());
        this.o = tagVar15;
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "participants_audit_log.full_name";
        a16.c = new wsy();
        tag tagVar16 = new tag(a16.a());
        this.p = tagVar16;
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.a = "participants_audit_log.first_name";
        a17.c = new wsy();
        tag tagVar17 = new tag(a17.a());
        this.q = tagVar17;
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "participants_audit_log.profile_photo_uri";
        a18.c = new wsy();
        tag tagVar18 = new tag(a18.a());
        this.r = tagVar18;
        agmi a19 = agmk.a();
        a19.d = 4;
        a19.a = "participants_audit_log.contact_photo_uri";
        a19.c = new wsy();
        tag tagVar19 = new tag(a19.a());
        this.s = tagVar19;
        agmi a20 = agmk.a();
        a20.d = 1;
        a20.a = "participants_audit_log.contact_id";
        a20.c = new wsy();
        tag tagVar20 = new tag(a20.a());
        this.t = tagVar20;
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "participants_audit_log.lookup_key";
        a21.c = new wsy();
        tag tagVar21 = new tag(a21.a());
        this.u = tagVar21;
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "participants_audit_log.color_palette_index";
        a22.c = new wsy();
        tag tagVar22 = new tag(a22.a());
        this.v = tagVar22;
        agmi a23 = agmk.a();
        a23.d = 1;
        a23.a = "participants_audit_log.color_type";
        a23.c = new wsy();
        tag tagVar23 = new tag(a23.a());
        this.w = tagVar23;
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "participants_audit_log.extended_color";
        a24.c = new wsy();
        tag tagVar24 = new tag(a24.a());
        this.x = tagVar24;
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "participants_audit_log.blocked";
        a25.c = new wsy();
        tag tagVar25 = new tag(a25.a());
        this.y = tagVar25;
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.a = "participants_audit_log.subscription_name";
        a26.c = new wsy();
        tag tagVar26 = new tag(a26.a());
        this.z = tagVar26;
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "participants_audit_log.subscription_color";
        a27.c = new wsy();
        tag tagVar27 = new tag(a27.a());
        this.A = tagVar27;
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "participants_audit_log.contact_destination";
        a28.c = new wsy();
        tag tagVar28 = new tag(a28.a());
        this.B = tagVar28;
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "participants_audit_log.participant_type";
        a29.c = new wsy();
        tag tagVar29 = new tag(a29.a());
        this.C = tagVar29;
        agmi a30 = agmk.a();
        a30.d = 1;
        a30.a = "participants_audit_log.video_reachability";
        a30.c = new wsy();
        tag tagVar30 = new tag(a30.a());
        this.D = tagVar30;
        agmi a31 = agmk.a();
        a31.d = 4;
        a31.a = "participants_audit_log.alias";
        a31.c = new wsy();
        tag tagVar31 = new tag(a31.a());
        this.E = tagVar31;
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "participants_audit_log.is_spam";
        a32.c = new wsy();
        tag tagVar32 = new tag(a32.a());
        this.F = tagVar32;
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "participants_audit_log.is_spam_source";
        a33.c = new wsy();
        tag tagVar33 = new tag(a33.a());
        this.G = tagVar33;
        agmi a34 = agmk.a();
        a34.d = 4;
        a34.a = "participants_audit_log.cms_id";
        a34.c = new wsy();
        tag tagVar34 = new tag(a34.a());
        this.H = tagVar34;
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "participants_audit_log.latest_verification_status";
        a35.c = new wsy();
        tag tagVar35 = new tag(a35.a());
        this.I = tagVar35;
        agmi a36 = agmk.a();
        a36.d = 4;
        a36.a = "participants_audit_log.profile_photo_blob_id";
        a36.c = new wsy();
        tag tagVar36 = new tag(a36.a());
        this.J = tagVar36;
        agmi a37 = agmk.a();
        a37.d = 5;
        a37.a = "participants_audit_log.profile_photo_encryption_key";
        a37.c = new wsy();
        tag tagVar37 = new tag(a37.a());
        this.K = tagVar37;
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "participants_audit_log.directory_id";
        a38.c = new wsy();
        tag tagVar38 = new tag(a38.a());
        this.L = tagVar38;
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.a = "participants_audit_log.is_check_constraint_enabled_via_phenotype";
        a39.c = new wsy();
        tag tagVar39 = new tag(a39.a());
        this.M = tagVar39;
        agmi a40 = agmk.a();
        a40.d = 1;
        a40.a = "participants_audit_log.is_valid_phone_number_data";
        a40.c = new wsy();
        tag tagVar40 = new tag(a40.a());
        this.N = tagVar40;
        agmi a41 = agmk.a();
        a41.d = 2;
        a41.a = "participants_audit_log.duplicate_of";
        a41.c = new wsy();
        tag tagVar41 = new tag(a41.a());
        this.O = tagVar41;
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "participants_audit_log.cms_life_cycle";
        a42.c = new wsy();
        tag tagVar42 = new tag(a42.a());
        this.P = tagVar42;
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "participants_audit_log.norm_ui_status";
        a43.c = new wsy();
        tag tagVar43 = new tag(a43.a());
        this.Q = tagVar43;
        agmi a44 = agmk.a();
        a44.d = 4;
        a44.a = "participants_audit_log.last_modified_by_key";
        a44.c = new wsy();
        tag tagVar44 = new tag(a44.a());
        this.R = tagVar44;
        agmi a45 = agmk.a();
        a45.d = 1;
        a45.a = "participants_audit_log.name_source";
        a45.c = new wsy();
        tag tagVar45 = new tag(a45.a());
        this.S = tagVar45;
        agmi a46 = agmk.a();
        a46.d = 1;
        a46.a = "participants_audit_log.photo_source";
        a46.c = new wsy();
        tag tagVar46 = new tag(a46.a());
        this.T = tagVar46;
        agmi a47 = agmk.a();
        a47.d = 1;
        a47.a = "participants_audit_log.profile_photo_user_preference";
        a47.c = new wsy();
        tag tagVar47 = new tag(a47.a());
        this.U = tagVar47;
        agmi a48 = agmk.a();
        a48.d = 5;
        a48.a = "participants_audit_log.contact_metadata";
        a48.c = new wsy();
        tag tagVar48 = new tag(a48.a());
        this.V = tagVar48;
        this.W = new tag[]{tagVar, tagVar2, tagVar3, tagVar4, tagVar5, tagVar6, tagVar7, tagVar8, tagVar9, tagVar10, tagVar11, tagVar12, tagVar13, tagVar14, tagVar15, tagVar16, tagVar17, tagVar18, tagVar19, tagVar20, tagVar21, tagVar22, tagVar23, tagVar24, tagVar25, tagVar26, tagVar27, tagVar28, tagVar29, tagVar30, tagVar31, tagVar32, tagVar33, tagVar34, tagVar35, tagVar36, tagVar37, tagVar38, tagVar39, tagVar40, tagVar41, tagVar42, tagVar43, tagVar44, tagVar45, tagVar46, tagVar47, tagVar48};
    }
}
