package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class tar {
    public final tas A;
    public final tas B;
    public final tas C;
    public final tas D;
    public final tas E;
    public final tas F;
    public final tas G;
    public final tas H;
    public final tas I;
    public final tas J;
    public final tas K;
    public final tas L;
    public final tas M;
    public final tas N;
    public final tas O;
    public final tas P;
    public final tas Q;
    public final tas R;
    public final tas S;
    public final tas[] T;
    public final tas a;
    public final tas b;
    public final tas c;
    public final tas d;
    public final tas e;
    public final tas f;
    public final tas g;
    public final tas h;
    public final tas i;
    public final tas j;
    public final tas k;
    public final tas l;
    public final tas m;
    public final tas n;
    public final tas o;
    public final tas p;
    public final tas q;
    public final tas r;
    public final tas s;
    public final tas t;
    public final tas u;
    public final tas v;
    public final tas w;
    public final tas x;
    public final tas y;
    public final tas z;

    public tar() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "participants._id";
        a.c = new wsy();
        tas tasVar = new tas(a.a());
        this.a = tasVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.c(true);
        a2.a = "participants.my_identity_token";
        a2.c = new wsy();
        tas tasVar2 = new tas(a2.a());
        this.b = tasVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.c(true);
        a3.d(true);
        a3.b = new taq(0);
        a3.a = "participants.my_identity_token_foreign_key";
        a3.c = new wsy();
        tas tasVar3 = new tas(a3.a());
        this.c = tasVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.c(true);
        a4.a = "participants.sub_id";
        a4.e(true);
        a4.c = new wsy();
        tas tasVar4 = new tas(a4.a());
        this.d = tasVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "participants.sim_slot_id";
        a5.c = new wsy();
        tas tasVar5 = new tas(a5.a());
        this.e = tasVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.c(true);
        a6.a = "participants.normalized_destination";
        a6.e(true);
        a6.c = new wsy();
        tas tasVar6 = new tas(a6.a());
        this.f = tasVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "participants.send_destination";
        a7.c = new wsy();
        tas tasVar7 = new tas(a7.a());
        this.g = tasVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "participants.display_destination";
        a8.c = new wsy();
        tas tasVar8 = new tas(a8.a());
        this.h = tasVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.j(true);
        a9.c(true);
        a9.a = "participants.comparable_destination";
        a9.e(true);
        a9.c = new wsy();
        tas tasVar9 = new tas(a9.a());
        this.i = tasVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "participants.country_code";
        a10.c = new wsy();
        tas tasVar10 = new tas(a10.a());
        this.j = tasVar10;
        agmi a11 = agmk.a();
        a11.d = 2;
        a11.j(true);
        a11.c(true);
        a11.a = "participants.recipient_id";
        a11.e(true);
        a11.c = new wsy();
        tas tasVar11 = new tas(a11.a());
        this.k = tasVar11;
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "participants.recipient_canonical_address";
        a12.c = new wsy();
        tas tasVar12 = new tas(a12.a());
        this.l = tasVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "participants.full_name";
        a13.c = new wsy();
        tas tasVar13 = new tas(a13.a());
        this.m = tasVar13;
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.a = "participants.first_name";
        a14.c = new wsy();
        tas tasVar14 = new tas(a14.a());
        this.n = tasVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "participants.profile_photo_uri";
        a15.c = new wsy();
        tas tasVar15 = new tas(a15.a());
        this.o = tasVar15;
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "participants.contact_photo_uri";
        a16.c = new wsy();
        tas tasVar16 = new tas(a16.a());
        this.p = tasVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "participants.contact_id";
        a17.c = new wsy();
        tas tasVar17 = new tas(a17.a());
        this.q = tasVar17;
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.a = "participants.lookup_key";
        a18.c = new wsy();
        tas tasVar18 = new tas(a18.a());
        this.r = tasVar18;
        agmi a19 = agmk.a();
        a19.d = 1;
        a19.a = "participants.color_palette_index";
        a19.c = new wsy();
        tas tasVar19 = new tas(a19.a());
        this.s = tasVar19;
        agmi a20 = agmk.a();
        a20.d = 1;
        a20.a = "participants.color_type";
        a20.c = new wsy();
        tas tasVar20 = new tas(a20.a());
        this.t = tasVar20;
        agmi a21 = agmk.a();
        a21.d = 1;
        a21.a = "participants.extended_color";
        a21.c = new wsy();
        tas tasVar21 = new tas(a21.a());
        this.u = tasVar21;
        agmi a22 = agmk.a();
        a22.d = 1;
        a22.a = "participants.blocked";
        a22.c = new wsy();
        tas tasVar22 = new tas(a22.a());
        this.v = tasVar22;
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "participants.subscription_name";
        a23.c = new wsy();
        tas tasVar23 = new tas(a23.a());
        this.w = tasVar23;
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "participants.subscription_color";
        a24.c = new wsy();
        tas tasVar24 = new tas(a24.a());
        this.x = tasVar24;
        agmi a25 = agmk.a();
        a25.d = 4;
        a25.a = "participants.contact_destination";
        a25.c = new wsy();
        tas tasVar25 = new tas(a25.a());
        this.y = tasVar25;
        agmi a26 = agmk.a();
        a26.d = 1;
        a26.a = "participants.participant_type";
        a26.c = new wsy();
        tas tasVar26 = new tas(a26.a());
        this.z = tasVar26;
        agmi a27 = agmk.a();
        a27.d = 1;
        a27.a = "participants.video_reachability";
        a27.c = new wsy();
        tas tasVar27 = new tas(a27.a());
        this.A = tasVar27;
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "participants.alias";
        a28.c = new wsy();
        tas tasVar28 = new tas(a28.a());
        this.B = tasVar28;
        agmi a29 = agmk.a();
        a29.d = 1;
        a29.a = "participants.is_spam";
        a29.c = new wsy();
        tas tasVar29 = new tas(a29.a());
        this.C = tasVar29;
        agmi a30 = agmk.a();
        a30.d = 1;
        a30.a = "participants.is_spam_source";
        a30.c = new wsy();
        tas tasVar30 = new tas(a30.a());
        this.D = tasVar30;
        agmi a31 = agmk.a();
        a31.d = 4;
        a31.j(true);
        a31.c(true);
        a31.a = "participants.cms_id";
        a31.e(true);
        a31.c = new wsy();
        tas tasVar31 = new tas(a31.a());
        this.E = tasVar31;
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "participants.latest_verification_status";
        a32.c = new wsy();
        tas tasVar32 = new tas(a32.a());
        this.F = tasVar32;
        agmi a33 = agmk.a();
        a33.d = 4;
        a33.a = "participants.profile_photo_blob_id";
        a33.c = new wsy();
        tas tasVar33 = new tas(a33.a());
        this.G = tasVar33;
        agmi a34 = agmk.a();
        a34.d = 5;
        a34.a = "participants.profile_photo_encryption_key";
        a34.c = new wsy();
        tas tasVar34 = new tas(a34.a());
        this.H = tasVar34;
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "participants.directory_id";
        a35.c = new wsy();
        tas tasVar35 = new tas(a35.a());
        this.I = tasVar35;
        agmi a36 = agmk.a();
        a36.d = 1;
        a36.a = "participants.is_check_constraint_enabled_via_phenotype";
        a36.c = new wsy();
        tas tasVar36 = new tas(a36.a());
        this.J = tasVar36;
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "participants.is_valid_phone_number_data";
        a37.c = new wsy();
        tas tasVar37 = new tas(a37.a());
        this.K = tasVar37;
        agmi a38 = agmk.a();
        a38.d = 2;
        a38.c(true);
        a38.d(true);
        a38.b = new taq(2);
        a38.a = "participants.duplicate_of";
        a38.c = new wsy();
        tas tasVar38 = new tas(a38.a());
        this.L = tasVar38;
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.a = "participants.cms_life_cycle";
        a39.c = new wsy();
        tas tasVar39 = new tas(a39.a());
        this.M = tasVar39;
        agmi a40 = agmk.a();
        a40.d = 1;
        a40.a = "participants.norm_ui_status";
        a40.c = new wsy();
        tas tasVar40 = new tas(a40.a());
        this.N = tasVar40;
        agmi a41 = agmk.a();
        a41.d = 4;
        a41.a = "participants.last_modified_by_key";
        a41.c = new wsy();
        tas tasVar41 = new tas(a41.a());
        this.O = tasVar41;
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "participants.name_source";
        a42.c = new wsy();
        tas tasVar42 = new tas(a42.a());
        this.P = tasVar42;
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "participants.photo_source";
        a43.c = new wsy();
        tas tasVar43 = new tas(a43.a());
        this.Q = tasVar43;
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "participants.profile_photo_user_preference";
        a44.c = new wsy();
        tas tasVar44 = new tas(a44.a());
        this.R = tasVar44;
        agmi a45 = agmk.a();
        a45.d = 5;
        a45.a = "participants.contact_metadata";
        a45.c = new wsy();
        tas tasVar45 = new tas(a45.a());
        this.S = tasVar45;
        this.T = new tas[]{tasVar, tasVar2, tasVar3, tasVar4, tasVar5, tasVar6, tasVar7, tasVar8, tasVar9, tasVar10, tasVar11, tasVar12, tasVar13, tasVar14, tasVar15, tasVar16, tasVar17, tasVar18, tasVar19, tasVar20, tasVar21, tasVar22, tasVar23, tasVar24, tasVar25, tasVar26, tasVar27, tasVar28, tasVar29, tasVar30, tasVar31, tasVar32, tasVar33, tasVar34, tasVar35, tasVar36, tasVar37, tasVar38, tasVar39, tasVar40, tasVar41, tasVar42, tasVar43, tasVar44, tasVar45};
    }
}
