package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class tbh {
    public final tbi A;
    public final tbi B;
    public final tbi C;
    public final tbi D;
    public final tbi E;
    public final tbi F;
    public final tbi G;
    public final tbi H;
    public final tbi I;
    public final tbi J;
    public final tbi K;
    public final tbi L;
    public final tbi M;
    public final tbi N;
    public final tbi O;
    public final tbi P;
    public final tbi Q;
    public final tbi R;
    public final tbi S;
    public final tbi T;
    public final tbi U;
    public final tbi V;
    public final tbi W;
    public final tbi X;
    public final tbi Y;
    public final tbi[] Z;
    public final tbi a;
    public final tbi b;
    public final tbi c;
    public final tbi d;
    public final tbi e;
    public final tbi f;
    public final tbi g;
    public final tbi h;
    public final tbi i;
    public final tbi j;
    public final tbi k;
    public final tbi l;
    public final tbi m;
    public final tbi n;
    public final tbi o;
    public final tbi p;
    public final tbi q;
    public final tbi r;
    public final tbi s;
    public final tbi t;
    public final tbi u;
    public final tbi v;
    public final tbi w;
    public final tbi x;
    public final tbi y;
    public final tbi z;

    public tbh() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "parts._id";
        a.c = new wsy();
        tbi tbiVar = new tbi(a.a());
        this.a = tbiVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.c(true);
        a2.d(true);
        a2.a = "parts.message_id";
        a2.c = new wsy();
        tbi tbiVar2 = new tbi(a2.a());
        this.b = tbiVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "parts.text";
        a3.c = new wsy();
        tbi tbiVar3 = new tbi(a3.a());
        this.c = tbiVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "parts.uri";
        a4.c = new wsy();
        tbi tbiVar4 = new tbi(a4.a());
        this.d = tbiVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.c(true);
        a5.a = "parts.content_type";
        a5.c = new wsy();
        tbi tbiVar5 = new tbi(a5.a());
        this.e = tbiVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "parts.original_uri";
        a6.c = new wsy();
        tbi tbiVar6 = new tbi(a6.a());
        this.f = tbiVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "parts.storage_uri";
        a7.c = new wsy();
        tbi tbiVar7 = new tbi(a7.a());
        this.g = tbiVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "parts.width";
        a8.c = new wsy();
        tbi tbiVar8 = new tbi(a8.a());
        this.h = tbiVar8;
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "parts.height";
        a9.c = new wsy();
        tbi tbiVar9 = new tbi(a9.a());
        this.i = tbiVar9;
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "parts.timestamp";
        a10.c = new wsy();
        tbi tbiVar10 = new tbi(a10.a());
        this.j = tbiVar10;
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.c(true);
        a11.a = "parts.output_uri";
        a11.c = new wsy();
        tbi tbiVar11 = new tbi(a11.a());
        this.k = tbiVar11;
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "parts.target_size";
        a12.c = new wsy();
        tbi tbiVar12 = new tbi(a12.a());
        this.l = tbiVar12;
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "parts.processing_status";
        a13.c = new wsy();
        tbi tbiVar13 = new tbi(a13.a());
        this.m = tbiVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "parts.cms_attachment_processing_status";
        a14.c = new wsy();
        tbi tbiVar14 = new tbi(a14.a());
        this.n = tbiVar14;
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.i(true);
        a15.c(true);
        a15.d(true);
        a15.a = "parts.conversation_id";
        a15.c = new wsy();
        tbi tbiVar15 = new tbi(a15.a());
        this.o = tbiVar15;
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "parts.sticker_set_id";
        a16.c = new wsy();
        tbi tbiVar16 = new tbi(a16.a());
        this.p = tbiVar16;
        agmi a17 = agmk.a();
        a17.d = 1;
        a17.a = "parts.sticker_id";
        a17.c = new wsy();
        tbi tbiVar17 = new tbi(a17.a());
        this.q = tbiVar17;
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "parts.media_modified_timestamp";
        a18.c = new wsy();
        tbi tbiVar18 = new tbi(a18.a());
        this.r = tbiVar18;
        agmi a19 = agmk.a();
        a19.d = 3;
        a19.a = "parts.longitude";
        a19.c = new wsy();
        tbi tbiVar19 = new tbi(a19.a());
        this.s = tbiVar19;
        agmi a20 = agmk.a();
        a20.d = 3;
        a20.a = "parts.latitude";
        a20.c = new wsy();
        tbi tbiVar20 = new tbi(a20.a());
        this.t = tbiVar20;
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "parts.preview_content_uri";
        a21.c = new wsy();
        tbi tbiVar21 = new tbi(a21.a());
        this.u = tbiVar21;
        agmi a22 = agmk.a();
        a22.d = 4;
        a22.c(true);
        a22.a = "parts.preview_content_type";
        a22.c = new wsy();
        tbi tbiVar22 = new tbi(a22.a());
        this.v = tbiVar22;
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.a = "parts.fallback_uri";
        a23.c = new wsy();
        tbi tbiVar23 = new tbi(a23.a());
        this.w = tbiVar23;
        agmi a24 = agmk.a();
        a24.d = 1;
        a24.a = "parts.source";
        a24.c = new wsy();
        tbi tbiVar24 = new tbi(a24.a());
        this.x = tbiVar24;
        agmi a25 = agmk.a();
        a25.d = 1;
        a25.a = "parts.bundle_index";
        a25.c = new wsy();
        tbi tbiVar25 = new tbi(a25.a());
        this.y = tbiVar25;
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.a = "parts.blob_id";
        a26.c = new wsy();
        tbi tbiVar26 = new tbi(a26.a());
        this.z = tbiVar26;
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.a = "parts.blob_gaia_email";
        a27.c = new wsy();
        tbi tbiVar27 = new tbi(a27.a());
        this.A = tbiVar27;
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "parts.cms_full_size_blob_id";
        a28.c = new wsy();
        tbi tbiVar28 = new tbi(a28.a());
        this.B = tbiVar28;
        agmi a29 = agmk.a();
        a29.d = 5;
        a29.a = "parts.cms_media_encryption_key";
        a29.c = new wsy();
        tbi tbiVar29 = new tbi(a29.a());
        this.C = tbiVar29;
        agmi a30 = agmk.a();
        a30.d = 5;
        a30.a = "parts.cms_compressed_media_encryption_key";
        a30.c = new wsy();
        tbi tbiVar30 = new tbi(a30.a());
        this.D = tbiVar30;
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "parts.blob_upload_permanent_failure";
        a31.c = new wsy();
        tbi tbiVar31 = new tbi(a31.a());
        this.E = tbiVar31;
        agmi a32 = agmk.a();
        a32.d = 1;
        a32.a = "parts.blob_upload_timestamp";
        a32.c = new wsy();
        tbi tbiVar32 = new tbi(a32.a());
        this.F = tbiVar32;
        agmi a33 = agmk.a();
        a33.d = 4;
        a33.a = "parts.expressive_sticker_name";
        a33.c = new wsy();
        tbi tbiVar33 = new tbi(a33.a());
        this.G = tbiVar33;
        agmi a34 = agmk.a();
        a34.d = 4;
        a34.a = "parts.file_name";
        a34.c = new wsy();
        tbi tbiVar34 = new tbi(a34.a());
        this.H = tbiVar34;
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "parts.duration";
        a35.c = new wsy();
        tbi tbiVar35 = new tbi(a35.a());
        this.I = tbiVar35;
        agmi a36 = agmk.a();
        a36.d = 4;
        a36.a = "parts.compressed_blob_id";
        a36.c = new wsy();
        tbi tbiVar36 = new tbi(a36.a());
        this.J = tbiVar36;
        agmi a37 = agmk.a();
        a37.d = 4;
        a37.a = "parts.cms_compressed_blob_id";
        a37.c = new wsy();
        tbi tbiVar37 = new tbi(a37.a());
        this.K = tbiVar37;
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "parts.compressed_blob_upload_permanent_failure";
        a38.c = new wsy();
        tbi tbiVar38 = new tbi(a38.a());
        this.L = tbiVar38;
        agmi a39 = agmk.a();
        a39.d = 1;
        a39.a = "parts.compressed_blob_upload_timestamp";
        a39.c = new wsy();
        tbi tbiVar39 = new tbi(a39.a());
        this.M = tbiVar39;
        agmi a40 = agmk.a();
        a40.d = 5;
        a40.a = "parts.media_encryption_key";
        a40.c = new wsy();
        tbi tbiVar40 = new tbi(a40.a());
        this.N = tbiVar40;
        agmi a41 = agmk.a();
        a41.d = 5;
        a41.a = "parts.compressed_media_encryption_key";
        a41.c = new wsy();
        tbi tbiVar41 = new tbi(a41.a());
        this.O = tbiVar41;
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "parts.missing_entry_in_telephony";
        a42.c = new wsy();
        tbi tbiVar42 = new tbi(a42.a());
        this.P = tbiVar42;
        agmi a43 = agmk.a();
        a43.d = 1;
        a43.a = "parts.awaiting_reverse_sync";
        a43.c = new wsy();
        tbi tbiVar43 = new tbi(a43.a());
        this.Q = tbiVar43;
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "parts.file_size_bytes";
        a44.c = new wsy();
        tbi tbiVar44 = new tbi(a44.a());
        this.R = tbiVar44;
        agmi a45 = agmk.a();
        a45.d = 4;
        a45.c(true);
        a45.a = "parts.local_cache_path";
        a45.c = new wsy();
        tbi tbiVar45 = new tbi(a45.a());
        this.S = tbiVar45;
        agmi a46 = agmk.a();
        a46.d = 1;
        a46.a = "parts.media_send_type";
        a46.c = new wsy();
        tbi tbiVar46 = new tbi(a46.a());
        this.T = tbiVar46;
        agmi a47 = agmk.a();
        a47.d = 5;
        a47.a = "parts.voice_metadata";
        a47.c = new wsy();
        tbi tbiVar47 = new tbi(a47.a());
        this.U = tbiVar47;
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "parts.validation_status";
        a48.c = new wsy();
        tbi tbiVar48 = new tbi(a48.a());
        this.V = tbiVar48;
        agmi a49 = agmk.a();
        a49.d = 4;
        a49.a = "parts.processing_id";
        a49.c = new wsy();
        tbi tbiVar49 = new tbi(a49.a());
        this.W = tbiVar49;
        agmi a50 = agmk.a();
        a50.d = 1;
        a50.a = "parts.rich_card_media_download_failure_reason";
        a50.c = new wsy();
        tbi tbiVar50 = new tbi(a50.a());
        this.X = tbiVar50;
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.a = "parts.image_display_state";
        a51.c = new wsy();
        tbi tbiVar51 = new tbi(a51.a());
        this.Y = tbiVar51;
        this.Z = new tbi[]{tbiVar, tbiVar2, tbiVar3, tbiVar4, tbiVar5, tbiVar6, tbiVar7, tbiVar8, tbiVar9, tbiVar10, tbiVar11, tbiVar12, tbiVar13, tbiVar14, tbiVar15, tbiVar16, tbiVar17, tbiVar18, tbiVar19, tbiVar20, tbiVar21, tbiVar22, tbiVar23, tbiVar24, tbiVar25, tbiVar26, tbiVar27, tbiVar28, tbiVar29, tbiVar30, tbiVar31, tbiVar32, tbiVar33, tbiVar34, tbiVar35, tbiVar36, tbiVar37, tbiVar38, tbiVar39, tbiVar40, tbiVar41, tbiVar42, tbiVar43, tbiVar44, tbiVar45, tbiVar46, tbiVar47, tbiVar48, tbiVar49, tbiVar50, tbiVar51};
    }
}
