package defpackage;

import android.content.Context;
import com.google.android.apps.messaging.shared.datamodel.data.datatypes.ConversationIdType;
import com.google.android.apps.messaging.shared.datamodel.databasegen.tabledefinitions.ParticipantsTable;
import com.google.common.util.concurrent.ListenableFuture;
import j$.util.Optional;
import java.util.concurrent.Callable;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class tby {
    public final Object a;
    public final Object b;
    public final Object c;
    public final Object d;
    public final Object e;
    public final Object f;
    public final Object g;
    public final Object h;
    public final Object i;
    public final Object j;
    public final Object k;
    public final Object l;
    public final Object m;
    public final Object n;
    public final Object o;
    public final Object p;
    public final Object q;
    public final Object r;
    public final Object s;

    public tby(Context context, uac uacVar, ansy ansyVar, ahiy ahiyVar, zai zaiVar, anen anenVar, anen anenVar2, qya qyaVar, armf armfVar, armf armfVar2, armf armfVar3, yhw yhwVar, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10) {
        this.p = context;
        this.o = uacVar;
        this.l = anenVar;
        this.n = ahiyVar;
        this.r = ansyVar;
        this.q = zaiVar;
        this.d = anenVar2;
        this.e = qyaVar;
        this.a = armfVar;
        this.h = armfVar2;
        this.i = armfVar3;
        this.m = yhwVar;
        this.b = armfVar4;
        this.k = armfVar5;
        this.c = armfVar6;
        this.g = armfVar7;
        this.f = armfVar8;
        this.s = armfVar9;
        this.j = armfVar10;
    }

    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r10v1, types: [java.util.concurrent.Executor, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r11v1, types: [java.util.concurrent.Executor, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r11v8, types: [java.util.concurrent.Executor, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v3, types: [java.util.concurrent.Executor, java.lang.Object] */
    public final akul a(ConversationIdType conversationIdType, sne sneVar, final ListenableFuture listenableFuture) {
        final akul ai = aktp.ai(new gvk(sneVar, 12), this.l);
        final ListenableFuture Z = aktp.Z(listenableFuture, new ikd(this, conversationIdType, 6), andi.a);
        final ListenableFuture i = ai.i(new ici(this, 15), this.d);
        final akul ai2 = aktp.ai(new vwu(this, conversationIdType, 1), this.l);
        final akul i2 = ai.i(new ici(this, 16), andi.a);
        final akul i3 = ai.i(new ici(this, 17), this.l);
        return aktp.an(ai, listenableFuture, Z, i3, ai2, i, i2).h(new Callable() { // from class: izp
            @Override // java.util.concurrent.Callable
            public final Object call() {
                smr smrVar = (smr) albo.bQ(akul.this);
                rsa rsaVar = (rsa) albo.bQ(listenableFuture);
                Optional optional = (Optional) albo.bQ(i3);
                ParticipantsTable.BindData bindData = (ParticipantsTable.BindData) albo.bQ(Z);
                ParticipantsTable.BindData bindData2 = (ParticipantsTable.BindData) albo.bQ(ai2);
                boolean booleanValue = ((Boolean) albo.bQ(i)).booleanValue();
                Optional optional2 = (Optional) albo.bQ(i2);
                tqc A = smrVar.A();
                if (A == null) {
                    A = tqc.UNARCHIVED;
                }
                return new rsf(smrVar, rsaVar, optional, bindData, bindData2, booleanValue, A, optional2);
            }
        }, andi.a);
    }

    public tby(char[] cArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "participants_backup._id";
        a.c = new wsy();
        rou rouVar = new rou(a.a());
        this.j = rouVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.c(true);
        a2.d(true);
        a2.b = new roi(3);
        a2.a = "participants_backup.my_identity_token_foreign_key";
        a2.c = new wsy();
        rou rouVar2 = new rou(a2.a());
        this.c = rouVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.c(true);
        a3.a = "participants_backup.normalized_destination";
        a3.c = new wsy();
        rou rouVar3 = new rou(a3.a());
        this.g = rouVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "participants_backup.send_destination";
        a4.c = new wsy();
        rou rouVar4 = new rou(a4.a());
        this.i = rouVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "participants_backup.display_destination";
        a5.c = new wsy();
        rou rouVar5 = new rou(a5.a());
        this.n = rouVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "participants_backup.first_name";
        a6.c = new wsy();
        rou rouVar6 = new rou(a6.a());
        this.d = rouVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "participants_backup.full_name";
        a7.c = new wsy();
        rou rouVar7 = new rou(a7.a());
        this.a = rouVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "participants_backup.is_self";
        a8.c = new wsy();
        rou rouVar8 = new rou(a8.a());
        this.h = rouVar8;
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "participants_backup.blocked";
        a9.c = new wsy();
        rou rouVar9 = new rou(a9.a());
        this.p = rouVar9;
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "participants_backup.participant_type";
        a10.c = new wsy();
        rou rouVar10 = new rou(a10.a());
        this.k = rouVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "participants_backup.is_spam";
        a11.c = new wsy();
        rou rouVar11 = new rou(a11.a());
        this.f = rouVar11;
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "participants_backup.is_spam_source";
        a12.c = new wsy();
        rou rouVar12 = new rou(a12.a());
        this.b = rouVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "participants_backup.country_code";
        a13.c = new wsy();
        rou rouVar13 = new rou(a13.a());
        this.r = rouVar13;
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "participants_backup.color_palette_index";
        a14.c = new wsy();
        rou rouVar14 = new rou(a14.a());
        this.m = rouVar14;
        agmi a15 = agmk.a();
        a15.d = 1;
        a15.a = "participants_backup.color_type";
        a15.c = new wsy();
        rou rouVar15 = new rou(a15.a());
        this.q = rouVar15;
        agmi a16 = agmk.a();
        a16.d = 1;
        a16.a = "participants_backup.extended_color";
        a16.c = new wsy();
        rou rouVar16 = new rou(a16.a());
        this.l = rouVar16;
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.c(true);
        a17.a = "participants_backup.cms_id";
        a17.c = new wsy();
        rou rouVar17 = new rou(a17.a());
        this.e = rouVar17;
        agmi a18 = agmk.a();
        a18.d = 1;
        a18.a = "participants_backup.cms_life_cycle";
        a18.c = new wsy();
        rou rouVar18 = new rou(a18.a());
        this.o = rouVar18;
        this.s = new rou[]{rouVar, rouVar2, rouVar3, rouVar4, rouVar5, rouVar6, rouVar7, rouVar8, rouVar9, rouVar10, rouVar11, rouVar12, rouVar13, rouVar14, rouVar15, rouVar16, rouVar17, rouVar18};
    }

    public tby(byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.i(true);
        a.c(true);
        a.a = "contacts.cp2_id";
        a.e(true);
        a.c = new wsy();
        sjf sjfVar = new sjf(a.a());
        this.q = sjfVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.i(true);
        a2.c(true);
        a2.a = "contacts.contact_id";
        a2.c = new wsy();
        sjf sjfVar2 = new sjf(a2.a());
        this.o = sjfVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.i(true);
        a3.c(true);
        a3.a = "contacts.lookup_key";
        a3.c = new wsy();
        sjf sjfVar3 = new sjf(a3.a());
        this.h = sjfVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.i(true);
        a4.c(true);
        a4.a = "contacts.phone_number";
        a4.c = new wsy();
        sjf sjfVar4 = new sjf(a4.a());
        this.c = sjfVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.i(true);
        a5.a = "contacts.display_name";
        a5.c = new wsy();
        sjf sjfVar5 = new sjf(a5.a());
        this.n = sjfVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "contacts.given_name";
        a6.c = new wsy();
        sjf sjfVar6 = new sjf(a6.a());
        this.d = sjfVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "contacts.family_name";
        a7.c = new wsy();
        sjf sjfVar7 = new sjf(a7.a());
        this.l = sjfVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "contacts.photo";
        a8.c = new wsy();
        sjf sjfVar8 = new sjf(a8.a());
        this.g = sjfVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "contacts.thumbnail";
        a9.c = new wsy();
        sjf sjfVar9 = new sjf(a9.a());
        this.i = sjfVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "contacts.birthday";
        a10.c = new wsy();
        sjf sjfVar10 = new sjf(a10.a());
        this.e = sjfVar10;
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.a = "contacts.anniversary";
        a11.c = new wsy();
        sjf sjfVar11 = new sjf(a11.a());
        this.p = sjfVar11;
        agmi a12 = agmk.a();
        a12.d = 2;
        a12.i(true);
        a12.a = "contacts.last_updated_timestamp";
        a12.c = new wsy();
        sjf sjfVar12 = new sjf(a12.a());
        this.a = sjfVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.i(true);
        a13.a = "contacts.sort_key";
        a13.c = new wsy();
        sjf sjfVar13 = new sjf(a13.a());
        this.k = sjfVar13;
        agmi a14 = agmk.a();
        a14.d = 4;
        a14.i(true);
        a14.c(true);
        a14.a = "contacts.phonebook_label";
        a14.c = new wsy();
        sjf sjfVar14 = new sjf(a14.a());
        this.b = sjfVar14;
        agmi a15 = agmk.a();
        a15.d = 2;
        a15.c(true);
        a15.a = "contacts.phonebook_bucket";
        a15.c = new wsy();
        sjf sjfVar15 = new sjf(a15.a());
        this.f = sjfVar15;
        agmi a16 = agmk.a();
        a16.d = 2;
        a16.a = "contacts.contact_type";
        a16.c = new wsy();
        sjf sjfVar16 = new sjf(a16.a());
        this.m = sjfVar16;
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.a = "contacts.type_label";
        a17.c = new wsy();
        sjf sjfVar17 = new sjf(a17.a());
        this.j = sjfVar17;
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.i(true);
        a18.a = "contacts.display_destination";
        a18.c = new wsy();
        sjf sjfVar18 = new sjf(a18.a());
        this.r = sjfVar18;
        this.s = new sjf[]{sjfVar, sjfVar2, sjfVar3, sjfVar4, sjfVar5, sjfVar6, sjfVar7, sjfVar8, sjfVar9, sjfVar10, sjfVar11, sjfVar12, sjfVar13, sjfVar14, sjfVar15, sjfVar16, sjfVar17, sjfVar18};
    }

    public tby() {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "pending_incoming_message_rcs_table.rcs_message_id";
        a.c = new wsy();
        tbz tbzVar = new tbz(a.a());
        this.a = tbzVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.c(true);
        a2.a = "pending_incoming_message_rcs_table.remote_user_id";
        a2.c = new wsy();
        tbz tbzVar2 = new tbz(a2.a());
        this.b = tbzVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "pending_incoming_message_rcs_table.self_identity";
        a3.c = new wsy();
        tbz tbzVar3 = new tbz(a3.a());
        this.c = tbzVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "pending_incoming_message_rcs_table.raw_text";
        a4.c = new wsy();
        tbz tbzVar4 = new tbz(a4.a());
        this.d = tbzVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "pending_incoming_message_rcs_table.content_type";
        a5.c = new wsy();
        tbz tbzVar5 = new tbz(a5.a());
        this.e = tbzVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "pending_incoming_message_rcs_table.remote_instance";
        a6.c = new wsy();
        tbz tbzVar6 = new tbz(a6.a());
        this.f = tbzVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "pending_incoming_message_rcs_table.sent_timestamp";
        a7.c = new wsy();
        tbz tbzVar7 = new tbz(a7.a());
        this.g = tbzVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.c(true);
        a8.a = "pending_incoming_message_rcs_table.received_timestamp";
        a8.c = new wsy();
        tbz tbzVar8 = new tbz(a8.a());
        this.h = tbzVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "pending_incoming_message_rcs_table.sip_alias";
        a9.c = new wsy();
        tbz tbzVar9 = new tbz(a9.a());
        this.i = tbzVar9;
        agmi a10 = agmk.a();
        a10.d = 2;
        a10.a = "pending_incoming_message_rcs_table.spam_verdict";
        a10.c = new wsy();
        tbz tbzVar10 = new tbz(a10.a());
        this.j = tbzVar10;
        agmi a11 = agmk.a();
        a11.d = 2;
        a11.a = "pending_incoming_message_rcs_table.session_id";
        a11.c = new wsy();
        tbz tbzVar11 = new tbz(a11.a());
        this.k = tbzVar11;
        agmi a12 = agmk.a();
        a12.d = 2;
        a12.a = "pending_incoming_message_rcs_table.message_status";
        a12.c = new wsy();
        tbz tbzVar12 = new tbz(a12.a());
        this.l = tbzVar12;
        agmi a13 = agmk.a();
        a13.d = 5;
        a13.a = "pending_incoming_message_rcs_table.custom_headers";
        a13.c = new wsy();
        tbz tbzVar13 = new tbz(a13.a());
        this.m = tbzVar13;
        agmi a14 = agmk.a();
        a14.d = 2;
        a14.a = "pending_incoming_message_rcs_table.is_group";
        a14.c = new wsy();
        tbz tbzVar14 = new tbz(a14.a());
        this.n = tbzVar14;
        agmi a15 = agmk.a();
        a15.d = 4;
        a15.a = "pending_incoming_message_rcs_table.conversation_id";
        a15.c = new wsy();
        tbz tbzVar15 = new tbz(a15.a());
        this.o = tbzVar15;
        agmi a16 = agmk.a();
        a16.d = 4;
        a16.a = "pending_incoming_message_rcs_table.conference_uri";
        a16.c = new wsy();
        tbz tbzVar16 = new tbz(a16.a());
        this.p = tbzVar16;
        agmi a17 = agmk.a();
        a17.d = 2;
        a17.i(true);
        a17.a = "pending_incoming_message_rcs_table.is_delivery_report_requested";
        a17.c = new wsy();
        tbz tbzVar17 = new tbz(a17.a());
        this.q = tbzVar17;
        agmi a18 = agmk.a();
        a18.d = 2;
        a18.i(true);
        a18.a = "pending_incoming_message_rcs_table.is_display_report_requested";
        a18.c = new wsy();
        tbz tbzVar18 = new tbz(a18.a());
        this.r = tbzVar18;
        this.s = new tbz[]{tbzVar, tbzVar2, tbzVar3, tbzVar4, tbzVar5, tbzVar6, tbzVar7, tbzVar8, tbzVar9, tbzVar10, tbzVar11, tbzVar12, tbzVar13, tbzVar14, tbzVar15, tbzVar16, tbzVar17, tbzVar18};
    }
}
