package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class toc {
    public static final String[] a = {"user_refs_concat_view.message_id_user_references", "user_refs_concat_view.participant_id_user_references", "user_refs_concat_view.user_ref_datetime_user_references", "user_refs_concat_view.user_references__ROWID_user_references", "user_refs_concat_view.user_ref_display_name", "user_refs_concat_view.user_ref_profile_photo_uri", "user_refs_concat_view.user_ref_full_name", "user_refs_concat_view.user_ref_lookup_key", "user_refs_concat_view.normalized_destination_participants", "user_refs_concat_view.color_palette_index_participants", "user_refs_concat_view.color_type_participants", "user_refs_concat_view.extended_color_participants", "user_refs_concat_view.participants__ROWID_participants"};

    static {
        alok alokVar = new alok();
        alokVar.h("user_refs_concat_view.user_ref_display_name", 0);
        alokVar.h("user_refs_concat_view.user_ref_profile_photo_uri", 0);
        alokVar.h("user_refs_concat_view.user_ref_full_name", 0);
        alokVar.h("user_refs_concat_view.user_ref_lookup_key", 0);
        alokVar.h("user_refs_concat_view.color_type_participants", 1000);
        alokVar.h("user_refs_concat_view.extended_color_participants", 10027);
        alokVar.b();
        d.aF();
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.i(true);
        a2.c(true);
        a2.d(true);
        a2.b = new tls(16);
        a2.a = "user_refs_concat_view.message_id_user_references";
        a2.e(true);
        a2.c = new wsy();
        a2.a();
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.i(true);
        a3.c(true);
        a3.d(true);
        a3.b = new tls(17);
        a3.a = "user_refs_concat_view.participant_id_user_references";
        a3.e(true);
        a3.c = new wsy();
        a3.a();
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "user_refs_concat_view.user_ref_datetime_user_references";
        a4.c = new wsy();
        a4.a();
        agmi a5 = agmk.a();
        a5.d = 8;
        a5.a = "user_refs_concat_view.user_references__ROWID_user_references";
        a5.c = new wsy();
        a5.a();
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.j(true);
        a6.f(true);
        a6.c(true);
        a6.a = "user_refs_concat_view._id_user_references";
        a6.c = new wsy();
        a6.a();
        agmi a7 = agmk.a();
        a7.d = 8;
        a7.a = "user_refs_concat_view.user_ref_display_name";
        a7.c = new wsy();
        a7.a();
        agmi a8 = agmk.a();
        a8.d = 8;
        a8.a = "user_refs_concat_view.user_ref_profile_photo_uri";
        a8.c = new wsy();
        a8.a();
        agmi a9 = agmk.a();
        a9.d = 8;
        a9.a = "user_refs_concat_view.user_ref_full_name";
        a9.c = new wsy();
        a9.a();
        agmi a10 = agmk.a();
        a10.d = 8;
        a10.a = "user_refs_concat_view.user_ref_lookup_key";
        a10.c = new wsy();
        a10.a();
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.c(true);
        a11.a = "user_refs_concat_view.normalized_destination_participants";
        a11.e(true);
        a11.c = new wsy();
        a11.a();
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "user_refs_concat_view.color_palette_index_participants";
        a12.c = new wsy();
        a12.a();
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "user_refs_concat_view.color_type_participants";
        a13.c = new wsy();
        a13.a();
        agmi a14 = agmk.a();
        a14.d = 1;
        a14.a = "user_refs_concat_view.extended_color_participants";
        a14.c = new wsy();
        a14.a();
        agmi a15 = agmk.a();
        a15.d = 8;
        a15.a = "user_refs_concat_view.participants__ROWID_participants";
        a15.c = new wsy();
        a15.a();
        agmi a16 = agmk.a();
        a16.d = 2;
        a16.j(true);
        a16.f(true);
        a16.c(true);
        a16.a = "user_refs_concat_view._id_participants";
        a16.c = new wsy();
        a16.a();
        agmi a17 = agmk.a();
        a17.d = 4;
        a17.c(true);
        a17.a = "user_refs_concat_view.my_identity_token_participants";
        a17.c = new wsy();
        a17.a();
        agmi a18 = agmk.a();
        a18.d = 4;
        a18.c(true);
        a18.d(true);
        a18.b = new tls(19);
        a18.a = "user_refs_concat_view.my_identity_token_foreign_key_participants";
        a18.c = new wsy();
        a18.a();
        agmi a19 = agmk.a();
        a19.d = 1;
        a19.c(true);
        a19.a = "user_refs_concat_view.sub_id_participants";
        a19.e(true);
        a19.c = new wsy();
        a19.a();
        agmi a20 = agmk.a();
        a20.d = 1;
        a20.a = "user_refs_concat_view.sim_slot_id_participants";
        a20.c = new wsy();
        a20.a();
        agmi a21 = agmk.a();
        a21.d = 4;
        a21.a = "user_refs_concat_view.send_destination_participants";
        a21.c = new wsy();
        a21.a();
        agmi a22 = agmk.a();
        a22.d = 4;
        a22.a = "user_refs_concat_view.display_destination_participants";
        a22.c = new wsy();
        a22.a();
        agmi a23 = agmk.a();
        a23.d = 4;
        a23.j(true);
        a23.c(true);
        a23.a = "user_refs_concat_view.comparable_destination_participants";
        a23.e(true);
        a23.c = new wsy();
        a23.a();
        agmi a24 = agmk.a();
        a24.d = 4;
        a24.a = "user_refs_concat_view.country_code_participants";
        a24.c = new wsy();
        a24.a();
        agmi a25 = agmk.a();
        a25.d = 2;
        a25.j(true);
        a25.c(true);
        a25.a = "user_refs_concat_view.recipient_id_participants";
        a25.e(true);
        a25.c = new wsy();
        a25.a();
        agmi a26 = agmk.a();
        a26.d = 4;
        a26.a = "user_refs_concat_view.recipient_canonical_address_participants";
        a26.c = new wsy();
        a26.a();
        agmi a27 = agmk.a();
        a27.d = 4;
        a27.a = "user_refs_concat_view.full_name_participants";
        a27.c = new wsy();
        a27.a();
        agmi a28 = agmk.a();
        a28.d = 4;
        a28.a = "user_refs_concat_view.first_name_participants";
        a28.c = new wsy();
        a28.a();
        agmi a29 = agmk.a();
        a29.d = 4;
        a29.a = "user_refs_concat_view.profile_photo_uri_participants";
        a29.c = new wsy();
        a29.a();
        agmi a30 = agmk.a();
        a30.d = 4;
        a30.a = "user_refs_concat_view.contact_photo_uri_participants";
        a30.c = new wsy();
        a30.a();
        agmi a31 = agmk.a();
        a31.d = 1;
        a31.a = "user_refs_concat_view.contact_id_participants";
        a31.c = new wsy();
        a31.a();
        agmi a32 = agmk.a();
        a32.d = 4;
        a32.a = "user_refs_concat_view.lookup_key_participants";
        a32.c = new wsy();
        a32.a();
        agmi a33 = agmk.a();
        a33.d = 1;
        a33.a = "user_refs_concat_view.blocked_participants";
        a33.c = new wsy();
        a33.a();
        agmi a34 = agmk.a();
        a34.d = 4;
        a34.a = "user_refs_concat_view.subscription_name_participants";
        a34.c = new wsy();
        a34.a();
        agmi a35 = agmk.a();
        a35.d = 1;
        a35.a = "user_refs_concat_view.subscription_color_participants";
        a35.c = new wsy();
        a35.a();
        agmi a36 = agmk.a();
        a36.d = 4;
        a36.a = "user_refs_concat_view.contact_destination_participants";
        a36.c = new wsy();
        a36.a();
        agmi a37 = agmk.a();
        a37.d = 1;
        a37.a = "user_refs_concat_view.participant_type_participants";
        a37.c = new wsy();
        a37.a();
        agmi a38 = agmk.a();
        a38.d = 1;
        a38.a = "user_refs_concat_view.video_reachability_participants";
        a38.c = new wsy();
        a38.a();
        agmi a39 = agmk.a();
        a39.d = 4;
        a39.a = "user_refs_concat_view.alias_participants";
        a39.c = new wsy();
        a39.a();
        agmi a40 = agmk.a();
        a40.d = 1;
        a40.a = "user_refs_concat_view.is_spam_participants";
        a40.c = new wsy();
        a40.a();
        agmi a41 = agmk.a();
        a41.d = 1;
        a41.a = "user_refs_concat_view.is_rcs_available_participants";
        a41.c = new wsy();
        a41.a();
        agmi a42 = agmk.a();
        a42.d = 1;
        a42.a = "user_refs_concat_view.is_spam_source_participants";
        a42.c = new wsy();
        a42.a();
        agmi a43 = agmk.a();
        a43.d = 4;
        a43.j(true);
        a43.c(true);
        a43.a = "user_refs_concat_view.cms_id_participants";
        a43.e(true);
        a43.c = new wsy();
        a43.a();
        agmi a44 = agmk.a();
        a44.d = 1;
        a44.a = "user_refs_concat_view.latest_verification_status_participants";
        a44.c = new wsy();
        a44.a();
        agmi a45 = agmk.a();
        a45.d = 4;
        a45.a = "user_refs_concat_view.profile_photo_blob_id_participants";
        a45.c = new wsy();
        a45.a();
        agmi a46 = agmk.a();
        a46.d = 5;
        a46.a = "user_refs_concat_view.profile_photo_encryption_key_participants";
        a46.c = new wsy();
        a46.a();
        agmi a47 = agmk.a();
        a47.d = 1;
        a47.a = "user_refs_concat_view.directory_id_participants";
        a47.c = new wsy();
        a47.a();
        agmi a48 = agmk.a();
        a48.d = 1;
        a48.a = "user_refs_concat_view.is_check_constraint_enabled_via_phenotype_participants";
        a48.c = new wsy();
        a48.a();
        agmi a49 = agmk.a();
        a49.d = 1;
        a49.a = "user_refs_concat_view.is_valid_phone_number_data_participants";
        a49.c = new wsy();
        a49.a();
        agmi a50 = agmk.a();
        a50.d = 2;
        a50.c(true);
        a50.d(true);
        a50.b = new tls(18);
        a50.a = "user_refs_concat_view.duplicate_of_participants";
        a50.c = new wsy();
        a50.a();
        agmi a51 = agmk.a();
        a51.d = 1;
        a51.a = "user_refs_concat_view.cms_life_cycle_participants";
        a51.c = new wsy();
        a51.a();
        agmi a52 = agmk.a();
        a52.d = 1;
        a52.a = "user_refs_concat_view.norm_ui_status_participants";
        a52.c = new wsy();
        a52.a();
        agmi a53 = agmk.a();
        a53.d = 4;
        a53.a = "user_refs_concat_view.last_modified_by_key_participants";
        a53.c = new wsy();
        a53.a();
        agmi a54 = agmk.a();
        a54.d = 1;
        a54.a = "user_refs_concat_view.name_source_participants";
        a54.c = new wsy();
        a54.a();
        agmi a55 = agmk.a();
        a55.d = 1;
        a55.a = "user_refs_concat_view.photo_source_participants";
        a55.c = new wsy();
        a55.a();
        agmi a56 = agmk.a();
        a56.d = 1;
        a56.a = "user_refs_concat_view.profile_photo_user_preference_participants";
        a56.c = new wsy();
        a56.a();
        agmi a57 = agmk.a();
        a57.d = 5;
        a57.a = "user_refs_concat_view.contact_metadata_participants";
        a57.c = new wsy();
        a57.a();
    }
}
