package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class toz {
    public final agmh a;
    public final agmh b;
    public final agmh c;
    public final agmh d;
    public final agmh e;
    public final agmh f;
    public final agmh g;
    final agmh[] h;

    public toz(byte[] bArr, byte[] bArr2) {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.i(true);
        a.f(true);
        a.c(true);
        a.a = "recent_gifs.original_image_url";
        a.c = new wsy();
        tft tftVar = new tft(a.a());
        this.g = tftVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.a = "recent_gifs.content_uri";
        a2.c = new wsy();
        tft tftVar2 = new tft(a2.a());
        this.b = tftVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.i(true);
        a3.a = "recent_gifs.domain";
        a3.c = new wsy();
        tft tftVar3 = new tft(a3.a());
        this.d = tftVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.i(true);
        a4.a = "recent_gifs.image_search_url";
        a4.c = new wsy();
        tft tftVar4 = new tft(a4.a());
        this.e = tftVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.i(true);
        a5.a = "recent_gifs.width";
        a5.c = new wsy();
        tft tftVar5 = new tft(a5.a());
        this.a = tftVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.i(true);
        a6.a = "recent_gifs.height";
        a6.c = new wsy();
        tft tftVar6 = new tft(a6.a());
        this.f = tftVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.i(true);
        a7.c(true);
        a7.a = "recent_gifs.last_used_timestamp";
        a7.c = new wsy();
        tft tftVar7 = new tft(a7.a());
        this.c = tftVar7;
        this.h = new tft[]{tftVar, tftVar2, tftVar3, tftVar4, tftVar5, tftVar6, tftVar7};
    }

    public toz(char[] cArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "self_profiles._id";
        a.c = new wsy();
        tku tkuVar = new tku(a.a());
        this.a = tkuVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.c(true);
        a2.d(true);
        a2.b = new tif(17);
        a2.a = "self_profiles.my_identity_token";
        a2.c = new wsy();
        tku tkuVar2 = new tku(a2.a());
        this.e = tkuVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "self_profiles.limited_profile_display_name";
        a3.c = new wsy();
        tku tkuVar3 = new tku(a3.a());
        this.f = tkuVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "self_profiles.photo_uri";
        a4.c = new wsy();
        tku tkuVar4 = new tku(a4.a());
        this.c = tkuVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "self_profiles.is_self_profile_shareable";
        a5.c = new wsy();
        tku tkuVar5 = new tku(a5.a());
        this.d = tkuVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.a = "self_profiles.belongs_to_self_gaia";
        a6.c = new wsy();
        tku tkuVar6 = new tku(a6.a());
        this.b = tkuVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "self_profiles.update_timestamp";
        a7.c = new wsy();
        tku tkuVar7 = new tku(a7.a());
        this.g = tkuVar7;
        this.h = new tku[]{tkuVar, tkuVar2, tkuVar3, tkuVar4, tkuVar5, tkuVar6, tkuVar7};
    }

    public toz(byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "stickers._id";
        a.c = new wsy();
        tmy tmyVar = new tmy(a.a());
        this.a = tmyVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.d(true);
        a2.a = "stickers.sticker_set_id";
        a2.c = new wsy();
        tmy tmyVar2 = new tmy(a2.a());
        this.g = tmyVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "stickers.sticker_id";
        a3.c = new wsy();
        tmy tmyVar3 = new tmy(a3.a());
        this.c = tmyVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "stickers.icon_uri_static";
        a4.c = new wsy();
        tmy tmyVar4 = new tmy(a4.a());
        this.e = tmyVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "stickers.icon_uri_animated";
        a5.c = new wsy();
        tmy tmyVar5 = new tmy(a5.a());
        this.f = tmyVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "stickers.display_name";
        a6.c = new wsy();
        tmy tmyVar6 = new tmy(a6.a());
        this.b = tmyVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "stickers.display_order";
        a7.c = new wsy();
        tmy tmyVar7 = new tmy(a7.a());
        this.d = tmyVar7;
        this.h = new tmy[]{tmyVar, tmyVar2, tmyVar3, tmyVar4, tmyVar5, tmyVar6, tmyVar7};
    }

    public toz() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "verified_sms_brands._id";
        a.c = new wsy();
        tpa tpaVar = new tpa(a.a());
        this.a = tpaVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.j(true);
        a2.i(true);
        a2.c(true);
        a2.a = "verified_sms_brands.brand_id";
        a2.c = new wsy();
        tpa tpaVar2 = new tpa(a2.a());
        this.b = tpaVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.i(true);
        a3.a = "verified_sms_brands.name";
        a3.c = new wsy();
        tpa tpaVar3 = new tpa(a3.a());
        this.c = tpaVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.i(true);
        a4.a = "verified_sms_brands.description";
        a4.c = new wsy();
        tpa tpaVar4 = new tpa(a4.a());
        this.d = tpaVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.i(true);
        a5.a = "verified_sms_brands.logo_url";
        a5.c = new wsy();
        tpa tpaVar5 = new tpa(a5.a());
        this.e = tpaVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "verified_sms_brands.logo_uri";
        a6.c = new wsy();
        tpa tpaVar6 = new tpa(a6.a());
        this.f = tpaVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.i(true);
        a7.a = "verified_sms_brands.version_token";
        a7.c = new wsy();
        tpa tpaVar7 = new tpa(a7.a());
        this.g = tpaVar7;
        this.h = new tpa[]{tpaVar, tpaVar2, tpaVar3, tpaVar4, tpaVar5, tpaVar6, tpaVar7};
    }
}
