package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class upt {
    public final agmh a;
    public final agmh b;
    public final agmh c;
    public final agmh d;
    public final agmh e;
    public final agmh f;
    public final agmh g;
    public final agmh h;
    public final agmh i;
    public final agmh j;
    public final agmh k;
    public final agmh[] l;

    public upt(byte[] bArr, byte[] bArr2) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "cms_dead_letter_queue._id";
        a.c = new wsy();
        sgy sgyVar = new sgy(a.a());
        this.a = sgyVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.c(true);
        a2.a = "cms_dead_letter_queue.cms_id";
        a2.c = new wsy();
        sgy sgyVar2 = new sgy(a2.a());
        this.b = sgyVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "cms_dead_letter_queue.cms_data_type";
        a3.c = new wsy();
        sgy sgyVar3 = new sgy(a3.a());
        this.e = sgyVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.c(true);
        a4.a = "cms_dead_letter_queue.abandoned_action";
        a4.c = new wsy();
        sgy sgyVar4 = new sgy(a4.a());
        this.d = sgyVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "cms_dead_letter_queue.failure_reason";
        a5.c = new wsy();
        sgy sgyVar5 = new sgy(a5.a());
        this.i = sgyVar5;
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.a = "cms_dead_letter_queue.bugle_table_type";
        a6.c = new wsy();
        sgy sgyVar6 = new sgy(a6.a());
        this.c = sgyVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.c(true);
        a7.a = "cms_dead_letter_queue.bugle_id";
        a7.c = new wsy();
        sgy sgyVar7 = new sgy(a7.a());
        this.f = sgyVar7;
        agmi a8 = agmk.a();
        a8.d = 5;
        a8.a = "cms_dead_letter_queue.cms_backup_parameters";
        a8.c = new wsy();
        sgy sgyVar8 = new sgy(a8.a());
        this.h = sgyVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.a = "cms_dead_letter_queue.backup_flags";
        a9.c = new wsy();
        sgy sgyVar9 = new sgy(a9.a());
        this.j = sgyVar9;
        agmi a10 = agmk.a();
        a10.d = 2;
        a10.a = "cms_dead_letter_queue.backup_dependency_table_type";
        a10.c = new wsy();
        sgy sgyVar10 = new sgy(a10.a());
        this.g = sgyVar10;
        agmi a11 = agmk.a();
        a11.d = 2;
        a11.a = "cms_dead_letter_queue.backup_dependency_bugle_id";
        a11.c = new wsy();
        sgy sgyVar11 = new sgy(a11.a());
        this.k = sgyVar11;
        this.l = new sgy[]{sgyVar, sgyVar2, sgyVar3, sgyVar4, sgyVar5, sgyVar6, sgyVar7, sgyVar8, sgyVar9, sgyVar10, sgyVar11};
    }

    public upt(char[] cArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "generic_worker_queue._id";
        a.c = new wsy();
        srf srfVar = new srf(a.a());
        this.a = srfVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.a = "generic_worker_queue.worker_type";
        a2.c = new wsy();
        srf srfVar2 = new srf(a2.a());
        this.i = srfVar2;
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.a = "generic_worker_queue.item_table_type";
        a3.c = new wsy();
        srf srfVar3 = new srf(a3.a());
        this.c = srfVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "generic_worker_queue.item_id";
        a4.c = new wsy();
        srf srfVar4 = new srf(a4.a());
        this.f = srfVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.a = "generic_worker_queue.account_id";
        a5.c = new wsy();
        srf srfVar5 = new srf(a5.a());
        this.d = srfVar5;
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.c(true);
        a6.a = "generic_worker_queue.in_flight";
        a6.c = new wsy();
        srf srfVar6 = new srf(a6.a());
        this.j = srfVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "generic_worker_queue.retry_count";
        a7.c = new wsy();
        srf srfVar7 = new srf(a7.a());
        this.e = srfVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "generic_worker_queue.flags";
        a8.c = new wsy();
        srf srfVar8 = new srf(a8.a());
        this.g = srfVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.c(true);
        a9.a = "generic_worker_queue.next_execute_timestamp";
        a9.c = new wsy();
        srf srfVar9 = new srf(a9.a());
        this.h = srfVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "generic_worker_queue.trigger_name";
        a10.c = new wsy();
        srf srfVar10 = new srf(a10.a());
        this.b = srfVar10;
        agmi a11 = agmk.a();
        a11.d = 2;
        a11.a = "generic_worker_queue.enqueued_timestamp";
        a11.c = new wsy();
        srf srfVar11 = new srf(a11.a());
        this.k = srfVar11;
        this.l = new srf[]{srfVar, srfVar2, srfVar3, srfVar4, srfVar5, srfVar6, srfVar7, srfVar8, srfVar9, srfVar10, srfVar11};
    }

    public upt(byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "link_preview._id";
        a.c = new wsy();
        ssk sskVar = new ssk(a.a());
        this.a = sskVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.j(true);
        a2.i(true);
        a2.c(true);
        a2.d(true);
        a2.b = new srr(9);
        a2.a = "link_preview.message_id";
        a2.c = new wsy();
        ssk sskVar2 = new ssk(a2.a());
        this.b = sskVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.i(true);
        a3.a = "link_preview.trigger_url";
        a3.c = new wsy();
        ssk sskVar3 = new ssk(a3.a());
        this.i = sskVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "link_preview.expiration_time_millis";
        a4.c = new wsy();
        ssk sskVar4 = new ssk(a4.a());
        this.d = sskVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "link_preview.link_title";
        a5.c = new wsy();
        ssk sskVar5 = new ssk(a5.a());
        this.e = sskVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "link_preview.link_description";
        a6.c = new wsy();
        ssk sskVar6 = new ssk(a6.a());
        this.g = sskVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "link_preview.link_image_url";
        a7.c = new wsy();
        ssk sskVar7 = new ssk(a7.a());
        this.f = sskVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "link_preview.link_domain";
        a8.c = new wsy();
        ssk sskVar8 = new ssk(a8.a());
        this.j = sskVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "link_preview.link_canonical_url";
        a9.c = new wsy();
        ssk sskVar9 = new ssk(a9.a());
        this.k = sskVar9;
        agmi a10 = agmk.a();
        a10.d = 2;
        a10.a = "link_preview.link_preview_prevented";
        a10.c = new wsy();
        ssk sskVar10 = new ssk(a10.a());
        this.h = sskVar10;
        agmi a11 = agmk.a();
        a11.d = 2;
        a11.a = "link_preview.link_preview_failed";
        a11.c = new wsy();
        ssk sskVar11 = new ssk(a11.a());
        this.c = sskVar11;
        this.l = new ssk[]{sskVar, sskVar2, sskVar3, sskVar4, sskVar5, sskVar6, sskVar7, sskVar8, sskVar9, sskVar10, sskVar11};
    }

    public upt() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "work_queue._id";
        a.c = new wsy();
        upu upuVar = new upu(a.a());
        this.a = upuVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.i(true);
        a2.c(true);
        a2.a = "work_queue.type";
        a2.c = new wsy();
        upu upuVar2 = new upu(a2.a());
        this.b = upuVar2;
        agmi a3 = agmk.a();
        a3.d = 5;
        a3.i(true);
        a3.a = "work_queue.rawdata";
        a3.c = new wsy();
        upu upuVar3 = new upu(a3.a());
        this.c = upuVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "work_queue.attempts";
        a4.c = new wsy();
        upu upuVar4 = new upu(a4.a());
        this.d = upuVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.a = "work_queue.timestamp";
        a5.c = new wsy();
        upu upuVar5 = new upu(a5.a());
        this.e = upuVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.c(true);
        a6.a = "work_queue.queue";
        a6.c = new wsy();
        upu upuVar6 = new upu(a6.a());
        this.f = upuVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.c(true);
        a7.a = "work_queue.deduplication_tag";
        a7.c = new wsy();
        upu upuVar7 = new upu(a7.a());
        this.g = upuVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.c(true);
        a8.a = "work_queue.scheduled_in_workmanager";
        a8.c = new wsy();
        upu upuVar8 = new upu(a8.a());
        this.h = upuVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "work_queue.workmanager_id";
        a9.c = new wsy();
        upu upuVar9 = new upu(a9.a());
        this.i = upuVar9;
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "work_queue.minimum_start_time";
        a10.c = new wsy();
        upu upuVar10 = new upu(a10.a());
        this.j = upuVar10;
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.a = "work_queue.cancellation_tag";
        a11.c = new wsy();
        upu upuVar11 = new upu(a11.a());
        this.k = upuVar11;
        this.l = new upu[]{upuVar, upuVar2, upuVar3, upuVar4, upuVar5, upuVar6, upuVar7, upuVar8, upuVar9, upuVar10, upuVar11};
    }
}
