package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class uqu {
    public final Object a;
    public final Object b;
    public final Object c;
    public final Object d;
    public final Object e;
    public final Object f;
    public final Object g;
    public final Object h;
    public final Object i;
    public final Object j;

    public uqu(byte[] bArr, char[] cArr) {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.f(true);
        a.c(true);
        a.d(true);
        a.b = new qqe(10);
        a.a = "groups.token";
        a.c = new wsy();
        quc qucVar = new quc(a.a());
        this.c = qucVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.i(true);
        a2.c(true);
        a2.a = "groups.group_type";
        a2.c = new wsy();
        quc qucVar2 = new quc(a2.a());
        this.j = qucVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "groups.rcs_conference_uri";
        a3.c = new wsy();
        quc qucVar3 = new quc(a3.a());
        this.a = qucVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "groups.name";
        a4.c = new wsy();
        quc qucVar4 = new quc(a4.a());
        this.d = qucVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "groups.rcs_icon_url";
        a5.c = new wsy();
        quc qucVar5 = new quc(a5.a());
        this.e = qucVar5;
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.a = "groups.rcs_group_state";
        a6.c = new wsy();
        quc qucVar6 = new quc(a6.a());
        this.g = qucVar6;
        agmi a7 = agmk.a();
        a7.d = 5;
        a7.a = "groups.tachygram_group_routing_token";
        a7.c = new wsy();
        quc qucVar7 = new quc(a7.a());
        this.i = qucVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "groups.rcs_group_capabilities";
        a8.c = new wsy();
        quc qucVar8 = new quc(a8.a());
        this.h = qucVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.a = "groups.rcs_group_last_sync_timestamp";
        a9.c = new wsy();
        quc qucVar9 = new quc(a9.a());
        this.f = qucVar9;
        this.b = new quc[]{qucVar, qucVar2, qucVar3, qucVar4, qucVar5, qucVar6, qucVar7, qucVar8, qucVar9};
    }

    public uqu(short[] sArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "link_preview_backup._id";
        a.c = new wsy();
        rlp rlpVar = new rlp(a.a());
        this.c = rlpVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.j(true);
        a2.i(true);
        a2.c(true);
        a2.d(true);
        a2.b = new rlm(2);
        a2.a = "link_preview_backup.message_id";
        a2.c = new wsy();
        rlp rlpVar2 = new rlp(a2.a());
        this.e = rlpVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.i(true);
        a3.a = "link_preview_backup.trigger_url";
        a3.c = new wsy();
        rlp rlpVar3 = new rlp(a3.a());
        this.i = rlpVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "link_preview_backup.expiration_time_millis";
        a4.c = new wsy();
        rlp rlpVar4 = new rlp(a4.a());
        this.j = rlpVar4;
        agmi a5 = agmk.a();
        a5.d = 4;
        a5.a = "link_preview_backup.link_title";
        a5.c = new wsy();
        rlp rlpVar5 = new rlp(a5.a());
        this.g = rlpVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "link_preview_backup.link_description";
        a6.c = new wsy();
        rlp rlpVar6 = new rlp(a6.a());
        this.a = rlpVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "link_preview_backup.link_image_url";
        a7.c = new wsy();
        rlp rlpVar7 = new rlp(a7.a());
        this.f = rlpVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "link_preview_backup.link_domain";
        a8.c = new wsy();
        rlp rlpVar8 = new rlp(a8.a());
        this.h = rlpVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "link_preview_backup.link_canonical_url";
        a9.c = new wsy();
        rlp rlpVar9 = new rlp(a9.a());
        this.d = rlpVar9;
        this.b = new rlp[]{rlpVar, rlpVar2, rlpVar3, rlpVar4, rlpVar5, rlpVar6, rlpVar7, rlpVar8, rlpVar9};
    }

    public uqu(byte[] bArr, byte[] bArr2, byte[] bArr3) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "conversation_participants_audit_log._id";
        a.c = new wsy();
        skn sknVar = new skn(a.a());
        this.c = sknVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.i(true);
        a2.a = "conversation_participants_audit_log.operation_datetime";
        a2.c = new wsy();
        skn sknVar2 = new skn(a2.a());
        this.f = sknVar2;
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.i(true);
        a3.a = "conversation_participants_audit_log.operation_type";
        a3.c = new wsy();
        skn sknVar3 = new skn(a3.a());
        this.g = sknVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.i(true);
        a4.a = "conversation_participants_audit_log.conversation_participants_id";
        a4.c = new wsy();
        skn sknVar4 = new skn(a4.a());
        this.d = sknVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.i(true);
        a5.a = "conversation_participants_audit_log.conversation_id";
        a5.c = new wsy();
        skn sknVar5 = new skn(a5.a());
        this.j = sknVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.i(true);
        a6.a = "conversation_participants_audit_log.participant_id";
        a6.c = new wsy();
        skn sknVar6 = new skn(a6.a());
        this.e = sknVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "conversation_participants_audit_log.is_normalized";
        a7.c = new wsy();
        skn sknVar7 = new skn(a7.a());
        this.a = sknVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "conversation_participants_audit_log.rcs_group_join_status";
        a8.c = new wsy();
        skn sknVar8 = new skn(a8.a());
        this.i = sknVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "conversation_participants_audit_log.last_modified_by_key";
        a9.c = new wsy();
        skn sknVar9 = new skn(a9.a());
        this.h = sknVar9;
        this.b = new skn[]{sknVar, sknVar2, sknVar3, sknVar4, sknVar5, sknVar6, sknVar7, sknVar8, sknVar9};
    }

    public uqu(char[] cArr, byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "lighter_conversations_table._id";
        a.c = new wsy();
        srs srsVar = new srs(a.a());
        this.c = srsVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.c(true);
        a2.d(true);
        a2.b = new srr(0);
        a2.a = "lighter_conversations_table.conversation_id";
        a2.c = new wsy();
        srs srsVar2 = new srs(a2.a());
        this.d = srsVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.j(true);
        a3.c(true);
        a3.a = "lighter_conversations_table.business_id";
        a3.e(true);
        a3.c = new wsy();
        srs srsVar3 = new srs(a3.a());
        this.j = srsVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "lighter_conversations_table.lighter_conversation_id_json";
        a4.c = new wsy();
        srs srsVar4 = new srs(a4.a());
        this.g = srsVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.c(true);
        a5.a = "lighter_conversations_table.read";
        a5.c = new wsy();
        srs srsVar5 = new srs(a5.a());
        this.e = srsVar5;
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.a = "lighter_conversations_table.is_last_message_outgoing";
        a6.c = new wsy();
        srs srsVar6 = new srs(a6.a());
        this.h = srsVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "lighter_conversations_table.conversation_status";
        a7.c = new wsy();
        srs srsVar7 = new srs(a7.a());
        this.a = srsVar7;
        agmi a8 = agmk.a();
        a8.d = 1;
        a8.a = "lighter_conversations_table.last_action_timestamp";
        a8.c = new wsy();
        srs srsVar8 = new srs(a8.a());
        this.f = srsVar8;
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "lighter_conversations_table.sync_timestamp_ms";
        a9.c = new wsy();
        srs srsVar9 = new srs(a9.a());
        this.i = srsVar9;
        this.b = new srs[]{srsVar, srsVar2, srsVar3, srsVar4, srsVar5, srsVar6, srsVar7, srsVar8, srsVar9};
    }

    public uqu(byte[] bArr, byte[] bArr2) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "remote_instances._id";
        a.c = new wsy();
        tgu tguVar = new tgu(a.a());
        this.c = tguVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.i(true);
        a2.a = "remote_instances.remote_instance_id";
        a2.c = new wsy();
        tgu tguVar2 = new tgu(a2.a());
        this.g = tguVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "remote_instances.etouffee";
        a3.c = new wsy();
        tgu tguVar3 = new tgu(a3.a());
        this.d = tguVar3;
        agmi a4 = agmk.a();
        a4.d = 4;
        a4.a = "remote_instances.tachyon_id";
        a4.c = new wsy();
        tgu tguVar4 = new tgu(a4.a());
        this.e = tguVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.a = "remote_instances.last_modified_timestamp";
        a5.c = new wsy();
        tgu tguVar5 = new tgu(a5.a());
        this.f = tguVar5;
        agmi a6 = agmk.a();
        a6.d = 5;
        a6.a = "remote_instances.identity_key";
        a6.c = new wsy();
        tgu tguVar6 = new tgu(a6.a());
        this.a = tguVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "remote_instances.updated_at_hash";
        a7.c = new wsy();
        tgu tguVar7 = new tgu(a7.a());
        this.i = tguVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "remote_instances.guaranteed_fresh_as_of_timestamp";
        a8.c = new wsy();
        tgu tguVar8 = new tgu(a8.a());
        this.j = tguVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.a = "remote_instances.is_updated_at_hash_valid";
        a9.c = new wsy();
        tgu tguVar9 = new tgu(a9.a());
        this.h = tguVar9;
        this.b = new tgu[]{tguVar, tguVar2, tguVar3, tguVar4, tguVar5, tguVar6, tguVar7, tguVar8, tguVar9};
    }

    public uqu(char[] cArr) {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "remote_registrations_table.tachyon_registration_id";
        a.c = new wsy();
        the theVar = new the(a.a());
        this.i = theVar;
        agmi a2 = agmk.a();
        a2.d = 1;
        a2.a = "remote_registrations_table.etouffee";
        a2.c = new wsy();
        the theVar2 = new the(a2.a());
        this.d = theVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "remote_registrations_table.better_etouffee";
        a3.c = new wsy();
        the theVar3 = new the(a3.a());
        this.a = theVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.a = "remote_registrations_table.messages_feature_hash";
        a4.c = new wsy();
        the theVar4 = new the(a4.a());
        this.e = theVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.a = "remote_registrations_table.last_modified_timestamp";
        a5.c = new wsy();
        the theVar5 = new the(a5.a());
        this.g = theVar5;
        agmi a6 = agmk.a();
        a6.d = 5;
        a6.a = "remote_registrations_table.identity_key";
        a6.c = new wsy();
        the theVar6 = new the(a6.a());
        this.h = theVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "remote_registrations_table.updated_at_hash";
        a7.c = new wsy();
        the theVar7 = new the(a7.a());
        this.c = theVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "remote_registrations_table.guaranteed_fresh_as_of_timestamp";
        a8.c = new wsy();
        the theVar8 = new the(a8.a());
        this.j = theVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.a = "remote_registrations_table.is_updated_at_hash_valid";
        a9.c = new wsy();
        the theVar9 = new the(a9.a());
        this.f = theVar9;
        this.b = new the[]{theVar, theVar2, theVar3, theVar4, theVar5, theVar6, theVar7, theVar8, theVar9};
    }

    public uqu(byte[] bArr) {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "self_participants._id";
        a.c = new wsy();
        tkj tkjVar = new tkj(a.a());
        this.b = tkjVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.a = "self_participants.phone_number";
        a2.c = new wsy();
        tkj tkjVar2 = new tkj(a2.a());
        this.a = tkjVar2;
        agmi a3 = agmk.a();
        a3.d = 4;
        a3.a = "self_participants.sim_serial_number";
        a3.c = new wsy();
        tkj tkjVar3 = new tkj(a3.a());
        this.h = tkjVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "self_participants.sim_slot_index";
        a4.c = new wsy();
        tkj tkjVar4 = new tkj(a4.a());
        this.f = tkjVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "self_participants.sub_id";
        a5.c = new wsy();
        tkj tkjVar5 = new tkj(a5.a());
        this.c = tkjVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "self_participants.subscription_name";
        a6.c = new wsy();
        tkj tkjVar6 = new tkj(a6.a());
        this.i = tkjVar6;
        agmi a7 = agmk.a();
        a7.d = 1;
        a7.a = "self_participants.subscription_color";
        a7.c = new wsy();
        tkj tkjVar7 = new tkj(a7.a());
        this.e = tkjVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "self_participants.participant_id";
        a8.c = new wsy();
        tkj tkjVar8 = new tkj(a8.a());
        this.d = tkjVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "self_participants.smsc";
        a9.c = new wsy();
        tkj tkjVar9 = new tkj(a9.a());
        this.g = tkjVar9;
        this.j = new tkj[]{tkjVar, tkjVar2, tkjVar3, tkjVar4, tkjVar5, tkjVar6, tkjVar7, tkjVar8, tkjVar9};
    }

    public uqu(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.d = armfVar2;
        armfVar3.getClass();
        this.b = armfVar3;
        armfVar4.getClass();
        this.j = armfVar4;
        armfVar5.getClass();
        this.f = armfVar5;
        armfVar6.getClass();
        this.g = armfVar6;
        armfVar7.getClass();
        this.c = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.e = armfVar10;
    }

    public uqu() {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "work_queue_work_manager_ids.queue";
        a.c = new wsy();
        uqv uqvVar = new uqv(a.a());
        this.a = uqvVar;
        agmi a2 = agmk.a();
        a2.d = 4;
        a2.a = "work_queue_work_manager_ids.workmanager_id";
        a2.c = new wsy();
        uqv uqvVar2 = new uqv(a2.a());
        this.b = uqvVar2;
        agmi a3 = agmk.a();
        a3.d = 1;
        a3.a = "work_queue_work_manager_ids.scheduled_at_time";
        a3.c = new wsy();
        uqv uqvVar3 = new uqv(a3.a());
        this.c = uqvVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "work_queue_work_manager_ids.minimum_start_time";
        a4.c = new wsy();
        uqv uqvVar4 = new uqv(a4.a());
        this.d = uqvVar4;
        agmi a5 = agmk.a();
        a5.d = 1;
        a5.a = "work_queue_work_manager_ids.requires_network_type";
        a5.c = new wsy();
        uqv uqvVar5 = new uqv(a5.a());
        this.e = uqvVar5;
        agmi a6 = agmk.a();
        a6.d = 2;
        a6.a = "work_queue_work_manager_ids.requires_charging";
        a6.c = new wsy();
        uqv uqvVar6 = new uqv(a6.a());
        this.f = uqvVar6;
        agmi a7 = agmk.a();
        a7.d = 2;
        a7.a = "work_queue_work_manager_ids.requires_device_idle";
        a7.c = new wsy();
        uqv uqvVar7 = new uqv(a7.a());
        this.g = uqvVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.a = "work_queue_work_manager_ids.requires_battery_not_low";
        a8.c = new wsy();
        uqv uqvVar8 = new uqv(a8.a());
        this.h = uqvVar8;
        agmi a9 = agmk.a();
        a9.d = 2;
        a9.a = "work_queue_work_manager_ids.requires_storage_not_low";
        a9.c = new wsy();
        uqv uqvVar9 = new uqv(a9.a());
        this.i = uqvVar9;
        this.j = new uqv[]{uqvVar, uqvVar2, uqvVar3, uqvVar4, uqvVar5, uqvVar6, uqvVar7, uqvVar8, uqvVar9};
    }
}
