package defpackage;

import android.content.Context;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class vid {
    public final Object a;
    public final Object b;
    public final Object c;
    public final Object d;
    public final Object e;
    public final Object f;
    public final Object g;
    public final Object h;
    public final Object i;
    public final Object j;
    public final Object k;
    public final Object l;
    public final Object m;
    public final Object n;

    public vid(Context context, wys wysVar, xnv xnvVar, wzs wzsVar, xbf xbfVar, rgf rgfVar, armf armfVar, ryg rygVar, agnq agnqVar, armf armfVar2, armf armfVar3, odn odnVar, armf armfVar4, anen anenVar) {
        this.i = context;
        this.a = wysVar;
        this.n = xnvVar;
        this.f = wzsVar;
        this.l = xbfVar;
        this.e = rgfVar;
        this.m = armfVar;
        this.d = rygVar;
        this.b = agnqVar;
        this.k = armfVar2;
        this.h = armfVar3;
        this.c = odnVar;
        this.j = armfVar4;
        this.g = anenVar;
    }

    /* JADX WARN: Type inference failed for: r10v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r13v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r14v0, types: [apwt, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r15v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v10, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v12, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v13, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v15, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v17, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v2, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v4, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v6, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v8, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r9v0, types: [apwt, java.lang.Object] */
    public final rry a() {
        xvc xvcVar = (xvc) this.i.b();
        xvcVar.getClass();
        rtb rtbVar = (rtb) this.g.b();
        rtbVar.getClass();
        rvx rvxVar = (rvx) this.b.b();
        rvxVar.getClass();
        trz trzVar = (trz) this.f.b();
        trzVar.getClass();
        iew iewVar = (iew) this.l.b();
        iewVar.getClass();
        msk mskVar = (msk) this.j.b();
        mskVar.getClass();
        ?? b = this.k.b();
        b.getClass();
        uli uliVar = (uli) this.e.b();
        uliVar.getClass();
        ujx ujxVar = (ujx) this.m.b();
        ujxVar.getClass();
        ?? b2 = this.h.b();
        b2.getClass();
        ?? r15 = this.d;
        return new rry(xvcVar, rtbVar, rvxVar, trzVar, iewVar, mskVar, b, this.n, uliVar, ujxVar, this.a, b2, r15);
    }

    /* JADX WARN: Type inference failed for: r10v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r13v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r14v0, types: [apwt, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r15v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v10, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v12, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v13, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v15, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v17, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v2, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v4, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v6, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v8, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r9v0, types: [apwt, java.lang.Object] */
    public final rry b(saz sazVar) {
        xvc xvcVar = (xvc) this.i.b();
        xvcVar.getClass();
        rtb rtbVar = (rtb) this.g.b();
        rtbVar.getClass();
        rvx rvxVar = (rvx) this.b.b();
        rvxVar.getClass();
        trz trzVar = (trz) this.f.b();
        trzVar.getClass();
        iew iewVar = (iew) this.l.b();
        iewVar.getClass();
        msk mskVar = (msk) this.j.b();
        mskVar.getClass();
        ?? b = this.k.b();
        b.getClass();
        uli uliVar = (uli) this.e.b();
        uliVar.getClass();
        ujx ujxVar = (ujx) this.m.b();
        ujxVar.getClass();
        ?? b2 = this.h.b();
        b2.getClass();
        sazVar.getClass();
        ?? r15 = this.d;
        return new rry(xvcVar, rtbVar, rvxVar, trzVar, iewVar, mskVar, (apwt) b, (armf) this.n, uliVar, ujxVar, (armf) this.a, (apwt) b2, (armf) r15, sazVar);
    }

    /* JADX WARN: Type inference failed for: r10v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r13v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r14v0, types: [apwt, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r15v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v0, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v10, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v12, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v13, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v15, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v17, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v2, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v4, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v6, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r1v8, types: [armf, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r9v0, types: [apwt, java.lang.Object] */
    public final rry c(sbd sbdVar) {
        xvc xvcVar = (xvc) this.i.b();
        xvcVar.getClass();
        rtb rtbVar = (rtb) this.g.b();
        rtbVar.getClass();
        rvx rvxVar = (rvx) this.b.b();
        rvxVar.getClass();
        trz trzVar = (trz) this.f.b();
        trzVar.getClass();
        iew iewVar = (iew) this.l.b();
        iewVar.getClass();
        msk mskVar = (msk) this.j.b();
        mskVar.getClass();
        ?? b = this.k.b();
        b.getClass();
        uli uliVar = (uli) this.e.b();
        uliVar.getClass();
        ujx ujxVar = (ujx) this.m.b();
        ujxVar.getClass();
        ?? b2 = this.h.b();
        b2.getClass();
        ?? r15 = this.d;
        return new rry(xvcVar, rtbVar, rvxVar, trzVar, iewVar, mskVar, (apwt) b, (armf) this.n, uliVar, ujxVar, (armf) this.a, (apwt) b2, (armf) r15, sbdVar);
    }

    public vid(char[] cArr) {
        agmi a = agmk.a();
        a.k(2);
        a.j(true);
        a.f(true);
        a.c(true);
        a.b("messages._id");
        a.h(new wsy());
        this.m = new sbc(a.a());
        agmi a2 = agmk.a();
        a2.k(1);
        a2.c(true);
        a2.d(true);
        a2.b("messages.conversation_id");
        a2.h(new wsy());
        this.a = new sbc(a2.a());
        agmi a3 = agmk.a();
        a3.k(1);
        a3.c(true);
        a3.d(true);
        a3.b("messages.sender_id");
        a3.h(new wsy());
        a3.a();
        agmi a4 = agmk.a();
        a4.k(1);
        a4.c(true);
        a4.b("messages.sent_timestamp");
        a4.h(new wsy());
        this.h = new sbc(a4.a());
        agmi a5 = agmk.a();
        a5.k(1);
        a5.c(true);
        a5.b("messages.received_timestamp");
        a5.h(new wsy());
        this.j = new sbc(a5.a());
        agmi a6 = agmk.a();
        a6.k(1);
        a6.b("messages.message_protocol");
        a6.h(new wsy());
        this.f = new sbc(a6.a());
        agmi a7 = agmk.a();
        a7.k(1);
        a7.c(true);
        a7.b("messages.message_status");
        a7.h(new wsy());
        this.l = new sbc(a7.a());
        agmi a8 = agmk.a();
        a8.k(1);
        a8.b("messages.message_report_status");
        a8.h(new wsy());
        a8.a();
        agmi a9 = agmk.a();
        a9.k(1);
        a9.c(true);
        a9.b("messages.seen");
        a9.e(true);
        a9.h(new wsy());
        a9.a();
        agmi a10 = agmk.a();
        a10.k(1);
        a10.c(true);
        a10.b("messages.read");
        a10.h(new wsy());
        a10.a();
        agmi a11 = agmk.a();
        a11.k(4);
        a11.c(true);
        a11.b("messages.sms_message_uri");
        a11.h(new wsy());
        this.k = new sbc(a11.a());
        agmi a12 = agmk.a();
        a12.k(1);
        a12.b("messages.sms_priority");
        a12.h(new wsy());
        a12.a();
        agmi a13 = agmk.a();
        a13.k(1);
        a13.b("messages.sms_message_size");
        a13.h(new wsy());
        a13.a();
        agmi a14 = agmk.a();
        a14.k(4);
        a14.b("messages.mms_subject");
        a14.h(new wsy());
        a14.a();
        agmi a15 = agmk.a();
        a15.k(1);
        a15.b("messages.mms_expiry");
        a15.h(new wsy());
        a15.a();
        agmi a16 = agmk.a();
        a16.k(1);
        a16.c(true);
        a16.b("messages.rcs_expiry");
        a16.h(new wsy());
        a16.a();
        agmi a17 = agmk.a();
        a17.k(4);
        a17.b("messages.mms_retrieve_text");
        a17.h(new wsy());
        this.b = new sbc(a17.a());
        agmi a18 = agmk.a();
        a18.k(1);
        a18.b("messages.raw_status");
        a18.h(new wsy());
        this.g = new sbc(a18.a());
        agmi a19 = agmk.a();
        a19.k(1);
        a19.c(true);
        a19.d(true);
        a19.b("messages.self_id");
        a19.h(new wsy());
        a19.a();
        agmi a20 = agmk.a();
        a20.k(4);
        a20.c(true);
        a20.b("messages.rcs_message_id_with_text_type");
        a20.e(true);
        a20.h(new wsy());
        a20.a();
        agmi a21 = agmk.a();
        a21.k(1);
        a21.b("messages.etouffee_status");
        a21.h(new wsy());
        a21.a();
        agmi a22 = agmk.a();
        a22.k(1);
        a22.b("messages.verification_status");
        a22.h(new wsy());
        a22.a();
        agmi a23 = agmk.a();
        a23.k(1);
        a23.c(true);
        a23.b("messages.is_hidden");
        a23.h(new wsy());
        a23.a();
        agmi a24 = agmk.a();
        a24.k(1);
        a24.b("messages.rcs_file_transfer_session_id");
        a24.h(new wsy());
        a24.a();
        agmi a25 = agmk.a();
        a25.k(1);
        a25.b("messages.sms_error_code");
        a25.h(new wsy());
        a25.a();
        agmi a26 = agmk.a();
        a26.k(4);
        a26.b("messages.sms_error_desc_map_name");
        a26.h(new wsy());
        a26.a();
        agmi a27 = agmk.a();
        a27.k(4);
        a27.j(true);
        a27.c(true);
        a27.b("messages.cms_id");
        a27.e(true);
        a27.h(new wsy());
        a27.a();
        agmi a28 = agmk.a();
        a28.k(4);
        a28.c(true);
        a28.b("messages.web_id");
        a28.h(new wsy());
        a28.a();
        agmi a29 = agmk.a();
        a29.k(1);
        a29.b("messages.usage_stats_logging_id");
        a29.h(new wsy());
        a29.a();
        agmi a30 = agmk.a();
        a30.k(4);
        a30.c(true);
        a30.b("messages.original_rcs_message_id");
        a30.h(new wsy());
        a30.a();
        agmi a31 = agmk.a();
        a31.k(1);
        a31.b("messages.result_code");
        a31.h(new wsy());
        a31.a();
        agmi a32 = agmk.a();
        a32.k(1);
        a32.b("messages.cms_life_cycle");
        a32.h(new wsy());
        a32.a();
        agmi a33 = agmk.a();
        a33.k(1);
        a33.b("messages.fallback_reason");
        a33.h(new wsy());
        a33.a();
        agmi a34 = agmk.a();
        a34.k(5);
        a34.b("messages.trace_id");
        a34.h(new wsy());
        a34.a();
        agmi a35 = agmk.a();
        a35.k(1);
        a35.b("messages.xms_transport");
        a35.h(new wsy());
        a35.a();
        agmi a36 = agmk.a();
        a36.k(4);
        a36.b("messages.sender_send_destination");
        a36.h(new wsy());
        a36.a();
        agmi a37 = agmk.a();
        a37.k(4);
        a37.b("messages.msisdn_receiving_rcs_message");
        a37.h(new wsy());
        a37.a();
        agmi a38 = agmk.a();
        a38.k(4);
        a38.b("messages.receiving_network_country");
        a38.h(new wsy());
        a38.a();
        agmi a39 = agmk.a();
        a39.k(1);
        a39.b("messages.queue_insert_timestamp");
        a39.h(new wsy());
        a39.a();
        agmi a40 = agmk.a();
        a40.k(4);
        a40.b("messages.mms_transaction_id");
        a40.h(new wsy());
        a40.a();
        agmi a41 = agmk.a();
        a41.k(4);
        a41.b("messages.mms_content_location");
        a41.h(new wsy());
        this.n = new sbc(a41.a());
        agmi a42 = agmk.a();
        a42.k(4);
        a42.c(true);
        a42.b("messages.my_identity");
        a42.h(new wsy());
        a42.a();
        agmi a43 = agmk.a();
        a43.k(4);
        a43.c(true);
        a43.d(true);
        a43.g(new sbb(15));
        a43.b("messages.my_identity_foreign_key");
        a43.h(new wsy());
        a43.a();
        agmi a44 = agmk.a();
        a44.k(1);
        a44.b("messages.retry_start_timestamp");
        a44.h(new wsy());
        a44.a();
        agmi a45 = agmk.a();
        a45.k(4);
        a45.c(true);
        a45.b("messages.cloud_sync_id");
        a45.h(new wsy());
        a45.a();
        agmi a46 = agmk.a();
        a46.k(7);
        a46.c(true);
        a46.b("messages.rcs_message_id");
        a46.e(true);
        a46.h(new wsy());
        a46.a();
        agmi a47 = agmk.a();
        a47.k(1);
        a47.b("messages.rcs_ui_status");
        a47.h(new wsy());
        a47.a();
        agmi a48 = agmk.a();
        a48.k(7);
        a48.b("messages.rcs_remote_instance");
        a48.h(new wsy());
        a48.a();
        agmi a49 = agmk.a();
        a49.k(4);
        a49.b("messages.correlation_id");
        a49.h(new wsy());
        a49.a();
        agmi a50 = agmk.a();
        a50.k(2);
        a50.b("messages.cms_last_mod_seq");
        a50.h(new wsy());
        a50.a();
        agmi a51 = agmk.a();
        a51.k(1);
        a51.b("messages.send_counter");
        a51.h(new wsy());
        a51.a();
        agmi a52 = agmk.a();
        a52.k(4);
        a52.b("messages.custom_delivery_receipt_mime_type");
        a52.h(new wsy());
        a52.a();
        agmi a53 = agmk.a();
        a53.k(5);
        a53.b("messages.custom_delivery_receipt_content");
        a53.h(new wsy());
        a53.a();
        agmi a54 = agmk.a();
        a54.k(1);
        a54.b("messages.report_attempt_acounter");
        a54.h(new wsy());
        a54.a();
        agmi a55 = agmk.a();
        a55.k(5);
        a55.b("messages.custom_headers");
        a55.h(new wsy());
        a55.a();
        agmi a56 = agmk.a();
        a56.k(4);
        a56.j(true);
        a56.c(true);
        a56.b("messages.cms_correlation_id");
        a56.e(true);
        a56.h(new wsy());
        a56.a();
        agmi a57 = agmk.a();
        a57.k(1);
        a57.c(true);
        a57.d(true);
        a57.g(new sbb(16));
        a57.b("messages.group_private_participant");
        a57.h(new wsy());
        a57.a();
        agmi a58 = agmk.a();
        a58.k(1);
        a58.c(true);
        a58.d(true);
        a58.g(new sbb(17));
        a58.b("messages.original_message_id");
        a58.h(new wsy());
        a58.a();
        agmi a59 = agmk.a();
        a59.k(1);
        a59.b("messages.awaiting_reverse_sync");
        a59.h(new wsy());
        a59.a();
        agmi a60 = agmk.a();
        a60.k(4);
        a60.b("messages.old_sms_message_uri");
        a60.h(new wsy());
        a60.a();
        agmi a61 = agmk.a();
        a61.k(4);
        a61.j(true);
        a61.c(true);
        a61.b("messages.draft_id");
        a61.e(true);
        a61.h(new wsy());
        a61.a();
        agmi a62 = agmk.a();
        a62.k(1);
        a62.b("messages.auto_retry_counter");
        a62.h(new wsy());
        a62.a();
        agmi a63 = agmk.a();
        a63.k(2);
        a63.b("messages.can_revoke_before_delivered_with_rcs");
        a63.h(new wsy());
        a63.a();
        agmi a64 = agmk.a();
        a64.k(1);
        a64.b("messages.outgoing_delivery_report_status");
        a64.h(new wsy());
        a64.a();
        agmi a65 = agmk.a();
        a65.k(1);
        a65.b("messages.outgoing_read_report_status");
        a65.h(new wsy());
        a65.a();
        agmi a66 = agmk.a();
        a66.k(1);
        a66.b("messages.message_original_protocol");
        a66.h(new wsy());
        a66.a();
        agmi a67 = agmk.a();
        a67.k(4);
        a67.j(true);
        a67.c(true);
        a67.b("messages.satellite_datagram_id");
        a67.e(true);
        a67.h(new wsy());
        a67.a();
        agmi a68 = agmk.a();
        a68.k(1);
        a68.b("messages.encryption_protocol");
        a68.h(new wsy());
        a68.a();
        agmi a69 = agmk.a();
        a69.k(4);
        a69.j(true);
        a69.c(true);
        a69.b("messages.message_persistence_id");
        a69.e(true);
        a69.h(new wsy());
        a69.a();
        agmi a70 = agmk.a();
        a70.k(8);
        a70.b("parts_count");
        a70.h(new wsy());
        a70.a();
        agmi a71 = agmk.a();
        a71.k(2);
        a71.j(true);
        a71.f(true);
        a71.c(true);
        a71.b("parts._id");
        a71.h(new wsy());
        a71.a();
        agmi a72 = agmk.a();
        a72.k(1);
        a72.c(true);
        a72.d(true);
        a72.b("parts.message_id");
        a72.h(new wsy());
        a72.a();
        agmi a73 = agmk.a();
        a73.k(4);
        a73.b("parts.text");
        a73.h(new wsy());
        a73.a();
        agmi a74 = agmk.a();
        a74.k(4);
        a74.b("parts.uri");
        a74.h(new wsy());
        a74.a();
        agmi a75 = agmk.a();
        a75.k(4);
        a75.c(true);
        a75.b("parts.content_type");
        a75.h(new wsy());
        a75.a();
        agmi a76 = agmk.a();
        a76.k(4);
        a76.b("parts.original_uri");
        a76.h(new wsy());
        a76.a();
        agmi a77 = agmk.a();
        a77.k(4);
        a77.b("parts.storage_uri");
        a77.h(new wsy());
        a77.a();
        agmi a78 = agmk.a();
        a78.k(1);
        a78.b("parts.width");
        a78.h(new wsy());
        a78.a();
        agmi a79 = agmk.a();
        a79.k(1);
        a79.b("parts.height");
        a79.h(new wsy());
        a79.a();
        agmi a80 = agmk.a();
        a80.k(1);
        a80.b("parts.timestamp");
        a80.h(new wsy());
        a80.a();
        agmi a81 = agmk.a();
        a81.k(4);
        a81.c(true);
        a81.b("parts.output_uri");
        a81.h(new wsy());
        a81.a();
        agmi a82 = agmk.a();
        a82.k(1);
        a82.b("parts.target_size");
        a82.h(new wsy());
        a82.a();
        agmi a83 = agmk.a();
        a83.k(1);
        a83.b("parts.processing_status");
        a83.h(new wsy());
        a83.a();
        agmi a84 = agmk.a();
        a84.k(1);
        a84.b("parts.cms_attachment_processing_status");
        a84.h(new wsy());
        a84.a();
        agmi a85 = agmk.a();
        a85.k(1);
        a85.c(true);
        a85.d(true);
        a85.b("parts.conversation_id");
        a85.h(new wsy());
        a85.a();
        agmi a86 = agmk.a();
        a86.k(1);
        a86.b("parts.sticker_set_id");
        a86.h(new wsy());
        a86.a();
        agmi a87 = agmk.a();
        a87.k(1);
        a87.b("parts.sticker_id");
        a87.h(new wsy());
        a87.a();
        agmi a88 = agmk.a();
        a88.k(1);
        a88.b("parts.media_modified_timestamp");
        a88.h(new wsy());
        a88.a();
        agmi a89 = agmk.a();
        a89.k(3);
        a89.b("parts.longitude");
        a89.h(new wsy());
        a89.a();
        agmi a90 = agmk.a();
        a90.k(3);
        a90.b("parts.latitude");
        a90.h(new wsy());
        a90.a();
        agmi a91 = agmk.a();
        a91.k(4);
        a91.b("parts.preview_content_uri");
        a91.h(new wsy());
        a91.a();
        agmi a92 = agmk.a();
        a92.k(4);
        a92.c(true);
        a92.b("parts.preview_content_type");
        a92.h(new wsy());
        a92.a();
        agmi a93 = agmk.a();
        a93.k(4);
        a93.b("parts.fallback_uri");
        a93.h(new wsy());
        a93.a();
        agmi a94 = agmk.a();
        a94.k(1);
        a94.b("parts.source");
        a94.h(new wsy());
        a94.a();
        agmi a95 = agmk.a();
        a95.k(1);
        a95.b("parts.bundle_index");
        a95.h(new wsy());
        a95.a();
        agmi a96 = agmk.a();
        a96.k(4);
        a96.b("parts.blob_id");
        a96.h(new wsy());
        a96.a();
        agmi a97 = agmk.a();
        a97.k(4);
        a97.b("parts.blob_gaia_email");
        a97.h(new wsy());
        a97.a();
        agmi a98 = agmk.a();
        a98.k(4);
        a98.b("parts.cms_full_size_blob_id");
        a98.h(new wsy());
        a98.a();
        agmi a99 = agmk.a();
        a99.k(5);
        a99.b("parts.cms_media_encryption_key");
        a99.h(new wsy());
        a99.a();
        agmi a100 = agmk.a();
        a100.k(5);
        a100.b("parts.cms_compressed_media_encryption_key");
        a100.h(new wsy());
        a100.a();
        agmi a101 = agmk.a();
        a101.k(1);
        a101.b("parts.blob_upload_permanent_failure");
        a101.h(new wsy());
        a101.a();
        agmi a102 = agmk.a();
        a102.k(1);
        a102.b("parts.blob_upload_timestamp");
        a102.h(new wsy());
        a102.a();
        agmi a103 = agmk.a();
        a103.k(4);
        a103.b("parts.expressive_sticker_name");
        a103.h(new wsy());
        a103.a();
        agmi a104 = agmk.a();
        a104.k(4);
        a104.b("parts.file_name");
        a104.h(new wsy());
        a104.a();
        agmi a105 = agmk.a();
        a105.k(1);
        a105.b("parts.duration");
        a105.h(new wsy());
        a105.a();
        agmi a106 = agmk.a();
        a106.k(4);
        a106.b("parts.compressed_blob_id");
        a106.h(new wsy());
        a106.a();
        agmi a107 = agmk.a();
        a107.k(4);
        a107.b("parts.cms_compressed_blob_id");
        a107.h(new wsy());
        a107.a();
        agmi a108 = agmk.a();
        a108.k(1);
        a108.b("parts.compressed_blob_upload_permanent_failure");
        a108.h(new wsy());
        a108.a();
        agmi a109 = agmk.a();
        a109.k(1);
        a109.b("parts.compressed_blob_upload_timestamp");
        a109.h(new wsy());
        a109.a();
        agmi a110 = agmk.a();
        a110.k(5);
        a110.b("parts.media_encryption_key");
        a110.h(new wsy());
        a110.a();
        agmi a111 = agmk.a();
        a111.k(5);
        a111.b("parts.compressed_media_encryption_key");
        a111.h(new wsy());
        a111.a();
        agmi a112 = agmk.a();
        a112.k(1);
        a112.b("parts.missing_entry_in_telephony");
        a112.h(new wsy());
        a112.a();
        agmi a113 = agmk.a();
        a113.k(1);
        a113.b("parts.awaiting_reverse_sync");
        a113.h(new wsy());
        a113.a();
        agmi a114 = agmk.a();
        a114.k(1);
        a114.b("parts.file_size_bytes");
        a114.h(new wsy());
        a114.a();
        agmi a115 = agmk.a();
        a115.k(4);
        a115.c(true);
        a115.b("parts.local_cache_path");
        a115.h(new wsy());
        a115.a();
        agmi a116 = agmk.a();
        a116.k(1);
        a116.b("parts.media_send_type");
        a116.h(new wsy());
        a116.a();
        agmi a117 = agmk.a();
        a117.k(5);
        a117.b("parts.voice_metadata");
        a117.h(new wsy());
        a117.a();
        agmi a118 = agmk.a();
        a118.k(1);
        a118.b("parts.validation_status");
        a118.h(new wsy());
        a118.a();
        agmi a119 = agmk.a();
        a119.k(4);
        a119.b("parts.processing_id");
        a119.h(new wsy());
        a119.a();
        agmi a120 = agmk.a();
        a120.k(1);
        a120.b("parts.rich_card_media_download_failure_reason");
        a120.h(new wsy());
        a120.a();
        agmi a121 = agmk.a();
        a121.k(1);
        a121.b("parts.image_display_state");
        a121.h(new wsy());
        a121.a();
        agmi a122 = agmk.a();
        a122.k(8);
        a122.b("parts__ROWID");
        a122.h(new wsy());
        a122.a();
        agmi a123 = agmk.a();
        a123.k(4);
        a123.c(true);
        a123.b("participants.normalized_destination");
        a123.e(true);
        a123.h(new wsy());
        a123.a();
        agmi a124 = agmk.a();
        a124.k(4);
        a124.b("participants.send_destination");
        a124.h(new wsy());
        a124.a();
        agmi a125 = agmk.a();
        a125.k(4);
        a125.b("participants.display_destination");
        a125.h(new wsy());
        a125.a();
        agmi a126 = agmk.a();
        a126.k(4);
        a126.b("participants.full_name");
        a126.h(new wsy());
        a126.a();
        agmi a127 = agmk.a();
        a127.k(4);
        a127.b("participants.first_name");
        a127.h(new wsy());
        a127.a();
        agmi a128 = agmk.a();
        a128.k(4);
        a128.b("participants.profile_photo_uri");
        a128.h(new wsy());
        a128.a();
        agmi a129 = agmk.a();
        a129.k(1);
        a129.b("participants.contact_id");
        a129.h(new wsy());
        a129.a();
        agmi a130 = agmk.a();
        a130.k(4);
        a130.b("participants.lookup_key");
        a130.h(new wsy());
        a130.a();
        agmi a131 = agmk.a();
        a131.k(1);
        a131.b("participants.color_palette_index");
        a131.h(new wsy());
        a131.a();
        agmi a132 = agmk.a();
        a132.k(1);
        a132.b("participants.color_type");
        a132.h(new wsy());
        a132.a();
        agmi a133 = agmk.a();
        a133.k(1);
        a133.b("participants.extended_color");
        a133.h(new wsy());
        a133.a();
        agmi a134 = agmk.a();
        a134.k(1);
        a134.b("participants.blocked");
        a134.h(new wsy());
        a134.a();
        agmi a135 = agmk.a();
        a135.k(1);
        a135.b("participants.participant_type");
        a135.h(new wsy());
        a135.a();
        agmi a136 = agmk.a();
        a136.k(1);
        a136.b("participants.is_spam");
        a136.h(new wsy());
        a136.a();
        agmi a137 = agmk.a();
        a137.k(1);
        a137.b("participants.latest_verification_status");
        a137.h(new wsy());
        a137.a();
        agmi a138 = agmk.a();
        a138.k(1);
        a138.b("participants.directory_id");
        a138.h(new wsy());
        a138.a();
        agmi a139 = agmk.a();
        a139.k(1);
        a139.b("participants.name_source");
        a139.h(new wsy());
        a139.a();
        agmi a140 = agmk.a();
        a140.k(1);
        a140.b("participants.photo_source");
        a140.h(new wsy());
        a140.a();
        agmi a141 = agmk.a();
        a141.k(2);
        a141.j(true);
        a141.f(true);
        a141.c(true);
        a141.b("participants._id");
        a141.h(new wsy());
        a141.a();
        agmi a142 = agmk.a();
        a142.k(4);
        a142.c(true);
        a142.b("participants.my_identity_token");
        a142.h(new wsy());
        a142.a();
        agmi a143 = agmk.a();
        a143.k(4);
        a143.c(true);
        a143.d(true);
        a143.g(new sbb(18));
        a143.b("participants.my_identity_token_foreign_key");
        a143.h(new wsy());
        a143.a();
        agmi a144 = agmk.a();
        a144.k(1);
        a144.c(true);
        a144.b("participants.sub_id");
        a144.e(true);
        a144.h(new wsy());
        a144.a();
        agmi a145 = agmk.a();
        a145.k(1);
        a145.b("participants.sim_slot_id");
        a145.h(new wsy());
        a145.a();
        agmi a146 = agmk.a();
        a146.k(4);
        a146.j(true);
        a146.c(true);
        a146.b("participants.comparable_destination");
        a146.e(true);
        a146.h(new wsy());
        a146.a();
        agmi a147 = agmk.a();
        a147.k(4);
        a147.b("participants.country_code");
        a147.h(new wsy());
        a147.a();
        agmi a148 = agmk.a();
        a148.k(2);
        a148.j(true);
        a148.c(true);
        a148.b("participants.recipient_id");
        a148.e(true);
        a148.h(new wsy());
        a148.a();
        agmi a149 = agmk.a();
        a149.k(4);
        a149.b("participants.recipient_canonical_address");
        a149.h(new wsy());
        this.e = new sbc(a149.a());
        agmi a150 = agmk.a();
        a150.k(4);
        a150.b("participants.contact_photo_uri");
        a150.h(new wsy());
        a150.a();
        agmi a151 = agmk.a();
        a151.k(4);
        a151.b("participants.subscription_name");
        a151.h(new wsy());
        a151.a();
        agmi a152 = agmk.a();
        a152.k(1);
        a152.b("participants.subscription_color");
        a152.h(new wsy());
        a152.a();
        agmi a153 = agmk.a();
        a153.k(4);
        a153.b("participants.contact_destination");
        a153.h(new wsy());
        a153.a();
        agmi a154 = agmk.a();
        a154.k(1);
        a154.b("participants.video_reachability");
        a154.h(new wsy());
        a154.a();
        agmi a155 = agmk.a();
        a155.k(4);
        a155.b("participants.alias");
        a155.h(new wsy());
        a155.a();
        agmi a156 = agmk.a();
        a156.k(1);
        a156.b("participants.is_rcs_available");
        a156.h(new wsy());
        a156.a();
        agmi a157 = agmk.a();
        a157.k(1);
        a157.b("participants.is_spam_source");
        a157.h(new wsy());
        a157.a();
        agmi a158 = agmk.a();
        a158.k(4);
        a158.j(true);
        a158.c(true);
        a158.b("participants.cms_id");
        a158.e(true);
        a158.h(new wsy());
        a158.a();
        agmi a159 = agmk.a();
        a159.k(4);
        a159.b("participants.profile_photo_blob_id");
        a159.h(new wsy());
        a159.a();
        agmi a160 = agmk.a();
        a160.k(5);
        a160.b("participants.profile_photo_encryption_key");
        a160.h(new wsy());
        a160.a();
        agmi a161 = agmk.a();
        a161.k(1);
        a161.b("participants.is_check_constraint_enabled_via_phenotype");
        a161.h(new wsy());
        a161.a();
        agmi a162 = agmk.a();
        a162.k(1);
        a162.b("participants.is_valid_phone_number_data");
        a162.h(new wsy());
        a162.a();
        agmi a163 = agmk.a();
        a163.k(2);
        a163.c(true);
        a163.d(true);
        a163.g(new sbb(19));
        a163.b("participants.duplicate_of");
        a163.h(new wsy());
        a163.a();
        agmi a164 = agmk.a();
        a164.k(1);
        a164.b("participants.cms_life_cycle");
        a164.h(new wsy());
        a164.a();
        agmi a165 = agmk.a();
        a165.k(1);
        a165.b("participants.norm_ui_status");
        a165.h(new wsy());
        a165.a();
        agmi a166 = agmk.a();
        a166.k(4);
        a166.b("participants.last_modified_by_key");
        a166.h(new wsy());
        a166.a();
        agmi a167 = agmk.a();
        a167.k(1);
        a167.b("participants.profile_photo_user_preference");
        a167.h(new wsy());
        a167.a();
        agmi a168 = agmk.a();
        a168.k(5);
        a168.b("participants.contact_metadata");
        a168.h(new wsy());
        a168.a();
        agmi a169 = agmk.a();
        a169.k(2);
        a169.c(true);
        a169.b("reports_concat_view._id_read_reports");
        a169.h(new wsy());
        a169.a();
        agmi a170 = agmk.a();
        a170.k(1);
        a170.i(true);
        a170.c(true);
        a170.d(true);
        a170.b("reports_concat_view.message_id_read_reports");
        a170.e(true);
        a170.h(new wsy());
        a170.a();
        agmi a171 = agmk.a();
        a171.k(1);
        a171.i(true);
        a171.c(true);
        a171.d(true);
        a171.b("reports_concat_view.participant_id_read_reports");
        a171.e(true);
        a171.h(new wsy());
        a171.a();
        agmi a172 = agmk.a();
        a172.k(1);
        a172.b("reports_concat_view.receive_time_read_reports");
        a172.h(new wsy());
        a172.a();
        agmi a173 = agmk.a();
        a173.k(1);
        a173.b("reports_concat_view.read_time_read_reports");
        a173.h(new wsy());
        a173.a();
        agmi a174 = agmk.a();
        a174.k(2);
        a174.b("reports_concat_view.ftd_time_read_reports");
        a174.h(new wsy());
        a174.a();
        agmi a175 = agmk.a();
        a175.k(8);
        a175.b("reports_concat_view.read_reports__ROWID_read_reports");
        a175.h(new wsy());
        a175.a();
        agmi a176 = agmk.a();
        a176.k(2);
        a176.i(true);
        a176.c(true);
        a176.d(true);
        a176.g(new sbb(20));
        a176.b("user_refs_concat_view.message_id_user_references");
        a176.e(true);
        a176.h(new wsy());
        a176.a();
        agmi a177 = agmk.a();
        a177.k(2);
        a177.i(true);
        a177.c(true);
        a177.d(true);
        a177.g(new sbg(1));
        a177.b("user_refs_concat_view.participant_id_user_references");
        a177.e(true);
        a177.h(new wsy());
        a177.a();
        agmi a178 = agmk.a();
        a178.k(2);
        a178.b("user_refs_concat_view.user_ref_datetime_user_references");
        a178.h(new wsy());
        a178.a();
        agmi a179 = agmk.a();
        a179.k(8);
        a179.b("user_refs_concat_view.user_references__ROWID_user_references");
        a179.h(new wsy());
        a179.a();
        agmi a180 = agmk.a();
        a180.k(8);
        a180.b("user_refs_concat_view.user_ref_display_name");
        a180.h(new wsy());
        a180.a();
        agmi a181 = agmk.a();
        a181.k(8);
        a181.b("user_refs_concat_view.user_ref_profile_photo_uri");
        a181.h(new wsy());
        a181.a();
        agmi a182 = agmk.a();
        a182.k(8);
        a182.b("user_refs_concat_view.user_ref_full_name");
        a182.h(new wsy());
        a182.a();
        agmi a183 = agmk.a();
        a183.k(8);
        a183.b("user_refs_concat_view.user_ref_lookup_key");
        a183.h(new wsy());
        a183.a();
        agmi a184 = agmk.a();
        a184.k(4);
        a184.c(true);
        a184.b("user_refs_concat_view.normalized_destination_participants");
        a184.e(true);
        a184.h(new wsy());
        a184.a();
        agmi a185 = agmk.a();
        a185.k(1);
        a185.b("user_refs_concat_view.color_palette_index_participants");
        a185.h(new wsy());
        a185.a();
        agmi a186 = agmk.a();
        a186.k(1);
        a186.b("user_refs_concat_view.color_type_participants");
        a186.h(new wsy());
        a186.a();
        agmi a187 = agmk.a();
        a187.k(1);
        a187.b("user_refs_concat_view.extended_color_participants");
        a187.h(new wsy());
        a187.a();
        agmi a188 = agmk.a();
        a188.k(8);
        a188.b("user_refs_concat_view.participants__ROWID_participants");
        a188.h(new wsy());
        a188.a();
        agmi a189 = agmk.a();
        a189.k(2);
        a189.j(true);
        a189.c(true);
        a189.d(true);
        a189.g(new sbb(0));
        a189.b("link_preview.message_id");
        a189.h(new wsy());
        a189.a();
        agmi a190 = agmk.a();
        a190.k(4);
        a190.b("link_preview.trigger_url");
        a190.h(new wsy());
        a190.a();
        agmi a191 = agmk.a();
        a191.k(2);
        a191.b("link_preview.expiration_time_millis");
        a191.h(new wsy());
        a191.a();
        agmi a192 = agmk.a();
        a192.k(4);
        a192.b("link_preview.link_title");
        a192.h(new wsy());
        a192.a();
        agmi a193 = agmk.a();
        a193.k(4);
        a193.b("link_preview.link_description");
        a193.h(new wsy());
        a193.a();
        agmi a194 = agmk.a();
        a194.k(4);
        a194.b("link_preview.link_image_url");
        a194.h(new wsy());
        a194.a();
        agmi a195 = agmk.a();
        a195.k(4);
        a195.b("link_preview.link_domain");
        a195.h(new wsy());
        a195.a();
        agmi a196 = agmk.a();
        a196.k(4);
        a196.b("link_preview.link_canonical_url");
        a196.h(new wsy());
        a196.a();
        agmi a197 = agmk.a();
        a197.k(2);
        a197.b("link_preview.link_preview_prevented");
        a197.h(new wsy());
        a197.a();
        agmi a198 = agmk.a();
        a198.k(2);
        a198.b("link_preview.link_preview_failed");
        a198.h(new wsy());
        a198.a();
        agmi a199 = agmk.a();
        a199.k(2);
        a199.j(true);
        a199.f(true);
        a199.c(true);
        a199.b("link_preview._id");
        a199.h(new wsy());
        a199.a();
        agmi a200 = agmk.a();
        a200.k(4);
        a200.j(true);
        a200.f(true);
        a200.c(true);
        a200.b("verified_sms_senders.sender_id");
        a200.h(new wsy());
        a200.a();
        agmi a201 = agmk.a();
        a201.k(4);
        a201.b("verified_sms_senders.brand_id");
        a201.h(new wsy());
        a201.a();
        agmi a202 = agmk.a();
        a202.k(4);
        a202.b("verified_sms_brands.name");
        a202.h(new wsy());
        a202.a();
        agmi a203 = agmk.a();
        a203.k(4);
        a203.b("verified_sms_brands.description");
        a203.h(new wsy());
        a203.a();
        agmi a204 = agmk.a();
        a204.k(4);
        a204.b("verified_sms_brands.logo_uri");
        a204.h(new wsy());
        a204.a();
        agmi a205 = agmk.a();
        a205.k(2);
        a205.j(true);
        a205.f(true);
        a205.c(true);
        a205.b("verified_sms_brands._id");
        a205.h(new wsy());
        a205.a();
        agmi a206 = agmk.a();
        a206.k(4);
        a206.j(true);
        a206.c(true);
        a206.b("verified_sms_brands.brand_id");
        a206.h(new wsy());
        a206.a();
        agmi a207 = agmk.a();
        a207.k(4);
        a207.b("verified_sms_brands.logo_url");
        a207.h(new wsy());
        a207.a();
        agmi a208 = agmk.a();
        a208.k(4);
        a208.b("verified_sms_brands.version_token");
        a208.h(new wsy());
        a208.a();
        agmi a209 = agmk.a();
        a209.k(4);
        a209.c(true);
        a209.b("conversations.participant_normalized_destination");
        a209.h(new wsy());
        a209.a();
        agmi a210 = agmk.a();
        a210.k(1);
        a210.b("conversations.conv_type");
        a210.h(new wsy());
        a210.a();
        agmi a211 = agmk.a();
        a211.k(1);
        a211.b("conversations.has_ea2p_bot_recipient");
        a211.h(new wsy());
        this.i = new sbc(a211.a());
        agmi a212 = agmk.a();
        a212.k(4);
        a212.c(true);
        a212.b("conversations.rcs_group_id");
        a212.h(new wsy());
        this.c = new sbc(a212.a());
        agmi a213 = agmk.a();
        a213.k(1);
        a213.b("conversations.rcs_session_allows_revocation");
        a213.h(new wsy());
        a213.a();
        agmi a214 = agmk.a();
        a214.k(2);
        a214.b("conversations.recipient_offline_timestamp_ms");
        a214.h(new wsy());
        a214.a();
        agmi a215 = agmk.a();
        a215.k(2);
        a215.j(true);
        a215.f(true);
        a215.c(true);
        a215.b("conversations._id");
        a215.h(new wsy());
        this.d = new sbc(a215.a());
        agmi a216 = agmk.a();
        a216.k(1);
        a216.c(true);
        a216.b("conversations.sms_thread_id");
        a216.h(new wsy());
        a216.a();
        agmi a217 = agmk.a();
        a217.k(4);
        a217.b("conversations.name");
        a217.h(new wsy());
        a217.a();
        agmi a218 = agmk.a();
        a218.k(2);
        a218.b("conversations.name_is_automatic");
        a218.h(new wsy());
        a218.a();
        agmi a219 = agmk.a();
        a219.k(4);
        a219.b("conversations.subtitle");
        a219.h(new wsy());
        a219.a();
        agmi a220 = agmk.a();
        a220.k(1);
        a220.b("conversations.latest_message_id");
        a220.h(new wsy());
        a220.a();
        agmi a221 = agmk.a();
        a221.k(4);
        a221.b("conversations.snippet_text");
        a221.h(new wsy());
        a221.a();
        agmi a222 = agmk.a();
        a222.k(4);
        a222.b("conversations.subject_text");
        a222.h(new wsy());
        a222.a();
        agmi a223 = agmk.a();
        a223.k(4);
        a223.b("conversations.preview_uri");
        a223.h(new wsy());
        a223.a();
        agmi a224 = agmk.a();
        a224.k(4);
        a224.b("conversations.preview_content_type");
        a224.h(new wsy());
        a224.a();
        agmi a225 = agmk.a();
        a225.k(1);
        a225.b("conversations.show_draft");
        a225.h(new wsy());
        a225.a();
        agmi a226 = agmk.a();
        a226.k(4);
        a226.b("conversations.draft_snippet_text");
        a226.h(new wsy());
        a226.a();
        agmi a227 = agmk.a();
        a227.k(4);
        a227.b("conversations.draft_subject_text");
        a227.h(new wsy());
        a227.a();
        agmi a228 = agmk.a();
        a228.k(4);
        a228.b("conversations.draft_preview_uri");
        a228.h(new wsy());
        a228.a();
        agmi a229 = agmk.a();
        a229.k(4);
        a229.b("conversations.draft_preview_content_type");
        a229.h(new wsy());
        a229.a();
        agmi a230 = agmk.a();
        a230.k(1);
        a230.b("conversations.etouffee_default");
        a230.h(new wsy());
        a230.a();
        agmi a231 = agmk.a();
        a231.k(1);
        a231.c(true);
        a231.b("conversations.archive_status");
        a231.h(new wsy());
        a231.a();
        agmi a232 = agmk.a();
        a232.k(1);
        a232.c(true);
        a232.b("conversations.sort_timestamp");
        a232.h(new wsy());
        a232.a();
        agmi a233 = agmk.a();
        a233.k(1);
        a233.b("conversations.last_read_timestamp");
        a233.h(new wsy());
        a233.a();
        agmi a234 = agmk.a();
        a234.k(4);
        a234.b("conversations.icon");
        a234.h(new wsy());
        a234.a();
        agmi a235 = agmk.a();
        a235.k(1);
        a235.b("conversations.participant_contact_id");
        a235.h(new wsy());
        a235.a();
        agmi a236 = agmk.a();
        a236.k(1);
        a236.b("conversations.normalized_participant_contact_id");
        a236.h(new wsy());
        a236.a();
        agmi a237 = agmk.a();
        a237.k(4);
        a237.b("conversations.participant_lookup_key");
        a237.h(new wsy());
        a237.a();
        agmi a238 = agmk.a();
        a238.k(4);
        a238.b("conversations.normalized_participant_lookup_key");
        a238.h(new wsy());
        a238.a();
        agmi a239 = agmk.a();
        a239.k(4);
        a239.j(true);
        a239.c(true);
        a239.b("conversations.participant_comparable_destination");
        a239.e(true);
        a239.h(new wsy());
        a239.a();
        agmi a240 = agmk.a();
        a240.k(4);
        a240.b("conversations.current_self_id");
        a240.h(new wsy());
        a240.a();
        agmi a241 = agmk.a();
        a241.k(4);
        a241.b("conversations.current_my_identity");
        a241.h(new wsy());
        a241.a();
        agmi a242 = agmk.a();
        a242.k(4);
        a242.c(true);
        a242.d(true);
        a242.g(new sbb(2));
        a242.b("conversations.current_my_identity_foreign_key");
        a242.h(new wsy());
        a242.a();
        agmi a243 = agmk.a();
        a243.k(4);
        a243.c(true);
        a243.d(true);
        a243.g(new sbb(3));
        a243.b("conversations.destination_token");
        a243.h(new wsy());
        a243.a();
        agmi a244 = agmk.a();
        a244.k(1);
        a244.b("conversations.participant_count");
        a244.h(new wsy());
        a244.a();
        agmi a245 = agmk.a();
        a245.k(1);
        a245.b("conversations.notification_enabled");
        a245.h(new wsy());
        a245.a();
        agmi a246 = agmk.a();
        a246.k(4);
        a246.b("conversations.notification_sound_uri");
        a246.h(new wsy());
        a246.a();
        agmi a247 = agmk.a();
        a247.k(1);
        a247.b("conversations.notification_vibration");
        a247.h(new wsy());
        a247.a();
        agmi a248 = agmk.a();
        a248.k(1);
        a248.b("conversations.include_email_addr");
        a248.h(new wsy());
        a248.a();
        agmi a249 = agmk.a();
        a249.k(4);
        a249.b("conversations.sms_service_center");
        a249.h(new wsy());
        a249.a();
        agmi a250 = agmk.a();
        a250.k(4);
        a250.b("conversations.participant_id_list");
        a250.h(new wsy());
        a250.a();
        agmi a251 = agmk.a();
        a251.k(4);
        a251.j(true);
        a251.c(true);
        a251.b("conversations.normalized_participant_id_list");
        a251.e(true);
        a251.h(new wsy());
        a251.a();
        agmi a252 = agmk.a();
        a252.k(1);
        a252.b("conversations.source_type");
        a252.h(new wsy());
        a252.a();
        agmi a253 = agmk.a();
        a253.k(1);
        a253.c(true);
        a253.b("conversations.rcs_session_id");
        a253.h(new wsy());
        a253.a();
        agmi a254 = agmk.a();
        a254.k(1);
        a254.b("conversations.join_state");
        a254.h(new wsy());
        a254.a();
        agmi a255 = agmk.a();
        a255.k(1);
        a255.b("conversations.send_mode");
        a255.h(new wsy());
        a255.a();
        agmi a256 = agmk.a();
        a256.k(1);
        a256.b("conversations.IS_ENTERPRISE");
        a256.h(new wsy());
        a256.a();
        agmi a257 = agmk.a();
        a257.k(1);
        a257.b("conversations.last_interactive_event_timestamp");
        a257.h(new wsy());
        a257.a();
        agmi a258 = agmk.a();
        a258.k(4);
        a258.b("conversations.participant_display_destination");
        a258.h(new wsy());
        a258.a();
        agmi a259 = agmk.a();
        a259.k(4);
        a259.b("conversations.normalized_participant_display_destination");
        a259.h(new wsy());
        a259.a();
        agmi a260 = agmk.a();
        a260.k(1);
        a260.b("conversations.spam_warning_dismiss_status");
        a260.h(new wsy());
        a260.a();
        agmi a261 = agmk.a();
        a261.k(1);
        a261.b("conversations.open_count");
        a261.h(new wsy());
        a261.a();
        agmi a262 = agmk.a();
        a262.k(1);
        a262.b("conversations.last_logged_scooby_metadata_timestamp");
        a262.h(new wsy());
        a262.a();
        agmi a263 = agmk.a();
        a263.k(1);
        a263.c(true);
        a263.b("conversations.delete_timestamp");
        a263.h(new wsy());
        a263.a();
        agmi a264 = agmk.a();
        a264.k(4);
        a264.j(true);
        a264.c(true);
        a264.b("conversations.cms_id");
        a264.e(true);
        a264.h(new wsy());
        a264.a();
        agmi a265 = agmk.a();
        a265.k(4);
        a265.b("conversations.rcs_conference_uri");
        a265.h(new wsy());
        a265.a();
        agmi a266 = agmk.a();
        a266.k(5);
        a266.b("conversations.tachygram_group_routing_info_token");
        a266.h(new wsy());
        a266.a();
        agmi a267 = agmk.a();
        a267.k(1);
        a267.b("conversations.cms_most_recent_read_message_timestamp_ms");
        a267.h(new wsy());
        a267.a();
        agmi a268 = agmk.a();
        a268.k(2);
        a268.b("conversations.rcs_subject_change_timestamp_ms");
        a268.h(new wsy());
        a268.a();
        agmi a269 = agmk.a();
        a269.k(2);
        a269.b("conversations.rcs_group_capabilities");
        a269.h(new wsy());
        a269.a();
        agmi a270 = agmk.a();
        a270.k(1);
        a270.b("conversations.awaiting_reverse_sync");
        a270.h(new wsy());
        a270.a();
        agmi a271 = agmk.a();
        a271.k(2);
        a271.c(true);
        a271.d(true);
        a271.g(new sbb(4));
        a271.b("conversations.duplicate_of");
        a271.h(new wsy());
        a271.a();
        agmi a272 = agmk.a();
        a272.k(2);
        a272.c(true);
        a272.d(true);
        a272.g(new sbb(5));
        a272.b("conversations.new_duplicate_of");
        a272.h(new wsy());
        a272.a();
        agmi a273 = agmk.a();
        a273.k(1);
        a273.b("conversations.error_state");
        a273.h(new wsy());
        a273.a();
        agmi a274 = agmk.a();
        a274.k(1);
        a274.b("conversations.cms_life_cycle");
        a274.h(new wsy());
        a274.a();
        agmi a275 = agmk.a();
        a275.k(4);
        a275.b("conversations.rcs_group_self_msisdn");
        a275.h(new wsy());
        a275.a();
        agmi a276 = agmk.a();
        a276.k(2);
        a276.b("conversations.rcs_group_last_sync_timestamp");
        a276.h(new wsy());
        a276.a();
        agmi a277 = agmk.a();
        a277.k(1);
        a277.b("conversations.has_been_e2ee");
        a277.h(new wsy());
        a277.a();
        agmi a278 = agmk.a();
        a278.k(1);
        a278.b("conversations.marked_as_unread");
        a278.h(new wsy());
        a278.a();
        agmi a279 = agmk.a();
        a279.k(5);
        a279.b("conversations.custom_theme");
        a279.h(new wsy());
        a279.a();
        agmi a280 = agmk.a();
        a280.k(2);
        a280.b("conversations.mms_group_upgrade_status");
        a280.h(new wsy());
        a280.a();
        agmi a281 = agmk.a();
        a281.k(2);
        a281.b("conversations.mms_group_upgrade_retries");
        a281.h(new wsy());
        a281.a();
        agmi a282 = agmk.a();
        a282.k(2);
        a282.b("conversations.encryption_protocol");
        a282.h(new wsy());
        a282.a();
        agmi a283 = agmk.a();
        a283.k(4);
        a283.b("conversations.encryption_id");
        a283.h(new wsy());
        a283.a();
        agmi a284 = agmk.a();
        a284.k(4);
        a284.j(true);
        a284.c(true);
        a284.b("conversations.cms_correlation_id");
        a284.e(true);
        a284.h(new wsy());
        a284.a();
        agmi a285 = agmk.a();
        a285.k(5);
        a285.b("message_reactions.reactions_data");
        a285.h(new wsy());
        a285.a();
        agmi a286 = agmk.a();
        a286.k(2);
        a286.j(true);
        a286.f(true);
        a286.c(true);
        a286.b("message_reactions._id");
        a286.h(new wsy());
        a286.a();
        agmi a287 = agmk.a();
        a287.k(2);
        a287.j(true);
        a287.c(true);
        a287.d(true);
        a287.g(new sbb(6));
        a287.b("message_reactions.message_id");
        a287.h(new wsy());
        a287.a();
        agmi a288 = agmk.a();
        a288.k(2);
        a288.c(true);
        a288.d(true);
        a288.g(new sbb(7));
        a288.b("message_reactions.reacted_message_id");
        a288.h(new wsy());
        a288.a();
        agmi a289 = agmk.a();
        a289.k(2);
        a289.b("message_reactions.reaction");
        a289.h(new wsy());
        a289.a();
        agmi a290 = agmk.a();
        a290.k(5);
        a290.b("message_reactions.applied_reaction");
        a290.h(new wsy());
        a290.a();
        agmi a291 = agmk.a();
        a291.k(5);
        a291.c(true);
        a291.b("message_reactions.animation_effect");
        a291.h(new wsy());
        a291.a();
        agmi a292 = agmk.a();
        a292.k(4);
        a292.c(true);
        a292.b("file_transfer.transfer_id");
        a292.h(new wsy());
        a292.a();
        agmi a293 = agmk.a();
        a293.k(1);
        a293.j(true);
        a293.f(true);
        a293.c(true);
        a293.d(true);
        a293.g(new sbb(8));
        a293.b("file_transfer.message_id");
        a293.h(new wsy());
        a293.a();
        agmi a294 = agmk.a();
        a294.k(1);
        a294.b("file_transfer.transfer_type");
        a294.h(new wsy());
        a294.a();
        agmi a295 = agmk.a();
        a295.k(5);
        a295.b("file_transfer.attachment_upload_response");
        a295.h(new wsy());
        a295.a();
        agmi a296 = agmk.a();
        a296.k(5);
        a296.b("file_transfer.file_information");
        a296.h(new wsy());
        a296.a();
        agmi a297 = agmk.a();
        a297.k(5);
        a297.b("file_transfer.thumbnail_information");
        a297.h(new wsy());
        a297.a();
        agmi a298 = agmk.a();
        a298.k(4);
        a298.b("file_transfer.transfer_handle");
        a298.h(new wsy());
        a298.a();
        agmi a299 = agmk.a();
        a299.k(5);
        a299.b("file_transfer.opaque_data");
        a299.h(new wsy());
        a299.a();
        agmi a300 = agmk.a();
        a300.k(2);
        a300.j(true);
        a300.c(true);
        a300.d(true);
        a300.g(new sbb(9));
        a300.b("message_star.message_id");
        a300.e(true);
        a300.h(new wsy());
        a300.a();
        agmi a301 = agmk.a();
        a301.k(2);
        a301.j(true);
        a301.f(true);
        a301.c(true);
        a301.b("message_star._id");
        a301.h(new wsy());
        a301.a();
        agmi a302 = agmk.a();
        a302.k(5);
        a302.b("message_photos_sharing.sharing_state");
        a302.h(new wsy());
        a302.a();
        agmi a303 = agmk.a();
        a303.k(2);
        a303.j(true);
        a303.c(true);
        a303.d(true);
        a303.g(new sbb(10));
        a303.b("message_photos_sharing.message_id");
        a303.e(true);
        a303.h(new wsy());
        a303.a();
        agmi a304 = agmk.a();
        a304.k(2);
        a304.j(true);
        a304.c(true);
        a304.d(true);
        a304.g(new sbb(11));
        a304.b("vmt.part_id");
        a304.e(true);
        a304.h(new wsy());
        a304.a();
        agmi a305 = agmk.a();
        a305.k(2);
        a305.b("vmt.vmt_status");
        a305.h(new wsy());
        a305.a();
        agmi a306 = agmk.a();
        a306.k(4);
        a306.b("vmt.text");
        a306.h(new wsy());
        a306.a();
        agmi a307 = agmk.a();
        a307.k(4);
        a307.b("vmt.locale");
        a307.h(new wsy());
        a307.a();
        agmi a308 = agmk.a();
        a308.k(8);
        a308.b("vmt__ROWID");
        a308.h(new wsy());
        a308.a();
        agmi a309 = agmk.a();
        a309.k(2);
        a309.j(true);
        a309.i(true);
        a309.c(true);
        a309.d(true);
        a309.g(new sbb(12));
        a309.b("message_replies_view.message_id_message_replies");
        a309.e(true);
        a309.h(new wsy());
        a309.a();
        agmi a310 = agmk.a();
        a310.k(2);
        a310.c(true);
        a310.b("message_replies_view._id_messages");
        a310.h(new wsy());
        a310.a();
        agmi a311 = agmk.a();
        a311.k(1);
        a311.c(true);
        a311.b("message_replies_view.received_timestamp_messages");
        a311.h(new wsy());
        a311.a();
        agmi a312 = agmk.a();
        a312.k(2);
        a312.c(true);
        a312.b("message_replies_view._id_participants");
        a312.h(new wsy());
        a312.a();
        agmi a313 = agmk.a();
        a313.k(1);
        a313.c(true);
        a313.b("message_replies_view.sub_id_participants");
        a313.e(true);
        a313.h(new wsy());
        a313.a();
        agmi a314 = agmk.a();
        a314.k(4);
        a314.c(true);
        a314.b("message_replies_view.normalized_destination_participants");
        a314.e(true);
        a314.h(new wsy());
        a314.a();
        agmi a315 = agmk.a();
        a315.k(4);
        a315.b("message_replies_view.display_destination_participants");
        a315.h(new wsy());
        a315.a();
        agmi a316 = agmk.a();
        a316.k(4);
        a316.b("message_replies_view.full_name_participants");
        a316.h(new wsy());
        a316.a();
        agmi a317 = agmk.a();
        a317.k(4);
        a317.b("message_replies_view.first_name_participants");
        a317.h(new wsy());
        a317.a();
        agmi a318 = agmk.a();
        a318.k(2);
        a318.c(true);
        a318.b("message_replies_view._id_parts");
        a318.h(new wsy());
        a318.a();
        agmi a319 = agmk.a();
        a319.k(4);
        a319.b("message_replies_view.text_parts");
        a319.h(new wsy());
        a319.a();
        agmi a320 = agmk.a();
        a320.k(4);
        a320.b("message_replies_view.uri_parts");
        a320.h(new wsy());
        a320.a();
        agmi a321 = agmk.a();
        a321.k(4);
        a321.c(true);
        a321.b("message_replies_view.content_type_parts");
        a321.h(new wsy());
        a321.a();
        agmi a322 = agmk.a();
        a322.k(4);
        a322.b("message_replies_view.file_name_parts");
        a322.h(new wsy());
        a322.a();
        agmi a323 = agmk.a();
        a323.k(1);
        a323.b("message_replies_view.duration_parts");
        a323.h(new wsy());
        a323.a();
        agmi a324 = agmk.a();
        a324.k(8);
        a324.b("message_replies_view.parts__ROWID_parts");
        a324.h(new wsy());
        a324.a();
        agmi a325 = agmk.a();
        a325.k(4);
        a325.i(true);
        a325.b("message_replies_view.trigger_url_link_preview");
        a325.h(new wsy());
        a325.a();
        agmi a326 = agmk.a();
        a326.k(2);
        a326.b("message_replies_view.expiration_time_millis_link_preview");
        a326.h(new wsy());
        a326.a();
        agmi a327 = agmk.a();
        a327.k(4);
        a327.b("message_replies_view.link_title_link_preview");
        a327.h(new wsy());
        a327.a();
        agmi a328 = agmk.a();
        a328.k(4);
        a328.b("message_replies_view.link_image_url_link_preview");
        a328.h(new wsy());
        a328.a();
        agmi a329 = agmk.a();
        a329.k(2);
        a329.b("message_replies_view.link_preview_failed_link_preview");
        a329.h(new wsy());
        a329.a();
        agmi a330 = agmk.a();
        a330.k(4);
        a330.b("profiles_table.display_name");
        a330.h(new wsy());
        a330.a();
        agmi a331 = agmk.a();
        a331.k(2);
        a331.j(true);
        a331.f(true);
        a331.c(true);
        a331.b("profiles_table._id");
        a331.h(new wsy());
        a331.a();
        agmi a332 = agmk.a();
        a332.k(2);
        a332.c(true);
        a332.d(true);
        a332.g(new sbb(13));
        a332.b("profiles_table.participant_id");
        a332.h(new wsy());
        a332.a();
        agmi a333 = agmk.a();
        a333.k(4);
        a333.b("profiles_table.person_id");
        a333.h(new wsy());
        a333.a();
        agmi a334 = agmk.a();
        a334.k(4);
        a334.b("profiles_table.profile_access_token");
        a334.h(new wsy());
        a334.a();
        agmi a335 = agmk.a();
        a335.k(2);
        a335.b("profiles_table.sending_self_profile_interaction_state");
        a335.h(new wsy());
        a335.a();
        agmi a336 = agmk.a();
        a336.k(5);
        a336.b("profiles_table.self_profile_sharing_metadata");
        a336.h(new wsy());
        a336.a();
        agmi a337 = agmk.a();
        a337.k(4);
        a337.b("profiles_table.first_name");
        a337.h(new wsy());
        a337.a();
        agmi a338 = agmk.a();
        a338.k(4);
        a338.b("profiles_table.last_name");
        a338.h(new wsy());
        a338.a();
        agmi a339 = agmk.a();
        a339.k(4);
        a339.b("profiles_table.photo_uri");
        a339.h(new wsy());
        a339.a();
        agmi a340 = agmk.a();
        a340.k(4);
        a340.b("profiles_table.sender_last_updated_time");
        a340.h(new wsy());
        a340.a();
        agmi a341 = agmk.a();
        a341.k(4);
        a341.b("profiles_table.sender_last_updated_time_from_rcs");
        a341.h(new wsy());
        a341.a();
        agmi a342 = agmk.a();
        a342.k(4);
        a342.c(true);
        a342.b("profiles_table.contact_lookup_key");
        a342.h(new wsy());
        a342.a();
        agmi a343 = agmk.a();
        a343.k(4);
        a343.c(true);
        a343.b("profiles_table.phone_number");
        a343.h(new wsy());
        a343.a();
        agmi a344 = agmk.a();
        a344.k(1);
        a344.b("profiles_table.is_self_profile_shareable");
        a344.h(new wsy());
        a344.a();
        agmi a345 = agmk.a();
        a345.k(2);
        a345.b("profiles_table.has_shared_access_token_with_user");
        a345.h(new wsy());
        a345.a();
        agmi a346 = agmk.a();
        a346.k(1);
        a346.b("profiles_table.name_timestamp");
        a346.h(new wsy());
        a346.a();
        agmi a347 = agmk.a();
        a347.k(1);
        a347.b("profiles_table.photo_timestamp");
        a347.h(new wsy());
        a347.a();
        agmi a348 = agmk.a();
        a348.k(1);
        a348.b("profiles_table.belongs_to_self_gaia");
        a348.h(new wsy());
        a348.a();
        agmi a349 = agmk.a();
        a349.k(1);
        a349.b("profiles_table.gaia_update_timestamp");
        a349.h(new wsy());
        a349.a();
        agmi a350 = agmk.a();
        a350.k(4);
        a350.b("message_captions.caption");
        a350.h(new wsy());
        a350.a();
        agmi a351 = agmk.a();
        a351.k(2);
        a351.j(true);
        a351.c(true);
        a351.d(true);
        a351.g(new sbb(14));
        a351.b("message_captions.message_id");
        a351.e(true);
        a351.h(new wsy());
        a351.a();
    }

    public vid(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, byte[] bArr) {
        armfVar.getClass();
        this.i = armfVar;
        armfVar2.getClass();
        this.g = armfVar2;
        armfVar3.getClass();
        this.b = armfVar3;
        armfVar4.getClass();
        this.f = armfVar4;
        armfVar5.getClass();
        this.l = armfVar5;
        armfVar6.getClass();
        this.j = armfVar6;
        this.k = armfVar7;
        armfVar8.getClass();
        this.c = armfVar8;
        armfVar9.getClass();
        this.n = armfVar9;
        armfVar10.getClass();
        this.e = armfVar10;
        armfVar11.getClass();
        this.m = armfVar11;
        armfVar12.getClass();
        this.a = armfVar12;
        this.h = armfVar13;
        armfVar14.getClass();
        this.d = armfVar14;
    }

    public vid(byte[] bArr) {
        agmi a = agmk.a();
        a.d = 4;
        a.j(true);
        a.i(true);
        a.f(true);
        a.c(true);
        a.a = "message_send_receive_attempt._id";
        a.c = new wsy();
        swf swfVar = new swf(a.a());
        this.m = swfVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.i(true);
        a2.c(true);
        a2.d(true);
        a2.b = new svc(19);
        a2.a = "message_send_receive_attempt.message_id";
        a2.e(true);
        a2.c = new wsy();
        swf swfVar2 = new swf(a2.a());
        this.b = swfVar2;
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.i(true);
        a3.a = "message_send_receive_attempt.timestamp";
        a3.c = new wsy();
        swf swfVar3 = new swf(a3.a());
        this.h = swfVar3;
        agmi a4 = agmk.a();
        a4.d = 2;
        a4.i(true);
        a4.a = "message_send_receive_attempt.message_sending_attempt";
        a4.e(true);
        a4.c = new wsy();
        swf swfVar4 = new swf(a4.a());
        this.g = swfVar4;
        agmi a5 = agmk.a();
        a5.d = 2;
        a5.a = "message_send_receive_attempt.message_protocol";
        a5.c = new wsy();
        swf swfVar5 = new swf(a5.a());
        this.k = swfVar5;
        agmi a6 = agmk.a();
        a6.d = 4;
        a6.a = "message_send_receive_attempt.current_sim_network_country";
        a6.c = new wsy();
        swf swfVar6 = new swf(a6.a());
        this.d = swfVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "message_send_receive_attempt.current_sim_country";
        a7.c = new wsy();
        swf swfVar7 = new swf(a7.a());
        this.c = swfVar7;
        agmi a8 = agmk.a();
        a8.d = 4;
        a8.a = "message_send_receive_attempt.current_sim_carrier_country";
        a8.c = new wsy();
        swf swfVar8 = new swf(a8.a());
        this.i = swfVar8;
        agmi a9 = agmk.a();
        a9.d = 4;
        a9.a = "message_send_receive_attempt.settings_country";
        a9.c = new wsy();
        swf swfVar9 = new swf(a9.a());
        this.j = swfVar9;
        agmi a10 = agmk.a();
        a10.d = 4;
        a10.a = "message_send_receive_attempt.default_sms_sim_country";
        a10.c = new wsy();
        swf swfVar10 = new swf(a10.a());
        this.f = swfVar10;
        agmi a11 = agmk.a();
        a11.d = 4;
        a11.a = "message_send_receive_attempt.locale_country";
        a11.c = new wsy();
        swf swfVar11 = new swf(a11.a());
        this.n = swfVar11;
        agmi a12 = agmk.a();
        a12.d = 4;
        a12.a = "message_send_receive_attempt.default_sms_sim_network_country";
        a12.c = new wsy();
        swf swfVar12 = new swf(a12.a());
        this.l = swfVar12;
        agmi a13 = agmk.a();
        a13.d = 4;
        a13.a = "message_send_receive_attempt.default_sms_sim_carrier_country";
        a13.c = new wsy();
        swf swfVar13 = new swf(a13.a());
        this.a = swfVar13;
        this.e = new swf[]{swfVar, swfVar2, swfVar3, swfVar4, swfVar5, swfVar6, swfVar7, swfVar8, swfVar9, swfVar10, swfVar11, swfVar12, swfVar13};
    }

    public vid() {
        agmi a = agmk.a();
        a.d = 2;
        a.j(true);
        a.f(true);
        a.c(true);
        a.a = "message_spam._id";
        a.c = new wsy();
        swo swoVar = new swo(a.a());
        this.m = swoVar;
        agmi a2 = agmk.a();
        a2.d = 2;
        a2.c(true);
        a2.d(true);
        a2.b = new swm(2);
        a2.a = "message_spam.message_id";
        a2.c = new wsy();
        swo swoVar2 = new swo(a2.a());
        this.n = swoVar2;
        agmi a3 = agmk.a();
        a3.d = 2;
        a3.c(true);
        a3.d(true);
        a3.b = new swm(3);
        a3.a = "message_spam.conversation_id";
        a3.c = new wsy();
        swo swoVar3 = new swo(a3.a());
        this.f = swoVar3;
        agmi a4 = agmk.a();
        a4.d = 1;
        a4.a = "message_spam.source";
        a4.c = new wsy();
        swo swoVar4 = new swo(a4.a());
        this.h = swoVar4;
        agmi a5 = agmk.a();
        a5.d = 3;
        a5.a = "message_spam.score";
        a5.c = new wsy();
        swo swoVar5 = new swo(a5.a());
        this.j = swoVar5;
        agmi a6 = agmk.a();
        a6.d = 1;
        a6.a = "message_spam.outcome";
        a6.c = new wsy();
        swo swoVar6 = new swo(a6.a());
        this.b = swoVar6;
        agmi a7 = agmk.a();
        a7.d = 4;
        a7.a = "message_spam.ares_initiated_by";
        a7.c = new wsy();
        swo swoVar7 = new swo(a7.a());
        this.d = swoVar7;
        agmi a8 = agmk.a();
        a8.d = 2;
        a8.c(true);
        a8.a = "message_spam.classification_timestamp";
        a8.c = new wsy();
        swo swoVar8 = new swo(a8.a());
        this.a = swoVar8;
        agmi a9 = agmk.a();
        a9.d = 1;
        a9.a = "message_spam.trigger";
        a9.c = new wsy();
        swo swoVar9 = new swo(a9.a());
        this.k = swoVar9;
        agmi a10 = agmk.a();
        a10.d = 1;
        a10.a = "message_spam.action_type";
        a10.c = new wsy();
        swo swoVar10 = new swo(a10.a());
        this.c = swoVar10;
        agmi a11 = agmk.a();
        a11.d = 1;
        a11.a = "message_spam.action_contributors";
        a11.c = new wsy();
        swo swoVar11 = new swo(a11.a());
        this.i = swoVar11;
        agmi a12 = agmk.a();
        a12.d = 1;
        a12.a = "message_spam.error_code";
        a12.c = new wsy();
        swo swoVar12 = new swo(a12.a());
        this.l = swoVar12;
        agmi a13 = agmk.a();
        a13.d = 1;
        a13.a = "message_spam.reclassification_index";
        a13.c = new wsy();
        swo swoVar13 = new swo(a13.a());
        this.g = swoVar13;
        this.e = new swo[]{swoVar, swoVar2, swoVar3, swoVar4, swoVar5, swoVar6, swoVar7, swoVar8, swoVar9, swoVar10, swoVar11, swoVar12, swoVar13};
    }

    public vid(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14) {
        armfVar.getClass();
        this.e = armfVar;
        armfVar2.getClass();
        this.h = armfVar2;
        armfVar3.getClass();
        this.d = armfVar3;
        armfVar4.getClass();
        this.c = armfVar4;
        armfVar5.getClass();
        this.j = armfVar5;
        armfVar6.getClass();
        this.l = armfVar6;
        armfVar7.getClass();
        this.m = armfVar7;
        armfVar8.getClass();
        this.a = armfVar8;
        armfVar9.getClass();
        this.k = armfVar9;
        armfVar10.getClass();
        this.g = armfVar10;
        armfVar11.getClass();
        this.f = armfVar11;
        armfVar12.getClass();
        this.n = armfVar12;
        armfVar13.getClass();
        this.b = armfVar13;
        armfVar14.getClass();
        this.i = armfVar14;
    }

    public vid(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17) {
        armfVar.getClass();
        this.a = armfVar;
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar6;
        armfVar7.getClass();
        this.f = armfVar7;
        armfVar8.getClass();
        armfVar9.getClass();
        this.g = armfVar10;
        armfVar11.getClass();
        this.h = armfVar11;
        armfVar12.getClass();
        this.i = armfVar12;
        this.j = armfVar13;
        armfVar14.getClass();
        this.k = armfVar14;
        armfVar15.getClass();
        this.l = armfVar15;
        armfVar16.getClass();
        this.m = armfVar16;
        this.n = armfVar17;
    }
}
