package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public enum vwf {
    RECIPIENT_MMS_GROUP_UPGRADE_ELIGIBLE,
    RECIPIENT_NOT_NORMALIZED_NUMBER,
    RECIPIENT_CAPABILITY_EXCHANGE_FAILED,
    RECIPIENT_NOT_RCS_CAPABLE,
    RECIPIENT_TACHYON_MESSAGES_FEATURES_RETRIEVAL_FAIL,
    RECIPIENT_NO_MMS_GROUP_UPGRADE_FEATURE
}
