package defpackage;

import android.content.Context;
import java.util.ArrayList;
import java.util.Set;

/* compiled from: PG */
/* loaded from: classes3.dex */
public final class xjb {
    private final armf A;
    private final armf B;
    private final armf C;
    private final armf D;
    private final armf E;
    private final armf F;
    private final armf G;
    private final armf H;
    private final armf I;
    private final armf J;
    private final armf K;
    private final armf L;
    private final armf M;
    private final armf a;
    private final armf b;
    private final armf c;
    private final armf d;
    private final armf e;
    private final armf f;
    private final armf g;
    private final armf h;
    private final armf i;
    private final armf j;
    private final armf k;
    private final armf l;
    private final armf m;
    private final armf n;
    private final armf o;
    private final armf p;
    private final armf q;
    private final armf r;
    private final armf s;
    private final armf t;
    private final armf u;
    private final armf v;
    private final armf w;
    private final armf x;
    private final armf y;
    private final armf z;

    public xjb(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, armf armfVar28, armf armfVar29, armf armfVar30, armf armfVar31, armf armfVar32, armf armfVar33, armf armfVar34, armf armfVar35, armf armfVar36, armf armfVar37, armf armfVar38, armf armfVar39, armf armfVar40) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.j = armfVar10;
        armfVar11.getClass();
        this.k = armfVar11;
        armfVar12.getClass();
        this.l = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.n = armfVar14;
        armfVar15.getClass();
        this.o = armfVar15;
        armfVar16.getClass();
        this.p = armfVar16;
        armfVar17.getClass();
        this.q = armfVar17;
        armfVar18.getClass();
        this.r = armfVar18;
        armfVar19.getClass();
        this.s = armfVar19;
        armfVar20.getClass();
        this.t = armfVar20;
        armfVar21.getClass();
        this.u = armfVar21;
        armfVar22.getClass();
        this.v = armfVar22;
        armfVar23.getClass();
        this.w = armfVar23;
        armfVar24.getClass();
        this.x = armfVar24;
        armfVar25.getClass();
        this.y = armfVar25;
        armfVar26.getClass();
        this.z = armfVar26;
        armfVar27.getClass();
        this.A = armfVar27;
        armfVar28.getClass();
        this.B = armfVar28;
        armfVar29.getClass();
        this.C = armfVar29;
        armfVar30.getClass();
        this.D = armfVar30;
        armfVar31.getClass();
        this.E = armfVar31;
        armfVar32.getClass();
        this.F = armfVar32;
        armfVar33.getClass();
        this.G = armfVar33;
        armfVar34.getClass();
        this.H = armfVar34;
        armfVar35.getClass();
        armfVar36.getClass();
        this.I = armfVar36;
        armfVar37.getClass();
        this.J = armfVar37;
        armfVar38.getClass();
        this.K = armfVar38;
        armfVar39.getClass();
        this.L = armfVar39;
        armfVar40.getClass();
        this.M = armfVar40;
    }

    public final xja a(ArrayList arrayList, ArrayList arrayList2, ArrayList arrayList3, ArrayList arrayList4, Set set, Set set2) {
        wnq wnqVar = (wnq) this.a.b();
        wnqVar.getClass();
        wyp wypVar = (wyp) this.b.b();
        wypVar.getClass();
        wzs wzsVar = (wzs) this.i.b();
        wzsVar.getClass();
        xae xaeVar = (xae) this.j.b();
        xaeVar.getClass();
        uhj uhjVar = (uhj) this.k.b();
        uhjVar.getClass();
        tqx tqxVar = (tqx) this.m.b();
        tqxVar.getClass();
        agnq agnqVar = (agnq) this.n.b();
        agnqVar.getClass();
        ((Context) this.o.b()).getClass();
        yjf yjfVar = (yjf) this.q.b();
        yjfVar.getClass();
        yjy yjyVar = (yjy) this.r.b();
        yjyVar.getClass();
        xii xiiVar = (xii) this.F.b();
        xiiVar.getClass();
        armf armfVar = this.G;
        armf armfVar2 = this.H;
        armf armfVar3 = this.I;
        armf armfVar4 = this.J;
        armf armfVar5 = this.K;
        armf armfVar6 = this.L;
        armf armfVar7 = this.M;
        armf armfVar8 = this.u;
        armf armfVar9 = this.v;
        armf armfVar10 = this.w;
        armf armfVar11 = this.x;
        armf armfVar12 = this.y;
        armf armfVar13 = this.z;
        armf armfVar14 = this.A;
        armf armfVar15 = this.B;
        armf armfVar16 = this.C;
        armf armfVar17 = this.D;
        armf armfVar18 = this.E;
        armf armfVar19 = this.s;
        armf armfVar20 = this.t;
        armf armfVar21 = this.p;
        return new xja(wnqVar, wypVar, this.c, this.d, this.e, this.f, this.g, this.h, wzsVar, xaeVar, uhjVar, this.l, tqxVar, agnqVar, armfVar21, yjfVar, yjyVar, armfVar19, armfVar20, arrayList, arrayList2, arrayList3, arrayList4, set, set2, armfVar8, armfVar9, armfVar10, armfVar11, armfVar12, armfVar13, armfVar14, armfVar15, armfVar16, armfVar17, armfVar18, xiiVar, armfVar, armfVar2, armfVar3, armfVar4, armfVar5, armfVar6, armfVar7);
    }
}
