package defpackage;

import j$.util.DesugarCollections;

/* compiled from: PG */
/* loaded from: classes3.dex */
final class ymr extends arrp implements arqg {
    public static final ymr a = new ymr();

    public ymr() {
        super(0);
    }

    @Override // defpackage.arqg
    public final /* synthetic */ Object a() {
        aozy createBuilder = ymq.a.createBuilder();
        createBuilder.getClass();
        if (!createBuilder.b.isMutable()) {
            createBuilder.u();
        }
        apag apagVar = createBuilder.b;
        ((ymq) apagVar).d = "default";
        apzk apzkVar = apzk.DO_NOTHING;
        apzkVar.getClass();
        if (!apagVar.isMutable()) {
            createBuilder.u();
        }
        ((ymq) createBuilder.b).b = apzkVar.a();
        utz utzVar = ymd.a;
        if (!ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
            aozy createBuilder2 = ymu.a.createBuilder();
            createBuilder2.getClass();
            DesugarCollections.unmodifiableList(((ymu) createBuilder2.b).b).getClass();
            aozy createBuilder3 = ymj.a.createBuilder();
            createBuilder3.getClass();
            yyb.ad(3, createBuilder3);
            yyb.ac(brg.a, createBuilder3);
            yyb.ab(amzp.SPAM, createBuilder3);
            yyb.S(yyb.aa(createBuilder3), createBuilder2);
            yyb.Q(apzk.SHOW_WARNING, createBuilder2);
            yyb.Y(yyb.P(createBuilder2), createBuilder);
        }
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder4 = ymu.a.createBuilder();
        createBuilder4.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder4.b).b).getClass();
        aozy createBuilder5 = ymj.a.createBuilder();
        createBuilder5.getClass();
        yyb.ad(5, createBuilder5);
        yyb.ac(brg.a, createBuilder5);
        yyb.ab(amzp.SPAM, createBuilder5);
        yyb.S(yyb.aa(createBuilder5), createBuilder4);
        yyb.Q(apzk.SHOW_WARNING, createBuilder4);
        yyb.Y(yyb.P(createBuilder4), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder6 = ymu.a.createBuilder();
        createBuilder6.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder6.b).b).getClass();
        aozy createBuilder7 = ymj.a.createBuilder();
        createBuilder7.getClass();
        yyb.ad(6, createBuilder7);
        yyb.ac(brg.a, createBuilder7);
        yyb.ab(amzp.SPAM, createBuilder7);
        yyb.S(yyb.aa(createBuilder7), createBuilder6);
        yyb.Q(apzk.SHOW_WARNING, createBuilder6);
        yyb.Y(yyb.P(createBuilder6), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder8 = ymu.a.createBuilder();
        createBuilder8.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder8.b).b).getClass();
        aozy createBuilder9 = ymj.a.createBuilder();
        createBuilder9.getClass();
        yyb.ad(7, createBuilder9);
        yyb.ac(brg.a, createBuilder9);
        yyb.ab(amzp.SPAM, createBuilder9);
        yyb.S(yyb.aa(createBuilder9), createBuilder8);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder8.b).e).getClass();
            aozy createBuilder10 = ymb.c.createBuilder();
            createBuilder10.getClass();
            yyb.aj(createBuilder10);
            yyb.ah(createBuilder10);
            yyb.ai(createBuilder10);
            yyb.ag(amzr.SHORT_CODE, createBuilder10);
            yyb.ai(createBuilder10);
            yyb.ag(amzr.ALPHA_CODE, createBuilder10);
            yyb.R(yyb.af(createBuilder10), createBuilder8);
        }
        yyb.Q(apzk.SHOW_WARNING, createBuilder8);
        yyb.Y(yyb.P(createBuilder8), createBuilder);
        if (!ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
            aozy createBuilder11 = ymu.a.createBuilder();
            createBuilder11.getClass();
            DesugarCollections.unmodifiableList(((ymu) createBuilder11.b).b).getClass();
            aozy createBuilder12 = ymj.a.createBuilder();
            createBuilder12.getClass();
            yyb.ad(7, createBuilder12);
            yyb.ac(brg.a, createBuilder12);
            yyb.ab(amzp.SPAM, createBuilder12);
            yyb.S(yyb.aa(createBuilder12), createBuilder11);
            DesugarCollections.unmodifiableList(((ymu) createBuilder11.b).b).getClass();
            aozy createBuilder13 = ymj.a.createBuilder();
            createBuilder13.getClass();
            yyb.ad(3, createBuilder13);
            yyb.ac(brg.a, createBuilder13);
            yyb.ab(amzp.SPAM, createBuilder13);
            yyb.S(yyb.aa(createBuilder13), createBuilder11);
            yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder11);
            yyb.Y(yyb.P(createBuilder11), createBuilder);
        }
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder14 = ymu.a.createBuilder();
        createBuilder14.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder14.b).b).getClass();
        aozy createBuilder15 = ymj.a.createBuilder();
        createBuilder15.getClass();
        yyb.ad(7, createBuilder15);
        yyb.ac(brg.a, createBuilder15);
        yyb.ab(amzp.SPAM, createBuilder15);
        yyb.S(yyb.aa(createBuilder15), createBuilder14);
        DesugarCollections.unmodifiableList(((ymu) createBuilder14.b).b).getClass();
        aozy createBuilder16 = ymj.a.createBuilder();
        createBuilder16.getClass();
        yyb.ad(6, createBuilder16);
        yyb.ac(brg.a, createBuilder16);
        yyb.ab(amzp.SPAM, createBuilder16);
        yyb.S(yyb.aa(createBuilder16), createBuilder14);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder14.b).e).getClass();
            aozy createBuilder17 = ymb.c.createBuilder();
            createBuilder17.getClass();
            yyb.aj(createBuilder17);
            yyb.ah(createBuilder17);
            yyb.ai(createBuilder17);
            yyb.ag(amzr.SHORT_CODE, createBuilder17);
            yyb.ai(createBuilder17);
            yyb.ag(amzr.ALPHA_CODE, createBuilder17);
            yyb.R(yyb.af(createBuilder17), createBuilder14);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder14);
        yyb.Y(yyb.P(createBuilder14), createBuilder);
        if (!ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
            aozy createBuilder18 = ymu.a.createBuilder();
            createBuilder18.getClass();
            DesugarCollections.unmodifiableList(((ymu) createBuilder18.b).b).getClass();
            aozy createBuilder19 = ymj.a.createBuilder();
            createBuilder19.getClass();
            yyb.ad(4, createBuilder19);
            yyb.ac(brg.a, createBuilder19);
            yyb.ab(amzp.SPAM, createBuilder19);
            yyb.S(yyb.aa(createBuilder19), createBuilder18);
            DesugarCollections.unmodifiableList(((ymu) createBuilder18.b).b).getClass();
            aozy createBuilder20 = ymj.a.createBuilder();
            createBuilder20.getClass();
            yyb.ad(3, createBuilder20);
            yyb.ac(brg.a, createBuilder20);
            yyb.ab(amzp.SPAM, createBuilder20);
            yyb.S(yyb.aa(createBuilder20), createBuilder18);
            yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder18);
            yyb.Y(yyb.P(createBuilder18), createBuilder);
        }
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder21 = ymu.a.createBuilder();
        createBuilder21.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder21.b).b).getClass();
        aozy createBuilder22 = ymj.a.createBuilder();
        createBuilder22.getClass();
        yyb.ad(4, createBuilder22);
        yyb.ac(brg.a, createBuilder22);
        yyb.ab(amzp.SPAM, createBuilder22);
        yyb.S(yyb.aa(createBuilder22), createBuilder21);
        DesugarCollections.unmodifiableList(((ymu) createBuilder21.b).b).getClass();
        aozy createBuilder23 = ymj.a.createBuilder();
        createBuilder23.getClass();
        yyb.ad(6, createBuilder23);
        yyb.ac(brg.a, createBuilder23);
        yyb.ab(amzp.SPAM, createBuilder23);
        yyb.S(yyb.aa(createBuilder23), createBuilder21);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder21.b).e).getClass();
            aozy createBuilder24 = ymb.c.createBuilder();
            createBuilder24.getClass();
            yyb.aj(createBuilder24);
            yyb.ah(createBuilder24);
            yyb.ai(createBuilder24);
            yyb.ag(amzr.SHORT_CODE, createBuilder24);
            yyb.ai(createBuilder24);
            yyb.ag(amzr.ALPHA_CODE, createBuilder24);
            yyb.R(yyb.af(createBuilder24), createBuilder21);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder21);
        yyb.Y(yyb.P(createBuilder21), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder25 = ymu.a.createBuilder();
        createBuilder25.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder25.b).b).getClass();
        aozy createBuilder26 = ymj.a.createBuilder();
        createBuilder26.getClass();
        yyb.ad(6, createBuilder26);
        yyb.ac(1.0f, createBuilder26);
        yyb.ab(amzp.SPAM, createBuilder26);
        yyb.S(yyb.aa(createBuilder26), createBuilder25);
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder25);
        yyb.Y(yyb.P(createBuilder25), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder27 = ymu.a.createBuilder();
        createBuilder27.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder27.b).b).getClass();
        aozy createBuilder28 = ymj.a.createBuilder();
        createBuilder28.getClass();
        yyb.ad(7, createBuilder28);
        yyb.ac(1.0f, createBuilder28);
        yyb.ab(amzp.SPAM, createBuilder28);
        yyb.S(yyb.aa(createBuilder28), createBuilder27);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder27.b).e).getClass();
            aozy createBuilder29 = ymb.c.createBuilder();
            createBuilder29.getClass();
            yyb.aj(createBuilder29);
            yyb.ah(createBuilder29);
            yyb.ai(createBuilder29);
            yyb.ag(amzr.SHORT_CODE, createBuilder29);
            yyb.ai(createBuilder29);
            yyb.ag(amzr.ALPHA_CODE, createBuilder29);
            yyb.R(yyb.af(createBuilder29), createBuilder27);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder27);
        yyb.Y(yyb.P(createBuilder27), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder30 = ymu.a.createBuilder();
        createBuilder30.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder30.b).b).getClass();
        aozy createBuilder31 = ymj.a.createBuilder();
        createBuilder31.getClass();
        yyb.ad(6, createBuilder31);
        yyb.ac(1.0f, createBuilder31);
        yyb.ab(amzp.NOT_SPAM, createBuilder31);
        yyb.S(yyb.aa(createBuilder31), createBuilder30);
        yyb.Q(apzk.ALLOW, createBuilder30);
        yyb.Y(yyb.P(createBuilder30), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder32 = ymu.a.createBuilder();
        createBuilder32.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder32.b).b).getClass();
        aozy createBuilder33 = ymj.a.createBuilder();
        createBuilder33.getClass();
        yyb.ad(10, createBuilder33);
        yyb.ac(0.5f, createBuilder33);
        yyb.ab(amzp.SPAM, createBuilder33);
        yyb.S(yyb.aa(createBuilder33), createBuilder32);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder32.b).e).getClass();
            aozy createBuilder34 = ymb.c.createBuilder();
            createBuilder34.getClass();
            yyb.aj(createBuilder34);
            yyb.ah(createBuilder34);
            yyb.ai(createBuilder34);
            yyb.ag(amzr.SHORT_CODE, createBuilder34);
            yyb.ai(createBuilder34);
            yyb.ag(amzr.ALPHA_CODE, createBuilder34);
            yyb.R(yyb.af(createBuilder34), createBuilder32);
        }
        yyb.Q(apzk.SHOW_WARNING, createBuilder32);
        yyb.Y(yyb.P(createBuilder32), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder35 = ymu.a.createBuilder();
        createBuilder35.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder35.b).b).getClass();
        aozy createBuilder36 = ymj.a.createBuilder();
        createBuilder36.getClass();
        yyb.ad(10, createBuilder36);
        yyb.ac(0.9f, createBuilder36);
        yyb.ab(amzp.SPAM, createBuilder36);
        yyb.S(yyb.aa(createBuilder36), createBuilder35);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder35.b).e).getClass();
            aozy createBuilder37 = ymb.c.createBuilder();
            createBuilder37.getClass();
            yyb.aj(createBuilder37);
            yyb.ah(createBuilder37);
            yyb.ai(createBuilder37);
            yyb.ag(amzr.SHORT_CODE, createBuilder37);
            yyb.ai(createBuilder37);
            yyb.ag(amzr.ALPHA_CODE, createBuilder37);
            yyb.R(yyb.af(createBuilder37), createBuilder35);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder35);
        yyb.Y(yyb.P(createBuilder35), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder38 = ymu.a.createBuilder();
        createBuilder38.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder38.b).b).getClass();
        aozy createBuilder39 = ymj.a.createBuilder();
        createBuilder39.getClass();
        yyb.ad(8, createBuilder39);
        yyb.ac(0.5f, createBuilder39);
        yyb.ab(amzp.SPAM, createBuilder39);
        yyb.S(yyb.aa(createBuilder39), createBuilder38);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder38.b).e).getClass();
            aozy createBuilder40 = ymb.c.createBuilder();
            createBuilder40.getClass();
            yyb.aj(createBuilder40);
            yyb.ah(createBuilder40);
            yyb.ai(createBuilder40);
            yyb.ag(amzr.SHORT_CODE, createBuilder40);
            yyb.ai(createBuilder40);
            yyb.ag(amzr.ALPHA_CODE, createBuilder40);
            yyb.R(yyb.af(createBuilder40), createBuilder38);
        }
        yyb.Q(apzk.SHOW_WARNING, createBuilder38);
        yyb.Y(yyb.P(createBuilder38), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder41 = ymu.a.createBuilder();
        createBuilder41.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder41.b).b).getClass();
        aozy createBuilder42 = ymj.a.createBuilder();
        createBuilder42.getClass();
        yyb.ad(8, createBuilder42);
        yyb.ac(1.0f, createBuilder42);
        yyb.ab(amzp.SPAM, createBuilder42);
        yyb.S(yyb.aa(createBuilder42), createBuilder41);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder41.b).e).getClass();
            aozy createBuilder43 = ymb.c.createBuilder();
            createBuilder43.getClass();
            yyb.aj(createBuilder43);
            yyb.ah(createBuilder43);
            yyb.ai(createBuilder43);
            yyb.ag(amzr.SHORT_CODE, createBuilder43);
            yyb.ai(createBuilder43);
            yyb.ag(amzr.ALPHA_CODE, createBuilder43);
            yyb.R(yyb.af(createBuilder43), createBuilder41);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder41);
        yyb.Y(yyb.P(createBuilder41), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder44 = ymu.a.createBuilder();
        createBuilder44.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder44.b).b).getClass();
        aozy createBuilder45 = ymj.a.createBuilder();
        createBuilder45.getClass();
        yyb.ad(9, createBuilder45);
        yyb.ac(0.5f, createBuilder45);
        yyb.ab(amzp.SPAM, createBuilder45);
        yyb.S(yyb.aa(createBuilder45), createBuilder44);
        yyb.Q(apzk.SHOW_WARNING, createBuilder44);
        yyb.Y(yyb.P(createBuilder44), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder46 = ymu.a.createBuilder();
        createBuilder46.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder46.b).b).getClass();
        aozy createBuilder47 = ymj.a.createBuilder();
        createBuilder47.getClass();
        yyb.ad(9, createBuilder47);
        yyb.ac(0.5f, createBuilder47);
        yyb.ab(amzp.SPAM, createBuilder47);
        yyb.S(yyb.aa(createBuilder47), createBuilder46);
        DesugarCollections.unmodifiableList(((ymu) createBuilder46.b).b).getClass();
        aozy createBuilder48 = ymj.a.createBuilder();
        createBuilder48.getClass();
        yyb.ad(7, createBuilder48);
        yyb.ac(brg.a, createBuilder48);
        yyb.ab(amzp.SPAM, createBuilder48);
        yyb.S(yyb.aa(createBuilder48), createBuilder46);
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder46);
        yyb.Y(yyb.P(createBuilder46), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder49 = ymu.a.createBuilder();
        createBuilder49.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder49.b).b).getClass();
        aozy createBuilder50 = ymj.a.createBuilder();
        createBuilder50.getClass();
        yyb.ad(9, createBuilder50);
        yyb.ac(1.0f, createBuilder50);
        yyb.ab(amzp.SPAM, createBuilder50);
        yyb.S(yyb.aa(createBuilder50), createBuilder49);
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder49);
        yyb.Y(yyb.P(createBuilder49), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder51 = ymu.a.createBuilder();
        createBuilder51.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder51.b).b).getClass();
        aozy createBuilder52 = ymj.a.createBuilder();
        createBuilder52.getClass();
        yyb.ad(5, createBuilder52);
        yyb.ac(0.5f, createBuilder52);
        yyb.ab(amzp.SPAM, createBuilder52);
        yyb.S(yyb.aa(createBuilder52), createBuilder51);
        DesugarCollections.unmodifiableList(((ymu) createBuilder51.b).b).getClass();
        aozy createBuilder53 = ymj.a.createBuilder();
        createBuilder53.getClass();
        yyb.ad(10, createBuilder53);
        yyb.ac(0.5f, createBuilder53);
        yyb.ab(amzp.SPAM, createBuilder53);
        yyb.S(yyb.aa(createBuilder53), createBuilder51);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder51.b).e).getClass();
            aozy createBuilder54 = ymb.c.createBuilder();
            createBuilder54.getClass();
            yyb.aj(createBuilder54);
            yyb.ah(createBuilder54);
            yyb.ai(createBuilder54);
            yyb.ag(amzr.SHORT_CODE, createBuilder54);
            yyb.ai(createBuilder54);
            yyb.ag(amzr.ALPHA_CODE, createBuilder54);
            yyb.R(yyb.af(createBuilder54), createBuilder51);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder51);
        yyb.Y(yyb.P(createBuilder51), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder55 = ymu.a.createBuilder();
        createBuilder55.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder55.b).b).getClass();
        aozy createBuilder56 = ymj.a.createBuilder();
        createBuilder56.getClass();
        yyb.ad(6, createBuilder56);
        yyb.ac(0.5f, createBuilder56);
        yyb.ab(amzp.SPAM, createBuilder56);
        yyb.S(yyb.aa(createBuilder56), createBuilder55);
        DesugarCollections.unmodifiableList(((ymu) createBuilder55.b).b).getClass();
        aozy createBuilder57 = ymj.a.createBuilder();
        createBuilder57.getClass();
        yyb.ad(10, createBuilder57);
        yyb.ac(0.5f, createBuilder57);
        yyb.ab(amzp.SPAM, createBuilder57);
        yyb.S(yyb.aa(createBuilder57), createBuilder55);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder55.b).e).getClass();
            aozy createBuilder58 = ymb.c.createBuilder();
            createBuilder58.getClass();
            yyb.aj(createBuilder58);
            yyb.ah(createBuilder58);
            yyb.ai(createBuilder58);
            yyb.ag(amzr.SHORT_CODE, createBuilder58);
            yyb.ai(createBuilder58);
            yyb.ag(amzr.ALPHA_CODE, createBuilder58);
            yyb.R(yyb.af(createBuilder58), createBuilder55);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder55);
        yyb.Y(yyb.P(createBuilder55), createBuilder);
        DesugarCollections.unmodifiableList(((ymq) createBuilder.b).c).getClass();
        aozy createBuilder59 = ymu.a.createBuilder();
        createBuilder59.getClass();
        DesugarCollections.unmodifiableList(((ymu) createBuilder59.b).b).getClass();
        aozy createBuilder60 = ymj.a.createBuilder();
        createBuilder60.getClass();
        yyb.ad(9, createBuilder60);
        yyb.ac(0.5f, createBuilder60);
        yyb.ab(amzp.SPAM, createBuilder60);
        yyb.S(yyb.aa(createBuilder60), createBuilder59);
        DesugarCollections.unmodifiableList(((ymu) createBuilder59.b).b).getClass();
        aozy createBuilder61 = ymj.a.createBuilder();
        createBuilder61.getClass();
        yyb.ad(10, createBuilder61);
        yyb.ac(0.5f, createBuilder61);
        yyb.ab(amzp.SPAM, createBuilder61);
        yyb.S(yyb.aa(createBuilder61), createBuilder59);
        if (ymd.d().booleanValue()) {
            DesugarCollections.unmodifiableList(((ymu) createBuilder59.b).e).getClass();
            aozy createBuilder62 = ymb.c.createBuilder();
            createBuilder62.getClass();
            yyb.aj(createBuilder62);
            yyb.ah(createBuilder62);
            yyb.ai(createBuilder62);
            yyb.ag(amzr.SHORT_CODE, createBuilder62);
            yyb.ai(createBuilder62);
            yyb.ag(amzr.ALPHA_CODE, createBuilder62);
            yyb.R(yyb.af(createBuilder62), createBuilder59);
        }
        yyb.Q(apzk.MOVE_TO_SPAM_FOLDER, createBuilder59);
        yyb.Y(yyb.P(createBuilder59), createBuilder);
        apag s = createBuilder.s();
        s.getClass();
        return (ymq) s;
    }
}
