package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class zrj {
    public final armf A;
    public final armf B;
    public final armf C;
    public final armf D;
    public final armf E;
    public final armf F;
    public final armf G;
    public final armf H;
    public final armf I;
    public final armf J;
    public final armf K;
    public final armf L;
    public final armf M;
    public final armf N;
    public final armf O;
    public final armf P;
    public final armf Q;
    public final armf R;
    public final armf S;
    public final armf T;
    public final armf U;
    public final armf V;
    public final armf W;
    public final armf X;
    public final armf a;
    public final armf b;
    public final armf c;
    public final armf d;
    public final armf e;
    public final armf f;
    public final armf g;
    public final armf h;
    public final armf i;
    public final armf j;
    public final armf k;
    public final armf l;
    public final armf m;
    public final armf n;
    public final armf o;
    public final armf p;
    public final armf q;
    public final armf r;
    public final armf s;
    public final armf t;
    public final armf u;
    public final armf v;
    public final armf w;
    public final armf x;
    public final armf y;
    public final armf z;

    public zrj(armf armfVar, armf armfVar2, armf armfVar3, armf armfVar4, armf armfVar5, armf armfVar6, armf armfVar7, armf armfVar8, armf armfVar9, armf armfVar10, armf armfVar11, armf armfVar12, armf armfVar13, armf armfVar14, armf armfVar15, armf armfVar16, armf armfVar17, armf armfVar18, armf armfVar19, armf armfVar20, armf armfVar21, armf armfVar22, armf armfVar23, armf armfVar24, armf armfVar25, armf armfVar26, armf armfVar27, armf armfVar28, armf armfVar29, armf armfVar30, armf armfVar31, armf armfVar32, armf armfVar33, armf armfVar34, armf armfVar35, armf armfVar36, armf armfVar37, armf armfVar38, armf armfVar39, armf armfVar40, armf armfVar41, armf armfVar42, armf armfVar43, armf armfVar44, armf armfVar45, armf armfVar46, armf armfVar47, armf armfVar48, armf armfVar49, armf armfVar50) {
        armfVar.getClass();
        this.a = armfVar;
        armfVar2.getClass();
        this.b = armfVar2;
        armfVar3.getClass();
        this.c = armfVar3;
        armfVar4.getClass();
        this.d = armfVar4;
        armfVar5.getClass();
        this.e = armfVar5;
        armfVar6.getClass();
        this.f = armfVar6;
        armfVar7.getClass();
        this.g = armfVar7;
        armfVar8.getClass();
        this.h = armfVar8;
        armfVar9.getClass();
        this.i = armfVar9;
        armfVar10.getClass();
        this.j = armfVar10;
        armfVar11.getClass();
        this.k = armfVar11;
        armfVar12.getClass();
        this.l = armfVar12;
        armfVar13.getClass();
        this.m = armfVar13;
        armfVar14.getClass();
        this.n = armfVar14;
        armfVar15.getClass();
        this.o = armfVar15;
        armfVar16.getClass();
        this.p = armfVar16;
        armfVar17.getClass();
        this.q = armfVar17;
        armfVar18.getClass();
        this.r = armfVar18;
        armfVar19.getClass();
        this.s = armfVar19;
        armfVar20.getClass();
        this.t = armfVar20;
        armfVar21.getClass();
        this.u = armfVar21;
        armfVar22.getClass();
        this.v = armfVar22;
        armfVar23.getClass();
        this.w = armfVar23;
        armfVar24.getClass();
        this.x = armfVar24;
        armfVar25.getClass();
        this.y = armfVar25;
        armfVar26.getClass();
        this.z = armfVar26;
        armfVar27.getClass();
        this.A = armfVar27;
        armfVar28.getClass();
        this.B = armfVar28;
        armfVar29.getClass();
        this.C = armfVar29;
        armfVar30.getClass();
        this.D = armfVar30;
        armfVar31.getClass();
        this.E = armfVar31;
        armfVar32.getClass();
        this.F = armfVar32;
        this.G = armfVar33;
        armfVar34.getClass();
        this.H = armfVar34;
        armfVar35.getClass();
        this.I = armfVar35;
        armfVar36.getClass();
        this.J = armfVar36;
        armfVar37.getClass();
        this.K = armfVar37;
        armfVar38.getClass();
        this.L = armfVar38;
        armfVar39.getClass();
        this.M = armfVar39;
        armfVar40.getClass();
        this.N = armfVar40;
        armfVar41.getClass();
        this.O = armfVar41;
        armfVar42.getClass();
        this.P = armfVar42;
        armfVar43.getClass();
        this.Q = armfVar43;
        armfVar44.getClass();
        this.R = armfVar44;
        armfVar45.getClass();
        this.S = armfVar45;
        armfVar46.getClass();
        this.T = armfVar46;
        armfVar47.getClass();
        this.U = armfVar47;
        armfVar48.getClass();
        this.V = armfVar48;
        armfVar49.getClass();
        this.W = armfVar49;
        armfVar50.getClass();
        this.X = armfVar50;
    }
}
