package org.bouncycastle.asn1.pkcs;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* compiled from: PG */
/* loaded from: classes4.dex */
public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier A;
    public static final ASN1ObjectIdentifier B;
    public static final ASN1ObjectIdentifier C;
    public static final ASN1ObjectIdentifier D;
    public static final ASN1ObjectIdentifier E;
    public static final ASN1ObjectIdentifier F;
    public static final ASN1ObjectIdentifier G;
    public static final ASN1ObjectIdentifier H;
    public static final ASN1ObjectIdentifier I;
    public static final ASN1ObjectIdentifier fA;
    public static final ASN1ObjectIdentifier fB;
    public static final ASN1ObjectIdentifier fC;
    public static final ASN1ObjectIdentifier fD;
    public static final ASN1ObjectIdentifier fE;
    public static final ASN1ObjectIdentifier fF;
    public static final ASN1ObjectIdentifier fG;
    public static final ASN1ObjectIdentifier h;
    public static final ASN1ObjectIdentifier i;
    public static final ASN1ObjectIdentifier j;
    public static final ASN1ObjectIdentifier k;
    public static final ASN1ObjectIdentifier l;
    public static final ASN1ObjectIdentifier m;
    public static final ASN1ObjectIdentifier n;
    public static final ASN1ObjectIdentifier o;
    public static final ASN1ObjectIdentifier p;
    public static final ASN1ObjectIdentifier q;
    public static final ASN1ObjectIdentifier r;
    public static final ASN1ObjectIdentifier s;
    public static final ASN1ObjectIdentifier t;
    public static final ASN1ObjectIdentifier u;
    public static final ASN1ObjectIdentifier v;
    public static final ASN1ObjectIdentifier w;
    public static final ASN1ObjectIdentifier x;
    public static final ASN1ObjectIdentifier y;
    public static final ASN1ObjectIdentifier z;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        fA = aSN1ObjectIdentifier;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "1");
        fB = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "3");
        fC = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "4");
        fD = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "7");
        fE = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "8");
        fF = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "9");
        fG = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "10");
        h = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "11");
        i = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "12");
        j = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "13");
        k = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "14");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "15");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "16");
        ASN1ObjectIdentifier aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        l = aSN1ObjectIdentifier2;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        m = aSN1ObjectIdentifier3;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "10");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "11");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "12");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "13");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "14");
        ASN1ObjectIdentifier aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        n = aSN1ObjectIdentifier4;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "4");
        ASN1ObjectIdentifier aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        o = aSN1ObjectIdentifier5;
        p = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "2");
        q = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "4");
        r = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "7").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "8").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "9").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "10").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "11").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "12").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "13").g();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").g();
        s = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").g();
        t = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").g();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").g();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").g();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").g();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").g();
        ASN1ObjectIdentifier aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        u = aSN1ObjectIdentifier6;
        v = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1").g();
        w = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "2").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "3").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "4").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "5").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "6").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "7").g();
        x = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "8").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "9").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "13").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "14").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "15").g();
        ASN1ObjectIdentifier g = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "16").g();
        y = g;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "16.2.46").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "20").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "21").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "22.1");
        ASN1ObjectIdentifier aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "22");
        z = aSN1ObjectIdentifier7;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "1").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "2").g();
        ASN1ObjectIdentifier aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "23");
        A = aSN1ObjectIdentifier8;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "1").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "52").g();
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "15.1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "15.2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "15.3");
        ASN1ObjectIdentifier aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        B = aSN1ObjectIdentifier9;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "9");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "23");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "31");
        ASN1ObjectIdentifier aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier(g, "3");
        C = aSN1ObjectIdentifier10;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "8");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "9");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "10");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "14");
        D = new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "17");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "18");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "28");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "29");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "30");
        ASN1ObjectIdentifier aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        E = aSN1ObjectIdentifier11;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        F = aSN1ObjectIdentifier12;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "10");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "11");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "12");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "47");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "7");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "14");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "15");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "16");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "17");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "18");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "19");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "20");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "21");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "22");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "23");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "24");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "25");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "26");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "27");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "37");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "38");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "54");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "43");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        ASN1ObjectIdentifier aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        G = aSN1ObjectIdentifier13;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "10.1");
        H = aSN1ObjectIdentifier14;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "6");
        ASN1ObjectIdentifier aSN1ObjectIdentifier15 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "1");
        I = aSN1ObjectIdentifier15;
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "1");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "2");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "3");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "4");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "5");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "6");
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "6");
    }
}
